everypolitician/everypolitician-data

- countries.json
- data/Ghana/Parliament/ep-popolo-v1.0.json
- data/Ghana/Parliament/sources/instructions.json
- data/Ghana/Parliament/sources/wikidata/elections.json
- data/Ghana/Parliament/unstable/stats.json
> Ghana (Parliament) — add Election information

- countries.json
- data/Madagascar/Assembly/ep-popolo-v1.0.json
- data/Madagascar/Assembly/sources/instructions.json
- data/Madagascar/Assembly/sources/wikidata/elections.json
- data/Madagascar/Assembly/unstable/stats.json
> Madagascar (Assembly) — add Election information

- countries.json
- data/Malaysia/Dewan_Rakyat/ep-popolo-v1.0.json
- data/Malaysia/Dewan_Rakyat/sources/instructions.json
- data/Malaysia/Dewan_Rakyat/sources/wikidata/elections.json
- data/Malaysia/Dewan_Rakyat/unstable/stats.json
> Malaysia (Dewan Rakyat) — add Election information

- countries.json
- data/Aland/Lagting/ep-popolo-v1.0.json
- data/Aland/Lagting/sources/instructions.json
- data/Aland/Lagting/sources/wikidata/elections.json
- data/Aland/Lagting/unstable/stats.json
> Aland (Lagting) — add Election information

- countries.json
- data/Singapore/Parliament/ep-popolo-v1.0.json
- data/Singapore/Parliament/sources/instructions.json
- data/Singapore/Parliament/sources/wikidata/elections.json
- data/Singapore/Parliament/unstable/stats.json
> Singapore (Parliament) — add Election information

- countries.json
- data/Uruguay/Deputies/ep-popolo-v1.0.json
- data/Uruguay/Deputies/sources/instructions.json
- data/Uruguay/Deputies/sources/wikidata/elections.json
- data/Uruguay/Deputies/unstable/stats.json
> Uruguay (Deputies) — add Election information

- countries.json
- data/Niger/Assembly/ep-popolo-v1.0.json
- data/Niger/Assembly/sources/instructions.json
- data/Niger/Assembly/sources/wikidata/elections.json
- data/Niger/Assembly/unstable/stats.json
> Niger (Assembly) — add Election information

- countries.json
- data/Rwanda/Deputies/ep-popolo-v1.0.json
- data/Rwanda/Deputies/sources/instructions.json
- data/Rwanda/Deputies/sources/wikidata/elections.json
- data/Rwanda/Deputies/unstable/stats.json
> Rwanda (Deputies) — add Election information

- countries.json
- data/Mali/Assembly/ep-popolo-v1.0.json
- data/Mali/Assembly/sources/instructions.json
- data/Mali/Assembly/sources/wikidata/elections.json
- data/Mali/Assembly/unstable/stats.json
> Mali (Assembly) — add Election information

- countries.json
- data/Chad/Assembly/ep-popolo-v1.0.json
- data/Chad/Assembly/sources/instructions.json
- data/Chad/Assembly/sources/wikidata/elections.json
- data/Chad/Assembly/unstable/stats.json
> Chad (Assembly) — add Election information

- countries.json
- data/Senegal/Assembly/ep-popolo-v1.0.json
- data/Senegal/Assembly/sources/instructions.json
- data/Senegal/Assembly/sources/wikidata/elections.json
- data/Senegal/Assembly/term-2012.csv
- data/Senegal/Assembly/unstable/stats.json
> Senegal (Assembly) — add Election information

- countries.json
- data/Zambia/Assembly/ep-popolo-v1.0.json
- data/Zambia/Assembly/sources/instructions.json
- data/Zambia/Assembly/sources/wikidata/elections.json
- data/Zambia/Assembly/unstable/stats.json
> Zambia (Assembly) — add Election information

- countries.json
- data/South_Sudan/Assembly/ep-popolo-v1.0.json
- data/South_Sudan/Assembly/sources/instructions.json
- data/South_Sudan/Assembly/sources/wikidata/elections.json
- data/South_Sudan/Assembly/unstable/stats.json
> South Sudan (Assembly) — add Election information

- countries.json
- data/Tunisia/Majlis/ep-popolo-v1.0.json
- data/Tunisia/Majlis/sources/instructions.json
- data/Tunisia/Majlis/sources/wikidata/elections.json
- data/Tunisia/Majlis/unstable/stats.json
> Tunisia (Majlis) — add Election information

- countries.json
- data/Burundi/Assembly/ep-popolo-v1.0.json
- data/Burundi/Assembly/sources/instructions.json
- data/Burundi/Assembly/sources/wikidata/elections.json
- data/Burundi/Assembly/unstable/stats.json
> Burundi (Assembly) — add Election information

- countries.json
- data/Togo/Assembly/ep-popolo-v1.0.json
- data/Togo/Assembly/sources/instructions.json
- data/Togo/Assembly/sources/wikidata/elections.json
- data/Togo/Assembly/unstable/stats.json
> Togo (Assembly) — add Election information

- countries.json
- data/Sierra_Leone/Parliament/ep-popolo-v1.0.json
- data/Sierra_Leone/Parliament/sources/instructions.json
- data/Sierra_Leone/Parliament/sources/wikidata/elections.json
- data/Sierra_Leone/Parliament/unstable/stats.json
> Sierra Leone (Parliament) — add Election information

- countries.json
- data/Mauritania/National_Assembly/ep-popolo-v1.0.json
- data/Mauritania/National_Assembly/sources/instructions.json
- data/Mauritania/National_Assembly/sources/wikidata/elections.json
- data/Mauritania/National_Assembly/unstable/stats.json
> Mauritania (National Assembly) — add Election information

- countries.json
- data/Namibia/Assembly/ep-popolo-v1.0.json
- data/Namibia/Assembly/sources/instructions.json
- data/Namibia/Assembly/sources/wikidata/elections.json
- data/Namibia/Assembly/unstable/stats.json
> Namibia (Assembly) — add Election information

- countries.json
- data/Botswana/Assembly/ep-popolo-v1.0.json
- data/Botswana/Assembly/sources/instructions.json
- data/Botswana/Assembly/sources/wikidata/elections.json
- data/Botswana/Assembly/unstable/stats.json
> Botswana (Assembly) — add Election information

- countries.json
- data/Gambia/National_Assembly/ep-popolo-v1.0.json
- data/Gambia/National_Assembly/sources/instructions.json
- data/Gambia/National_Assembly/sources/wikidata/elections.json
- data/Gambia/National_Assembly/unstable/stats.json
> Gambia (National Assembly) — add Election information

- countries.json
- data/Benin/National_Assembly/ep-popolo-v1.0.json
- data/Benin/National_Assembly/sources/instructions.json
- data/Benin/National_Assembly/sources/wikidata/elections.json
- data/Benin/National_Assembly/unstable/stats.json
> Benin (National Assembly) — add Election information

- countries.json
- data/Gibraltar/Parliament/ep-popolo-v1.0.json
- data/Gibraltar/Parliament/sources/instructions.json
- data/Gibraltar/Parliament/sources/wikidata/elections.json
- data/Gibraltar/Parliament/unstable/stats.json
> Gibraltar (Parliament) — add Election information

- countries.json
- data/Comoros/Assembly/ep-popolo-v1.0.json
- data/Comoros/Assembly/sources/instructions.json
- data/Comoros/Assembly/sources/wikidata/elections.json
- data/Comoros/Assembly/unstable/stats.json
> Comoros (Assembly) — add Election information

- countries.json
- data/Gabon/Assembly/ep-popolo-v1.0.json
- data/Gabon/Assembly/sources/instructions.json
- data/Gabon/Assembly/sources/wikidata/elections.json
- data/Gabon/Assembly/unstable/stats.json
> Gabon (Assembly) — add Election information

- countries.json
- data/Maldives/Majlis/ep-popolo-v1.0.json
- data/Maldives/Majlis/sources/instructions.json
- data/Maldives/Majlis/sources/wikidata/elections.json
- data/Maldives/Majlis/unstable/stats.json
> Maldives (Majlis) — add Election information

- countries.json
- data/Cabo_Verde/Assembly/ep-popolo-v1.0.json
- data/Cabo_Verde/Assembly/sources/instructions.json
- data/Cabo_Verde/Assembly/sources/wikidata/elections.json
- data/Cabo_Verde/Assembly/unstable/stats.json
> Cabo Verde (Assembly) — add Election information

- countries.json
- data/Mauritius/National_Assembly/ep-popolo-v1.0.json
- data/Mauritius/National_Assembly/sources/instructions.json
- data/Mauritius/National_Assembly/sources/wikidata/elections.json
- data/Mauritius/National_Assembly/unstable/stats.json
> Mauritius (National Assembly) — add Election information

- countries.json
- data/Belize/Representatives/ep-popolo-v1.0.json
- data/Belize/Representatives/sources/instructions.json
- data/Belize/Representatives/sources/wikidata/elections.json
- data/Belize/Representatives/unstable/stats.json
> Belize (Representatives) — add Election information

- countries.json
- data/Cameroon/Assembly/ep-popolo-v1.0.json
- data/Cameroon/Assembly/sources/manual/terms.csv
- data/Cameroon/Assembly/unstable/stats.json
Add exact start date of current term.
> Cameroon (Assembly): Better term dates

- countries.json
- data/Suriname/Assembly/ep-popolo-v1.0.json
- data/Suriname/Assembly/sources/manual/terms.csv
- data/Suriname/Assembly/unstable/stats.json
> Suriname (Assembly): better Term dates

- countries.json
- data/Mexico/Deputies/ep-popolo-v1.0.json
- data/Mexico/Deputies/sources/instructions.json
- data/Mexico/Deputies/sources/wikidata/elections.json
- data/Mexico/Deputies/unstable/stats.json
> Mexico (Deputies) — add Election information

- countries.json
- data/Ecuador/Asamblea/ep-popolo-v1.0.json
- data/Ecuador/Asamblea/sources/manual/terms.csv
- data/Ecuador/Asamblea/unstable/stats.json
```
* 6 of 36 unmatched
{:id=>"Q363069", :name=>"Iván Hurtado"}
{:id=>"Q11954889", :name=>"Virgilio Hernández Paesa"}
{:id=>"Q20994955", :name=>"Paola Pabón"}
{:id=>"Q20656121", :name=>"Denisse Robles"}
{:id=>"Q23685495", :name=>"Alexandra Arce"}
{:id=>"Q4664698", :name=>"Dalo Bucaram"}
30 x wikidata
3 x freebase
2 x fifa
Persons matched to Wikidata: 30 ✓ | 110 ✘
No wikidata: María José Carrión Cevallos (c7fc764a-d768-40a0-8028-91457c7cb634)
No wikidata: Mónica Alemán Mármol (16496d8a-db57-453b-a275-9c73babf92c4)
No wikidata: …
```
> Ecuador (Asamblea): better Term dates

- countries.json
- data/Yemen/Majlis/ep-popolo-v1.0.json
- data/Yemen/Majlis/sources/manual/terms.csv
- data/Yemen/Majlis/unstable/stats.json
```
Persons matched to Wikidata: 0 ✓ | 302 ✘
Parties matched to Wikidata: 0 ✓ | 6 ✘
```
> Yemen (Majlis): better Term dates

- countries.json
- data/Senegal/Assembly/ep-popolo-v1.0.json
- data/Senegal/Assembly/sources/manual/terms.csv
- data/Senegal/Assembly/unstable/stats.json
- rake_helpers/generate_ep_popolo.rb
```
* 37 of 48 unmatched
{:id=>"Q2821364", :name=>"Abdoulaye Bathily"}
{:id=>"Q2821374", :name=>"Abdoulaye Fofana"}
{:id=>"Q16267249", :name=>"Assane Diagne"}
{:id=>"Q284311", :name=>"Aïda Mbodj"}
{:id=>"Q2608966", :name=>"Jacques Diouf"}
{:id=>"Q3276586", :name=>"Magatte Lô"}
{:id=>"Q2840878", :name=>"Amadou Lamine-Guèye"}
{:id=>"Q3125323", :name=>"Habib Sy"}
{:id=>"Q2843389", :name=>"Aminata Mbengue Ndiaye"}
{:id=>"Q154545", :name=>"Léopold Sédar Senghor"}
11 x wikidata
3 x freebase
1 x bnf
1 x sudoc
1 x viaf
Persons …
```
> Senegal (Assembly): better Term dates from Parline

- countries.json
- data/Brazil/Deputies/ep-popolo-v1.0.json
- data/Brazil/Deputies/sources/instructions.json
- data/Brazil/Deputies/sources/wikidata/elections.json
- data/Brazil/Deputies/unstable/stats.json
- rake_helpers/generate_ep_popolo.rb
> Brazil (Deputies) — add Election information

- countries.json
- data/Chile/Deputies/ep-popolo-v1.0.json
- data/Chile/Deputies/sources/instructions.json
- data/Chile/Deputies/sources/wikidata/elections.json
- data/Chile/Deputies/unstable/stats.json
> Chile (Deputies) — add Election information

- countries.json
- data/Mongolia/Assembly/ep-popolo-v1.0.json
- data/Mongolia/Assembly/sources/instructions.json
- data/Mongolia/Assembly/sources/wikidata/elections.json
- data/Mongolia/Assembly/unstable/stats.json
> Mongolia (Assembly) — add Election information

- countries.json
- data/Indonesia/Council/ep-popolo-v1.0.json
- data/Indonesia/Council/sources/instructions.json
- data/Indonesia/Council/sources/wikidata/elections.json
- data/Indonesia/Council/unstable/stats.json
> Indonesia (Council) — add Election information

- countries.json
- data/Nepal/Assembly/ep-popolo-v1.0.json
- data/Nepal/Assembly/sources/instructions.json
- data/Nepal/Assembly/sources/wikidata/elections.json
- data/Nepal/Assembly/unstable/stats.json
> Nepal (Assembly) — add Election information

- countries.json
- data/Uzbekistan/Legislative_Chamber/ep-popolo-v1.0.json
- data/Uzbekistan/Legislative_Chamber/sources/manual/terms.csv
- data/Uzbekistan/Legislative_Chamber/unstable/stats.json
```
Persons matched to Wikidata: 0 ✓ | 147 ✘
```
> Uzbekistan (Legislative Chamber): better Term dates from Parline

- countries.json
- data/Iraq/Majlis/ep-popolo-v1.0.json
- data/Iraq/Majlis/sources/manual/terms.csv
- data/Iraq/Majlis/unstable/stats.json
```
Persons matched to Wikidata: 0 ✓ | 328 ✘
Parties matched to Wikidata: 0 ✓ | 30 ✘
```
> Iraq (Majlis): better Term dates from Parline

- data/British_Virgin_Islands/Council/ep-popolo-v1.0.json
- data/British_Virgin_Islands/Council/sources/manual/terms.csv
- data/British_Virgin_Islands/Council/unstable/stats.json
```
* 2 of 13 unmatched
{:id=>"Q5215432", :name=>"Dancia Penn"}
{:id=>"Q16214258", :name=>"Myron Walwyn"}
⚥ data for 2; 2 added
Creating 9 term files
11 x wikidata
4 x freebase
1 x fast
1 x viaf
Persons matched to Wikidata: 11 ✓ | 25 ✘
No wikidata: Lloyd BLACK (ce0c0721-5823-4a04-b3d7-db3c3d3f66b1)
No wikidata: Andrew FAHIE (d03ac8e2-6cfb-4b02-aef2-fee72e7cd1d5)
No wikidata: PARSONS, Eilieene Lucia (d0c44524-a1a0-4339-ad5c-65789937a44e)
No wikidata: Eileene PARSONS (85fdf223-058a-4aaf-9da6-191ef2237ee4)
No wikidata: Andre PENN (2ae84a9b-552c-4cad-84b8-3607926ef9f5)
No …
```
> British Virgin Islands (Council): better Term dates

- bin/dashboard.rb
[Now](https://github.com/everypolitician/everypolitician-data/pull/12260) that we have stats files for all legislatures, read those rather
than rolling our own statistics.
> Dashboard: read from Stats files

- countries.json
- data/Albania/Assembly/ep-popolo-v1.0.json
- data/Albania/Assembly/sources/manual/terms.csv
- data/Albania/Assembly/unstable/stats.json
```
Add memberships from sources/morph/wikipedia-7.csv
Merging with sources/morph/official-8.csv
* 11 of 140 unmatched
{:id=>"9820", :name=>"Shkëlqim Troplini"}
{:id=>"9840", :name=>"Antoneta Dhima"}
{:id=>"14952", :name=>"Mirela Ferracaku"}
{:id=>"9690", :name=>"Arbjola Halimi"}
{:id=>"9614", :name=>"Edlira Çekrezi"}
{:id=>"9618", :name=>"Bujar Çela"}
{:id=>"9750", :name=>"Tahir Muhedini"}
{:id=>"9752", :name=>"Eduart Ndocaj"}
{:id=>"9720", :name=>"Irma Kopliku"}
{:id=>"9714", :name=>"Piro Kapurani"}
* 1 of 115 unmatched
{:id=>"Q983272", :name=>"Fatmir Mediu"}
☁ Mismatch in birth_date for cc761c3b-11c8-4108-9e1a-f65a55987d26 (1968-02-18) vs 1968-11-18 (for Q1727869)
Adding …
```
> Albania (Assembly): better Term dates from Parline

- countries.json
- data/Kiribati/Parliament/ep-popolo-v1.0.json
- data/Kiribati/Parliament/sources/manual/terms.csv
- data/Kiribati/Parliament/unstable/stats.json
```
Add memberships from sources/morph/wikipedia-9.csv
Creating 2 term files
11 x wikidata
5 x freebase
2 x viaf
1 x ted
1 x lcauth
Persons matched to Wikidata: 11 ✓ | 51 ✘
No wikidata: Kirabuke Teiaaua (a59bd516-9d08-4940-be10-3fedc77b8966)
No wikidata: Teetan Mweretaka (37701518-5766-4a40-9934-416ac4eea71a)
No wikidata: Boutu Bateriki (4916229b-568a-459b-80bd-425e343a9e0b)
No wikidata: Taneti Mamau (77f2d864-73ac-47ed-9f8a-1838a6bc167c)
No wikidata: Willie Tokataake (8611225f-d91f-4f3b-bec4-7efa09c7d1df)
No wikidata: Tom Murdock …
```
> Kiribati (Parliament): better Term dates from Parline

- countries.json
- data/Panama/Assembly/ep-popolo-v1.0.json
- data/Panama/Assembly/sources/manual/terms.csv
- data/Panama/Assembly/unstable/stats.json
```
Persons matched to Wikidata: 0 ✓ | 74 ✘
Parties matched to Wikidata: 6 ✓ 
```
> Panama (Assembly): better Term dates from Parline

- countries.json
- data/Bolivia/Deputies/ep-popolo-v1.0.json
- data/Bolivia/Deputies/sources/manual/terms.csv
- data/Bolivia/Deputies/unstable/stats.json
```
* 53 of 54 unmatched
{:id=>"Q6752896", :name=>"Manuel Suárez Ávila"}
{:id=>"Q6299387", :name=>"Juan Carlos Riss Cecin"}
{:id=>"Q21089579", :name=>"Carlos Aparicio Vedia"}
{:id=>"Q18643897", :name=>"Hector Borda Leaño"}
{:id=>"Q6278204", :name=>"Jorge Ledezma"}
{:id=>"Q5339974", :name=>"Edmundo Novillo"}
{:id=>"Q15966128", :name=>"Pedro Nuni"}
{:id=>"Q16576556", :name=>"Hugo San Martín"}
{:id=>"Q2511035", :name=>"José Luis Tejada Sorzano"}
{:id=>"Q5649284", :name=>"Remedios Loza"}
⚥ data for 127; 127 added
1 x wikidata
Persons matched to Wikidata: …
```
> Bolivia (Deputies): better Term dates from Parline

- countries.json
- data/Tajikistan/Representatives/ep-popolo-v1.0.json
- data/Tajikistan/Representatives/sources/manual/terms.csv
- data/Tajikistan/Representatives/unstable/stats.json
```
Persons matched to Wikidata: 0 ✓ | 62 ✘
Parties matched to Wikidata: 0 ✓ 
```
> Tajikistan (Representatives): better Term dates from Parline

- countries.json
- data/Maldives/Majlis/ep-popolo-v1.0.json
- data/Maldives/Majlis/sources/manual/terms.csv
- data/Maldives/Majlis/unstable/stats.json
```
Persons matched to Wikidata: 0 ✓ | 85 ✘
```
> Maldives (Majlis): better Term dates from Parline

- countries.json
- data/British_Virgin_Islands/Assembly/ep-popolo-v1.0.json
- data/British_Virgin_Islands/Assembly/sources/manual/terms.csv
- data/British_Virgin_Islands/Assembly/unstable/stats.json
```
* 6 of 13 unmatched
{:id=>"Q16866678", :name=>"Conrad Maduro"}
{:id=>"Q7703251", :name=>"Terrance B. Lettsome"}
{:id=>"Q518666", :name=>"Hamilton Lavity Stoutt"}
{:id=>"Q691131", :name=>"Willard Wheatley"}
{:id=>"Q1148676", :name=>"Cyril Romney"}
{:id=>"Q16873237", :name=>"Qwominer William Osborne"}
⚥ data for 5; 5 added
Creating 3 term files
7 x wikidata
2 x freebase
Persons matched to Wikidata: 7 ✓ | 16 ✘
No wikidata: Andrew A. Fahie (8db45da9-a003-4aeb-9e35-0c36e443ed5d)
No wikidata: Archibald Christian (aaea5f10-fbad-4b98-bf8d-752c43f218bf)
No wikidata: Alvera …
```
> British Virgin Islands (Assembly): better term dates

- countries.json
- data/Lebanon/Parliament/ep-popolo-v1.0.json
- data/Lebanon/Parliament/sources/manual/terms.csv
- data/Lebanon/Parliament/unstable/stats.json
```
* 19 of 93 unmatched
{:id=>"Q2429767", :name=>"Ali La Pointe"}
{:id=>"Q16122381", :name=>"نبيل نقولا"}
{:id=>"Q16123647", :name=>"عماد الحوت"}
{:id=>"Q12252104", :name=>"يوسف خليل"}
{:id=>"Q20409433", :name=>"عاطف مجدلاني"}
{:id=>"Q6765230", :name=>"خالد زهرمان"}
{:id=>"Q20423212", :name=>"محمد قباني"}
{:id=>"Q20392616", :name=>"إبراهيم كنعان"}
{:id=>"Q12214805", :name=>"زياد أسود"}
{:id=>"Q16119754", :name=>"سليم سلهب"}
Discarding duplicate membership: {:area_id=>"area/beirut_ii", :legislative_period_id=>"term/2009", :on_behalf_of_id=>"party/future_movement", :organization_id=>"legislature", …
```
> Lebanon (Parliament): better Term dates from Parline

- countries.json
- data/Cambodia/National_Assembly/ep-popolo-v1.0.json
- data/Cambodia/National_Assembly/sources/manual/terms.csv
- data/Cambodia/National_Assembly/unstable/stats.json
```
45 x wikidata
8 x freebase
5 x viaf
3 x lcauth
2 x fast
Unknown position (x1): Q769308 Cambodian People's Party — e.g. Q1068666
Unknown position (x1): Q6501749 General Secretary — e.g. Q1935910
Persons matched to Wikidata: 45 ✓ | 78 ✘
No wikidata: Sak Setha (ab602872-340f-4bae-8b09-c49f7d7f07a1)
No wikidata: Loy Sophat (58cd42f1-f701-401b-9fda-483620d1fb24)
No wikidata: Sok Oumsea (31f1dffc-7c80-4905-8311-45657e635221)
No wikidata: Ouch Sereyvuth (2dbb6193-9aa8-4f9d-b987-5bdb9c3c8c22)
No wikidata: Bin Chhin …
```
> Cambodia (National Assembly): better Term dates from Parline

- countries.json
- data/Nicaragua/Asamblea/ep-popolo-v1.0.json
- data/Nicaragua/Asamblea/sources/gender-balance/results.csv
- data/Nicaragua/Asamblea/sources/manual/terms.csv
- data/Nicaragua/Asamblea/sources/wikidata/groups.json
- data/Nicaragua/Asamblea/unstable/stats.json
```
Persons matched to Wikidata: 0 ✓ | 90 ✘
Parties matched to Wikidata: 3 ✓ 
```
> Nicaragua (Asamblea): better Term dates from Parline

- countries.json
- data/Jamaica/House_of_Representatives/ep-popolo-v1.0.json
- data/Jamaica/House_of_Representatives/sources/manual/terms.csv
- data/Jamaica/House_of_Representatives/unstable/stats.json
```
Creating 2 term files
36 x wikidata
4 x freebase
4 x viaf
3 x lcauth
1 x imdb
Persons matched to Wikidata: 36 ✓ | 44 ✘
No wikidata: Andrew Wheatley (ceb54a82-6f64-4172-b72d-3d93fd47508b)
No wikidata: Natalie Neita-Headley (8a89dbb0-7634-46fc-b008-97056f35234f)
No wikidata: Heroy Clarke (71512db3-ce37-470d-ad3d-c22998f63bec)
No wikidata: Zavia Mayne (0b6af07f-0a6a-4993-97ce-2736ea9c3360)
No wikidata: Dave Brown (c84370ed-ad12-4066-8d17-e11db4bb09eb)
No wikidata: Michael Stewart (40ee48a9-b938-46f0-8874-f1265467e91a)
No wikidata: Floyd Green …
```
> Jamaica (House of Representatives): better Term dates from Parline

- countries.json
- data/Samoa/Parliament/ep-popolo-v1.0.json
- data/Samoa/Parliament/sources/manual/terms.csv
- data/Samoa/Parliament/unstable/stats.json
```
Merging with sources/morph/data.csv
* 7 of 49 unmatched
{:id=>"43", :name=>"Tofa ALO Fulifuli Taveuveu"}
{:id=>"25", :name=>"Hon Afioga LAUTAFI Fio Selafi Purcell"}
{:id=>"45", :name=>"Tofa Fagaaivalu Kenrick Samu"}
{:id=>"152", :name=>"Tofa-Faimalotoa-Kika-Iemaima-Stowers"}
{:id=>"31", :name=>"Afioga TUFUGA Gafoaleata Faitua"}
{:id=>"40", :name=>"Susuga PAPALII Lio Faavaivaiomanu Taeu Masipau"}
{:id=>"1119", :name=>"Susuga Seiuli Ueligitone Seiuli"}
17 x wikidata
1 x freebase
Persons matched to Wikidata: 17 ✓ | 32 ✘
No …
```
> Samoa (Parliament): better Term dates from Parline

- countries.json
- data/Honduras/Congreso_Nacional/ep-popolo-v1.0.json
- data/Honduras/Congreso_Nacional/sources/manual/terms.csv
- data/Honduras/Congreso_Nacional/unstable/stats.json
```
3 x wikidata
1 x lcauth
1 x freebase
1 x fast
1 x sudoc
Persons matched to Wikidata: 3 ✓ | 126 ✘
No wikidata: Claudia Garmendia (5a5484cb-8c38-4413-a8d5-576867aed2ab)
No wikidata: Jaime Villegas (80c67255-7dfd-46b6-87b3-bebb600204c5)
No wikidata: Marco Andino (ac0a57df-34ee-48e6-b766-dfbba00994d5)
No wikidata: Gerardo Martínez (777e4c27-fe8c-4812-8bee-31535f72808a)
No wikidata: Irma Reyes (c2c92756-3dd2-47e5-bcf9-9036d9619cf4)
No wikidata: Gladis López (436e87d8-05b8-4322-ba6a-4ef4c84f84ce)
No wikidata: Mario Ayala …
```
> Honduras (Congreso Nacional): better Term dates from Parline

- countries.json
- data/Swaziland/Assembly/ep-popolo-v1.0.json
- data/Swaziland/Assembly/sources/manual/terms.csv
- data/Swaziland/Assembly/unstable/stats.json
```
Add memberships from sources/manual/scraped.csv
Creating 2 term files
Persons matched to Wikidata: 0 ✓ | 93 ✘
Parties matched to Wikidata: 0 ✓ 
```
> Swaziland (Assembly): better Term dates from Parline

- countries.json
- data/Barbados/House_of_Assembly/ep-popolo-v1.0.json
- data/Barbados/House_of_Assembly/sources/manual/terms.csv
- data/Barbados/House_of_Assembly/sources/wikidata/groups.json
- data/Barbados/House_of_Assembly/unstable/stats.json
```
⚥ data for 30; 30 added
Persons matched to Wikidata: 0 ✓ | 30 ✘
Parties matched to Wikidata: 2 ✓ 
```
> Barbados (House of Assembly): better Term dates from Parline

- countries.json
- data/Rwanda/Deputies/ep-popolo-v1.0.json
- data/Rwanda/Deputies/sources/manual/terms.csv
- data/Rwanda/Deputies/sources/wikidata/elections.json
- data/Rwanda/Deputies/unstable/stats.json
```
Persons matched to Wikidata: 0 ✓ | 77 ✘
Parties matched to Wikidata: 0 ✓ | 10 ✘
```
> Rwanda (Deputies): better Term dates from Parline

- countries.json
- data/Guinea-Bissau/Assembly/ep-popolo-v1.0.json
- data/Guinea-Bissau/Assembly/sources/manual/terms.csv
- data/Guinea-Bissau/Assembly/sources/wikidata/groups.json
- data/Guinea-Bissau/Assembly/unstable/stats.json
```
Persons matched to Wikidata: 0 ✓ | 100 ✘
```
> Guinea-Bissau (Assembly): better Term dates from Parline

- countries.json
- data/Vietnam/National_Assembly/ep-popolo-v1.0.json
- data/Vietnam/National_Assembly/sources/manual/terms.csv
- data/Vietnam/National_Assembly/unstable/stats.json
```
* 1148 of 1600 unmatched
{:id=>"Q10799717", :name=>"Nguyễn Thị Thảnh"}
{:id=>"Q10799505", :name=>"Nguyễn Thanh Tân"}
{:id=>"Q10787512", :name=>"Lâm Văn Kỷ"}
{:id=>"Q10787791", :name=>"Lê Quý Quỳnh"}
{:id=>"Q10807003", :name=>"Phạm Thiều"}
{:id=>"Q10769017", :name=>"Hoàng Thanh Phú"}
{:id=>"Q10842194", :name=>"Đỗ Xuân Công"}
{:id=>"Q10771204", :name=>"Hù Chà Cây"}
{:id=>"Q10799447", :name=>"Nguyễn Quốc Thước"}
{:id=>"Q10787927", :name=>"Lê Văn Mạnh"}
☁ Mismatch in birth_date for 04d91bab-adeb-4c12-8445-614d6e15af82 (1956-05-25) vs 1959-05-25 (for Q10744338)
☁ Mismatch in birth_date for e251bfc6-140f-4587-9700-ada6c7db14d9 (1953-04-08) vs 1953-04-18 (for Q10798976)
☁ Mismatch in gender …
```
> Vietnam (National Assembly): better Term dates from Parline

- countries.json
- data/Palau/House_of_Delegates/ep-popolo-v1.0.json
- data/Palau/House_of_Delegates/sources/manual/terms.csv
- data/Palau/House_of_Delegates/unstable/stats.json
```
* 1 of 1 unmatched
{:id=>"Q3195401", :name=>"Kerai Mariur"}
Persons matched to Wikidata: 0 ✓ | 16 ✘
Parties matched to Wikidata: 1 ✓ 
```
> Palau (House of Delegates): better Term dates from Parline

- countries.json
- data/Comoros/Assembly/ep-popolo-v1.0.json
- data/Comoros/Assembly/sources/manual/terms.csv
- data/Comoros/Assembly/unstable/stats.json
```
Persons matched to Wikidata: 0 ✓ | 24 ✘
Parties matched to Wikidata: 7 ✓ 
```
> Comoros (Assembly): better Term dates from Parline

- countries.json
- data/Timor_Leste/Parlamento/ep-popolo-v1.0.json
- data/Timor_Leste/Parlamento/sources/manual/terms.csv
- data/Timor_Leste/Parlamento/sources/wikidata/groups.json
- data/Timor_Leste/Parlamento/unstable/stats.json
```
Persons matched to Wikidata: 0 ✓ | 65 ✘
Parties matched to Wikidata: 4 ✓ 
```
> Timor Leste (Parlamento): better Term dates from Parline

- countries.json
- data/Saint_Lucia/Assembly/ep-popolo-v1.0.json
- data/Saint_Lucia/Assembly/sources/manual/terms.csv
- data/Saint_Lucia/Assembly/unstable/stats.json
```
Merging with sources/morph/images.csv
* 13 of 35 unmatched
{:name=>"Dr. Gayle Tracey C. Rigobert", :id=>"dr.-gayle-tracey-c.-rigobert"}
{:name=>"Guy Eardley Joseph", :id=>"guy-eardley-joseph"}
{:name=>"Peter Foster", :id=>"peter-foster"}
{:name=>"Allen M. Chastanet", :id=>"allen-m.-chastanet"}
{:name=>"Herold A. Stanislas", :id=>"herold-a.-stanislas"}
{:name=>"John Bradley Felix", :id=>"john-bradley-felix"}
{:name=>"Phillip J. Pierre", :id=>"phillip-j.-pierre"}
{:name=>"Alva R. Baptiste", :id=>"alva-r.-baptiste"}
{:name=>"Dominic Francis Fedee", :id=>"dominic-francis-fedee"}
{:name=>"Shawn Andrey Edward", :id=>"shawn-andrey-edward"}
☁ Mismatch in wikipedia__en for …
```
> Saint Lucia (Assembly): better Term dates from Parline

- countries.json
- data/Grenada/House_of_Representatives/ep-popolo-v1.0.json
- data/Grenada/House_of_Representatives/sources/manual/terms.csv
- data/Grenada/House_of_Representatives/unstable/stats.json
```
Persons matched to Wikidata: 0 ✓ | 15 ✘
Parties matched to Wikidata: 1 ✓ 
```
> Grenada (House of Representatives): better Term dates from Parline

- countries.json
- data/Saint_Kitts_and_Nevis/Assembly/ep-popolo-v1.0.json
- data/Saint_Kitts_and_Nevis/Assembly/sources/manual/terms.csv
- data/Saint_Kitts_and_Nevis/Assembly/unstable/stats.json
```
Add memberships from sources/morph/electionpassport.csv
Add memberships from sources/morph/electionpassport-2010.csv
Add memberships from sources/morph/electionpassport-2004.csv
Add memberships from sources/morph/electionpassport-2000.csv
Add memberships from sources/morph/electionpassport-1995.csv
Add memberships from sources/morph/electionpassport-1993.csv
Add memberships from sources/morph/electionpassport-1989.csv
Add memberships from sources/morph/electionpassport-1984.csv
Merging with sources/morph/wikipedia.csv
* 2 of 13 unmatched
{:id=>"Q7346038", :name=>"Robert James Dugu Gordon"}
{:id=>"Q22675574", :name=>"Ada Mae Edwards"}
Creating 8 term files …
```
> Saint Kitts and Nevis (Assembly): better Term dates from Parline

- countries.json
- data/Saint_Vincent_and_the_Grenadines/Assembly/ep-popolo-v1.0.json
- data/Saint_Vincent_and_the_Grenadines/Assembly/sources/instructions.json
- data/Saint_Vincent_and_the_Grenadines/Assembly/sources/wikidata/elections.json
- data/Saint_Vincent_and_the_Grenadines/Assembly/unstable/stats.json
> Saint Vincent and the Grenadines (Assembly) — add Election information

- countries.json
- data/Ivory_Coast/Assembly/ep-popolo-v1.0.json
- data/Ivory_Coast/Assembly/sources/instructions.json
- data/Ivory_Coast/Assembly/sources/wikidata/elections.json
- data/Ivory_Coast/Assembly/sources/wikidata/groups.json
- data/Ivory_Coast/Assembly/unstable/stats.json
> Ivory Coast (Assembly) — add Election information

- countries.json
- data/Ecuador/Asamblea/ep-popolo-v1.0.json
- data/Ecuador/Asamblea/sources/instructions.json
- data/Ecuador/Asamblea/sources/wikidata/elections.json
- data/Ecuador/Asamblea/unstable/stats.json
> Ecuador (Asamblea) — add Election information

- countries.json
- data/Faroe_Islands/Logting/ep-popolo-v1.0.json
- data/Faroe_Islands/Logting/sources/instructions.json
- data/Faroe_Islands/Logting/sources/manual/group_wikidata.csv
- data/Faroe_Islands/Logting/sources/wikidata/groups.json
- data/Faroe_Islands/Logting/unstable/stats.json
> Faroe Islands (Logting) — add Group information

- countries.json
- data/Iceland/Assembly/ep-popolo-v1.0.json
- data/Iceland/Assembly/sources/instructions.json
- data/Iceland/Assembly/sources/manual/group_wikidata.csv
- data/Iceland/Assembly/sources/wikidata/groups.json
- data/Iceland/Assembly/unstable/stats.json
> Iceland (Assembly) — add Group information

- countries.json
- data/Albania/Assembly/ep-popolo-v1.0.json
- data/Albania/Assembly/sources/instructions.json
- data/Albania/Assembly/sources/manual/group_wikidata.csv
- data/Albania/Assembly/sources/wikidata/groups.json
- data/Albania/Assembly/unstable/stats.json
> Albania (Assembly) — add Group information

- countries.json
- data/Israel/Knesset/ep-popolo-v1.0.json
- data/Israel/Knesset/sources/instructions.json
- data/Israel/Knesset/sources/wikidata/elections.json
- data/Israel/Knesset/unstable/stats.json
> Israel (Knesset) — add Election information

- countries.json
- data/Yemen/Majlis/ep-popolo-v1.0.json
- data/Yemen/Majlis/sources/instructions.json
- data/Yemen/Majlis/sources/wikidata/elections.json
- data/Yemen/Majlis/unstable/stats.json
> Yemen (Majlis) — add Election information

- countries.json
- data/Rwanda/Deputies/ep-popolo-v1.0.json
- data/Rwanda/Deputies/sources/instructions.json
- data/Rwanda/Deputies/sources/manual/group_wikidata.csv
- data/Rwanda/Deputies/sources/wikidata/groups.json
- data/Rwanda/Deputies/unstable/stats.json
> Rwanda (Deputies) — add Group information

- countries.json
- data/Vanuatu/Parliament/ep-popolo-v1.0.json
- data/Vanuatu/Parliament/sources/instructions.json
- data/Vanuatu/Parliament/sources/manual/group_wikidata.csv
- data/Vanuatu/Parliament/sources/wikidata/groups.json
- data/Vanuatu/Parliament/unstable/stats.json
> Vanuatu (Parliament) — add Group information

- countries.json
- data/Benin/National_Assembly/ep-popolo-v1.0.json
- data/Benin/National_Assembly/sources/instructions.json
- data/Benin/National_Assembly/sources/manual/group_wikidata.csv
- data/Benin/National_Assembly/sources/wikidata/groups.json
- data/Benin/National_Assembly/unstable/stats.json
> Benin (National Assembly) — add Group information

- countries.json
- data/Senegal/Assembly/ep-popolo-v1.0.json
- data/Senegal/Assembly/sources/instructions.json
- data/Senegal/Assembly/sources/manual/group_wikidata.csv
- data/Senegal/Assembly/sources/wikidata/groups.json
- data/Senegal/Assembly/unstable/stats.json
> Senegal (Assembly) — add Group information

- countries.json
- data/British_Virgin_Islands/Assembly/sources/manual/group_wikidata.csv
- data/British_Virgin_Islands/Council/ep-popolo-v1.0.json
- data/British_Virgin_Islands/Council/sources/instructions.json
- data/British_Virgin_Islands/Council/sources/manual/group_wikidata.csv
- data/British_Virgin_Islands/Council/sources/wikidata/groups.json
- data/British_Virgin_Islands/Council/unstable/stats.json
> British Virgin Islands (Council) — add Group information

- countries.json
- data/Thailand/National_Legislative_Assembly/ep-popolo-v1.0.json
- data/Thailand/National_Legislative_Assembly/sources/instructions.json
- data/Thailand/National_Legislative_Assembly/sources/wikidata/elections.json
- data/Thailand/National_Legislative_Assembly/unstable/stats.json
> Thailand (National Legislative Assembly) — add Election information

- countries.json
- data/Congo-Brazzaville/Assembly/ep-popolo-v1.0.json
- data/Congo-Brazzaville/Assembly/sources/instructions.json
- data/Congo-Brazzaville/Assembly/sources/manual/group_wikidata.csv
- data/Congo-Brazzaville/Assembly/sources/wikidata/groups.json
- data/Congo-Brazzaville/Assembly/unstable/stats.json
> Congo-Brazzaville (Assembly) — add Group information

- countries.json
- data/Congo-Kinshasa/Assembly/ep-popolo-v1.0.json
- data/Congo-Kinshasa/Assembly/sources/instructions.json
- data/Congo-Kinshasa/Assembly/sources/manual/group_wikidata.csv
- data/Congo-Kinshasa/Assembly/sources/wikidata/groups.json
- data/Congo-Kinshasa/Assembly/unstable/stats.json
> Congo-Kinshasa (Assembly) — add Group information

- countries.json
- data/Congo-Kinshasa/Assembly/ep-popolo-v1.0.json
- data/Congo-Kinshasa/Assembly/sources/instructions.json
- data/Congo-Kinshasa/Assembly/sources/wikidata/elections.json
- data/Congo-Kinshasa/Assembly/unstable/stats.json
> Congo-Kinshasa (Assembly) — add Election information

- countries.json
- data/Congo-Brazzaville/Assembly/ep-popolo-v1.0.json
- data/Congo-Brazzaville/Assembly/sources/instructions.json
- data/Congo-Brazzaville/Assembly/sources/wikidata/elections.json
- data/Congo-Brazzaville/Assembly/unstable/stats.json
> Congo-Brazzaville (Assembly) — add Election information

- data/Seychelles/Assembly/ep-popolo-v1.0.json
- data/Seychelles/Assembly/sources/instructions.json
- data/Seychelles/Assembly/sources/wikidata/elections.json
- data/Seychelles/Assembly/unstable/stats.json
> Seychelles (Assembly) — add Election information

- countries.json
- data/Argentina/Diputados/ep-popolo-v1.0.json
- data/Argentina/Diputados/sources/instructions.json
- data/Argentina/Diputados/sources/manual/position-filter.json
- data/Argentina/Diputados/sources/wikidata/elections.json
- data/Argentina/Diputados/unstable/stats.json
> Argentina (Diputados) — add Election information

- countries.json
- data/Sri_Lanka/Parliament/ep-popolo-v1.0.json
- data/Sri_Lanka/Parliament/sources/instructions.json
- data/Sri_Lanka/Parliament/sources/wikidata/elections.json
- data/Sri_Lanka/Parliament/unstable/stats.json
> Sri Lanka (Parliament) — add Election information

- countries.json
- data/Venezuela/Assembly/ep-popolo-v1.0.json
- data/Venezuela/Assembly/sources/instructions.json
- data/Venezuela/Assembly/sources/wikidata/elections.json
- data/Venezuela/Assembly/unstable/stats.json
> Venezuela (Assembly) — add Election information

- countries.json
- data/Colombia/Representatives/ep-popolo-v1.0.json
- data/Colombia/Representatives/sources/instructions.json
- data/Colombia/Representatives/sources/wikidata/elections.json
- data/Colombia/Representatives/unstable/stats.json
> Colombia (Representatives) — add Election information

- countries.json
- data/Panama/Assembly/ep-popolo-v1.0.json
- data/Panama/Assembly/sources/instructions.json
- data/Panama/Assembly/sources/wikidata/elections.json
- data/Panama/Assembly/unstable/stats.json
> Panama (Assembly) — add Election information

- countries.json
- data/Guatemala/Congress/ep-popolo-v1.0.json
- data/Guatemala/Congress/sources/instructions.json
- data/Guatemala/Congress/sources/wikidata/elections.json
- data/Guatemala/Congress/unstable/stats.json
> Guatemala (Congress) — add Election information

- countries.json
- data/Peru/Congreso/ep-popolo-v1.0.json
- data/Peru/Congreso/sources/instructions.json
- data/Peru/Congreso/sources/manual/position-filter.json
- data/Peru/Congreso/sources/wikidata/elections.json
- data/Peru/Congreso/unstable/stats.json
> Peru (Congreso) — add Election information

- countries.json
- data/Nicaragua/Asamblea/ep-popolo-v1.0.json
- data/Nicaragua/Asamblea/sources/instructions.json
- data/Nicaragua/Asamblea/sources/wikidata/elections.json
- data/Nicaragua/Asamblea/unstable/stats.json
> Nicaragua (Asamblea) — add Election information

- countries.json
- data/Cambodia/National_Assembly/ep-popolo-v1.0.json
- data/Cambodia/National_Assembly/sources/instructions.json
- data/Cambodia/National_Assembly/sources/manual/position-filter.json
- data/Cambodia/National_Assembly/sources/wikidata/elections.json
- data/Cambodia/National_Assembly/unstable/stats.json
> Cambodia (National Assembly) — add Election information

- countries.json
- data/Puerto_Rico/House_of_Representatives/ep-popolo-v1.0.json
- data/Puerto_Rico/House_of_Representatives/sources/instructions.json
- data/Puerto_Rico/House_of_Representatives/sources/wikidata/elections.json
- data/Puerto_Rico/House_of_Representatives/unstable/stats.json
> Puerto Rico (House of Representatives) — add Election information

- countries.json
- data/Hong_Kong/Legislative_Council/ep-popolo-v1.0.json
- data/Hong_Kong/Legislative_Council/sources/instructions.json
- data/Hong_Kong/Legislative_Council/sources/wikidata/elections.json
- data/Hong_Kong/Legislative_Council/unstable/stats.json
> Hong Kong (Legislative Council) — add Election information

- countries.json
- data/Antigua_and_Barbuda/Representatives/ep-popolo-v1.0.json
- data/Antigua_and_Barbuda/Representatives/sources/instructions.json
- data/Antigua_and_Barbuda/Representatives/sources/wikidata/elections.json
- data/Antigua_and_Barbuda/Representatives/unstable/stats.json
> Antigua and Barbuda (Representatives) — add Election information

- countries.json
- data/Alderney/States/ep-popolo-v1.0.json
- data/Alderney/States/sources/instructions.json
- data/Alderney/States/sources/wikidata/elections.json
- data/Alderney/States/unstable/stats.json
> Alderney (States) — add Election information

- countries.json
- data/Lebanon/Parliament/ep-popolo-v1.0.json
- data/Lebanon/Parliament/sources/instructions.json
- data/Lebanon/Parliament/sources/wikidata/elections.json
- data/Lebanon/Parliament/unstable/stats.json
> Lebanon (Parliament) — add Election information

- countries.json
- data/South_Ossetia/Parliament/ep-popolo-v1.0.json
- data/South_Ossetia/Parliament/sources/instructions.json
- data/South_Ossetia/Parliament/sources/wikidata/elections.json
- data/South_Ossetia/Parliament/unstable/stats.json
> South Ossetia (Parliament) — add Election information

- countries.json
- data/Congo-Kinshasa/Assembly/ep-popolo-v1.0.json
- data/Congo-Kinshasa/Assembly/sources/manual/terms.csv
- data/Congo-Kinshasa/Assembly/unstable/stats.json
```
* 3 of 23 unmatched
{:id=>"Q16195146", :name=>"Jeannette Kavira Mapera"}
{:id=>"Q586135", :name=>"Pierre Pay-Pay wa Syakasighe"}
{:id=>"Q3421171", :name=>"Raymond Tshibanda"}
20 x wikidata
Persons matched to Wikidata: 20 ✓ | 478 ✘
No wikidata: MBAW MBAW YEMATA Jean-Marie (d5ebe70a-36a5-4ee7-954a-7ddb0edd8a67)
No wikidata: FASO MUSHIGO Celestin (1cd7324a-08fe-4993-9b33-b0445eb39670)
No wikidata: MUTUALE Olivier Randi (4a8d4581-8871-46d8-9736-161a01d8d10e)
No wikidata: RAMAZANI SHADARI Emmanuel (d73880e7-d03c-4694-bfa0-c449b0a75e68)
No wikidata: MANSHIMBA …
```
> Congo-Kinshasa (Assembly): better term date from IPU

- countries.json
- data/United_Arab_Emirates/Federal_National_Council/ep-popolo-v1.0.json
- data/United_Arab_Emirates/Federal_National_Council/sources/instructions.json
- data/United_Arab_Emirates/Federal_National_Council/sources/wikidata/elections.json
- data/United_Arab_Emirates/Federal_National_Council/unstable/stats.json
> United Arab Emirates (Federal National Council) — add Election information

- countries.json
- data/North_Korea/National_Assembly/ep-popolo-v1.0.json
- data/North_Korea/National_Assembly/sources/instructions.json
- data/North_Korea/National_Assembly/sources/manual/position-filter.json
- data/North_Korea/National_Assembly/sources/wikidata/elections.json
- data/North_Korea/National_Assembly/unstable/stats.json
> North Korea (National Assembly) — add Election information

- countries.json
- data/Syria/Majlis/ep-popolo-v1.0.json
- data/Syria/Majlis/sources/instructions.json
- data/Syria/Majlis/sources/wikidata/elections.json
- data/Syria/Majlis/unstable/stats.json
> Syria (Majlis) — add Election information

- countries.json
- data/Thailand/National_Legislative_Assembly/ep-popolo-v1.0.json
- data/Thailand/National_Legislative_Assembly/sources/manual/terms.csv
- data/Thailand/National_Legislative_Assembly/unstable/stats.json
```
* 2 of 68 unmatched
{:id=>"Q24174890", :name=>"ณะ อารีนิจ"}
{:id=>"Q3739908", :name=>"พงศพัศ พงษ์เจริญ"}
⚥ data for 216; 205 added
No dates for election Q16937892 (Thai general election, 2016)
66 x wikidata
1 x sudoc
1 x freebase
1 x viaf
Unknown position (x1): Q19360223 Province Governor (Thailand) — e.g. Q13016271
Persons matched to Wikidata: 66 ✓ | 154 ✘
No wikidata: มหรรณพ เดชวิทักษ์ (7621606f-70c3-4b70-b97f-a45578c2d6fd)
No wikidata: สมพล เกียรติไพบูลย์ (d29946e8-0380-48ea-87f4-503225d2779d)
No wikidata: สุธรรม พันธุศักดิ์ …
```
> Thailand (National Legislative Assembly): better term date from IPU

- countries.json
- data/American_Samoa/House/ep-popolo-v1.0.json
- data/American_Samoa/House/sources/manual/terms.csv
- data/American_Samoa/House/unstable/stats.json
```
2 x wikidata
Persons matched to Wikidata: 2 ✓ | 15 ✘
No wikidata: Maugaoali’i Sipa Anoa’i (a5c945b3-4553-467a-900f-8eeb2b1599d5)
No wikidata: Puleleiite Lia Tufele Jr. (79727204-8b03-4827-8146-a5be5098a6c7)
No wikidata: Fetu Fetui Jr. (7e92d0d9-0b8b-4dac-9ab5-72e5d34f23ae)
No wikidata: Manumaua Wayne Wilson (62eff89f-5a19-4194-b26b-321aa5e30a7b)
No wikidata: Legae’e Mauga (2c1b00d2-9c0e-4c3c-8466-d0d9d61893d2)
No wikidata: Faimealelei Anthony Fu’e Allen (75ab2e43-b23a-4883-9e87-b31989eb1a9b)
No wikidata: Vailoata Eteuati …
```
> American Samoa: Term start date

- countries.json
- data/Haiti/Deputies/ep-popolo-v1.0.json
- data/Haiti/Deputies/sources/manual/terms.csv
- data/Haiti/Deputies/unstable/stats.json
```
Persons matched to Wikidata: 0 ✓ | 99 ✘
Parties matched to Wikidata: 5 ✓ | 13 ✘
No wikidata: LIBÉRATION (party/libÉration)
No wikidata: PLAPH (party/plaph)
No wikidata: RASANBLE (party/rasanble)
No wikidata: ALTERNATIVE (party/alternative)
No wikidata: KONBIT (party/konbit)
```
> Haiti (Deputies): better term dates from IPU

- countries.json
- data/Haiti/Deputies/ep-popolo-v1.0.json
- data/Haiti/Deputies/sources/instructions.json
- data/Haiti/Deputies/sources/wikidata/elections.json
- data/Haiti/Deputies/unstable/stats.json
```
Persons matched to Wikidata: 0 ✓ | 99 ✘
Parties matched to Wikidata: 5 ✓ | 13 ✘
No wikidata: MAS (party/mas)
No wikidata: RASANBLE (party/rasanble)
No wikidata: MOCHRENA (party/mochrena)
No wikidata: MODELH (party/modelh)
No wikidata: ALTERNATIVE (party/alternative)
```
> Haiti (Deputies) — add Election information

- countries.json
- data/Anguilla/Assembly/ep-popolo-v1.0.json
- data/Anguilla/Assembly/sources/instructions.json
- data/Anguilla/Assembly/sources/wikidata/elections.json
- data/Anguilla/Assembly/unstable/stats.json
> Anguilla (Assembly) — add Election information

- countries.json
- data/Dominican_Republic/Diputados/ep-popolo-v1.0.json
- data/Dominican_Republic/Diputados/sources/instructions.json
- data/Dominican_Republic/Diputados/sources/wikidata/elections.json
- data/Dominican_Republic/Diputados/unstable/stats.json
> Dominican Republic (Diputados) — add Election information

- countries.json
- data/Isle_of_Man/House_of_Keys/ep-popolo-v1.0.json
- data/Isle_of_Man/House_of_Keys/sources/instructions.json
- data/Isle_of_Man/House_of_Keys/sources/wikidata/elections.json
- data/Isle_of_Man/House_of_Keys/unstable/stats.json
> Isle of Man (House of Keys) — add Election information

- countries.json
- data/Jersey/States/ep-popolo-v1.0.json
- data/Jersey/States/sources/instructions.json
- data/Jersey/States/sources/wikidata/elections.json
- data/Jersey/States/sources/wikidata/groups.json
- data/Jersey/States/unstable/stats.json
> Jersey (States) — add Election information

- countries.json
- data/El_Salvador/Legislative_Assembly/ep-popolo-v1.0.json
- data/El_Salvador/Legislative_Assembly/sources/instructions.json
- data/El_Salvador/Legislative_Assembly/sources/wikidata/elections.json
- data/El_Salvador/Legislative_Assembly/sources/wikidata/groups.json
- data/El_Salvador/Legislative_Assembly/unstable/stats.json
> El Salvador (Legislative Assembly) — add Election information

- countries.json
- data/Costa_Rica/Assembly/ep-popolo-v1.0.json
- data/Costa_Rica/Assembly/sources/instructions.json
- data/Costa_Rica/Assembly/sources/wikidata/elections.json
- data/Costa_Rica/Assembly/unstable/stats.json
> Costa Rica (Assembly) — add Election information

- countries.json
- data/Jamaica/House_of_Representatives/ep-popolo-v1.0.json
- data/Jamaica/House_of_Representatives/sources/instructions.json
- data/Jamaica/House_of_Representatives/sources/wikidata/elections.json
- data/Jamaica/House_of_Representatives/unstable/stats.json
> Jamaica (House of Representatives) — add Election information

- countries.json
- data/Laos/Assembly/ep-popolo-v1.0.json
- data/Laos/Assembly/sources/instructions.json
- data/Laos/Assembly/sources/wikidata/elections.json
- data/Laos/Assembly/unstable/stats.json
> Laos (Assembly) — add Election information

- countries.json
- data/Paraguay/Deputies/ep-popolo-v1.0.json
- data/Paraguay/Deputies/sources/instructions.json
- data/Paraguay/Deputies/sources/wikidata/elections.json
- data/Paraguay/Deputies/sources/wikidata/groups.json
- data/Paraguay/Deputies/unstable/stats.json
> Paraguay (Deputies) — add Election information

- countries.json
- data/Bhutan/Assembly/ep-popolo-v1.0.json
- data/Bhutan/Assembly/sources/instructions.json
- data/Bhutan/Assembly/sources/wikidata/elections.json
- data/Bhutan/Assembly/sources/wikidata/groups.json
- data/Bhutan/Assembly/unstable/stats.json
> Bhutan (Assembly) — add Election information

- rake_build/generate_final_csvs.rb
Report on Executive positions with no start/end dates, so we can tidy
them up on Wikidata.
> warn about missing Executive position dates

- countries.json
- data/South_Ossetia/Parliament/ep-popolo-v1.0.json
- data/South_Ossetia/Parliament/sources/manual/terms.csv
- data/South_Ossetia/Parliament/unstable/stats.json
```
Persons matched to Wikidata: 0 ✓ | 34 ✘
Parties matched to Wikidata: 4 ✓ 
```
> South Ossetia (Parliament): better start date

- countries.json
- data/Oman/Majlis/ep-popolo-v1.0.json
- data/Oman/Majlis/sources/instructions.json
- data/Oman/Majlis/sources/wikidata/elections.json
- data/Oman/Majlis/unstable/stats.json
> Oman (Majlis) — add Election information

- countries.json
- data/Vietnam/National_Assembly/ep-popolo-v1.0.json
- data/Vietnam/National_Assembly/sources/instructions.json
- data/Vietnam/National_Assembly/sources/wikidata/elections.json
- data/Vietnam/National_Assembly/unstable/stats.json
> Vietnam (National Assembly) — add Election information

- countries.json
- data/Macao/Assembly/ep-popolo-v1.0.json
- data/Macao/Assembly/sources/instructions.json
- data/Macao/Assembly/sources/wikidata/elections.json
- data/Macao/Assembly/unstable/stats.json
> Macao (Assembly) — add Election information

- countries.json
- data/Bahrain/Council_of_Representatives/ep-popolo-v1.0.json
- data/Bahrain/Council_of_Representatives/sources/instructions.json
- data/Bahrain/Council_of_Representatives/sources/wikidata/elections.json
- data/Bahrain/Council_of_Representatives/unstable/stats.json
> Bahrain (Council of Representatives) — add Election information

- countries.json
- data/Guam/Parliament/ep-popolo-v1.0.json
- data/Guam/Parliament/sources/instructions.json
- data/Guam/Parliament/sources/wikidata/elections.json
- data/Guam/Parliament/unstable/stats.json
> Guam (Parliament) — add Election information

- countries.json
- data/Curacao/Estates/ep-popolo-v1.0.json
- data/Curacao/Estates/sources/instructions.json
- data/Curacao/Estates/sources/wikidata/elections.json
- data/Curacao/Estates/unstable/stats.json
> Curacao (Estates) — add Election information

- countries.json
- data/Guernsey/States/ep-popolo-v1.0.json
- data/Guernsey/States/sources/instructions.json
- data/Guernsey/States/sources/wikidata/elections.json
- data/Guernsey/States/sources/wikidata/positions.json
- data/Guernsey/States/unstable/stats.json
> Guernsey (States) — add Election information

- countries.json
- data/Sark/Chief_Pleas/ep-popolo-v1.0.json
- data/Sark/Chief_Pleas/sources/instructions.json
- data/Sark/Chief_Pleas/sources/wikidata/elections.json
- data/Sark/Chief_Pleas/sources/wikidata/groups.json
- data/Sark/Chief_Pleas/unstable/stats.json
> Sark (Chief Pleas) — add Election information

- countries.json
- data/Sint_Maarten/Estates/ep-popolo-v1.0.json
- data/Sint_Maarten/Estates/sources/instructions.json
- data/Sint_Maarten/Estates/sources/wikidata/elections.json
- data/Sint_Maarten/Estates/unstable/stats.json
> Sint Maarten (Estates) — add Election information

- countries.json
- data/Grenada/House_of_Representatives/ep-popolo-v1.0.json
- data/Grenada/House_of_Representatives/sources/instructions.json
- data/Grenada/House_of_Representatives/sources/wikidata/elections.json
- data/Grenada/House_of_Representatives/unstable/stats.json
> Grenada (House of Representatives) — add Election information

- countries.json
- data/Cayman_Islands/Legislative_Assembly/ep-popolo-v1.0.json
- data/Cayman_Islands/Legislative_Assembly/sources/instructions.json
- data/Cayman_Islands/Legislative_Assembly/sources/wikidata/elections.json
- data/Cayman_Islands/Legislative_Assembly/unstable/stats.json
> Cayman Islands (Legislative Assembly) — add Election information

- countries.json
- data/Somaliland/Representatives/ep-popolo-v1.0.json
- data/Somaliland/Representatives/names.csv
- data/Somaliland/Representatives/sources/instructions.json
- data/Somaliland/Representatives/sources/wikidata/elections.json
- data/Somaliland/Representatives/unstable/stats.json
> Somaliland (Representatives) — add Election information

- countries.json
- data/Bermuda/Assembly/ep-popolo-v1.0.json
- data/Bermuda/Assembly/sources/instructions.json
- data/Bermuda/Assembly/sources/wikidata/elections.json
- data/Bermuda/Assembly/unstable/stats.json
> Bermuda (Assembly) — add Election information

- countries.json
- data/Saint_Helena/Legislative_Council/ep-popolo-v1.0.json
- data/Saint_Helena/Legislative_Council/sources/instructions.json
- data/Saint_Helena/Legislative_Council/sources/wikidata/elections.json
- data/Saint_Helena/Legislative_Council/sources/wikidata/groups.json
- data/Saint_Helena/Legislative_Council/unstable/stats.json
> Saint Helena (Legislative Council) — add Election information

- countries.json
- data/UK/Commons/sources/wikidata/positions.json
- data/UK/Commons/unstable/positions.csv
Change in Prime Minister today means this is worth building separately.
> UK (Commons): rebuild position data

- .travis.yml
- Rakefile.rb
- test/reconciliation_fuzzer_test.rb
Fix test that was failing on `master`.
I've also added a `.travis.yml` and a default rake task so the tests can run on Travis for each PR.
> Fix broken reconciler test and setup Travis CI

- lib/source.rb
- lib/uuid_map.rb
- test/uuid_map_test.rb
Add a new class to represent the `data-ids.cv` files we use to map incoming
source IDs to our UUIDs.
> add a new UUID Mapping class

- lib/source.rb
- lib/uuid_map.rb
- test/uuid_map_test.rb
lets us simplify the code a bit more (and ensure that the directory for
the file exists before writing to it)
> use Pathname for id-map files

- data/Finland/Eduskunta/sources/manual/position-filter.json
- data/Finland/Eduskunta/unstable/positions.csv
- data/Finland/Eduskunta/unstable/stats.json
- rake_build/generate_final_csvs.rb
- rakefile_common.rb
First steps towards moving the Position Filter logic out of the
Rakefile. There's still much more to do, but this is in a working state,
and is merge-able now, to avoid later clashes with https://github.com/everypolitician/everypolitician-data/pull/16368
> Extract PositionFilter class

- Rakefile.rb
- lib/country_data.rb
Move lots of the logic for this out of the Rakefile and into a library.
> Refactor countries.json generation

- rake_build/generate_final_csvs.rb
Get rid of all the direct JSON lookups, and switch to using
EveryPolitician::Popolo
Part of https://github.com/everypolitician/everypolitician/issues/320
> generate_final_csvs: use EveryPolitician::Popolo more

- .travis.yml
- Gemfile
- Gemfile.lock
- Rakefile.rb
This adds an extra rake task to the Travis CI build. When the task is run it will add a comment to the current pull request containing a summary of changes.
Similar to #16718 
Related to https://github.com/everypolitician/everypolitician/issues/449
> Run pull request summarizer on Travis CI

- countries.json
- data/Turkey/Assembly/names.csv
- data/Turkey/Assembly/sources/idmap/data.csv
- data/Turkey/Assembly/sources/morph/data.csv
- data/Turkey/Assembly/term-23.csv
- data/Turkey/Assembly/term-24.csv
- data/Turkey/Assembly/term-25.csv
- data/Turkey/Assembly/term-26.csv
- data/Turkey/Assembly/unstable/stats.json
- lib/source/membership.rb
In #18063 we refreshed Wikidata etc.; now we're refreshing the Membership source
```
☁ Mismatch in wikipedia__tk for 8eb878de-9491-47b1-b5a0-a01675095109 (Recep Tayyip Erdoğan) vs Rejep Taýýyp Ärdogan (for Q39259)
☁ Mismatch in wikipedia__tk for a7d524e4-8594-452d-ae56-ebdd6c8f187b (Abdülhak Hamit Tarhan) vs Abdylhak Hamit Tarhan (for Q318014)
☁ Mismatch in wikipedia__tk for 97c30e2d-aa11-4b98-9b19-7873a6e4b580 (Mustafa Kemal Paşa) vs Mustafa Kemal Atatürk (for Q5152)
* 30 of 4278 unmatched
{:id=>"Q20744474", :name=>"Burcu Köksal"}
{:id=>"Q26234889", :name=>"Mehmet Emin Dindar"}
{:id=>"Q3671598", :name=>"Mustafa Balbay"}
{:id=>"Q20195222", :name=>"İbrahim Halil Fırat"}
{:id=>"Q20988525", …
```
> Turkey (Assembly): rebuild data

- countries.json
https://github.com/everypolitician/everypolitician-data/pull/18231 committed a broken countries.json — fix this.
> Refresh countries.json

- lib/source.rb
Rather than a giant case statement, switch the instantiation method to
be data-driven.
> Refactor lib/source

- rake_build/combine_sources.rb
- rake_build/fetch_sources.rb
- rake_build/merge_members.rb
- rake_build/turn_csv_to_popolo.rb
- rake_build/verify_source_data.rb
- rakefile_common.rb
Make it more obvious that this step is only about combining the Person and
Membership data that will be fed to csv-to-popolo, and that lots of other
data gets merged in at a later stage.
As part of this, extract 'fetch_sources' to a separate rakefile
> Rename 'combine_sources' as 'merge_members'

- lib/source/membership.rb
- lib/uuid_map.rb
- test/uuid_map_test.rb
We gradually moved the location of the UUID map file and thus needed to be
able to read from either place. These are now all moved, so we only care
about the single location.
Closes https://github.com/everypolitician/everypolitician/issues/510
> Simplify the UUID Map code

- data/Croatia/Sabor/sources/instructions.json
- data/Croatia/Sabor/sources/morph/sabor-7.csv
- data/Croatia/Sabor/sources/morph/sabor-8.csv
This makes it much easier to spot changes later.
```
Add memberships from sources/morph/sabor-7.csv
Add memberships from sources/morph/sabor-8.csv
☁ Mismatch in birth_date for 5351031d-1470-4256-ad6a-2665a15145a6 (1962-02-03) vs 1957-08-28 (for Q1254068)
☁ Mismatch in birth_date for 47cc223b-fcc3-4a56-a525-53ced82fb1b8 (1975-10-02) vs 1975-09-02 (for Q12628147)
☁ Mismatch in birth_date for f5f8279b-350e-450c-adc5-f57cd54ab17d (1962-01-19) vs 1962-02-19 (for Q7286273)
* 16 of 70 unmatched
{:id=>"Q7938757", :name=>"Vladimir Šišljagić"}
{:id=>"Q3443168", :name=>"Neven Mimica"}
{:id=>"Q11143940", :name=>"Tihomir Jakovina"}
{:id=>"Q1560823", :name=>"Božidar Kalmeta"}
{:id=>"Q165463", :name=>"Branko Grčić"}
{:id=>"Q1285099", …
```
> Croatia: Sort the incoming data

- lib/country_data.rb
fixes https://github.com/everypolitician/everypolitician/issues/526
> adds type to legislature metadata

- countries.json
- data/Morocco/House/ep-popolo-v1.0.json
- data/Morocco/House/sources/wikidata/elections.json
- data/Morocco/House/sources/wikidata/groups.json
- data/Morocco/House/unstable/stats.json
We have a broken import, so refesh everything other than data.csv to isolate the changes.
```
Persons matched to Wikidata: 0 ✓ | 401 ✘
Parties matched to Wikidata: 7 ✓ | 2 ✘
No wikidata: Group of Democratic Progress (party/group_of_democratic_progress)
No wikidata: Parliamentary Group of the Alliance of the center (party/parliamentary_group_of_the_alliance_of_the_center)
```
> Morocco (House): refresh data

- countries.json
- data/Syria/Majlis/ep-popolo-v1.0.json
- data/Syria/Majlis/sources/wikidata/elections.json
- data/Syria/Majlis/unstable/stats.json
```
⤈ No ORDER BY for sources/morph/data.csv
Persons matched to Wikidata: 0 ✓ | 274 ✘
Parties matched to Wikidata: 0 ✓ | 12 ✘
```
> Syria (Majlis): refresh data

- countries.json
- data/Myanmar/House_of_Representatives/ep-popolo-v1.0.json
- data/Myanmar/House_of_Representatives/sources/manual/terms.csv
```
Persons matched to Wikidata: 0 ✓ | 314 ✘
Parties matched to Wikidata: 0 ✓ | 19 ✘
```
> Myanmar (House of Representatives): refresh data

- countries.json
- data/Benin/National_Assembly/ep-popolo-v1.0.json
- data/Benin/National_Assembly/sources/wikidata/groups.json
- data/Benin/National_Assembly/unstable/stats.json
```
⚥ data for 1; 1 added
Persons matched to Wikidata: 0 ✓ | 83 ✘
Parties matched to Wikidata: 2 ✓ | 7 ✘
No wikidata: Refondation et Progrès (refondation_et_progrès)
No wikidata: PRD - Union fait la Nation (prd_union_fait_la_nation)
No wikidata: Refondation, Paix et Développement (refondation_paix_et_développement)
No wikidata: Autre (autre)
No wikidata: UMPP Unité – Solidarité – Progrès (umpp_unité_solidarité_progrès)
```
> Benin (National Assembly): refresh data

- countries.json
- data/Kenya/Assembly/ep-popolo-v1.0.json
- data/Kenya/Assembly/sources/manual/group_wikidata.csv
- data/Kenya/Assembly/sources/wikidata/groups.json
- data/Kenya/Assembly/unstable/stats.json
```
* 1 of 174 unmatched
{:id=>"2331", :name=>"Mutua Marcus Muluvi"}
☁ Mismatch in birth_date for 32bbb6b5-3cca-4ebf-9775-7572028b154f (1987) vs 1986 (for Q16866303)
☁ Mismatch in birth_date for 6161b2ca-deba-4a37-831e-571f023b32b5 (1978-07-06) vs 1978-06-06 (for Q17198176)
☁ Mismatch in birth_date for 8411c68d-6894-4e7d-b477-84fd35596c0e (1982-10-15) vs 1982-11-15 (for Q447119)
☁ Mismatch in birth_date for 8bd4c1df-14ae-4717-a75c-6c0c60a4a4f5 (1958) vs 1953-03-09 (for Q4664957)
☁ Mismatch in birth_date for 658e0ba6-a77a-4497-acfc-a92239ef10f3 (1967-06-15) vs 1969 (for Q4682154) …
```
> Kenya (Assembly): reconcile Independents

- countries.json
- data/Bhutan/Assembly/ep-popolo-v1.0.json
```
⚥ data for 47; 47 added
Persons matched to Wikidata: 0 ✓ | 47 ✘
Parties matched to Wikidata: 2 ✓ 
```
> Bhutan (Assembly): refresh data

- countries.json
- data/Latvia/Saeima/ep-popolo-v1.0.json
- data/Latvia/Saeima/unstable/stats.json
```
Wikidata renamings:
Q21974469
Add memberships from sources/morph/official-11.csv
Add memberships from sources/morph/official-10.csv
* 8 of 182 unmatched
{:id=>"Q380986", :name=>"Andris Bērziņš"}
{:id=>"Q342929", :name=>"Ģirts Valdis Kristovskis"}
{:id=>"Q57506", :name=>"Andris Bērziņš"}
{:id=>"Q465725", :name=>"Sarmīte Ēlerte"}
{:id=>"Q2576403", :name=>"Aigars Štokenbergs"}
{:id=>"Q2560770", :name=>"Linda Abu Meri"}
{:id=>"Q644688", :name=>"Inese Šlesere"}
{:id=>"Q2576442", :name=>"Artis Kampars"}
174 x wikidata
48 x viaf
42 x freebase
21 x lnb
19 x isni …
```
> Latvia (Saeima): refresh data

- countries.json
- data/South_Sudan/Assembly/ep-popolo-v1.0.json
- data/South_Sudan/Assembly/sources/wikidata/elections.json
```
⤈ No ORDER BY for sources/morph/data.csv
⤈ No ORDER BY for sources/morph/terms.csv
Persons matched to Wikidata: 0 ✓ | 167 ✘
Parties matched to Wikidata: 3 ✓ 
```
> South Sudan (Assembly): refresh data

- countries.json
- data/Curacao/Estates/ep-popolo-v1.0.json
- data/Curacao/Estates/sources/wikidata/elections.json
- data/Curacao/Estates/sources/wikidata/groups.json
- data/Curacao/Estates/unstable/stats.json
```
⤈ No ORDER BY for sources/morph/terms.csv
⚥ data for 21; 21 added
Persons matched to Wikidata: 0 ✓ | 21 ✘
Parties matched to Wikidata: 6 ✓ | 1 ✘
No wikidata: Independiente / Independent (III)
```
> Curacao (Estates): refresh data

- countries.json
- data/Ghana/Parliament/ep-popolo-v1.0.json
- data/Ghana/Parliament/sources/morph/wikidata.csv
```
☁ Mismatch in birth_date for 95c54fbf-4f7e-4de5-a8c8-c2dcf101eaa6 (1958-04-27) vs 1957-04-27 (for Q1698546)
☁ Mismatch in birth_date for 7ad99356-17be-4896-bec0-c08e4ae32631 (1946-05-17) vs 1956-05-17 (for Q5379334)
☁ Mismatch in birth_date for 495408a8-ea7a-4e93-bed9-cc7b5b357fd1 (1974-05-12) vs 1974-05-24 (for Q6732981)
* 2 of 34 unmatched
{:id=>"Q5721427", :name=>"Henry Ford Kamel"}
{:id=>"Q5341508", :name=>"Edward Adjaho"}
⚥ data for 269; 238 added
32 x wikidata
Unknown position (x1): Q6865980 Minister for Trade and Industry — e.g. Q5648740
Persons …
```
> Ghana (Parliament): refresh data

- countries.json
- data/Kyrgyzstan/Council/ep-popolo-v1.0.json
- data/Kyrgyzstan/Council/sources/wikidata/groups.json
```
⤈ No ORDER BY for sources/morph/official5.csv
⤈ No ORDER BY for sources/morph/official6.csv
Add memberships from sources/morph/official5.csv
Add memberships from sources/morph/official6.csv
Add memberships from sources/manual/members.csv
* 35 of 45 unmatched
{:id=>"Q58312", :name=>"Ruslan Kasakbajew"}
{:id=>"Q24692", :name=>"Almazbek Atambayev"}
{:id=>"Q24938260", :name=>"Силаев, Борис Иванович"}
{:id=>"Q4533403", :name=>"Эшимканов, Мелис Асаналиевич"}
{:id=>"Q2880365", :name=>"Bakyt Beshimov"}
{:id=>"Q3736573", :name=>"Temir Sariyev"}
{:id=>"Q25386837", :name=>"Акаев, Жанарбек Кубанычович"}
{:id=>"Q4279784", :name=>"Мамасаидов, Махаммаджан Ташалиевич"}
{:id=>"Q1101385", :name=>"Мар Ташимович Байджиев"}
{:id=>"Q4279779", …
```
> Kyrgyzstan (Council): refresh data

- countries.json
- data/Pakistan/Assembly/ep-popolo-v1.0.json
- data/Pakistan/Assembly/sources/manual/position-filter.json
- data/Pakistan/Assembly/sources/wikidata/positions.json
```
⤈ No ORDER BY for sources/morph/terms.csv
☁ Mismatch in gender for c4f06f4f-a091-4241-8867-cf853ba4090e (male) vs female (for Q23760943)
* 15 of 340 unmatched
{:id=>"Q19517970", :name=>"Sabiha Nadeem"}
{:id=>"Q134068", :name=>"Nawaz Sharif"}
{:id=>"Q19517911", :name=>"Syed Mir Shah"}
{:id=>"Q19560993", :name=>"Khalil Francis"}
{:id=>"Q18815911", :name=>"Syed Basit Sultan Bukhari"}
{:id=>"Q18763793", :name=>"Aisha Syed"}
{:id=>"Q18763842", :name=>"Ayesha Raza Farooq"}
{:id=>"Q19517968", :name=>"Shiza Fatima"}
{:id=>"Q18764047", :name=>"Fais Azeem"}
{:id=>"Q18816088", :name=>"Mazhar Ali"}
⚥ data for 47; 13 added
Top …
```
> Pakistan (Assembly): refresh data

- countries.json
- data/Zimbabwe/Senate/ep-popolo-v1.0.json
```
Add memberships from sources/google/memberships.csv
Merging with sources/google/people.csv
* 279 of 346 unmatched
{:id=>"160", :name=>"Jeffrey Runzirwai"}
{:id=>"103", :name=>"David Chapfika"}
{:id=>"133", :name=>"Denford Masiya"}
{:id=>"22", :name=>"Tendai Biti"}
{:id=>"113", :name=>"Sarah Mahoka"}
{:id=>"163", :name=>"Leonard Chikomba"}
{:id=>"115", :name=>"Temba Mliswa"}
{:id=>"191", :name=>"Roselyn Nkomo"}
{:id=>"76", :name=>"David Butau"}
{:id=>"278", :name=>"Judith Muzhavazhe"}
* 13 of 35 unmatched
{:id=>"chief-chitanga-chauke-fereni", :name=>"Fereni Chitanga Chauke Chief"}
{:id=>"chief-dandawa", :name=>"Dandawa Chief"}
{:id=>"clemence-nembire", :name=>"Clemence Nembire"}
{:id=>"tambudzani-mohadi", …
```
> Zimbabwe (Senate): refresh data

- countries.json
- data/Zambia/Assembly/ep-popolo-v1.0.json
- data/Zambia/Assembly/sources/manual/terms.csv
This PR updates the terms file to:
1) Update it to the new format described in <https://github.com/everypolitician/everypolitician/wiki/terms.csv>
2) Add the ending date of the previous term and the starting date of the new term according to [the IPU site](http://www.ipu.org/parline-e/reports/2359_E.htm)
> Zambia - National Assembly: update terms

- countries.json
- data/Mongolia/Assembly/ep-popolo-v1.0.json
- data/Mongolia/Assembly/sources/manual/terms.csv
Adds the end date of the 2012 term and start date of the 2016 term to terms.csv
This is a step towards importing data from the 2016 scraper.
Sanity check
------------
Pull request
------------
> Mongolia Assembly add term dates

- bin/run_command_for_each_legislature
Almost every time I run this script I change it to act like this. So
let's make it the default behaviour.
> Improve `run_command_for_each_legislature`

- countries.json
- data/Morocco/House/ep-popolo-v1.0.json
- data/Morocco/House/sources/wikidata/elections.json
Rebuild all sources other than morocco-house-of-representatives (which is a difficult import)
```
Persons matched to Wikidata: 0 ✓ | 401 ✘
Parties matched to Wikidata: 7 ✓ | 2 ✘
No wikidata: Parliamentary Group of the Alliance of the center (party/parliamentary_group_of_the_alliance_of_the_center)
No wikidata: Group of Democratic Progress (party/group_of_democratic_progress)
```
> Morocco (House): rebuild data

- countries.json
- data/Tonga/Assembly/ep-popolo-v1.0.json
- data/Tonga/Assembly/sources/wikidata/elections.json
Refresh all sources other than `duncanparkes/tonga` (which is a tricky import)
```
Persons matched to Wikidata: 0 ✓ | 26 ✘
Parties matched to Wikidata: 0 ✓ 
```
> Tonga (Assembly): rebuild data

- countries.json
- data/Myanmar/House_of_Representatives/ep-popolo-v1.0.json
- data/Myanmar/House_of_Representatives/sources/wikidata/elections.json
Complete rebuild
```
⤈ No ORDER BY for sources/morph/data.csv
Persons matched to Wikidata: 0 ✓ | 314 ✘
Parties matched to Wikidata: 0 ✓ | 19 ✘
```
> Myanmar (House of Representatives): rebuild data

- countries.json
- data/Niger/Assembly/ep-popolo-v1.0.json
- data/Niger/Assembly/sources/manual/terms.csv
This PR updates the terms file to:
1) Update it to the new format described in <https://github.com/everypolitician/everypolitician/wiki/terms.csv>
2) Add the ending date of the previous term and the starting date of the new term according to [the IPU site](http://www.ipu.org/parline-e/reports/2359_E.htm). Since there is no exact date for the dissolution of the outgoing legislature, the date was set to one day before the elections where celebrated.
> Niger - Assemblée Nationale: update terms

- data/Morocco/House/ep-popolo-v1.0.json
- data/Morocco/House/sources/manual/group_wikidata.csv
- data/Morocco/House/sources/wikidata/elections.json
- data/Morocco/House/sources/wikidata/groups.json
- data/Morocco/House/unstable/stats.json
```
Persons matched to Wikidata: 0 ✓ | 401 ✘
Parties matched to Wikidata: 8 ✓ | 1 ✘
No wikidata: Parliamentary Group of the Alliance of the center (party/parliamentary_group_of_the_alliance_of_the_center)
```
> Morocco (House): Reconcile group of Democratic Progress

- countries.json
- data/Germany/Bundestag/sources/manual/position-filter.json
- data/Germany/Bundestag/sources/wikidata/elections.json
- data/Germany/Bundestag/sources/wikidata/groups.json
- data/Germany/Bundestag/sources/wikidata/positions.json
- data/Germany/Bundestag/unstable/positions.csv
- data/Germany/Bundestag/unstable/stats.json
Refresh non Wikipedia/Wikidata sources
```
☁ Mismatch in death_date for edef6b9f-ab67-417a-9aa1-6c2e0b5ae280 (2001-05-10) vs 2001-05-09 (for Q98342)
☁ Mismatch in death_date for 1a73cd79-c798-42f5-bd15-75b514a9fa68 (2005-11-10) vs 2005-11-09 (for Q15427635)
☁ Mismatch in death_date for f177b48a-6544-4a09-b68c-9395d25295ca (1996-02-06) vs 1996-02-07 (for Q1725753)
☁ Mismatch in death_date for 4f2c210b-b0a4-4db4-b9e3-a6be36e8bef3 (1952-04-22) vs 1952-04-23 (for Q2574416)
☁ Mismatch in death_date for 47c8e9a6-fd0d-40a8-926e-86849482b4fc (1950-11-21) vs 1950-10-21 (for Q1352568)
☁ Mismatch in death_date for bb0fd1f9-8b6d-45cc-8e0e-8f5d40bbddc5 (1951-07-29) vs 1951-07-21 (for Q106049)
☁ Mismatch …
```
> Germany (Bundestag): refresh data

- countries.json
- data/Aland/Lagting/ep-popolo-v1.0.json
> AX (Lagting) — rebuild with moved Sources

- countries.json
- data/Bahamas/House_of_Assembly/ep-popolo-v1.0.json
> BS (House of Assembly) — rebuild with moved Sources

- countries.json
- data/Bahrain/Council_of_Representatives/ep-popolo-v1.0.json
> BH (Council of Representatives) — rebuild with moved Sources

- countries.json
- data/Barbados/House_of_Assembly/ep-popolo-v1.0.json
> Barbados (House of Assembly) — rebuild with moved Sources

- countries.json
- data/Estonia/Riigikogu/ep-popolo-v1.0.json
> Estonia (Riigikogu) — rebuild with moved Sources

- countries.json
- data/Macedonia/Sobranie/ep-popolo-v1.0.json
> Macedonia (Sobranie) — rebuild with moved Sources

- countries.json
- data/Malawi/Assembly/ep-popolo-v1.0.json
> Malawi (Assembly) — rebuild with moved Sources

- countries.json
- data/Mali/Assembly/ep-popolo-v1.0.json
> Mali (Assembly) — rebuild with moved Sources

- countries.json
- data/Malta/Assembly/ep-popolo-v1.0.json
> Malta (Assembly) — rebuild with moved Sources

- countries.json
- data/Marshall_Islands/Nitijela/ep-popolo-v1.0.json
> Marshall Islands (Nitijela) — rebuild with moved Sources

- countries.json
- data/Mauritius/National_Assembly/ep-popolo-v1.0.json
> Mauritius (National Assembly) — rebuild with moved Sources

- countries.json
- data/Mexico/Deputies/ep-popolo-v1.0.json
> Mexico (Deputies) — rebuild with moved Sources

- countries.json
- data/Monaco/Council/ep-popolo-v1.0.json
> Monaco (Council) — rebuild with moved Sources

- countries.json
- data/Macao/Assembly/ep-popolo-v1.0.json
> Macao (Assembly) — rebuild with moved Sources

- countries.json
- data/Kuwait/National_Assembly/ep-popolo-v1.0.json
> Kuwait (National Assembly) — rebuild with moved Sources

- countries.json
- data/Kyrgyzstan/Council/ep-popolo-v1.0.json
> Kyrgyzstan (Council) — rebuild with moved Sources

- countries.json
- data/Latvia/Saeima/ep-popolo-v1.0.json
> Latvia (Saeima) — rebuild with moved Sources

- countries.json
- data/Lebanon/Parliament/ep-popolo-v1.0.json
> Lebanon (Parliament) — rebuild with moved Sources

- countries.json
- data/Lesotho/Assembly/ep-popolo-v1.0.json
> Lesotho (Assembly) — rebuild with moved Sources

- countries.json
- data/Liberia/House/ep-popolo-v1.0.json
> Liberia (House) — rebuild with moved Sources

- countries.json
- data/Liechtenstein/Landtag/ep-popolo-v1.0.json
> Liechtenstein (Landtag) — rebuild with moved Sources

- countries.json
- data/Lithuania/Seimas/ep-popolo-v1.0.json
> Lithuania (Seimas) — rebuild with moved Sources

- countries.json
- data/Luxembourg/Chamber/ep-popolo-v1.0.json
> Luxembourg (Chamber) — rebuild with moved Sources

- countries.json
- data/Netherlands/House_of_Representatives/ep-popolo-v1.0.json
> Netherlands (House of Representatives) — rebuild with moved Sources

- countries.json
- data/Nagorno_Karabakh/Assembly/ep-popolo-v1.0.json
> Nagorno Karabakh (Assembly) — rebuild with moved Sources

- countries.json
- data/Myanmar/House_of_Representatives/ep-popolo-v1.0.json
> Myanmar (House of Representatives) — rebuild with moved Sources

- countries.json
- data/Mozambique/Assembly/ep-popolo-v1.0.json
> Mozambique (Assembly) — rebuild with moved Sources

- countries.json
- data/Montserrat/Assembly/ep-popolo-v1.0.json
> Montserrat (Assembly) — rebuild with moved Sources

- countries.json
- data/Montenegro/Assembly/ep-popolo-v1.0.json
> Montenegro (Assembly) — rebuild with moved Sources

- countries.json
- data/Jersey/States/ep-popolo-v1.0.json
> Jersey (States) — rebuild with moved Sources

- countries.json
- data/Japan/House_of_Representatives/ep-popolo-v1.0.json
> Japan (House of Representatives) — rebuild with moved Sources

- countries.json
- data/Italy/House/ep-popolo-v1.0.json
> Italy (House) — rebuild with moved Sources

- countries.json
> Israel (Knesset) — rebuild with moved Sources

- countries.json
- data/Isle_of_Man/House_of_Keys/ep-popolo-v1.0.json
> Isle of Man (House of Keys) — rebuild with moved Sources

- countries.json
- data/Indonesia/Council/ep-popolo-v1.0.json
> Indonesia (Council) — rebuild with moved Sources

- countries.json
- data/India/Lok_Sabha/ep-popolo-v1.0.json
> India (Lok Sabha) — rebuild with moved Sources

- countries.json
- data/New_Caledonia/Congress/ep-popolo-v1.0.json
> New Caledonia (Congress) — rebuild with moved Sources

- countries.json
- data/Niger/Assembly/ep-popolo-v1.0.json
> Niger (Assembly) — rebuild with moved Sources

- countries.json
- data/Niue/Assembly/ep-popolo-v1.0.json
> Niue (Assembly) — rebuild with moved Sources

- countries.json
- data/Norfolk_Island/Assembly/ep-popolo-v1.0.json
> Norfolk Island (Assembly) — rebuild with moved Sources

- countries.json
- data/Jordan/House_of_Representatives/ep-popolo-v1.0.json
> Jordan (House of Representatives) — rebuild with moved Sources

- countries.json
- data/Kazakhstan/Assembly/ep-popolo-v1.0.json
> Kazakhstan (Assembly) — rebuild with moved Sources

- countries.json
- data/Kenya/Assembly/ep-popolo-v1.0.json
> Kenya (Assembly) — rebuild with moved Sources

- countries.json
- data/Kiribati/Parliament/ep-popolo-v1.0.json
> Kiribati (Parliament) — rebuild with moved Sources

- countries.json
- data/Haiti/Deputies/ep-popolo-v1.0.json
> Haiti (Deputies) — rebuild with moved Sources

- countries.json
- data/Hong_Kong/Legislative_Council/ep-popolo-v1.0.json
> Hong Kong (Legislative Council) — rebuild with moved Sources

- countries.json
- data/Hungary/Assembly/ep-popolo-v1.0.json
> Hungary (Assembly) — rebuild with moved Sources

- countries.json
- data/Iceland/Assembly/ep-popolo-v1.0.json
> Iceland (Assembly) — rebuild with moved Sources

- countries.json
- data/Guinea-Bissau/Assembly/ep-popolo-v1.0.json
> Guinea-Bissau (Assembly) — rebuild with moved Sources

- countries.json
- data/Northern_Cyprus/Assembly/ep-popolo-v1.0.json
> Northern Cyprus (Assembly) — rebuild with moved Sources

- countries.json
- data/Northern_Mariana_Islands/House/ep-popolo-v1.0.json
> Northern Mariana Islands (House) — rebuild with moved Sources

- countries.json
- data/Nicaragua/Asamblea/ep-popolo-v1.0.json
> Nicaragua (Asamblea) — rebuild with moved Sources

- countries.json
- data/North_Korea/National_Assembly/ep-popolo-v1.0.json
> North Korea (National Assembly) — rebuild with moved Sources

- countries.json
- data/Guernsey/States/ep-popolo-v1.0.json
> Guernsey (States) — rebuild with moved Sources

- countries.json
- data/Guatemala/Congress/ep-popolo-v1.0.json
> Guatemala (Congress) — rebuild with moved Sources

- countries.json
- data/Guyana/National_Assembly/ep-popolo-v1.0.json
> Guyana (National Assembly) — rebuild with moved Sources

- countries.json
- data/Grenada/House_of_Representatives/ep-popolo-v1.0.json
> Grenada (House of Representatives) — rebuild with moved Sources

- countries.json
- data/France/National_Assembly/sources/manual/position-filter.json
> France (National Assembly) — rebuild with moved Sources

- countries.json
- data/French_Polynesia/Assembly/ep-popolo-v1.0.json
> French Polynesia (Assembly) — rebuild with moved Sources

- countries.json
- data/Dominican_Republic/Diputados/ep-popolo-v1.0.json
> Dominican Republic (Diputados) — rebuild with moved Sources

- countries.json
- data/Gabon/Assembly/ep-popolo-v1.0.json
> Gabon (Assembly) — rebuild with moved Sources

- countries.json
- data/Gambia/National_Assembly/ep-popolo-v1.0.json
> Gambia (National Assembly) — rebuild with moved Sources

- countries.json
- data/Georgia/Parliament/ep-popolo-v1.0.json
> Georgia (Parliament) — rebuild with moved Sources

- countries.json
- data/Bermuda/Assembly/ep-popolo-v1.0.json
> Bermuda (Assembly) — rebuild with moved Sources

- countries.json
- data/Bosnia_and_Herzegovina/House_of_Representatives/ep-popolo-v1.0.json
> Bosnia and Herzegovina (House of Representatives) — rebuild with moved Sources

- countries.json
- data/Benin/National_Assembly/ep-popolo-v1.0.json
> Benin (National Assembly) — rebuild with moved Sources

- countries.json
- data/Bolivia/Deputies/ep-popolo-v1.0.json
> Bolivia (Deputies) — rebuild with moved Sources

- countries.json
- data/Brunei/Legislative_Council/ep-popolo-v1.0.json
> Brunei (Legislative Council) — rebuild with moved Sources

- countries.json
- data/Botswana/Assembly/ep-popolo-v1.0.json
> Botswana (Assembly) — rebuild with moved Sources

- countries.json
- data/Brazil/Deputies/ep-popolo-v1.0.json
> Brazil (Deputies) — rebuild with moved Sources

- countries.json
- data/Bulgaria/National_Assembly/ep-popolo-v1.0.json
> Bulgaria (National Assembly) — rebuild with moved Sources

- countries.json
- data/Belize/Representatives/ep-popolo-v1.0.json
- data/Bhutan/Assembly/ep-popolo-v1.0.json
> Belize (Representatives) — rebuild with moved Sources

- countries.json
- data/Burundi/Assembly/ep-popolo-v1.0.json
> Burundi (Assembly) — rebuild with moved Sources

- countries.json
> Germany (Bundestag) — rebuild with moved Sources

- countries.json
- data/Burkina_Faso/Assembly/ep-popolo-v1.0.json
> Burkina Faso (Assembly) — rebuild with moved Sources

- countries.json
- data/Cabo_Verde/Assembly/ep-popolo-v1.0.json
> Cabo Verde (Assembly) — rebuild with moved Sources

- countries.json
- data/Cambodia/National_Assembly/ep-popolo-v1.0.json
> Cambodia (National Assembly) — rebuild with moved Sources

- countries.json
- data/Canada/Commons/ep-popolo-v1.0.json
> Canada (Commons) — rebuild with moved Sources

- countries.json
- data/Colombia/Representatives/ep-popolo-v1.0.json
> Colombia (Representatives) — rebuild with moved Sources

- countries.json
- data/Congo-Brazzaville/Assembly/ep-popolo-v1.0.json
> Congo-Brazzaville (Assembly) — rebuild with moved Sources

- countries.json
- data/Costa_Rica/Assembly/ep-popolo-v1.0.json
> Costa Rica (Assembly) — rebuild with moved Sources

- countries.json
- data/Croatia/Sabor/ep-popolo-v1.0.json
> Croatia (Sabor) — rebuild with moved Sources

- countries.json
- data/Curacao/Estates/ep-popolo-v1.0.json
> Curacao (Estates) — rebuild with moved Sources

- countries.json
- data/Denmark/Folketing/ep-popolo-v1.0.json
> Denmark (Folketing) — rebuild with moved Sources

- countries.json
- data/El_Salvador/Legislative_Assembly/ep-popolo-v1.0.json
> El Salvador (Legislative Assembly) — rebuild with moved Sources

- countries.json
- data/Bangladesh/House/ep-popolo-v1.0.json
> Bangladesh (House) — rebuild with moved Sources

- countries.json
- data/Falkland_Islands/Assembly/ep-popolo-v1.0.json
> Falkland Islands (Assembly) — rebuild with moved Sources

- countries.json
- data/Fiji/Parliament/ep-popolo-v1.0.json
> Fiji (Parliament) — rebuild with moved Sources

- countries.json
- data/Finland/Eduskunta/ep-popolo-v1.0.json
> Finland (Eduskunta) — rebuild with moved Sources

- countries.json
- data/Moldova/Parlamentul/ep-popolo-v1.0.json
> Moldova (Parlamentul) — rebuild with moved Sources

- countries.json
> Sweden (Riksdag) — rebuild with moved Sources

- countries.json
- data/Namibia/Assembly/ep-popolo-v1.0.json
> Namibia (Assembly) — rebuild with moved Sources

- countries.json
- data/Nigeria/Assembly/ep-popolo-v1.0.json
> Nigeria (Assembly) — rebuild with moved Sources

- countries.json
- data/Paraguay/Deputies/ep-popolo-v1.0.json
> Paraguay (Deputies) — rebuild with moved Sources

- countries.json
- data/Panama/Assembly/ep-popolo-v1.0.json
> Panama (Assembly) — rebuild with moved Sources

- countries.json
- data/Pakistan/Assembly/ep-popolo-v1.0.json
> Pakistan (Assembly) — rebuild with moved Sources

- countries.json
- data/Philippines/House/ep-popolo-v1.0.json
> Philippines (House) — rebuild with moved Sources

- countries.json
- data/Peru/Congreso/ep-popolo-v1.0.json
> Peru (Congreso) — rebuild with moved Sources

- countries.json
- data/Cayman_Islands/Legislative_Assembly/ep-popolo-v1.0.json
> Cayman Islands (Legislative Assembly) — rebuild with moved Sources

- countries.json
- data/Rwanda/Deputies/ep-popolo-v1.0.json
> Rwanda (Deputies) — rebuild with moved Sources

- countries.json
- data/Saint_Barthelemy/Council/ep-popolo-v1.0.json
> Saint Barthelemy (Council) — rebuild with moved Sources

- countries.json
- data/Saint_Helena/Legislative_Council/ep-popolo-v1.0.json
> Saint Helena (Legislative Council) — rebuild with moved Sources

- countries.json
- data/Puerto_Rico/House_of_Representatives/ep-popolo-v1.0.json
> Puerto Rico (House of Representatives) — rebuild with moved Sources

- countries.json
- data/Romania/Deputies/ep-popolo-v1.0.json
> Romania (Deputies) — rebuild with moved Sources

- countries.json
- data/Russia/Duma/ep-popolo-v1.0.json
> Russia (Duma) — rebuild with moved Sources

- countries.json
- data/Pitcairn/Island_Council/ep-popolo-v1.0.json
> Pitcairn (Island Council) — rebuild with moved Sources

- countries.json
> Poland (Sejm) — rebuild with moved Sources

- countries.json
- data/Saint_Vincent_and_the_Grenadines/Assembly/ep-popolo-v1.0.json
> Saint Vincent and the Grenadines (Assembly) — rebuild with moved Sources

- countries.json
- data/Saint_Pierre_and_Miquelon/Territorial_Council/ep-popolo-v1.0.json
> Saint Pierre and Miquelon (Territorial Council) — rebuild with moved Sources

- countries.json
- data/Saint_Martin/Council/ep-popolo-v1.0.json
> Saint Martin (Council) — rebuild with moved Sources

- countries.json
- data/Italy/Senate/ep-popolo-v1.0.json
> Italy (Senate) — rebuild with moved Sources

- countries.json
- data/Zimbabwe/Senate/ep-popolo-v1.0.json
> Zimbabwe (Senate) — rebuild with moved Sources

- countries.json
- data/Trinidad_and_Tobago/Senate/ep-popolo-v1.0.json
> Trinidad and Tobago (Senate) — rebuild with moved Sources

- countries.json
- data/Taiwan/Legislative_Yuan/ep-popolo-v1.0.json
> Taiwan (Legislative Yuan) — rebuild with moved Sources

- countries.json
- data/Syria/Majlis/ep-popolo-v1.0.json
> Syria (Majlis) — rebuild with moved Sources

- countries.json
- data/Timor_Leste/Parlamento/ep-popolo-v1.0.json
> Timor Leste (Parlamento) — rebuild with moved Sources

- countries.json
- data/Transnistria/Supreme_Council/ep-popolo-v1.0.json
> Transnistria (Supreme Council) — rebuild with moved Sources

- countries.json
- data/Tonga/Assembly/ep-popolo-v1.0.json
> Tonga (Assembly) — rebuild with moved Sources

- countries.json
- data/Uruguay/Deputies/ep-popolo-v1.0.json
> Uruguay (Deputies) — rebuild with moved Sources

- countries.json
- data/Uganda/Parliament/ep-popolo-v1.0.json
> Uganda (Parliament) — rebuild with moved Sources

- countries.json
- data/US_Virgin_Islands/Legislature/ep-popolo-v1.0.json
> US Virgin Islands (Legislature) — rebuild with moved Sources

- countries.json
- data/Venezuela/Assembly/ep-popolo-v1.0.json
> Venezuela (Assembly) — rebuild with moved Sources

- countries.json
- data/Wales/Assembly/ep-popolo-v1.0.json
> Wales (Assembly) — rebuild with moved Sources

- countries.json
- data/Zambia/Assembly/ep-popolo-v1.0.json
> Zambia (Assembly) — rebuild with moved Sources

- countries.json
- data/Zimbabwe/Assembly/ep-popolo-v1.0.json
> Zimbabwe (Assembly) — rebuild with moved Sources

- countries.json
- data/Namibia/Council/ep-popolo-v1.0.json
> Namibia (Council) — rebuild with moved Sources

- countries.json
- data/Uzbekistan/Legislative_Chamber/ep-popolo-v1.0.json
> Uzbekistan (Legislative Chamber) — rebuild with moved Sources

- countries.json
- data/Vanuatu/Parliament/ep-popolo-v1.0.json
> Vanuatu (Parliament) — rebuild with moved Sources

- countries.json
- data/Senegal/Assembly/ep-popolo-v1.0.json
> Senegal (Assembly) — rebuild with moved Sources

- countries.json
- data/Sark/Chief_Pleas/ep-popolo-v1.0.json
> Sark (Chief Pleas) — rebuild with moved Sources

- countries.json
- data/Seychelles/Assembly/ep-popolo-v1.0.json
> Seychelles (Assembly) — rebuild with moved Sources

- countries.json
- data/Serbia/National_Assembly/ep-popolo-v1.0.json
> Serbia (National Assembly) — rebuild with moved Sources

- countries.json
- data/Somalia/Lower/ep-popolo-v1.0.json
> Somalia (Lower) — rebuild with moved Sources

- countries.json
- data/Solomon_Islands/Parliament/ep-popolo-v1.0.json
> Solomon Islands (Parliament) — rebuild with moved Sources

- countries.json
- data/Tanzania/Assembly/ep-popolo-v1.0.json
> Tanzania (Assembly) — rebuild with moved Sources

- countries.json
- data/Thailand/National_Legislative_Assembly/ep-popolo-v1.0.json
> Thailand (National Legislative Assembly) — rebuild with moved Sources

- countries.json
- data/Trinidad_and_Tobago/Representatives/ep-popolo-v1.0.json
> Trinidad and Tobago (Representatives) — rebuild with moved Sources

- countries.json
- data/Sri_Lanka/Parliament/ep-popolo-v1.0.json
> Sri Lanka (Parliament) — rebuild with moved Sources

- countries.json
- data/Suriname/Assembly/ep-popolo-v1.0.json
> Suriname (Assembly) — rebuild with moved Sources

- countries.json
- data/Tajikistan/Representatives/ep-popolo-v1.0.json
> Tajikistan (Representatives) — rebuild with moved Sources

- countries.json
- data/Tunisia/Majlis/ep-popolo-v1.0.json
> Tunisia (Majlis) — rebuild with moved Sources

- countries.json
- data/Turkmenistan/Mejlis/ep-popolo-v1.0.json
> Turkmenistan (Mejlis) — rebuild with moved Sources

- countries.json
- data/Turks_and_Caicos_Islands/Assembly/ep-popolo-v1.0.json
> Turks and Caicos Islands (Assembly) — rebuild with moved Sources

- countries.json
- data/South_Korea/National_Assembly/ep-popolo-v1.0.json
> South Korea (National Assembly) — rebuild with moved Sources

- countries.json
- data/South_Ossetia/Parliament/ep-popolo-v1.0.json
> South Ossetia (Parliament) — rebuild with moved Sources

- countries.json
- data/South_Sudan/Assembly/ep-popolo-v1.0.json
> South Sudan (Assembly) — rebuild with moved Sources

- countries.json
- data/Somaliland/Representatives/ep-popolo-v1.0.json
> Somaliland (Representatives) — rebuild with moved Sources

- countries.json
- data/South_Africa/Assembly/ep-popolo-v1.0.json
> South Africa (Assembly) — rebuild with moved Sources

- countries.json
- data/San_Marino/Council/ep-popolo-v1.0.json
> San Marino (Council) — rebuild with moved Sources

- countries.json
- data/Slovakia/National_Council/ep-popolo-v1.0.json
> Slovakia (National Council) — rebuild with moved Sources

- countries.json
- data/Slovenia/National_Assembly/ep-popolo-v1.0.json
> Slovenia (National Assembly) — rebuild with moved Sources

- countries.json
- data/Morocco/House/ep-popolo-v1.0.json
> Morocco (House) — rebuild with moved Sources

- countries.json
- data/Aruba/Estates/ep-popolo-v1.0.json
> Aruba (Estates) — rebuild with moved Sources

- countries.json
- data/Armenia/Assembly/ep-popolo-v1.0.json
> Armenia (Assembly) — rebuild with moved Sources

- countries.json
- data/Antigua_and_Barbuda/Representatives/ep-popolo-v1.0.json
> Antigua and Barbuda (Representatives) — rebuild with moved Sources

- countries.json
- data/Belarus/Chamber/ep-popolo-v1.0.json
> Belarus (Chamber) — rebuild with moved Sources

- countries.json
- data/Austria/Nationalrat/ep-popolo-v1.0.json
> Austria (Nationalrat) — rebuild with moved Sources

- countries.json
- data/Australia/Representatives/ep-popolo-v1.0.json
> Australia (Representatives) — rebuild with moved Sources

- countries.json
> Greece (Parliament) — rebuild with moved Sources

- countries.json
- data/Ecuador/Asamblea/ep-popolo-v1.0.json
> Ecuador (Asamblea) — rebuild with moved Sources

- countries.json
- data/Djibouti/Assembly/ep-popolo-v1.0.json
> Djibouti (Assembly) — rebuild with moved Sources

- countries.json
- data/Ivory_Coast/Assembly/ep-popolo-v1.0.json
> Ivory Coast (Assembly) — rebuild with moved Sources

- countries.json
- data/Belgium/Representatives/ep-popolo-v1.0.json
> Belgium (Representatives) — rebuild with moved Sources

- countries.json
- data/Iraq/Majlis/ep-popolo-v1.0.json
> Iraq (Majlis) — rebuild with moved Sources

- countries.json
- data/Colombia/Senate/ep-popolo-v1.0.json
> Colombia (Senate) — rebuild with moved Sources

- countries.json
- data/Australia/Senate/ep-popolo-v1.0.json
> Australia (Senate) — rebuild with moved Sources

- countries.json
- data/British_Virgin_Islands/Council/ep-popolo-v1.0.json
> British Virgin Islands (Council) — rebuild with moved Sources

- countries.json
- data/Kosovo/Assembly/ep-popolo-v1.0.json
> Kosovo (Assembly) — rebuild with moved Sources

- countries.json
- data/Iran/Assembly/ep-popolo-v1.0.json
- data/Iran/Assembly/sources/google/term-10-sheet.csv
> Iran (Assembly) — rebuild with moved Sources

- bin/dashboard.rb
Report on the email/facebook/twitter counts added in https://github.com/everypolitician/everypolitician-data/pull/22628
Also switch from reporting on plain executive positions to cabinet positions.
> Dashboard: add contact info information

- rake_build/generate_final_csvs.rb
We're gradually migrating everything to using the library, rather than
acting directly on the JSON.
> use EveryPolitician::Popolo for `top_identifiers`

- rake_build/generate_final_csvs.rb
We're gradually migrating everything to using the library, rather than
acting directly on the JSON.
> use EveryPolitician::Popolo for `name_list`

- rake_build/generate_final_csvs.rb
We're gradually migrating everything to using the library, rather than
acting directly on the JSON.
> use EveryPolitician::Popolo for Wikidata `reports`

- countries.json
- data/Saint_Lucia/Assembly/ep-popolo-v1.0.json
- data/Saint_Lucia/Assembly/sources/instructions.json
- data/Saint_Lucia/Assembly/sources/morph/members.csv
```
Merging with sources/morph/images.csv
* 17 of 40 unmatched
{:name=>"Ernest Hilaire", :id=>"ernest-hilaire"}
{:name=>"Dr. Gale T C Rigobert", :id=>"dr.-gale-t-c-rigobert"}
{:name=>"Shawn Andrey Edward", :id=>"shawn-andrey-edward"}
{:name=>"John Bradley Felix", :id=>"john-bradley-felix"}
{:name=>"Sarah Flood Beaubrun", :id=>"sarah-flood-beaubrun"}
{:name=>"Herold A. Stanislas", :id=>"herold-a.-stanislas"}
{:name=>"Phillip J. Pierre", :id=>"phillip-j.-pierre"}
{:name=>"Peter Foster", :id=>"peter-foster"}
{:name=>"Allen M. Chastanet", :id=>"allen-m.-chastanet"}
{:name=>"Dominic Francis Fedee", :id=>"dominic-francis-fedee"}
Merging with …
```
> Saint Lucia (Assembly): reinstate source field

- countries.json
- data/Jamaica/House_of_Representatives/ep-popolo-v1.0.json
- data/Jamaica/House_of_Representatives/sources/instructions.json
- data/Jamaica/House_of_Representatives/sources/morph/wikipedia.csv
```
Merging with sources/morph/jmelections.csv
* 81 of 152 unmatched
{:id=>"terrence_lindo"}
{:id=>"joseph_hilton"}
{:id=>"delroy_slowley"}
{:id=>"patrick_roberts"}
{:id=>"hidran_mckulsky"}
{:id=>"wynter_mcintosh"}
{:id=>"norris_grant"}
{:id=>"noel_donaldson"}
{:id=>"dennis_messias"}
{:id=>"joseph_patterson"}
36 x wikidata
15 x freebase
5 x viaf
5 x lcauth
2 x imdb
Unknown position (x1): Q6508542 Leader of the Opposition — e.g. Q57597
Persons matched to …
```
> Jamaica (House of Representatives): reinstate source field

- countries.json
- data/Isle_of_Man/House_of_Keys/ep-popolo-v1.0.json
- data/Isle_of_Man/House_of_Keys/sources/instructions.json
- data/Isle_of_Man/House_of_Keys/sources/morph/members.csv
```
Add memberships from sources/manual/vanished.csv
Merging with sources/morph/images.csv
* 1 of 25 unmatched
{:id=>"bootgg", :name=>"Geoffrey George BOOT MHK"}
☁ Mismatch in birth_date for 36c0cc0b-feef-4de0-b077-b6c73441b442 (1948-09-03) vs 1950 (for Q5107888)
☁ Mismatch in wikipedia__en for 466039a1-814a-47c1-bb83-a44e6dccb560 (David Anderson (Isle of Man)) vs David Anderson (Manx politician) (for Q5230767)
☁ Mismatch in wikipedia__en for 072f50b4-d028-40cf-9aba-c946cd85a271 (John Houghton (Isle of Man)) vs John Houghton (politician) (for Q6239980) …
```
> Isle of Man (House of Keys): reinstate source field

- countries.json
- data/Canada/Commons/ep-popolo-v1.0.json
- data/Canada/Commons/sources/instructions.json
- data/Canada/Commons/sources/morph/wikipedia.csv
```
Merging with sources/morph/parlinfo.csv
Merging with sources/morph/data-41.csv
Merging with sources/morph/data-42.csv
☁ Mismatch in birth_date for 2db1d615-ccaa-4b6c-801d-74d35908a298 (1955-12-04) vs 1955-12-05 (for Q16187027)
☁ Mismatch in birth_date for bbd2c72c-64c4-40b0-8b67-e45119436f44 (1962-03-17) vs 1963-03-17 (for Q1841200)
☁ Mismatch in birth_date for 496d4ddd-e7f1-4c85-8bbc-df1d614b5f92 (1974-11-17) vs 1974-11-14 (for Q3528703)
☁ Mismatch in birth_date for 2deea873-d085-484c-b87b-04751ecc1b28 (1959-09-28) vs 1959-09-23 (for Q5241099)
☁ Mismatch in birth_date for cbbf1698-de8a-4ab7-ae84-731be1f26449 …
```
> Canada (Commons): reinstate source field

- data/British_Virgin_Islands/Assembly/ep-popolo-v1.0.json
- data/British_Virgin_Islands/Assembly/sources/instructions.json
- data/British_Virgin_Islands/Assembly/sources/morph/members.csv
```
* 6 of 13 unmatched
{:id=>"Q691131", :name=>"Willard Wheatley"}
{:id=>"Q7703251", :name=>"Terrance B. Lettsome"}
{:id=>"Q16873237", :name=>"Qwominer William Osborne"}
{:id=>"Q518666", :name=>"Hamilton Lavity Stoutt"}
{:id=>"Q16866678", :name=>"Conrad Maduro"}
{:id=>"Q1148676", :name=>"Cyril Romney"}
⚥ data for 15; 15 added
7 x wikidata
2 x freebase
Persons matched to Wikidata: 7 ✓ | 16 ✘
No wikidata: Mark Vanterpool (874b8f2b-5e30-461c-af74-6d89a60b430c)
No wikidata: Andrew Fahie …
```
> British Virgin Islands (Assembly): reinstate source field

- countries.json
- data/Falkland_Islands/Assembly/ep-popolo-v1.0.json
- data/Falkland_Islands/Assembly/sources/instructions.json
- data/Falkland_Islands/Assembly/sources/morph/wikipedia.csv
```
⚥ data for 75; 36 added
20 x wikidata
1 x freebase
1 x clara
1 x viaf
Persons matched to Wikidata: 20 ✓ | 29 ✘
No wikidata: Philip Miller (49d8b8f1-9b59-46aa-9983-84d9589a8db4)
No wikidata: William Henry Goss (72a1c546-2e4d-4919-9669-6bcb59fcd5e2)
No wikidata: John Edward Cheek (c636cd6f-fb28-4606-8891-a2ebd02b08dc)
No wikidata: Eric Goss (e2a486d2-67d0-4799-a7de-470c18e66642)
No wikidata: Harold Rowlands (f0c31a11-1ad4-4d7a-8bf6-eca28b529d4a)
No …
```
> Falkland Islands (Assembly): reinstate source field

- countries.json
- data/Mongolia/Assembly/ep-popolo-v1.0.json
- data/Mongolia/Assembly/sources/manual/terms.csv
- data/Mongolia/Assembly/unstable/stats.json
Separate Wikidata items did not exist for the terms so these were created.
(Cherry-picked from https://github.com/everypolitician/everypolitician-data/pull/22451)
```
* 1 of 72 unmatched
{:id=>"212", :name=>"SARANGEREL Davaajantsan"}
* 14 of 47 unmatched
{:id=>"Q24174855", :name=>"Агипарын Бакей"}
{:id=>"Q7281459", :name=>"Radnaasumbereliyn Gonchigdorj"}
{:id=>"Q24174857", :name=>"Мигэддоржийн Батчимэг"}
{:id=>"Q24174849", :name=>"Лувсанцэрэнгийн Энх-Амгалан"}
{:id=>"Q23771599", :name=>"Nyamaagiin Enkhbold"}
{:id=>"Q7070853", :name=>"Nyamjavyn Batbayar"}
{:id=>"Q25848773", :name=>"Жаргалтулгын Эрдэнэбат"}
{:id=>"Q24174853", …
```
> Mongolia (Assembly): Add Wikidata references to terms

- countries.json
- data/Sint_Maarten/Estates/ep-popolo-v1.0.json
- data/Sint_Maarten/Estates/sources/manual/terms.csv
- data/Sint_Maarten/Estates/unstable/stats.json
For details about when the parliament starts and ends (distinct from the
election dates), see the explanation here:
http://www.kabgsxm.com/news-entry.aspx?language=EN&id_news=141
(Cherry-picked from https://github.com/everypolitician/everypolitician-data/pull/17313)
```
Add memberships from sources/manual/official_term2.csv
Persons matched to Wikidata: 0 ✓ | 17 ✘
```
> Sint Maarten (Estates): Add new term dates

- Gemfile.lock
We want to use the version that doesn't report on terms and elections
unless there have been changes.
https://github.com/everypolitician/everypolitician-pull_request/pull/14
> update version of everypolitician-pull_request

- data/Mexico/Deputies/sources/instructions.json
Switch source of primary scraper from tmtmtmtm to everypolitician-scrapers
(There was no change in data)
> Mexico (Deputies): switch to EP morph source

- countries.json
- data/Belize/Representatives/ep-popolo-v1.0.json
- data/Belize/Representatives/sources/manual/terms.csv
- data/Belize/Representatives/sources/wikidata/elections.json
- data/Belize/Representatives/unstable/stats.json
New member data to follow
```
* 3 of 16 unmatched
{:id=>"Q7121680", :name=>"Pablo Marin"}
{:id=>"Q6256510", :name=>"John Saldivar"}
{:id=>"Q7146470", :name=>"Patrick Faber"}
⚥ data for 14; 14 added
13 x wikidata
3 x freebase
2 x viaf
2 x munzinger
2 x gnd
Unknown position (x1): Q121998 ambassador — e.g. Q5289506
Persons matched to Wikidata: 13 ✓ | 14 ✘
No wikidata: Herman R. Longsworth (c7fbeb75-652b-488f-8578-78d3b8fb645e)
No wikidata: Julius Espat (22696b1e-b7b5-48a1-8069-e2c0b151e768)
No wikidata: Michael Joseph Espat …
```
> Belize: Add info for 2015 term + election

- countries.json
- data/Turks_and_Caicos_Islands/Assembly/ep-popolo-v1.0.json
- data/Turks_and_Caicos_Islands/Assembly/sources/manual/terms.csv
- data/Turks_and_Caicos_Islands/Assembly/sources/wikidata/elections.json
- data/Turks_and_Caicos_Islands/Assembly/unstable/stats.json
```
Merging with sources/morph/wikipedia.csv
* 1 of 15 unmatched
{:name=>"Edwin Astwood", :id=>"edwin_astwood"}
⚥ data for 12; 12 added
6 x wikidata
1 x freebase
Persons matched to Wikidata: 6 ✓ | 12 ✘
No wikidata: George Alexander Lightbourne (dc1c0d1b-bcd4-483a-8be0-9bd8754e35f4)
No wikidata: Porsha Monique Stubbs-Smith (51931afb-361d-4d2a-9873-c692d6e79b78)
No wikidata: Ruth Delores Blackman (f6d8ace4-f66c-4260-a906-b17938a4dfdf)
No wikidata: Goldray McMillin Ewing (99a7157d-5b4c-46d7-a194-67f5e80da4fa)
No wikidata: John Philips …
```
> Turks and Caicos (Assembly): add new Term data

- rake_config/vanishing_data.rb
Rather than a single `missing_data:memberships` task, expand this to
report on rows either added or removed from a file. The interface is
now:
* `rake changing_sources:added_rows[source]`
* `rake changing_sources:removed_rows[source]`
> Extend the missing_data task to changing_sources

- countries.json
- data/Belarus/Chamber/ep-popolo-v1.0.json
- data/Belarus/Chamber/sources/instructions.json
The source URL for term five memberships had been previously given as the URL of the
national assembly of Belize.
> Belarus House of Representatives -- Correct source url

- countries.json
- data/Curacao/Estates/ep-popolo-v1.0.json
- data/Curacao/Estates/sources/manual/terms.csv
- data/Curacao/Estates/unstable/stats.json
Using `generate_terms_from_wikidata.rb Q28479622`
```
⚥ data for 21; 21 added
Persons matched to Wikidata: 0 ✓ | 21 ✘
Parties matched to Wikidata: 7 ✓ 
```
> Curacao (Estates): generate new Term file

- countries.json
- data/India/Lok_Sabha/ep-popolo-v1.0.json
- data/India/Lok_Sabha/sources/manual/terms.csv
- data/India/Lok_Sabha/unstable/stats.json
```
☁ Mismatch in birth_date for 58706936-ee16-4050-a9fb-0152ad829010 (1953-03-18) vs 1953-03-19 (for Q1151446)
☁ Mismatch in birth_date for 8eeabc90-1cd2-4892-945b-494bab577e69 (1951-09-22) vs 1952 (for Q13110635)
☁ Mismatch in birth_date for 35ad9676-8485-4137-9a16-50f2844f3ab2 (1956-05-08) vs 1955-06-01 (for Q13121505)
☁ Mismatch in birth_date for 15c7ed1a-ea43-4075-a27a-31f2377dd96e (1947-03-05) vs 1947-10-07 (for Q14922951)
☁ Mismatch in birth_date for 074e09de-ed01-4e76-b7e3-12f7cbf4e7cb (1963-07-06) vs 1965 (for Q15991037)
☁ Mismatch in birth_date for 08f950c3-ea03-4cb2-b1ec-78df35136ced (1942-01-01) vs 1959-11-05 (for Q16105883) …
```
> India (Lok Sabha): add Wikidata term information

- .travis.yml
We don't want the utility tasks to cause the build to fail, so run it
separately and then swallow any errors.
Fixes https://github.com/everypolitician/everypolitician/issues/565
> Run utility tasks on Travis separately

- countries.json
- data/Hong_Kong/Legislative_Council/ep-popolo-v1.0.json
- data/Hong_Kong/Legislative_Council/sources/manual/terms.csv
- data/Hong_Kong/Legislative_Council/unstable/stats.json
> Hong Kong: Wikidata ids for terms

- countries.json
- data/Ukraine/Verkhovna_Rada/ep-popolo-v1.0.json
- data/Ukraine/Verkhovna_Rada/sources/manual/terms.csv
- data/Ukraine/Verkhovna_Rada/unstable/stats.json
> Ukraine: Wikidata id

- countries.json
- data/Vietnam/National_Assembly/ep-popolo-v1.0.json
- data/Vietnam/National_Assembly/sources/manual/terms.csv
- data/Vietnam/National_Assembly/unstable/stats.json
Better than the wikipedia article
> Vietnam: Wikidata id

- countries.json
- data/Sri_Lanka/Parliament/ep-popolo-v1.0.json
- data/Sri_Lanka/Parliament/sources/manual/terms.csv
- data/Sri_Lanka/Parliament/unstable/stats.json
> Sri Lanka: Wikidata id for term

- data/Serbia/National_Assembly/sources/manual/terms.csv
Better visualization and reading
> Serbia: add missing column to term file

- countries.json
- data/Abkhazia/Assembly/ep-popolo-v1.0.json
- data/Abkhazia/Assembly/sources/manual/terms.csv
- data/Abkhazia/Assembly/unstable/stats.json
Better than wikipedia, I believe
> Abkhazia: Wikidata ID for term

- countries.json
- data/Cook_Islands/Parliament/ep-popolo-v1.0.json
- data/Cook_Islands/Parliament/sources/manual/terms.csv
- data/Cook_Islands/Parliament/unstable/stats.json
Smaller to bigger, plus wikidata_ids where available
> Cook Islands: Wikidata IDs for terms + reordering

- countries.json
- data/Philippines/House/ep-popolo-v1.0.json
- data/Philippines/House/sources/manual/terms.csv
- data/Philippines/House/unstable/stats.json
> Philippines: Wikidata ids for terms

- countries.json
- data/Philippines/House/ep-popolo-v1.0.json
- data/Philippines/House/sources/instructions.json
- data/Philippines/House/sources/wikidata/elections.json
- data/Philippines/House/unstable/stats.json
Use the House Elections rather than the General Elections. Closes https://github.com/everypolitician/everypolitician/issues/566
```
Add memberships from sources/manual/term-16.csv
Add memberships from sources/morph/term-17.csv
* 5 of 127 unmatched
{:id=>"Q17371295", :name=>"Danilo Suarez"}
{:id=>"Q23582946", :name=>"Antonio Bravo"}
{:id=>"Q4889315", :name=>"Benjamin Tupay Loong"}
{:id=>"Q16935127", :name=>"Mikee Romero"}
{:id=>"Q4666167", :name=>"Abdulmunir Mundoc Arbison"}
⚥ data for 111; 108 added
Discarding duplicate membership: {:person_id=>"95dca552-ff90-4bc9-b03c-af80e3e05510", :organization_id=>"02e84be8-6151-4224-90bf-94d1317da396", :role=>"member", …
```
> Philippines (House): add better source for election data

- countries.json
- data/Mexico/Deputies/ep-popolo-v1.0.json
- data/Mexico/Deputies/sources/manual/terms.csv
- data/Mexico/Deputies/unstable/stats.json
> Mexico: add more term info

- countries.json
- data/Sint_Maarten/Estates/ep-popolo-v1.0.json
- data/Sint_Maarten/Estates/sources/manual/terms.csv
- data/Sint_Maarten/Estates/unstable/stats.json
Part of: https://github.com/everypolitician/everypolitician-data/issues/25778
A step towards importing new term data.
> Sint Maarten (Estates): add wikidata ids to terms

- countries.json
- data/South_Africa/Assembly/ep-popolo-v1.0.json
- data/South_Africa/Assembly/sources/manual/terms.csv
- data/South_Africa/Assembly/unstable/stats.json
Add a reference to the Wikidata Item for the current term.
> South Africa (Assembly): add Wikidata for terms

- data/Northern_Ireland/Assembly/sources/manual/terms.csv
The term file needs this information so that `parlparse-to-csv` can
assign the data.
> Northern Ireland: Add 6th Assembly term

- countries.json
- data/Swaziland/Assembly/ep-popolo-v1.0.json
- data/Swaziland/Assembly/sources/manual/terms.csv
- data/Swaziland/Assembly/unstable/stats.json
Fix overlapping terms. Part of https://github.com/everypolitician/everypolitician/issues/594
```
Add memberships from sources/manual/scraped.csv
Persons matched to Wikidata: 0 ✓ | 93 ✘
Parties matched to Wikidata: 0 ✓ | 1 ✘
Areas matched to Wikidata: 0 ✓ | 56 ✘
```
> Swaziland (Assembly): correct term dates

- countries.json
- data/Namibia/Council/ep-popolo-v1.0.json
- data/Namibia/Council/sources/instructions.json
The membership data source was recorded as being the scraper. I correct it so it now references the site URL.
> Namibia Council correct source reference

- data/Russia/Duma/ep-popolo-v1.0.json
- data/Russia/Duma/sources/manual/terms.csv
- data/Russia/Duma/unstable/stats.json
part of https://github.com/everypolitician/everypolitician/issues/590
> Russia (Duma): add Wikidata IDs for terms

- data/Brazil/Deputies/ep-popolo-v1.0.json
- data/Brazil/Deputies/sources/manual/terms.csv
- data/Brazil/Deputies/unstable/stats.json
```
Merging with sources/morph/official-55.csv
☁ Mismatch in fullname for e6b0ea34-61bf-4013-9bda-cc990ecfe8f7 (Lázaro Botelho Martins) vs LÁZARO BOTELHO MARTINS (for 5830290)
☁ Mismatch in fullname for 28dcb4d1-7190-40be-a468-8244fcbd7857 (Sérgio Luís Lacerda Brito) vs SÉRGIO LUÍS LACERDA BRITO (for 5830291)
☁ Mismatch in fullname for 927120fe-33df-4ad5-82f3-7c3078cb5a52 (Osmar José Serraglio) vs OSMAR JOSÉ SERRAGLIO (for 5830293)
☁ Mismatch in fullname for 136ddab8-0d21-45ce-a696-129f594a51cc (Bruno Cavalcanti de Araújo) vs BRUNO CAVALCANTI DE ARAÚJO (for 5830294)
☁ Mismatch in fullname for bc51ab36-1049-4a71-98ab-1acf1f2d93c5 (Carlos Felipe Vazquez de …
```
> Brazil (Deputies): add Wikidata for terms

- data/Pakistan/Assembly/ep-popolo-v1.0.json
- data/Pakistan/Assembly/sources/manual/terms.csv
- data/Pakistan/Assembly/unstable/stats.json
```
Add memberships from sources/archive/official.csv
☁ Mismatch in gender for c4f06f4f-a091-4241-8867-cf853ba4090e (male) vs female (for Q23760943)
* 17 of 364 unmatched
{:id=>"Q17287330", :name=>"Tahira Asif"}
{:id=>"Q26924336", :name=>"Muhammad Ibrahim Jatoi"}
{:id=>"Q26923887", :name=>"Sadiq Ali Memon"}
{:id=>"Q18763831", :name=>"Ashiq Husain Khan"}
{:id=>"Q19560993", :name=>"Khalil Francis"}
{:id=>"Q16194435", :name=>"Liaqat Abbas Bhatti"}
{:id=>"Q2096387", :name=>"Shahbaz Sharif"}
{:id=>"Q6956893", :name=>"Nabil Gabol"}
{:id=>"Q18816019", :name=>"Rai Mansab Ali Khan"}
{:id=>"Q26923866", :name=>"Raja Aamer Zaman"} …
```
> Pakistan (Assembly): add Wikidata for term

- data/Saint_Pierre_and_Miquelon/Territorial_Council/ep-popolo-v1.0.json
- data/Saint_Pierre_and_Miquelon/Territorial_Council/sources/manual/terms.csv
- data/Saint_Pierre_and_Miquelon/Territorial_Council/unstable/stats.json
Add new term, and link all terms to Wikidata (https://github.com/everypolitician/everypolitician/issues/590)
```
3 x wikidata
2 x freebase
2 x sycomore
1 x viaf
1 x isni
Persons matched to Wikidata: 3 ✓ | 28 ✘
No wikidata: Alain Goupillière (55f87482-e8b4-4711-b588-51bed9883e7b)
No wikidata: Marine Garnier (8e56a78c-2099-4d01-9a67-363ab3f0c715)
No wikidata: Rosiane Gautier Zimmermann (17517bf7-f966-4459-ba1f-2c64f6d82464)
No wikidata: Isabelle Ozon (947b58d7-90ee-4bc6-a485-0313bc628b47)
No wikidata: Gildas Morel (112daa01-d35a-4434-89b6-cb5ec76936bf)
No wikidata: David Dodeman …
```
> Saint Pierre and Miquelon (Territorial Council): add new Term data

- data/Italy/House/ep-popolo-v1.0.json
- data/Italy/House/sources/manual/group_wikidata.csv
- data/Italy/House/sources/wikidata/groups.json
- data/Italy/House/unstable/stats.json
Slight mismatches between groups and parties, but I think these should be close enough.
```
Add memberships from sources/morph/camera.csv
Merging with sources/morph/openpolis.csv
☁ Mismatch in birth_date for 36c77839-d25d-4e51-9598-df91a443e864 (1971-09-30) vs 1971-09-20 (for Q15972640)
666 x wikidata
651 x italian_cod
117 x openpolis
96 x viaf
66 x freebase
Persons matched to Wikidata: 666 ✓ 
Parties matched to Wikidata: 21 ✓ | 11 ✘
No wikidata: MISTO - non iscritto ad alcuna componente politica (party/misto_-_non_iscritto_ad_alcuna_componente_politica)
No wikidata: MISTO - USEI-IDEA …
```
> Italy (House): reconcile more Groups

- data/Ecuador/Asamblea/ep-popolo-v1.0.json
- data/Ecuador/Asamblea/sources/manual/terms.csv
- data/Ecuador/Asamblea/unstable/stats.json
```
☁ Mismatch in gender for a7e8a7fe-bb8d-4f37-a8fb-a3a041f2876f (male) vs female (for Q29051867)
* 10 of 47 unmatched
{:id=>"Q23685495", :name=>"Alexandra Arce"}
{:id=>"Q27506674", :name=>"Johnny Terán"}
{:id=>"Q4664698", :name=>"Dalo Bucaram"}
{:id=>"Q20656121", :name=>"Denisse Robles"}
{:id=>"Q20994955", :name=>"Paola Pabón"}
{:id=>"Q28449676", :name=>"Lenin Lara"}
{:id=>"Q363069", :name=>"Iván Hurtado"}
{:id=>"Q5444658", :name=>"Fernando Cordero Cueva"}
{:id=>"Q28768779", :name=>"Paco Velasco"}
{:id=>"Q27097101", :name=>"Silvia Salgado Andrade"} …
```
> Ecuador (Asamblea): add Wikidata for Term

- lib/source/term.rb
If any terms in the source file overlap, blow up noisily.
Part of https://github.com/everypolitician/everypolitician/issues/594
> Complain about overlapping terms

- data/Guatemala/Congress/ep-popolo-v1.0.json
- data/Guatemala/Congress/sources/manual/group_wikidata.csv
- data/Guatemala/Congress/sources/wikidata/groups.json
- data/Guatemala/Congress/unstable/stats.json
```
Add memberships from sources/archive/official-term-7.csv
Persons matched to Wikidata: 0 ✓ | 245 ✘
Parties matched to Wikidata: 17 ✓ | 3 ✘
No wikidata: AC (party/ac)
No wikidata: IND (party/ind)
No wikidata: Convergencia (party/convergencia)
Areas matched to Wikidata: 0 ✓ | 24 ✘
```
> Guatemala (Congress): additional Party reconciliation

- data/Uganda/Parliament/ep-popolo-v1.0.json
- data/Uganda/Parliament/sources/manual/terms.csv
- data/Uganda/Parliament/unstable/stats.json
```
Add memberships from sources/morph/official-term-9.csv
Add memberships from sources/manual/missing-9.csv
Add memberships from sources/google/sheet.csv
☁ Mismatch in birth_date for f4b28bb4-2dce-4c62-823c-393ff0393532 (1973-06-08) vs 1973-08-06 (for Q1173623)
☁ Mismatch in birth_date for b6d9f4b3-d209-4b06-ad8b-823ccb0dd7ef (1954) vs 1969-09-12 (for Q16875907)
☁ Mismatch in birth_date for e011384f-4a11-40af-889d-249173d6998c (1947-07-11) vs 1947-11-07 (for Q1740843)
☁ Mismatch in birth_date for 375f6d55-9f58-4de7-bf2d-d852dad344cb (1939-05-04) vs 1939-04-05 (for Q1949128)
☁ Mismatch in birth_date for 9faa9a4b-982a-44d0-bbb3-fbcae22642cf (1964-05-04) vs …
```
> Uganda (Parliament): add Wikidata IDs for terms

- data/Georgia/Parliament/ep-popolo-v1.0.json
- data/Georgia/Parliament/sources/manual/terms.csv
- data/Georgia/Parliament/unstable/stats.json
Add information on the new Term, and Wikidata references for both terms.
```
Add memberships from sources/morph/chemiparlamenti.csv
* 3 of 12 unmatched
{:id=>"Q16364846", :name=>"ანზორ ბოლქვაძე"}
{:id=>"Q12867446", :name=>"ნაული ჯანაშია"}
{:id=>"Q16370108", :name=>"თინათინ ხიდაშელი"}
9 x wikidata
5 x freebase
1 x viaf
Persons matched to Wikidata: 9 ✓ | 139 ✘
No wikidata: Shalva Kiknavelidze (efba708e-6ba8-46d5-8ab9-bc6b80f6486e)
No wikidata: Nana Keinishvili (66376f5f-4a6c-4eee-9186-da6c991f10f6)
No wikidata: Leri Khabelovi (03b04f60-c024-4714-8e17-505eded5cc2c)
No wikidata: Paata Kiknavelidze (132af40b-0499-4a20-9a7b-9ccc5b6a918d)
No wikidata: Davit …
```
> Georgia (Parliament): add new Term data

- data/Scotland/Parliament/ep-popolo-v1.0.json
- data/Scotland/Parliament/sources/manual/terms.csv
- data/Scotland/Parliament/unstable/stats.json
part of https://github.com/everypolitician/everypolitician/issues/590
```
Add memberships from sources/parlparse/data.csv
* 3 of 121 unmatched
{:id=>"20544923", :name=>"Bill Bowman MSP"}
{:id=>"100491202", :name=>"Pauline McNeill"}
{:id=>"733368807612395520", :name=>"Rachael Hamilton MSP"}
⚥ data for 623; 0 added
302 x wikidata
302 x parlparse
207 x freebase
41 x viaf
29 x hansard
☇ No dates for Keith Brown (Q1738042) as Cabinet Secretary for Infrastructure, Investment and Cities
☇ No dates for Michael Russell (Q1929110) as Cabinet Secretary for Education and Lifelong Learning
☇ No dates for …
```
> Scotland (Parliament): add Wikidata IDs for terms

- data/Croatia/Sabor/ep-popolo-v1.0.json
- data/Croatia/Sabor/sources/manual/terms.csv
- data/Croatia/Sabor/unstable/stats.json
```
Add memberships from sources/morph/sabor-7.csv
Add memberships from sources/morph/sabor-8.csv
☁ Mismatch in birth_date for 47cc223b-fcc3-4a56-a525-53ced82fb1b8 (1975-10-02) vs 1975-09-02 (for Q12628147)
☁ Mismatch in birth_date for cd84e8aa-0699-4e99-9538-acce6e8c1eb9 (1964-09-28) vs 1964-09-25 (for Q25043794)
☁ Mismatch in birth_date for f5f8279b-350e-450c-adc5-f57cd54ab17d (1962-01-19) vs 1962-02-19 (for Q7286273)
* 11 of 81 unmatched
{:id=>"Q3443168", :name=>"Neven Mimica"}
{:id=>"Q22160025", :name=>"Miro Kovač"}
{:id=>"Q571574", :name=>"Ante Kotromanović"}
{:id=>"Q12752142", :name=>"Ivan Pernar"}
{:id=>"Q16115922", :name=>"Krešo Beljak"}
{:id=>"Q12645873", …
```
> Croatia (Sabor): add Wikidata IDs for terms

- data/Somalia/Lower/ep-popolo-v1.0.json
- data/Somalia/Lower/sources/gender-balance/results.csv
- data/Somalia/Lower/sources/instructions.json
- data/Somalia/Lower/sources/morph/genderbalance.csv
Part of https://github.com/everypolitician/everypolitician/issues/598
```
* 235 of 244 unmatched
{:id=>"Q17338731", :name=>"Ahmed Sheikh Jama"}
{:id=>"Q4664997", :name=>"Abdirashid Mohamed Hidig"}
{:id=>"Q7492896", :name=>"Sheikh Ali Dhere"}
{:id=>"Q18808491", :name=>"Abdullahi Mohamed Noor"}
{:id=>"Q19661800", :name=>"Sahra Mohamed Ali Samatar"}
{:id=>"Q672256", :name=>"Hasan Muhammad Nur Shatigadud"}
{:id=>"Q8061950", :name=>"Yusuf Haji Nur"}
{:id=>"Q16732741", :name=>"Mohamud Ibrihim Adan"}
{:id=>"Q19609487", :name=>"Mohamed Hassan Adam"}
{:id=>"Q4724530", :name=>"Ali Abdikadir Mo'allim"}
9 x wikidata …
```
> Somalia (Lower): switch to GenderBalance scraper

- data/Botswana/Assembly/ep-popolo-v1.0.json
- data/Botswana/Assembly/sources/manual/terms.csv
- data/Botswana/Assembly/unstable/stats.json
```
* 2 of 61 unmatched
{:name=>"Hon. Samson M. Guma", :id=>"hon.-samson-m.-guma"}
{:name=>"Hon. Gladys Kokorwe", :id=>"hon.-gladys-kokorwe"}
12 x wikidata
3 x viaf
2 x lcauth
2 x sudoc
2 x freebase
Persons matched to Wikidata: 12 ✓ | 51 ✘
No wikidata: Mokwaledi Moswaane (623ee59b-4606-4244-919c-44ec148bceff)
No wikidata: Sadique Kebonang (9367d41f-a58f-40d2-8769-a0eb84e185f7)
No wikidata: James Mathokgwane (48541bfe-e5a9-4847-ab4c-59752c1b4f83)
No wikidata: Ronald Shamukuni …
```
> Botswana (Assembly): add Wikidata for Terms

- data/Tanzania/Assembly/ep-popolo-v1.0.json
- data/Tanzania/Assembly/sources/manual/terms.csv
- data/Tanzania/Assembly/unstable/stats.json
```
Add memberships from sources/archive/term4.csv
Add memberships from sources/morph/term5.csv
Add memberships from sources/archive/term5-vanished.csv
☁ Mismatch in birth_date for 9a143f85-3c51-4011-82dd-d29578ebdfd1 (1961-01-01) vs 1961-07-01 (for Q16194369)
☁ Mismatch in birth_date for 12b02f92-44fd-4d94-aa85-4544a390d19f (1963-05-23) vs 1963-05-25 (for Q16195184)
☁ Mismatch in birth_date for 40eeeb49-a3ce-4ab7-8053-518ae6c52924 (1964-09-23) vs 1964-08-13 (for Q16195625)
☁ Mismatch in birth_date for 4438b413-f970-4a3c-b850-6da88f774750 (1970-10-10) vs 1971-10-10 (for Q16213580)
☁ Mismatch in birth_date for 0b9d2462-9e5c-49be-9432-35de19f49cb7 (1986-07-08) vs …
```
> Tanzania (Assembly): add Wikidata for terms

- data/Senegal/Assembly/ep-popolo-v1.0.json
- data/Senegal/Assembly/sources/gender-balance/results.csv
- data/Senegal/Assembly/sources/instructions.json
- data/Senegal/Assembly/sources/morph/genderbalance.csv
Part of https://github.com/everypolitician/everypolitician/issues/598
```
* 37 of 50 unmatched
{:id=>"Q154545", :name=>"Léopold Sédar Senghor"}
{:id=>"Q2608966", :name=>"Jacques Diouf"}
{:id=>"Q3217062", :name=>"Landing Savané"}
{:id=>"Q3276586", :name=>"Magatte Lô"}
{:id=>"Q3182467", :name=>"John Sleight"}
{:id=>"Q1165453", :name=>"Daouda Sow"}
{:id=>"Q525063", :name=>"Iba Der Thiam"}
{:id=>"Q2820233", :name=>"Abbas Guèye"}
{:id=>"Q2939995", :name=>"Caroline Faye Diop"}
{:id=>"Q2843389", :name=>"Aminata Mbengue Ndiaye"}
13 x wikidata
3 x freebase
2 x bnf
2 x viaf
1 x sudoc
Persons matched to Wikidata: 13 …
```
> Senegal (Assembly): switch to GenderBalance scraper

- data/Hungary/Assembly/ep-popolo-v1.0.json
- data/Hungary/Assembly/sources/manual/terms.csv
- data/Hungary/Assembly/unstable/stats.json
```
* 10 of 193 unmatched
{:id=>"Q1111980", :name=>"Kiss Péter"}
{:id=>"Q832221", :name=>"Navracsics Tibor"}
{:id=>"Q218872", :name=>"Balczó Zoltán"}
{:id=>"Q57595", :name=>"Bajnai Gordon"}
{:id=>"Q1229474", :name=>"Papcsák Ferenc"}
{:id=>"Q967118", :name=>"Molnár Csaba"}
{:id=>"Q848456", :name=>"Botka László"}
{:id=>"Q1164694", :name=>"Manninger Jenő"}
{:id=>"Q16194153", :name=>"Lasztovicza Jenő"}
{:id=>"Q16197183", :name=>"Rácz Róbert"}
183 x wikidata
27 x freebase
27 x viaf
9 x isni
7 x gnd
☇ No dates for Kövér, László (Q465476) as …
```
> Hungary (Assembly): add Wikidata for 40th term

- data/UK/Commons/sources/manual/terms.csv
```
Add memberships from sources/parlparse/data.csv
Merging with sources/morph/parliament.csv
* 2 of 660 unmatched
{:id=>"4595", :name=>"Gareth Snell"}
{:id=>"4593", :name=>"Trudy Harrison"}
* 6 of 564 unmatched
{:id=>"467210290", :name=>"Michael Parody Gove"}
{:id=>"461827669", :name=>"Denis Skinner"}
{:id=>"2249203393", :name=>"Lord Price CVO"}
{:id=>"1880622294", :name=>"Derek Thomas"}
{:id=>"3301636361", :name=>"@MhairiBlack"}
{:id=>"3346442313", :name=>"Leader's Office"}
Merging with sources/YNMP/winners.csv
☁ Mismatch in birth_date for 715cbcaa-1a45-4ee6-b516-eb7e01842e45 (1951-02-01) vs 1952-02-01 (for 10545)
☁ Mismatch in birth_date for c31db300-fc3c-41ea-bc2e-c954bc15745c (1965-03-06) vs …
```
> UK (Commons): add data for new Term

- data/Armenia/Assembly/ep-popolo-v1.0.json
- data/Armenia/Assembly/sources/manual/terms.csv
- data/Armenia/Assembly/unstable/stats.json
```
* 15 of 71 unmatched
{:id=>"Q4070525", :name=>"Դավիթ Հարությունյան"}
{:id=>"Q16398714", :name=>"Սամվել Թադևոսյան"}
{:id=>"Q2389114", :name=>"Րաֆֆի Կ. Հովհաննիսյան"}
{:id=>"Q21212025", :name=>"Արփինե Հովհաննիսյան"}
{:id=>"Q7413140", :name=>"Սամվել Բալասանյան"}
{:id=>"Q4518475", :name=>"Կարեն Ճշմարիտյան"}
{:id=>"Q7908607", :name=>"Վահե Հակոբյան"}
{:id=>"Q471353", :name=>"Վահան Հովհաննիսյան"}
{:id=>"Q20509987", :name=>"Խաչիկ Հարությունյան"}
{:id=>"Q1977367", :name=>"Գագիկ Բեգլարյան"}
56 x wikidata
8 x freebase
4 x viaf
2 x lcauth
2 x gnd
☇ No dates for Khosrov Harutyunyan (Q1975237) as Prime Minister of …
```
> Armenia (Assembly): add new term dates

- data/Kenya/Assembly/ep-popolo-v1.0.json
- data/Kenya/Assembly/sources/manual/terms.csv
- data/Kenya/Assembly/unstable/stats.json
```
Add memberships from sources/morph/mzalendo.csv
☁ Mismatch in birth_date for 32bbb6b5-3cca-4ebf-9775-7572028b154f (1987) vs 1986 (for Q16866303)
☁ Mismatch in birth_date for 6161b2ca-deba-4a37-831e-571f023b32b5 (1978-07-06) vs 1978-06-06 (for Q17198176)
☁ Mismatch in birth_date for 8411c68d-6894-4e7d-b477-84fd35596c0e (1982-10-15) vs 1982-11-15 (for Q447119)
☁ Mismatch in birth_date for 8bd4c1df-14ae-4717-a75c-6c0c60a4a4f5 (1958) vs 1953-03-09 (for Q4664957)
☁ Mismatch in birth_date for 658e0ba6-a77a-4497-acfc-a92239ef10f3 (1967-06-15) vs 1969 (for Q4682154) …
```
> Kenya (Assembly): add Wikidata for Term 11

- Gemfile
- Gemfile.lock
We don't care about only being at these specific version ranges; we almost
always simply want the latest.
> Don't pin csv_to_popolo or wikisnakker

- data/Kosovo/Assembly/ep-popolo-v1.0.json
- data/Kosovo/Assembly/sources/manual/terms.csv
```
Add memberships from sources/morph/parldata.csv
* 9 of 10 unmatched
{:id=>"Q13039726", :name=>"Halil Alidema"}
{:id=>"Q3338538", :name=>"Güner Ureya"}
{:id=>"Q16380606", :name=>"Veli Deva"}
{:id=>"Q2468119", :name=>"Bahri Oruçi"}
{:id=>"Q25567132", :name=>"Bajram Husa"}
{:id=>"Q25567795", :name=>"Afërdita Veliu"}
{:id=>"Q25567124", :name=>"Elvis Pista"}
{:id=>"Q5222412", :name=>"Dardan Gashi"}
{:id=>"Q27804600", :name=>"Hysen Ibrahimi"}
⚥ data for 216; 215 added
1 x freebase
1 x wikidata
Persons matched to Wikidata: 1 ✓ | 398 ✘
No wikidata: Haki Shatri (9ea40e79-c84e-44b5-9a65-6d7876f02cb8)
No wikidata: Adem Hoda …
```
> Kosovo (Assembly): end 5th term and add 6th

- data/Netherlands/House_of_Representatives/ep-popolo-v1.0.json
- data/Netherlands/House_of_Representatives/sources/manual/terms.csv
```
* 77 of 240 unmatched
{:id=>"engelshoven-ik-van-d66", :name=>"Ingrid K van Engelshoven"}
{:id=>"el-yassini-z-el-vvd", :name=>"Zohair El El Yassini"}
{:id=>"dijkhoff-khdm-vvd", :name=>"Klaas H D M Dijkhoff"}
{:id=>"la%D2%ABin-c-sp", :name=>"Cem Laҫin"}
{:id=>"kent-b-van-sp", :name=>"Bart van Kent"}
{:id=>"ye%C5%9Filg%C3%B6z-zegerius-d-vvd", :name=>"Dilan Yeşilgöz-Zegerius"}
{:id=>"brenk-cm-van-50plus", :name=>"Corrie M van Brenk"}
{:id=>"geselschap-jh-vvd", :name=>"Jock H Geselschap"}
{:id=>"molen-h-van-der-cda", :name=>"Harry van der Molen"}
{:id=>"ellemeet-ce-gl", :name=>"Corinne E Ellemeet"}
* 64 of 258 unmatched …
```
> Netherlands (House of Representatives): end 2012 term and start 2017 one

- data/New_Zealand/House/ep-popolo-v1.0.json
- data/New_Zealand/House/sources/manual/terms.csv
```
Add memberships from sources/archive/official-vanished.csv
* 27 of 136 unmatched
{:id=>"1440322177", :name=>"Lawrence Yule"}
{:id=>"421375843", :name=>"Nicola Willis"}
{:id=>"801460597", :name=>"Kieran McAnulty"}
{:id=>"38778433", :name=>"Tāmati Coffey"}
{:id=>"16674327", :name=>"Jan Tinetti"}
{:id=>"169451041", :name=>"Duncan Webb"}
{:id=>"844462713698963458", :name=>"Marja Lubeck"}
{:id=>"87850509", :name=>"Deborah Russell QEC"}
{:id=>"2617089288", :name=>"Priyanca R"}
{:id=>"2515043892", :name=>"HamishWalker"}
Discarding duplicate membership: …
```
> New Zealand (House): add dates for term change

- data/Ghana/Parliament/ep-popolo-v1.0.json
- data/Ghana/Parliament/sources/manual/terms.csv
- data/Ghana/Parliament/unstable/stats.json
```
Add memberships from sources/archive/official-term-6.csv
☁ Mismatch in birth_date for 81fec256-2405-4d3b-98f4-09d6ed992855 (1957-01-06) vs 1951-08-05 (for Q33134598)
☁ Mismatch in birth_date for 7ad99356-17be-4896-bec0-c08e4ae32631 (1946-05-17) vs 1956-05-17 (for Q5379334)
☁ Mismatch in birth_date for 495408a8-ea7a-4e93-bed9-cc7b5b357fd1 (1974-05-12) vs 1974-05-24 (for Q6732981)
* 2 of 36 unmatched
{:id=>"Q5341508", :name=>"Edward Adjaho"}
{:id=>"Q5721427", :name=>"Henry Ford Kamel"}
34 x wikidata
1 x freebase
Persons matched to Wikidata: 34 ✓ | 243 ✘
No wikidata: Stephen Nana Ato Arthur (Dr) …
```
> Ghana (Parliament): update terms.csv for new term

- data/Bulgaria/National_Assembly/ep-popolo-v1.0.json
- data/Bulgaria/National_Assembly/sources/manual/terms.csv
- data/Bulgaria/National_Assembly/unstable/stats.json
```
☁ Mismatch in birth_date for be3e6707-11ad-48c0-b440-41e217464247 (1945-07-15) vs 1945-06-15 (for Q12273947)
☁ Mismatch in birth_date for ec5a7066-942e-4b2d-826a-724376fe9381 (1954-06-05) vs 1956-06-05 (for Q12276107)
☁ Mismatch in birth_date for e7bf97b0-d4ae-42a3-a5a0-dd83e4c62783 (1956-10-05) vs 1956-09-05 (for Q12282211)
☁ Mismatch in birth_date for 26bcec3a-0c29-4ddc-a5d1-b820cbd6e071 (1949-09-15) vs 1949-01-27 (for Q12290429)
* 26 of 369 unmatched
{:id=>"Q11699699", :name=>"Гергана Паси"}
{:id=>"Q2080774", :name=>"Ангел Марин"}
{:id=>"Q12277877", :name=>"Денчо Бояджиев"}
{:id=>"Q20497733", :name=>"Списък на народните представители в 42-то Народно събрание"}
{:id=>"Q20498433", …
```
> Bulgaria (National Assembly): reconcile terms to Wikidata

- .rubocop_base.yml
- Gemfile.lock
- rake_build/generate_final_csvs.rb
Update to the latest rubocop, and fix any problems this raises.
> update rubocop to 0.52

- data/Turkey/Assembly/sources/idmap/wikipedia.csv
- data/Turkey/Assembly/sources/morph/wikipedia.csv
```
☁ Mismatch in wikipedia__tr for b2ee4381-f5fe-48a0-a1e6-492fe3be14aa (İsmail Cevat Çobanlı) vs Cevat Çobanlı (for Q1052624)
☁ Mismatch in wikipedia__tr for a692e94f-ddd3-408c-96af-92442c254b1f (Mehmet Arif Bey (Ayıcı Arif)) vs Mehmet Arif Bey (milletvekili) (for Q11109390)
☁ Mismatch in wikipedia__tr for 1d17c2e8-e91c-48b0-bda8-d6a708bfce1f (Ahmet Arslan (Milletvekili)) vs Ahmet Arslan (siyasetçi) (for Q12808316)
☁ Mismatch in wikipedia__tr for 05f819e7-9d1b-4bd3-be24-9ef2fc9c3989 (Refik Güran) vs Ahmet Refik Güran (for Q12808327)
☁ Mismatch in wikipedia__tr for a3f17739-bbce-45bb-94bc-b97f6e008d0f (Ali Arslan (milletvekili)) vs Ali Arslan (siyasetçi) (for Q12808415)
☁ Mismatch in …
```
> Turkey (Assembly): refresh wikipedia.csv

- data/Azerbaijan/National_Assembly/ep-popolo-v1.0.json
- data/Azerbaijan/National_Assembly/sources/manual/terms.csv
- data/Azerbaijan/National_Assembly/unstable/stats.json
> Azerbaijan (National Assembly): add Wikidata references for terms

- data/Sierra_Leone/Parliament/ep-popolo-v1.0.json
- data/Sierra_Leone/Parliament/sources/wikidata/elections.json
- data/Sierra_Leone/Parliament/sources/wikidata/groups.json
- data/Sierra_Leone/Parliament/unstable/stats.json
```
⤈ No ORDER BY for sources/morph/official.csv
⚥ data for 124; 124 added
Persons matched to Wikidata: 0 ✓ | 124 ✘
Parties matched to Wikidata: 3 ✓ 
Areas matched to Wikidata: 0 ✓ | 24 ✘
```
> Sierra Leone (Parliament): rebuild data

- data/South_Sudan/Assembly/ep-popolo-v1.0.json
- data/South_Sudan/Assembly/sources/wikidata/groups.json
- data/South_Sudan/Assembly/unstable/stats.json
```
⤈ No ORDER BY for sources/morph/official.csv
Persons matched to Wikidata: 0 ✓ | 167 ✘
Parties matched to Wikidata: 3 ✓ 
Areas matched to Wikidata: 0 ✓ | 11 ✘
```
> South Sudan (Assembly): rebuild data

- data/Colombia/Senate/ep-popolo-v1.0.json
- data/Colombia/Senate/sources/manual/terms.csv
- data/Colombia/Senate/unstable/stats.json
```
☁ Mismatch in tempname for d1c65f6b-ef74-462a-b409-4b71f150e7ea (Thania Vega) vs ThaniaVega Senadora (for 2411541594)
* 4 of 97 unmatched
{:id=>"818359970072817664"}
{:id=>"155964060"}
{:id=>"58982725"}
{:id=>"1978999279"}
* 163 of 264 unmatched
{:id=>"Q16941974", :name=>"Luis Alfonso Hoyos"}
{:id=>"Q5925537", :name=>"Jairo Mantilla Colmenares"}
{:id=>"Q704022", :name=>"Gustavo Petro"}
{:id=>"Q6174953", :name=>"Óscar Suárez Mira"}
{:id=>"Q5820301", :name=>"Efraín Torrado"}
{:id=>"Q5552352", :name=>"Germán Zea Hernández"}
{:id=>"Q5906231", :name=>"Héctor Julio …
```
> Colombia (Senate): add term end date and Wikidata

- data/Ivory_Coast/Assembly/ep-popolo-v1.0.json
- data/Ivory_Coast/Assembly/sources/wikidata/elections.json
- data/Ivory_Coast/Assembly/sources/wikidata/groups.json
```
Add memberships from sources/morph/abidjan-forums.csv
Persons matched to Wikidata: 0 ✓ | 241 ✘
Parties matched to Wikidata: 7 ✓ 
Areas matched to Wikidata: 0 ✓ | 89 ✘
```
> Ivory Coast (Assembly): rebuild wikidata

- data/El_Salvador/Legislative_Assembly/ep-popolo-v1.0.json
- data/El_Salvador/Legislative_Assembly/sources/wikidata/groups.json
```
☁ Mismatch in temp_name for 3b83a9e5-bb97-48c4-81ed-643e98107a44 (Cristina López) vs Cristina Lopez (for 4072796844)
* 48 of 107 unmatched
{:id=>"874130809"}
{:id=>"1311245508"}
{:id=>"44265584"}
{:id=>"2743952690"}
{:id=>"1951723148"}
{:id=>"130521584"}
{:id=>"627724956"}
{:id=>"2766826370"}
{:id=>"243727868"}
{:id=>"1489416746"}
⚥ data for 84; 84 added
Persons matched to Wikidata: 0 ✓ | 84 ✘
Areas matched to Wikidata: 0 ✓ | 14 ✘
```
> El Salvador (Legislative Assembly): rebuild wikidata

- data/Wales/Assembly/sources/idmap/group/official-4.csv
- data/Wales/Assembly/sources/idmap/group/official-5.csv
These were committed accidentally in ec2017ec
> Wales (Assembly): remove group idmap files

- data/Ireland/Dail/ep-popolo-v1.0.json
- data/Ireland/Dail/sources/manual/terms.csv
- data/Ireland/Dail/unstable/stats.json
```
Add memberships from sources/morph/kildare31.csv
Add memberships from sources/morph/kildare32.csv
Merging with sources/morph/twitter-donie.csv
* 7 of 233 unmatched
{:id=>"Q7147356", :name=>"Patrick Nulty"}
{:id=>"Q983508", :name=>"Phil Hogan"}
{:id=>"Q1499408", :name=>"Shane McEntee"}
{:id=>"Q912430", :name=>"Brian Lenihan, Jnr"}
{:id=>"Q3778169", :name=>"Luke 'Ming' Flanagan"}
{:id=>"Q13653269", :name=>"Nicky McFadden"}
{:id=>"Q4963985", :name=>"Brian Hayes"}
226 x wikidata
226 x oireachtas
110 x freebase
44 x viaf
16 x isni
☇ No dates for Joe Costello (Q3777446) as Minister of …
```
> Ireland (Dail): add Wikidata IDs for terms

- data/Ireland/Dail/sources/manual/position-filter.csv
- data/Ireland/Dail/unstable/positions.csv
- data/Ireland/Dail/unstable/stats.json
- data/Ireland/meta.json
It looks like we're losing a lot of data here, but this is almost entirely junior ministerial positions that aren’t actually in the Cabinet.
```
Add memberships from sources/morph/p39s.csv
Merging with sources/archive/kildare31.csv
Merging with sources/morph/kildare32.csv
Merging with sources/morph/twitter-donie.csv
* 843 of 1292 unmatched
{:id=>"Q1701797", :name=>"John Stafford"}
{:id=>"Q7807326", :name=>"Timothy Killeen"}
{:id=>"Q6767323", :name=>"Mark Deering"}
{:id=>"Q1388454", :name=>"Ray MacSharry"}
{:id=>"Q334586", :name=>"Austin Stack"}
{:id=>"Q2276053", :name=>"Seán Sherwin"}
{:id=>"Q1510184", :name=>"Gerard Sweetman"}
{:id=>"Q2057804", :name=>"Patrick McGrath"}
{:id=>"Q1187443", :name=>"Denis J. O'Sullivan"} …
```
> Ireland (Dail): generate Cabinet positions from Wikidata

- data/United_States_of_America/Senate/ep-popolo-v1.0.json
```
Add memberships from sources/morph/unitedstates-project.csv
Merging with sources/morph/socialmedia.csv
* 504 of 615 unmatched
{:id=>"D000619"}
{:id=>"K000387"}
{:id=>"M001197"}
{:id=>"A000374"}
{:id=>"W000806"}
{:id=>"S001156"}
{:id=>"M001200"}
{:id=>"H001071"}
{:id=>"C001072"}
{:id=>"F000466"}
☁ Mismatch in identifier__fec for 96324d91-c6e4-401a-b43e-a526dabe40a8 (S6AZ00019) vs P80002801 (for Q10390)
☁ Mismatch in identifier__ballotpedia for 96324d91-c6e4-401a-b43e-a526dabe40a8 (John McCain) vs John_McCain (for Q10390)
☁ Mismatch in identifier__cspan for 96324d91-c6e4-401a-b43e-a526dabe40a8 (7476) vs johnmccain (for Q10390)
☁ Mismatch in identifier__ballotpedia for 2a078b6c-0f3b-4319-aa4b-6f4d0fe6b80f …
```
> United States of America (Senate): rebuild areas

- data/Australia/Senate/ep-popolo-v1.0.json
```
Add memberships from sources/morph/openaustralia.csv
Merging with sources/morph/contacts.csv
* 1 of 109 unmatched
{:id=>"bv7", :name=>"Senator the Hon Arthur Sinodinos AO"}
* 340 of 603 unmatched
{:id=>"Q364568", :name=>"George Pearce"}
{:id=>"Q7364132", :name=>"Ron McAuliffe"}
{:id=>"Q5240654", :name=>"David Vigor"}
{:id=>"Q7931495", :name=>"Vince Gair"}
{:id=>"Q5272825", :name=>"Dick Dein"}
{:id=>"Q5294438", :name=>"Donald Grant"}
{:id=>"Q6249755", :name=>"John Mullan"}
{:id=>"Q6135061", :name=>"James Guy"}
{:id=>"Q4933967", :name=>"Bob Sherrington"}
{:id=>"Q6263710", :name=>"John Wheeldon"}
* 8 of 90 unmatched …
```
> Australia (Senate): rebuild areas

- data/New_Caledonia/Congress/sources/instructions.json
The scraper no longer provides this information.
> New Caledonia (Congress): note term of official.csv

- data/Russia/Duma/ep-popolo-v1.0.json
- data/Russia/Duma/sources/instructions.json
- data/Russia/Duma/sources/manual/terms.csv
- data/Russia/Duma/sources/morph/terms.csv
Part of https://github.com/everypolitician/everypolitician/issues/626 
```
Add memberships from sources/manual/official-6.csv
Add memberships from sources/morph/official-7.csv
☁ Mismatch in birth_date for e55c51dc-5362-4c4b-bd3c-713d91c0f04a (1950-11-20) vs 1950-10-21 (for Q2384738)
☁ Mismatch in birth_date for 474be04e-7da1-4dfc-8712-22221fa481e7 (1970-02-12) vs 1970-01-12 (for Q26776800)
☁ Mismatch in birth_date for 4e3633ee-6dba-4c18-995d-474f65a880e7 (1959-02-15) vs 1959-03-15 (for Q28919970)
☁ Mismatch in birth_date for cc7ed084-d7ba-4936-983b-623bb705eeba (1961-02-15) vs 1961-04-15 (for Q4089520)
☁ Mismatch in birth_date for 2179d93f-e54b-473d-85c3-f6c51375724d (1947-06-14) vs 1947-07-14 (for Q4362360)
☁ Mismatch in birth_date …
```
> Russia (Duma): switch to Wikidata for Term Info

- bin/dashboard.rb
Add three extra columns:
* mem_sources: the number of membership sources
* live_sources: the number of 'active' membership sources (not archived)
* p39_sources: the number of sources coming from Wikidata
> Add data about membership sources to dashboard

- data/Azerbaijan/National_Assembly/ep-popolo-v1.0.json
- data/Azerbaijan/National_Assembly/sources/instructions.json
- data/Azerbaijan/National_Assembly/sources/manual/terms.csv
- data/Azerbaijan/National_Assembly/sources/morph/terms.csv
Part of https://github.com/everypolitician/everypolitician/issues/626 
```
* 1 of 153 unmatched
{:id=>"Q23683183", :name=>"Anar Umudov"}
152 x wikidata
15 x isni
14 x viaf
12 x lcauth
6 x freebase
Persons matched to Wikidata: 152 ✓ 
Parties matched to Wikidata: 14 ✓ 
Areas matched to Wikidata: 0 ✓ | 125 ✘
```
> Azerbaijan (National Assembly): get terms from Wikidata

- rake_build/fetch_sources.rb
- rake_build/generate_final_csvs.rb
- rake_build/merge_members.rb
- rake_build/turn_csv_to_popolo.rb
- rake_build/validate_raw_sources.rb
- rake_build/verify_source_data.rb
- rakefile_common.rb
Push everything through this so we can have more complete and consistent output (now also including timestamps)
> Add a 'source_warn' helper

- lib/source/elections.rb
- lib/source/gender.rb
- rake_build/generate_final_csvs.rb
Make it more obvious in the build output if the most recent term has
finished.
> Add build warning if latest term has ended

- data/Pakistan/Assembly/ep-popolo-v1.0.json
- data/Pakistan/Assembly/sources/instructions.json
- data/Pakistan/Assembly/sources/manual/terms.csv
- data/Pakistan/Assembly/sources/morph/terms.csv
Part of https://github.com/everypolitician/everypolitician/issues/626 
```
08:43:25 Validating CSVs
08:43:25 Refetching sources/morph/terms.csv
08:43:26 Add memberships from sources/morph/official.csv
08:43:26 Add memberships from sources/archive/official-term-14.csv
08:43:26 Merging with sources/morph/wikidata.csv
* 13 of 365 unmatched
{:id=>"Q17287330", :name=>"Tahira Asif"}
{:id=>"Q7636919", :name=>"Sumaira Malik"}
{:id=>"Q26924450", :name=>"Zulfiqar Ali Behan"}
{:id=>"Q26923887", :name=>"Sadiq Ali Memon"}
{:id=>"Q26924336", :name=>"Muhammad Ibrahim Jatoi"}
{:id=>"Q18763842", :name=>"Ayesha Raza Farooq"}
{:id=>"Q26924444", :name=>"Muhammad Ijaz Ahmed Chaudhary"}
{:id=>"Q3073499", :name=>"Javed Hashmi"}
{:id=>"Q18816019", :name=>"Rai Mansab Ali Khan"}
{:id=>"Q6956893", :name=>"Nabil …
```
> Pakistan (Assembly): get terms from Wikidata

- rake_build/generate_stats.rb
This isn’t necessarily a sign of a problem, but it probably means it’s
worth looking at.
> Warn if update-able sources haven’t updated in >90 days

- data/Armenia/Assembly/sources/instructions.json
- data/Armenia/Assembly/sources/manual/terms.csv
- data/Armenia/Assembly/sources/morph/terms.csv
- data/Armenia/Assembly/unstable/stats.json
Part of https://github.com/everypolitician/everypolitician/issues/626
```
07:00:22 Validating CSVs
07:00:22 Add memberships from sources/archive/official-5.csv
07:00:22 Merging with sources/morph/wikidata.csv
* 290 of 383 unmatched
{:id=>"Q4408642", :name=>"Սաշիկ Սարգսյան"}
{:id=>"Q31196357", :name=>"Արսեն Միխայլով"}
{:id=>"Q31196321", :name=>"Արարատ Միրզոյան"}
{:id=>"Q4496756", :name=>"Վազգեն Խաչիկյան"}
{:id=>"Q4059731", :name=>"Հակոբ Հակոբյան"}
{:id=>"Q4282654", :name=>"Արմեն Մարտիրոսյան"}
{:id=>"Q4173589", :name=>"Արմեն Եղիազարյան"}
{:id=>"Q4280727", :name=>"Ռոմիկ Մանուկյան"}
{:id=>"Q4450763", :name=>"Համլետ Թամազյան"}
{:id=>"Q4126099", :name=>"Հրանտ Մուշեղի Ոսկանյան"}
07:00:23 Merging with sources/morph/genderbalance.csv
07:00:23 Generating legacy_id file
07:00:23 Verifying …
```
> Armenia (Assembly): get terms from Wikidata

- rake_build/generate_stats.rb
If we have 100% coverage of gender data, we don't need to report that
the GenderBalance source hasn't been updated.
Closes https://github.com/everypolitician/everypolitician/issues/643
> Only report on GenderBalance lastmod if missing gender

- data/South_Africa/Assembly/unstable/stats.json
```11:40:36 Validating CSVs
11:40:36 Refetching sources/morph/peoplesassembly.csv
11:40:37 Add memberships from sources/morph/wikidata-memberships.csv
11:40:38 Merging with sources/morph/peoplesassembly.csv
11:40:38 Merging with sources/morph/wikidata.csv
☁ Mismatch in identifier__wikidata for a1d9e2da-f187-4103-b050-394c2dd9613f (Q16765225) vs Q47529757 (for Q47529757)
☁ Mismatch in identifier__wikidata for c8095818-b01d-49b6-941f-e8dc3d540bbf (Q16765137) vs Q47529885 (for Q47529885)
☁ Mismatch in identifier__wikidata for fd4c7b9f-1446-45fe-b3ec-f0be3a54f850 (Q16765141) vs Q47529888 (for Q47529888)
☁ Mismatch in identifier__wikidata for 2a5c3062-5f83-4781-bd74-5021770cbbca (Q16744505) vs Q47530046 (for Q47530046)
☁ Mismatch in honorific_prefix for c4e3374e-12ba-477b-b654-abd17a9b343c …
```
> ZA: Rebuild following multiple merges and updates

- rake_build/merge_members.rb
Everything else has the -ing form, so bring this one in line.
> Make 'Add memberships' wording consistent

- Gemfile.lock
- lib/source/term.rb
Update to newest versions of gems.
> bundle update

- .travis.yml
- Gemfile
- Gemfile.lock
Some legislatures will have significant changes due to differences in case handling, and will need changes before being rebuilt - see https://github.com/everypolitician/everypolitician/issues/614
> Update to Ruby 2.4

- data/Cameroon/Senate/ep-popolo-v1.0.json
- data/Cameroon/Senate/sources/idmap/afroleadership.csv
- data/Cameroon/Senate/sources/wikidata/groups.json
- data/Cameroon/Senate/unstable/stats.json
Part of https://github.com/everypolitician/everypolitician/issues/614 
```
11:43:23 Validating CSVs
11:43:23 Adding memberships from sources/morph/afroleadership.csv
11:43:23 Adding unmigrated GenderBalance results from sources/gender-balance/results.csv
11:43:23 Generating legacy_id file
11:43:23 Verifying sources/merged.csv
11:43:23 Converting to Popolo
11:43:23 Creating termfiles
11:43:24 Creating names.csv
------------------------------------------------------------------------
Persons matched to Wikidata: 0 ✓ | 100 ✘
Areas matched to Wikidata: 0 ✓ | 10 ✘
Parties matched to Wikidata: 5 ✓ | 1 ✘
No wikidata: ANDP (andp)
Terms matched to Wikidata: 0 ✓ | 1 ✘
☢  morph/afroleadership.csv has not been updated for 680 days
☢  wikidata/groups.json has not been updated for 532 days
```
> Cameroon (Senate): fix case under ruby 2.4

- data/Honduras/Congreso_Nacional/ep-popolo-v1.0.json
- data/Honduras/Congreso_Nacional/sources/idmap/wikipedia.csv
- data/Honduras/Congreso_Nacional/sources/wikidata/elections.json
- data/Honduras/Congreso_Nacional/sources/wikidata/groups.json
- data/Honduras/Congreso_Nacional/unstable/stats.json
Part of https://github.com/everypolitician/everypolitician/issues/614 
```
11:55:55 Validating CSVs
11:55:55 Adding memberships from sources/morph/wikipedia.csv
11:55:55 Merging with sources/morph/wikidata.csv
11:55:55 Merging with sources/morph/genderbalance.csv
11:55:55 Generating legacy_id file
11:55:55 Verifying sources/merged.csv
11:55:55 Converting to Popolo
Imprecise end date (2018) for term VIII Legislatura
11:55:55 Creating termfiles
*** latest term ended on 2018 *** 
11:55:55 Creating names.csv
------------------------------------------------------------------------
Persons matched to Wikidata: 4 ✓ | 127 ✘
No wikidata: Aníbal Calix (0457fb6a-7d38-4992-b7e2-b32e1ddf59d9)
No wikidata: José Zambrano (6467bb70-a594-4719-b1e5-f0b60cf4864d)
No wikidata: Teresa Cálix …
```
> Honduras (Congreso Nacional): fix case under ruby 2.4

- data/Panama/Assembly/sources/idmap/official.csv
- data/Panama/Assembly/unstable/stats.json
Part of https://github.com/everypolitician/everypolitician/issues/614 
```
12:41:57 Validating CSVs
12:41:58 Adding memberships from sources/morph/official.csv
12:41:58 Merging with sources/morph/wikidata.csv
* 85 of 87 unmatched
{:id=>"Q4893848", :name=>"Bernardino González Ruiz"}
{:id=>"Q56066098", :name=>"Rómulo Roux"}
{:id=>"Q5797808", :name=>"Damián Castillo Durán"}
{:id=>"Q322234", :name=>"Federico Boyd"}
{:id=>"Q3810601", :name=>"José de Antequera y Castro"}
{:id=>"Q6005897", :name=>"Mateo Iturralde"}
{:id=>"Q603836", :name=>"Arnulfo Arias"}
{:id=>"Q5889225", :name=>"Gumercinda Páez"}
{:id=>"Q15919322", :name=>"Harmodio Arias Cerjack"}
{:id=>"Q3135903", :name=>"Tomás de Herrera"}
12:41:58 Merging with sources/morph/genderbalance.csv
12:41:58 Generating legacy_id file
12:41:58 …
```
> Panama (Assembly): fix case under ruby 2.4

- data/Netherlands/House_of_Representatives/sources/idmap/group/wikipedia-2012.csv
- data/Netherlands/House_of_Representatives/unstable/stats.json
Part of https://github.com/everypolitician/everypolitician/issues/614
```
14:51:09 Validating CSVs
14:51:10 Adding memberships from sources/archive/wikipedia-2012.csv
14:51:10 Adding memberships from sources/morph/wikipedia-2017.csv
14:51:10 Merging with sources/morph/official.csv
14:51:10 Merging with sources/morph/wikidata.csv
* 1 of 280 unmatched
{:id=>"Q27941488", :name=>"Jock Geselschap"}
14:51:11 Merging with sources/morph/genderbalance.csv
14:51:11 Merging with sources/morph/twitter.csv
* 4 of 220 unmatched
{:id=>"3053769383"}
{:id=>"197014877"}
{:id=>"90936873"}
{:id=>"155507136"}
14:51:11 Generating legacy_id file
14:51:11 Verifying sources/merged.csv
14:51:11 Converting to Popolo
14:51:11 Creating termfiles
14:51:11 Creating names.csv
14:51:11 Creating unstable/positions.csv
⁕ …
```
> Netherlands (House of Representatives): fix case under ruby 2.4

- data/United_States_of_America/House/sources/wikidata/elections.json
- data/United_States_of_America/House/unstable/stats.json
- lib/wikidata_lookup.rb
This avoids things like "United States House of Representatives elections
in Texas, 2018"
> Skip any elections that are 'part of' another legislative election

- lib/country_data.rb
- lib/task/rebuild_countries_json.rb
General tidying and refactoring.
> Refactor generation of countries.json file

- bin/dashboard.rb
Extract an AnalyticsFile class that better encapsulates what we're
actually doing here.
> Refactor 'dashboard'

- data/British_Virgin_Islands/Council/ep-popolo-v1.0.json
- data/British_Virgin_Islands/Council/sources/instructions.json
- data/British_Virgin_Islands/Council/sources/wikidata/elections.json
- data/British_Virgin_Islands/Council/unstable/stats.json
split out the elecctions to the Council from those to the Assembly
```
09:10:44 Validating CSVs
09:10:44 Refetching sources/wikidata/elections.json
09:10:46 Adding memberships from sources/morph/wikipedia.csv
⚠ Missing group UUID mapping
⚠ Missing area UUID mapping
09:10:46 Merging with sources/morph/wikidata.csv
* 2 of 13 unmatched
{:id=>"Q5215432", :name=>"Dancia Penn"}
{:id=>"Q16214258", :name=>"Myron Walwyn"}
09:10:46 Adding unmigrated GenderBalance results from sources/gender-balance/results.csv
⚥ data for 41; 41 added
09:10:46 Generating legacy_id file
09:10:46 Verifying sources/merged.csv
09:10:46 Converting to Popolo
09:10:46 Adding term information
Short end date (2003) for term 14th Council
Short end date (1999) for term 13th Council
Short end date (1995) for term 12th Council …
```
> British Virgin Islands (Council): add Elections

- data/Pitcairn/Island_Council/ep-popolo-v1.0.json
- data/Pitcairn/Island_Council/sources/idmap/group/data.csv
- data/Pitcairn/Island_Council/sources/manual/group_wikidata.csv
- data/Pitcairn/Island_Council/sources/wikidata/groups.json
- data/Pitcairn/Island_Council/term-2009.csv
- data/Pitcairn/Island_Council/term-2011.csv
- data/Pitcairn/Island_Council/term-2013.csv
- data/Pitcairn/Island_Council/unstable/latest.csv
- data/Pitcairn/Island_Council/unstable/stats.json
Part of https://github.com/everypolitician/everypolitician/issues/428
```
06:55:14 Validating CSVs
06:55:14 Refetching sources/wikidata/groups.json
06:55:15 Adding memberships from sources/wikipedia/data.csv
⚠ Missing area UUID mapping
06:55:15 Merging with sources/morph/wikidata.csv
06:55:15 Adding unmigrated GenderBalance results from sources/gender-balance/results.csv
⚥ data for 6; 6 added
06:55:15 Generating legacy_id file
06:55:15 Verifying sources/merged.csv
06:55:15 Converting to Popolo
06:55:15 Adding term information
06:55:15 Adding election information
06:55:15 Adding party information
06:55:15 Creating termfiles
06:55:15 Creating names.csv
------------------------------------------------------------------------
⚠ No wikidata cabinet item
Persons matched to Wikidata: 2 ✓ | 10 ✘ …
```
> Pitcairn (Island Council): add group UUIDs

- data/Greenland/Inatsisartut/ep-popolo-v1.0.json
- data/Greenland/Inatsisartut/sources/manual/group_wikidata.csv
- data/Greenland/Inatsisartut/sources/wikidata/groups.json
- data/Greenland/Inatsisartut/term-6.csv
- data/Greenland/Inatsisartut/unstable/stats.json
Part of https://github.com/everypolitician/everypolitician/issues/428
```
07:35:04 Validating CSVs
07:35:05 Refetching sources/wikidata/groups.json
07:35:07 Adding memberships from sources/morph/official.csv
⚠ Missing group UUID mapping
⚠ Missing area UUID mapping
07:35:07 Merging with sources/morph/wikidata.csv
* 4 of 45 unmatched
{:id=>"Q7429942", :name=>"Nikku Olsen"}
{:id=>"Q4569194", :name=>"Mikael Gam"}
{:id=>"Q11285650", :name=>"Arkalo Abelsen"}
{:id=>"Q12328916", :name=>"Niels Thomsen"}
07:35:07 Adding unmigrated GenderBalance results from sources/gender-balance/results.csv
⚥ data for 331; 193 added
07:35:07 Generating legacy_id file
07:35:07 Verifying sources/merged.csv
07:35:07 Converting to Popolo
07:35:07 Adding term information
Discarding duplicate membership: …
```
> Greenland (Inatsisartut): reconcile Kandidatforbund
