everypolitician/everypolitician-data

australia/Rakefile.rb
canada/Rakefile.rb
denmark/Rakefile.rb
iran/Rakefile.rb
italy/Rakefile.rb
rakefile_common.rb
wales/Rakefile.rb

Have a task that makes sure there’s at least one Term, and default it
to what’s in `@current_term`, so that each Rakefile doesn’t need to
specify that dependency directly.

remove need for explicitly adding the Current term

---

Rakefile.rb

Rather than auto generating a fairly meaningless Pull Request message,
prompt for what that should be.
If we ever automate this step, we’ll need to add the message back.

Rakefile publish promit

---

Rakefile.rb
countries.json

If apps want to make automated commits of new data, they shouldn’t rely
on a shared convention of where those should go, as then we can never
change our structures without ensuring that all those apps are changed.
Instead they should look up the `sources_directory` for a country and
use that.

Add a `sources_directory` to `countries.json`

---

Rakefile.rb
countries.json

The `name` of the Legislature should hopefully become the fuller version (e.g “House of Representatives” rather than just “House” RSN, so we should have a `slug` that can be used in URLs etc that is hopefully more unchanging.
The general consensus is that this should use “-“ rather than “_” as a separator (because Google, largely)

Add a `slug` for each country and chamber

---

rakefile_common.rb
rakefile_parlparse.rb

Remove all the code that deals with “@LEGISLATURE” meta-info being
supplied in the Rakefile. Everything will now be supplying this either
directly, or through a meta.json.

remove the "@LEGISLATURE" handler-code

---

data/Albania/Assembly/Rakefile.rb
data/Albania/Assembly/sources/parldata/instructions.json
data/Czech_Republic/Deputies/Rakefile.rb
data/Czech_Republic/Deputies/sources/parldata/instructions.json
data/Czech_Republic/Senate/Rakefile.rb
data/Czech_Republic/Senate/sources/parldata/instructions.json
data/Hungary/Assembly/Rakefile.rb
data/Hungary/Assembly/sources/parldata/instructions.json
data/Kosovo/Assembly/Rakefile.rb
data/Kosovo/Assembly/sources/parldata/instructions.json
data/Montenegro/Assembly/Rakefile.rb
data/Montenegro/Assembly/sources/parldata/instructions.json
data/Poland/Sejm/Rakefile.rb
data/Poland/Sejm/sources/parldata/instructions.json
data/Poland/Senat/Rakefile.rb
data/Poland/Senat/sources/parldata/instructions.json
data/Serbia/Assembly/Rakefile.rb
data/Serbia/Assembly/sources/parldata/instructions.json
data/Slovakia/National_Council/Rakefile.rb
data/Slovakia/National_Council/sources/parldata/instructions.json
rakefile_common.rb
rakefile_morph.rb
rakefile_parldata.rb

Make the Rakefiles as minimal as possible for Parldata countries, by moving the data on how to build them in `instructions.json` files.

Add instructions.json for Parldata countries

---

data/Denmark/Folketing/Rakefile.rb
data/Denmark/Folketing/sources/popit/instructions.json
data/Estonia/Riigikogu/Rakefile.rb
data/Estonia/Riigikogu/sources/popit/instructions.json
data/Greenland/Inatsisartut/Rakefile.rb
data/Greenland/Inatsisartut/sources/popit/instructions.json
data/Iran/Assembly/Rakefile.rb
data/Iran/Assembly/sources/popit/instructions.json
data/South_Africa/Assembly/Rakefile.rb
data/South_Africa/Assembly/sources/popit/instructions.json
data/Zimbabwe/Assembly/Rakefile.rb
data/Zimbabwe/Assembly/sources/popit/instructions.json
rakefile_common.rb
rakefile_popit.rb

Make the Rakefiles as minimal as possible for Popit-source countries, by moving the data on how to build them into `instructions.json` files.

Add instructions.json for Popit countries

---

data/Benin/National_Assembly/Rakefile.rb
data/Bermuda/Assembly/Rakefile.rb
data/Burkina_Faso/Assembly/Rakefile.rb
data/Cameroon/Assembly/Rakefile.rb
data/Czech_Republic/Deputies/Rakefile.rb
data/Czech_Republic/Senate/Rakefile.rb
data/Dominican_Republic/Diputados/Rakefile.rb
data/Gabon/Assembly/Rakefile.rb
data/Moldova/Parlamentul/Rakefile.rb

It’s easier to keep track of which Rakefiles still contain logic (#106) if we strip all the single-line ones of their trailing newlines.

Remove trailing blank lines from Rakefiles

---

lib/fetcher.rb
rakefile_morph.rb

It only does the fetching anyway, and we should keep the concepts separate.

Rename Builder to Fetcher

---

rakefile_merged.rb

When doing approximate matches, cache the Fuzzer, rather than rebuilding it on every match.

Don't rebuild the Fuzzer for every match

---

rakefile_common.rb

There’s a lot of obsolete code here from when individual Rakefiles could override lots of things in code, rather than all being data-driven. Simplify it.

Simplify Rakefile

---

Rakefile.rb

We no longer have such a complex process, and so don’t need this.
Perhaps later we’ll write another version of it.

Remove the instructions-builder code

---

README.md

Remove smart quote and replace it with a normal (dumb?) one. Makes it
so you can copy and past working code.

Fix quote in readme

---

README.md

Fix the references to the old two-step process that was replaced in #716. Closes #737, with apologies to @henare

Bring README up to date with new build instructions

---

rake_helpers/verify_source_data.rb

Add a check to the verification stage to ensure that all dates are valid.
For now we allow 'year-only' dates, though we probably want to tighten that up somehow later.
(Cameroon is currently breaking, but this is fixed upstream. Need to wait for Morph before merging that, though)

Check that all dates are valid

---

data/Somalia/Lower/ep-popolo-v1.0.json
data/Somalia/Lower/meta.json

Add last remaining missing Wikidata reference for a legislature. Closes https://github.com/everypolitician/everypolitician-data/issues/398

Somalia: Add wikidata reference

---

Gemfile

Instead of requiring an exact ruby version this just checks that the
user has at least ruby 2.0.0.
Fixes https://github.com/everypolitician/everypolitician/issues/181

Check that ruby version is at least 2.0.0 in Gemfile

---

bin/parties_in_country.rb
countries.json
data/British_Virgin_Islands/Council/meta.json

this has now been split out a separate item
Also add a simple script that displays information about parties in a country via Wikidata

BVI: add separate Wikidata ID for the Legislative Council

---

countries.json
data/Belgium/Representatives/ep-popolo-v1.0.json
data/Belgium/Representatives/sources/instructions.json

The incoming Wikidata data was incorrectly described, so didn't have
the identifiers attached.

Belgium: add wikidata identifiers

---

rake_helpers/verify_source_data.rb

When verifying merged.csv, just load it with a plain CSV.read rather
than the much slower csv_table version that does column remapping. In
the case of the US House of Representatives, this now only takes about
5-10 seconds to load, rather than 2-3 minutes.
Part of https://github.com/everypolitician/everypolitician/issues/190

faster CSV loading

---

Rakefile.rb

There's no real need to supply the -p, -s, and --no-notes to git-log if we're supplying our own --format

Cleaner git-log options

---

templates/reconciliation.js

We want to show 100% matches because they're not the same as exact
matches. e.g. you could have 'Joe Bloggs' and 'Joe A Bloggs' and they're
100% matches because the latter contains 100% of the former, but they're
not exact matches.

Show 100% matches in reconciliation interface

---

rake_helpers/combine_sources.rb
templates/reconciliation.html.erb
templates/reconciliation.js

Rather than just feeding the fields specified in instructions.json into
the template we instead give it the whole existing and incoming objects
so that any information can be displayed on that page.
This also changes the reconciliation csv format so there are now just
two columns, 'id' and 'uuid'.
Related to https://github.com/everypolitician/everypolitician/issues/195

Feed all person data into the reconciliation template

---

templates/reconciliation.html.erb
templates/reconciliation.js

Don't assume that the person's 'name' is always the field that we want to show. Sometimes the `incoming_field` might be set to `name__en`, in which case we should use that instead.

Use incoming and existing fields in reconciliation UI

---

countries.json
data/Turkey/Assembly/names.csv
data/Turkey/Assembly/sources/instructions.json
data/Turkey/Assembly/sources/morph/data.csv
data/Turkey/Assembly/term-1.csv
data/Turkey/Assembly/term-10.csv
data/Turkey/Assembly/term-11.csv
data/Turkey/Assembly/term-12.csv
data/Turkey/Assembly/term-13.csv
data/Turkey/Assembly/term-14.csv
data/Turkey/Assembly/term-15.csv
data/Turkey/Assembly/term-16.csv
data/Turkey/Assembly/term-17.csv
data/Turkey/Assembly/term-18.csv
data/Turkey/Assembly/term-19.csv
data/Turkey/Assembly/term-2.csv
data/Turkey/Assembly/term-20.csv
data/Turkey/Assembly/term-21.csv
data/Turkey/Assembly/term-22.csv
data/Turkey/Assembly/term-23.csv
data/Turkey/Assembly/term-24.csv
data/Turkey/Assembly/term-25.csv
data/Turkey/Assembly/term-3.csv
data/Turkey/Assembly/term-4.csv
data/Turkey/Assembly/term-5.csv
data/Turkey/Assembly/term-6.csv
data/Turkey/Assembly/term-7.csv
data/Turkey/Assembly/term-8.csv
data/Turkey/Assembly/term-9.csv

We should match on the page names displayed as links (as that's what we're
using in the original fetch), not on the actual name (as that might be
post-redirect, and different).
This matches an extra 145 people.

Turkey: match on pre-redirect names

---

rake_helpers/combine_sources.rb
templates/reconciliation.html.erb
templates/reconciliation.js

When there are new people to be reconciled persist the data so that only
the new people have to be reconciled rather than having to do everyone
again.
Closes https://github.com/everypolitician/everypolitician/issues/197

Persist CSV data between reconciliation runs

---

countries.json
templates/reconciliation.js

We calculate the width of the progress bar based on how big the votes
array is. So in order to make it work for skips we insert a null value
into the votes array. We then compact the votes array before creating
the CSV.
Closes https://github.com/everypolitician/everypolitician/issues/205

Make sure skipping moves the progress bar

---

data/Wales/Assembly/ep-popolo-v1.0.json
data/Wales/Assembly/sources/instructions.json
data/Wales/Assembly/sources/manual/parties_wikidata.csv
data/Wales/Assembly/sources/wikidata/parties.json

Use the new Wikidata Party approach from https://github.com/everypolitician/everypolitician-data/pull/1274 to add info about the parties in the Welsh Assembly.

Wales: Add wikidata about Parties

---

countries.json
data/Estonia/Riigikogu/ep-popolo-v1.0.json
data/Estonia/Riigikogu/sources/instructions.json
data/Estonia/Riigikogu/sources/manual/area_wikidata.csv
data/Estonia/Riigikogu/sources/wikidata/areas.json
lib/area_wikidata.rb
rake_helpers/combine_sources.rb
rake_helpers/generate_ep_popolo.rb

Similarly to how we fetch Party information from Wikidata, do the same thing for Areas
(There's a lot of overlap here that can be factored away later, but let's leave that until we've also done this for People, Terms, and the Legislature itself to avoid prematurely finding the wrong abstractions).

Estonia: Add Area information from Wikidata

---

rake_helpers/combine_sources.rb

We want to treat all cells in the reconciliation CSV as strings, so we
disable all converters to avoid any surprises.
This should fix the problem @tmtmtmtm was having in https://github.com/everypolitician/everypolitician-data/commit/31fefa1d3fccfee803da3b3a0876282fc8b6d2e4.

Disable converters for reconciled CSVs

---

lib/reconciliation.rb
lib/reconciliation/fuzzer.rb
lib/reconciliation/interface.rb
lib/reconciliation/legacy_csv.rb
lib/reconciliation/template.rb
rake_helpers/combine_sources.rb
templates/reconciliation.html.erb
templates/reconciliation.js
test/reconciliation_fuzzer_test.rb

Moves most of the reconciliation logic out of the `rake_helpers/combine_sources.rb` file and into separate classes in the `lib` directory. This makes it easier to focus in on particular bits of the code for refactoring, rather than having to comprehend what the whole blob of code is doing.
I've also added some extra logic to the reconciliation interface which displays fields which are common to both the existing and incoming fields, including images.
Related to https://github.com/everypolitician/everypolitician/issues/204
Closes https://github.com/everypolitician/everypolitician-data/issues/1215

Reconciliation improvements

---

countries.json
data/Northern_Ireland/Assembly/sources/parlparse/README
data/Scotland/Parliament/sources/parlparse/README
data/UK/Commons/sources/parlparse/README

We now fetch a streamlined CSV as part of the normal `rake` build, so
don't need the full JSON, or the instructions on how to do the
out-of-band pre-build.

UK: remove obsolete parlparse data and instructions

---

templates/reconciliation.html.erb
templates/reconciliation.js
templates/sass/_styles.scss

The new unified "No matches" button does what the old "Skip" button used to do (ie: adds a null row to window.votes, which is skipped by the CSV compiler).
Fixes everypolitician/everypolitician#216.

Combine "Skip" and "No matches" buttons

---

templates/reconciliation.html.erb
templates/reconciliation.js
templates/sass/_styles.scss

We use the Dice coefficient for each match to highlight strong matches, and de-emphasise weak matches. Middling matches (0.6-0.9) are pulled out in yellow.
Fixes everypolitician/everypolitician#201.

Colour-code existing matches based on match strength

---

templates/reconciliation.html.erb
templates/reconciliation.js
templates/sass/_styles.scss

When reconciling, show whether each field matches or not, to make it easier to scan for errors.
Closes https://github.com/everypolitician/everypolitician/issues/234

Reconciler: show matching fields as green or red

---

rake_helpers/combine_sources.rb

Currently the two main approaches to rebuilding the data for a
legislature are:
* bundle exec rake clean default
* bundle exec rake clobber default
The first simply regenerates the output based on the data previously
fetched from all the individual sources (in `instructions.json`)
The second re-fetches all of those sources first.
It would sometimes be useful to have more fine-grained control, so that
we could, for example, re-fetch _only_ the parlparse data for the UK,
rather than the Wikidata. This would allow us to have some updates that
are 'trusted', and so could be merged automatically, without risk of
unwanted changes from other sources sneaking in.
Here we introduce an environment variable REBUILD_SOURCE. If this is
set, any source which includes the string set in that variable …

Rebuild any sources in REBUILD_SOURCE

---

templates/reconciliation.html.erb
templates/reconciliation.js

Highlight individual words in the 'name' field (or equivalent) for each
match that also exist in the original record. This will make it easier
to see differences, especially in different alphabets
Closes https://github.com/everypolitician/everypolitician/issues/262

Reconciler: Highlight common words in the name

---

templates/reconciliation.html.erb
templates/reconciliation.js
templates/sass/_styles.scss

When there is an ambiguous match you might want to defer it until after
you've done the rest of the matching.
This change adds an option which can be activated with the '?' key, when
used this puts the card at the back of the stack so that it will be
shown again at the end of reconciliation.
Fixes https://github.com/everypolitician/everypolitician/issues/237

Reconciler: Add "Show me this card again later" option

---

rake_helpers/combine_sources.rb

Wrapping the call to 'combine_sources' with stackprof revealed that this
was the most expensive method being called. This change optimizes it to
use a hash lookup, which seems to speed up rebuilding a country quite
significantly.

combine_sources: Speed up remap function

---

bin/current_term_info.rb

Add a simple script to provide some stats on the data we have for
current members of a legislature.
This generates a report, for example for the UK, that tells us what % of
people have various fields filled currently:
e.g.
UK: 
* TOTAL: 650
* Email: 648 (99.7%)
* Facebook: 234 (36.0%)
* Twitter: 583 (89.7%)
* Wikidata: 649 (99.8%)
* Freebase: 62 (9.5%)
* DOB: 649 (99.8%)
* Gender: 649 (99.8%)
* Image: 637 (98.0%)
Estonia:
* TOTAL: 101
* Email: 101 (100.0%)
* Facebook: 0 (0.0%)
* Twitter: 1 (1.0%)
* Wikidata: 101 (100.0%)
* Freebase: 17 (16.8%)
* DOB: 101 (100.0%)
* Gender: 101 (100.0%)
* Image: 101 (100.0%)
Australia:
* TOTAL: 150
* Email: 150 (100.0%)
* Facebook: 127 (84.7%)
* Twitter: 0 (0.0%)
* Wikidata: 150 (100.0%)
* Freebase: 10 (6.7%)
* DOB: 149 (99.3%)
* Gender: 150 (100.0%)
* …

Report card for current terms

---

lib/reconciliation/interface.rb
lib/reconciliation/template.rb
rake_helpers/combine_sources.rb
templates/reconciliation.html.erb

The Reconciliation Interface was responsible for too many things, making it difficult to reuse it in other places (e.g. for Membership as well as Person reconciliation). Simplify it.

Simplify the Reconciler

---

templates/reconciliation.html.erb

Previously when a field name was truncated there was no way to see what the full field name was. This change adds a `title` tag to the `<dt>` so that the full field name appears on hover.
Fixes https://github.com/everypolitician/everypolitician/issues/295

Reconciler: Show full field name when hovering

---

countries.json
data/Scotland/Parliament/ep-popolo-v1.0.json
data/Scotland/Parliament/sources/manual/group_wikidata.csv
data/Scotland/Parliament/sources/wikidata/groups.json
rake_helpers/generate_ep_popolo.rb

A party of 'None' is used for the Presiding Officer, who has no alliances, and is slightly different from being an Independent.
Closes https://github.com/everypolitician/everypolitician/issues/304

Scotland: distinguish 'Independent' and 'None'

---

rake_helpers/generate_ep_popolo.rb

csv_to_popolo creates `executive` positions if there's a suitable
column. For now we're not doing anything with these, so discard them.

Discard 'executive' memberships

---

templates/reconciliation.html.erb
templates/reconciliation.js

When reconciling, show names in as many languages as we have, so we can spot matches that aren't so obvious.
Part of https://github.com/everypolitician/everypolitician/issues/263 (still need to add aliases, and also to tie these into the fuzzing)

Reconciler: Show names in multiple languages

---

Gemfile.lock
data/Wales/Assembly/sources/instructions.json
data/Wales/Assembly/sources/manual/position-filter.json
data/Wales/Assembly/sources/wikidata/positions.json
data/Wales/Assembly/unstable/positions.csv
lib/fetcher.rb
lib/wikidata_lookup.rb
rake_helpers/combine_sources.rb
rake_helpers/generate_final_csvs.rb
rakefile_common.rb

Store P39 (position held) data for all people with Wikidata links.
To add these, from the directory of a legislature run:
1. `bundle exec rake build_p39s` — adds instructions for how to build
2. `bundle exec rake clean default` — build the legislature as normal
3. edit `sources/manual/position-filter.json` — move the entries from 'unknown' to 'exclude' or 'include'
4. `bundle exec rake clean default` — rebuild the legislature

Wikidata positions

---

rake_helpers/generate_final_csvs.rb

We can't build build the output unless we have the source data, so bail out early in that case.
Also, remove the example Wikidata records from the filter data before writing it back out.

Don't try to create positions.csv unless we already have a raw positions.json file

---

data/Estonia/Riigikogu/sources/instructions.json
data/Estonia/Riigikogu/sources/manual/position-filter.json
data/Estonia/Riigikogu/sources/wikidata/positions.json
data/Estonia/Riigikogu/unstable/positions.csv
data/Wales/Assembly/sources/manual/position-filter.json
rake_helpers/generate_final_csvs.rb

Whilst we're building the Filter files, we should group the Positions by
what type they are — e.g. the Membership of this or other legislatures;
memberships of the Executive, etc.
This will let us process them differently, when we get around to doing more
(or output them better in Popolo)

Position Files: arrange the Filter file by Position type

---

data/Portugal/Assembly/ep-popolo-v1.0.json
data/Portugal/Assembly/sources/instructions.json

Portugal (Assembly) — point at original source

---

data/Cabo_Verde/Assembly/ep-popolo-v1.0.json
data/Cabo_Verde/Assembly/sources/instructions.json

Cabo Verde (Assembly) — point at original source

---

rake_helpers/generate_final_csvs.rb

Look up by direct hash access on person.id, rather than scanning the
full list every time. This reduces the build time for this section
significantly (in Turkey, it drops from 115 seconds to 3 seconds on my
laptop)

Build CSVs: Turn 'persons' into a hash

---

countries.json
data/Alderney/States/ep-popolo-v1.0.json
data/Alderney/States/term-2014.csv
rake_helpers/combine_sources.rb

When we're constructing the merged CSV file to be given to CSV-to-Popolo,
ensure that we add a gender header when reading data from GenderBalance,
rather than the headers from the Gender-Balance API file.
Without this, we end up with (usually blank) columns for 'male', 'female', etc,
and none for 'gender' itself, ensuring that the data is never recognised.

Ensure gender header is added to merged CSV

---

templates/reconciliation.html.erb
templates/reconciliation.js
templates/sass/_styles.scss

At the end of matching all incoming people to existing people, it's
possible that the matches between IDs (of incoming people) to UUIDs
(of existing people) aren't one-to-one.  With the change in this
commit, a warning will be displayed at the end if this is the case,
including the IDs / UUIDs so this can be investigated further.
(n.b. I slightly fiddled the data to make that screenshot, so the actual
IDs won't make sense...)
Fixes https://github.com/everypolitician/everypolitician/issues/240

Reconciler: warn if there are multiple IDs or UUIDs after matching

---

lib/remotesource.rb
rake_helpers/combine_sources.rb

Name this after what each thing _is_, rather than what this _does_. Then
move the instantiation code out of the Rakefile, and into the class.

combine_sources: Rename 'Fetcher' as 'RemoteSource'

---

countries.json
data/Australia/Representatives/sources/instructions.json
data/United_States_of_America/House/sources/instructions.json
data/United_States_of_America/Senate/sources/instructions.json
rake_helpers/combine_sources.rb

We also have other area data, so explicitly name the OCD instructions.

combine_sources: explicitly name 'OCD' type

---

lib/source.rb
rake_helpers/combine_sources.rb

The way this was previously defined meant that `super` wasn't behaving as expected when we wanted to add a new field for Wikidata sources, triggering:
```
TypeError: self has wrong type to call super in this context: Source::Wikidata (expected Binding)
```
This way is much cleaner.

Tidy up Source hierarchy

---

templates/reconciliation.html.erb
templates/reconciliation.js

The logic for showing the cards on the left and right side (incoming vs
existing people) was getting a little hard to follow, as they were both
using the same template, even though they were conceptually quite
different things, and almost every section of the card had to be wrapped
in a check to see which type it was.
Split these out so that it's easier to follow (even though there’s now a
small amount of duplication between them), but also harmonise some of
the other code that was needlessly different.

Reconciler: Some refactoring

---

data/Botswana/Assembly/ep-popolo-v1.0.json
data/Botswana/Assembly/sources/instructions.json
data/Botswana/Assembly/sources/manual/group_wikidata.csv
data/Botswana/Assembly/sources/wikidata/groups.json

Botswana (Assembly) — add Group information

---

data/Turks_and_Caicos_Islands/Assembly/ep-popolo-v1.0.json
data/Turks_and_Caicos_Islands/Assembly/sources/instructions.json
data/Turks_and_Caicos_Islands/Assembly/sources/manual/group_wikidata.csv
data/Turks_and_Caicos_Islands/Assembly/sources/wikidata/groups.json

Turks and Caicos Islands (Assembly) — add Group information

---

bin/wikidata_info.rb

When generating the report on how many parties are matched to Wikidata, don't include Unknowns.

Don’t include 'unknown' when calculating Party stats

---

lib/source.rb
rake_helpers/combine_sources.rb
rake_helpers/generate_final_csvs.rb

Remove some of the things that aren't so relevant, make other things more consistent:
*    Don’t report on _how_ we’re merging
*    Only warn of unmatched data if there is some
*    Report only on how many term files created
*    Make Corrections files consistent
*    Warn about some of the unmatched Parties
*    Make Top Identifiers more distinctly a new section
*    Make the 'Reading…" lines green

Make the build output quieter and more consistent

---

lib/source.rb
rake_helpers/combine_sources.rb

A gender wins if it got at least 80% of the votes for any gender
— ignoring skips.
Also warn if the winning vote differs from any gender already set from a
different source.

Don’t count "skipped" GenderBalance votes towards threshold

---

templates/reconciliation.js
templates/sass/_styles.scss

We want to be able to do other things in the card that require clicking
(e.g. following links, adding a "show more…" button), so prepare for
this by restricting the "Click to match" area to the header.
(As 99% of usage of the reconciler is currently by me, and I almost
always use the keyboard rather than the mouse, the negative impact of
this should be negligible)

Reconciler: restrict the clicking area to the header

---

countries.json
data/Australia/Representatives/sources/instructions.json
data/Canada/Commons/sources/instructions.json
data/Finland/Eduskunta/sources/instructions.json
lib/source.rb
rake_helpers/combine_sources.rb

Rather than looking for a "corrections" file at a specified location,
require it to be explicitly set in the `instructions.son` file to be used.

Require 'corrections' to be an explicit Source

---

bin/wikidata_missing_report.rb

Generate a report of all legislatures for which we have zero people matched to Wikidata (suitable for keeping the comment on https://github.com/everypolitician/everypolitician/issues/393 up to date)

Add script to report on missing Wikidata

---

data/Northern_Ireland/Assembly/sources/manual/terms.csv
data/Scotland/Parliament/sources/manual/terms.csv

Parlparse lists the start date of Memberships as election day, and
parlparse-to-csv gets confused if that's before the start_date of the term.
We should probably fix parlparse-to-csv to Do The Right Thing™ here, but
for now it's simplest to just set the start date.

Scotland/NI: move term start date to election day

---

lib/remotesource.rb
lib/wikidata_lookup.rb

Rather than printing a big stack trace when an http request fails we instead just print an error message and exit.

Better error messages when fetching remote urls

---

Gemfile.lock

The latest version includes a fix for lookups that don't contain any entities - https://github.com/everypolitician/wikisnakker/pull/40.

Update to latest version of wikisnakker

---

bin/last_updated.rb
bin/learn_position.rb
bin/legislature_wikidata_ids.rb
countries.json

A shebang line which hardcodes /usr/bin/ruby may cause problems
if you are using rbenv or in any other situation where the version
of ruby that comes first in your PATH is not /usr/bin/ruby.
Using /usr/bin/env ruby in the shebang line will exec the ruby
binary that comes first in your PATH.
Investigated with Dave Whiteland (@davewhiteland).

Update shebang lines in scripts to use /usr/bin/env ruby

---

rake_helpers/generate_final_csvs.rb

"Wikidata Persons matched" is a little ambiguous, as it seems like it
means "People we got from Wikidata who we couldn't match up to existing
people", rather than "People for whom we couldn't find any matches
within Wikidata".
Make it a little more explicit which direction we're reporting on.

Tweak reporting of Info with no Wikidata

---

rake_helpers/generate_ep_popolo.rb

If duplicate memberships are detected we emit a warning and then discard
the duplicates.
Fixes https://github.com/everypolitician/everypolitician/issues/395

Remove duplicate memberships from Popolo output

---

rake_helpers/verify_source_data.rb

Rather than asking each row of `merged.csv` in turn what date columns it
has, pre-build the list of all the date columns in the CSV.
In the most extreme case (Turkey, with over 12,000 rows) this speeds
this task from ~40 seconds to ~0.2 seconds!

Build speed: Pre-generate date_headers list

---

countries.json
data/Antigua_and_Barbuda/Representatives/ep-popolo-v1.0.json
data/Antigua_and_Barbuda/Representatives/sources/instructions.json
data/Antigua_and_Barbuda/Representatives/sources/manual/group_wikidata.csv
data/Antigua_and_Barbuda/Representatives/sources/wikidata/groups.json

Antigua and Barbuda (Representatives) — add Group information

---

lib/wikidata_lookup.rb

The WDQ url isn't very reliable so this changes the election lookup to use the SPARQL query endpoint instead.
First part of https://github.com/everypolitician/everypolitician/issues/402

Switch to SPARQL endpoint for election lookup

---

countries.json
data/Canada/Commons/sources/instructions.json
lib/source.rb
rake_helpers/combine_sources.rb

We used to allow multi-approach merging, but this is only used now by
Canada, as it didn't turn out to be a useful approach. Simplifying this
will allow to us harmonise more of this code in advance of switching the
approach more generally.

Only allow a single merge-method

---

rakefile_common.rb

Some events have string ids and others have symbols. When trying to sort
events those that have the same start_date fall back to sorting by id,
which was failing because of the comparison between a symbol and a
string.
This should fix most of the Rollbar errors that have come in over the past couple of days.

Convert event ids to strings when sorting

---

bin/election_report.rb

Generate a list of all legislatures, ordered according to an external
mechanism, showing whether we have election data for them yet or not.
This lets us work down them all in a rough priority order.

Report on which Legislatures need Election data

---

lib/reconciliation/interface.rb

We already ordered the results by how good the first match was. But lots
of the time we have lots of matches that are 100%, so we want to next
order by how _bad_ the second match is (i.e we're even more confident
that the first match must be right, as nothing else is even close)
Closes https://github.com/everypolitician/everypolitician/issues/260

Reconciler: order next by weakness of 2nd match

---

bin/dashboard.rb
rake_helpers/generate_stats.rb
rakefile_common.rb

Rather than generating stats from a `bin/` file (as we currently do in
the dashboard script, and others), auto-generate them any time we're
rebuilding a legislature.
This will live in `unstable/` whilst we play around with the format etc for it.

Add a `stats.json` file

---

countries.json
data/Antigua_and_Barbuda/Representatives/ep-popolo-v1.0.json
data/Antigua_and_Barbuda/Representatives/sources/wikidata/groups.json
data/Antigua_and_Barbuda/Representatives/unstable/stats.json
lib/wikidata_lookup.rb

Allows multiple groups to be matched up to the same wikidata identifer. Previously this didn't work if multiple groups were matched up to a single wikidata id, in that case only one group would be correctly matched to wikidata.
Initial work towards https://github.com/everypolitician/everypolitician/issues/428

Match multiple groups to a single wikidata identifier

---

countries.json
data/Colombia/Representatives/ep-popolo-v1.0.json
data/Colombia/Representatives/sources/instructions.json
data/Colombia/Representatives/sources/manual/group_wikidata.csv
data/Colombia/Representatives/sources/wikidata/groups.json
data/Colombia/Representatives/unstable/stats.json

Colombia (Representatives) — add Group information

---

templates/reconciliation.js

Previously, it would attempt to extract the UUID from the header
element though the UUID attribute is actually set on its parent.

Fix click voting in reconciler

---

data/Australia/Representatives/sources/instructions.json

Spotted that we're not pulling in the twitter data that the OpenAustralia scraper already has, so added `twitter` to the columns we're using.
(Right now, this doesn't pick up any new data, but the more sources the merrier)

Australia (House of Representatives) collect twitter data from openaustralia scraper

---

countries.json
data/Colombia/Representatives/ep-popolo-v1.0.json
data/Colombia/Representatives/sources/manual/terms.csv
data/Colombia/Representatives/unstable/stats.json

```
* 2 of 56 unmatched
{:id=>"Q6005013", :name=>"María del Socorro Bustamante"}
{:id=>"Q20022295", :name=>"Yahir Acuña"}
54 x wikidata
1 x isni
1 x fast
1 x freebase
1 x gnd
Persons matched to Wikidata: 54 ✓ | 114 ✘
No wikidata: LUIS FERNANDO URREGO CARVAJAL (33f1985f-bf69-47e5-96ce-ac1d928cc111)
No wikidata: NERY OROS ORTÍZ (aed4ba2c-f89d-4f88-8588-a7c5c5d02b15)
No wikidata: DIELA LILIANA BENAVIDES SOLARTE (6b04d2b3-7e60-4d6f-a380-946c0956f505)
No wikidata: MARÍA EUGENIA TRIANA VARGAS (8148dfd3-248c-458f-a581-ca9a5b215531)
No …
```

Colombia (Representatives): better Term dates

---

rake_helpers/generate_stats.rb

In the stats file, include some initial data on P39 positions. For now only include Executive posts.

Stats: include count of Executive positions

---

countries.json
data/Brazil/Deputies/sources/manual/position-filter.json
data/Brazil/Deputies/sources/wikidata/positions.json
data/Brazil/Deputies/unstable/positions.csv
data/Brazil/Deputies/unstable/stats.json

```
* 11 of 274 unmatched
{:id=>"Q10393111", :name=>"Walter Shindi Ihoshi"}
{:id=>"Q16940797", :name=>"Sérgio Olímpio Gomes"}
{:id=>"Q16940022", :name=>"Flavio Augusto da Silva"}
{:id=>"Q10390275", :name=>"Vicente Paulo da Silva"}
{:id=>"Q16337696", :name=>"José Olímpio Silveira Moraes"}
{:id=>"Q20045978", :name=>"Luis Antonio Franciscatto Covatti"}
{:id=>"Q10281433", :name=>"Fernando Marroni"}
{:id=>"Q20045762", :name=>"Fábio Abreu Costa"}
{:id=>"Q10309081", :name=>"José Carlos Becker de Oliveira e Silva"}
{:id=>"Q19708978", :name=>"Giovani Feltes"}
⚥ data for 519; 284 added
263 x wikidata
9 x viaf
8 …
```

Brazil (Deputies): Learn new Positions

---

bin/dashboard.rb

The version in `start_date` expands partial dates, e.g. 2014 to
2014-01-01, and we want the underlying information to notice which ones
we need to find more precise information for.

Dashboard: use raw `start_date` for terms

---

bin/dashboard.rb

Whilst we're clearing the backlog, only show the largest legislature for
each country.

Dashboard: Only show one legislature per country

---

countries.json
data/Laos/Assembly/ep-popolo-v1.0.json
data/Laos/Assembly/sources/manual/terms.csv
data/Laos/Assembly/unstable/stats.json

```
* 37 of 55 unmatched
{:id=>"Q7429308", :name=>"Saysmone Khomthavong"}
{:id=>"Q7711395", :name=>"Thatsadaphone Nosing"}
{:id=>"Q7795970", :name=>"Thongvankham Sithilath"}
{:id=>"Q6399936", :name=>"Khamchanh Sakountava"}
{:id=>"Q5072184", :name=>"Chanhthuem Latmany"}
{:id=>"Q5072182", :name=>"Chanhsouk Bounpachit"}
{:id=>"Q4855525", :name=>"Bangon Xayalath"}
{:id=>"Q7111324", :name=>"Ousavanh Thiengthetvonga"}
{:id=>"Q5072183", :name=>"Chanhsy Vannavongxay"}
{:id=>"Q6399978", :name=>"Khamlek Keosomphanh"}
18 x wikidata
Persons matched to Wikidata: 18 ✓ | 114 …
```

Laos (Assembly): better term dates

---

countries.json
data/Moldova/Parlamentul/ep-popolo-v1.0.json
data/Moldova/Parlamentul/sources/manual/terms.csv

```
Add memberships from sources/manual/gone.csv
* 14 of 107 unmatched
{:id=>"Q6845152", :name=>"Mihai Moldovanu"}
{:id=>"Q20429568", :name=>"Vasile Bîtca"}
{:id=>"Q15071201", :name=>"Monica Babuc"}
{:id=>"Q13428691", :name=>"Vasile Botnari"}
{:id=>"Q7911411", :name=>"Valeriu Munteanu"}
{:id=>"Q12731069", :name=>"Irina Vlah"}
{:id=>"Q6968023", :name=>"Natalia Gherman"}
{:id=>"Q20431851", :name=>"Oleg Balan"}
{:id=>"Q15071069", :name=>"Maia Sandu"}
{:id=>"Q1110215", :name=>"Dorin Chirtoacă"}
93 x wikidata
15 x freebase
4 x viaf
2 x isni
2 x gnd
Creating …
```

Moldova (Parlamentul): better Term name

---

bin/clean_ids_file.rb

Over time the (incoming ID)→(EP UUID) mapping files can drift out of
date, as underlying IDs change etc. This script will clean one up by
removing any entries that refer to IDs that are no longer in the
incoming data.

Clean an ID mapping file

---

countries.json
data/El_Salvador/Legislative_Assembly/sources/instructions.json

The upstream scraper doesn't have the area columns, and no longer works
against the site anyway, so (at least for now) just use the existing
snapshot (so full rebuilds aren't lossy)

El Salvador: don't refresh data

---

lib/wikidata_lookup.rb

If we look up the Wikidata for a list of items, and one of those has
been renamed, we will get back the data keyed against the _new_ ID,
rather than the old one. Ideally this would all get resolved
transparently, but for now we can at least cope better with not having
the expected results for an item.
This should stop the Rollbar errors for Lebanon, Sweden, and Greece.

Warn of renamed Wikidata items

---

countries.json
data/Estonia/Riigikogu/ep-popolo-v1.0.json
data/Finland/Eduskunta/ep-popolo-v1.0.json
rake_helpers/combine_sources.rb

We already allow a single source to supply multiple values for any of these
fields (;-separated) — now we extend that to combine the data from multiple
sources — e.g. an image from the official site + another one from Wikidata.

Accept multiple sources for twitter/facebook/image

---

templates/reconciliation.js

If you skipped more than one match in the reconciler, they would be
reported a duplicate IDs for the UUID "null".  This commit filters out
such skipped votes before looking for duplicates in them.
Fixes everypolitician/everypolitician#367

Reconciler: don't consider skipped matches when listing duplicates

---

rake_build/generate_final_csvs.rb
rakefile_common.rb

This is a workaround for [sort_by working differently between OS X and
Linux](https://bugs.ruby-lang.org/issues/11379).

Add an Enumerable#portable_sort_by method

---

lib/remotesource.rb

We want the incoming data to be in a consistent order, so that diffs are
more obvious, and we don't get false positives simply from reordering.
So warn any time we have a query that doesn't contain an ORDER BY, so we
can more easily notice and go tidy them up.
Closes https://github.com/everypolitician/everypolitician/issues/458

Warn if Morph queries have no ORDER BY

---

templates/reconciliation.html.erb

Try to split the fields on the `;` and display all parts separately, rather than as one.
Fixes https://github.com/everypolitician/everypolitician/issues/469

Reconciler: Ensure `;` separated fields are rendered correctly

---

countries.json
data/Burkina_Faso/Assembly/ep-popolo-v1.0.json
data/Burkina_Faso/Assembly/sources/manual/terms.csv

Specifically this is providing end dates that were previously both fuzzy (only years) and missing (missing `end_date` heading in the CSV, whoops)
Closes #13994

update Burkina Faso term dates to be more accurate

---

templates/reconciliation.html.erb
templates/reconciliation.js

When generating cards in the Reconciler, we previously only included fields
that were common between the incoming card and at least one of the
comparisons. However, there are some fields we should _always_ display. Let's start with images and twitter handles, and make the twitter links clickable.
Closes https://github.com/everypolitician/everypolitician/issues/468

Reconciler: Always show twitter links, and make them clicky

---

Rakefile.rb
lib/git.rb

The `countries.json` file includes the URLs of files via
cdn.rawgit.com, and those URLs include the commit's object name (also
known as its hash or SHA-1) so that a known version of every file is
referred to in each version of countries.json.
The commit object names used in these URLs (for both the Popolo JSON
and term CSV files) would always be the same for all files in a
particular country, since the commit and last modification time would be
found from a command like:
git --no-pager log --format='%h|%at' -1 data/Australia/
... and the results would be used for all files for that country.
This meant that if any file for that country was updated, then all files
for that country would have a new commit object name in their URL. This
was bad, because a consumer of that data may be using …

Use finer-grained git commit object names in file URLs

---

CHANGES.md
rake_build/generate_ep_popolo.rb

Since 0f58dcfe42d32f5941f452c7e66ad17e1591609e, each legislature has had its own UUID. Use that as the ID (taking care to make sure that legislative memberships reflect it)
Closes https://github.com/everypolitician/everypolitician/issues/427

Use the legislature’s UUID as its ID

---

Rakefile.rb

This seems to be an interface change in a recent version of the JSON
gem, and is now incompatible with :symbolize_names, so turn it off.

Turn off 'create_additions' when loading JSON

---

Gemfile
Gemfile.lock
lib/reconciliation/fuzzer.rb
templates/reconciliation.html.erb
templates/reconciliation.js

If we’re comparing twitter handles, it’s _much_ better if they’re actually
in the same format, rather than comparing "tmtm" with "https://www.twitter.com/tmtm"
Closes https://github.com/everypolitician/everypolitician/issues/476

Reconciler: standardise Twitter handles when comparing

---

lib/patcher.rb
rake_build/combine_sources.rb
test/patcher_test.rb

Small steps towards refactoring `combine_sources`: pull out a Patcher
class that combines an existing row with an incoming row, according to a
set of instructions.
I've put in place a very simple test framework for this, but it still
needs major refactoring and testing.
It does, however, drop the flog score for `combine_sources` itself from
637.4 to 472.6

Add a Patcher to combine_sources

---

rake_build/combine_sources.rb
rake_build/generate_ep_popolo.rb
rake_build/generate_final_csvs.rb
rake_build/generate_stats.rb
rake_build/turn_csv_to_popolo.rb
rake_build/verify_source_data.rb
rakefile_common.rb

To simplify the build logic, extact some of the fixed filenames we use
(e.g. merged.csv, merged.json, positions files) as constants, and use
Pathname to make them easier to handle.

Build: extract filenames as constants

---

.rubocop.yml
.rubocop_base.yml

Rubocop can inherit configuration from a file at a remote URL. This
allows us to use the config in this repo, as the base for _all_ our
related ones, rather than having to keep them all in sync manually.
So split out the inheritable one to `.rubocop_base.yml`, and keep the
project specific config on the main .`rubocop.yml`

Split out a 'base' Rubocop configuration

---

.rubocop_base.yml

We actually want the default behaviour here, which is to always prefer `/…/` style regexes, except where there's a literal slash, in which case switch to `%r{}`-style.
(NB: http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/RegexpLiteral is
more than a little confusing (largely as it doesn't define what 'mixed' means),
but the default config file includes a much better explanation!)

Change our default Rubocop Regex preferences

---

lib/source.rb
rake_build/combine_sources.rb

Today's inch-by-inch refactoring of `combine_sources`:
Rather than pre-scanning the configuration of each source to make sure
it has a 'type', move that check into the constructor method.
(`flog` score moves from 460.0 to 451.2)

Move 'type'-checking into Source class

---

templates/reconciliation.html.erb

This was broken in a previous pull request because I forgot the `return` from the `_.any` function body.
Fixes https://github.com/everypolitician/everypolitician/issues/478

Fix reconciler match highlighting

---

rake_build/combine_sources.rb

Rather than having this loop do two slightly different things, separate out the "map all incoming IDs to their UUIDs" from the "give each row of data a UUID". This is a little clumsier now (flog score rises from 451.2 to 464.1), but will make it easier to factor out each of those bits to different places.

Separate out the UUID generation code

---

lib/source.rb
rake_build/combine_sources.rb

Since https://github.com/everypolitician/everypolitician-data/pull/10981 we only allow instructions files to provide a single set of merge instructions per source. So we should use that directly, rather than wrapped up in a single-entry list.
(Reduces flog score from to 464.1 to 457.1)

Single merge instructions

---

lib/reconciliation.rb
rake_build/combine_sources.rb

This returns the previously_reconciled data, or throws an error if empty.
On the way out we simply catch it and abort with it.
(Flog drops from 457.1 to 425.7)

Refactor interface with Reconciler

---

lib/uuid_map.rb
test/uuid_map_test.rb

Every Membership source has a parallel `source-ids.csv` file to provide
the mapping between the incoming source IDs, and our matching UUIDs.
Currently those live in the same directory as the source file.
We would like to, instead, move those into their own directory, so that
it's much more obvious that these are a different type of file, and the
source directory only contains files that are actually from the remote
sources.
We can do that by hooking into the UUID Map class to make it aware of
both the old location, and the new one. Then if it can't read from the
new location, it will fall back on the old location — but always
rewrite the file out to the new location. Over time, as we build every
country, the files will gradually all be moved, and we can simplify
this down again.

Gradually move -ids.csv files

---

countries.json
data/Jersey/meta.json

This got set to UK data by error, as Wikidata doesn't have a `Country` set,
but only an "located in the administrative territorial entity" which is set
to "UK"

Fix meta.json for Jersey

---

Gemfile

support for ruby 2.0.0 (including security fixes) ended in February:
https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/
Upgrading our minimal version to 2.1 also gives us aaccess to a few features we
want to start using, including:
* Pathname.write
* required named parameters

Require ruby 2.1.0 onwards

---

Gemfile
Gemfile.lock

We want to reduce the complexity of the build process, so tracking the [Flog](http://ruby.sadi.st/Flog.html) scores is a good proxy for checking if we're moving in the right direction.

Add `flog` to Gemfile

---

countries.json
lib/git.rb

We recently hit a case where the short version doesn't work: Peru was pointing at https://github.com/everypolitician/everypolitician-data/commit/8b15cc3, but we have a clash between https://github.com/everypolitician/everypolitician-data/commit/8b15cc3c (which is what we need here) and https://github.com/everypolitician/everypolitician-data/commit/8b15cc39 
So instead switch to using the full version.

Use full commit hash rather than abbreviated one

---

lib/ocd_id.rb
lib/source.rb
rake_build/combine_sources.rb

Pull the OCD Lookup class to its own file, and split out separate classes for plain lookups and fuzzy lookups.
(flog drops from 430.5 → 428.7)

Split up OCD Lookup classes

---

rake_build/verify_source_data.rb

The build process is meant to check that date fields have values that
actually look like dates. But it hasn't been working, because it’s been
looking for "date" columns by string, rather than symbol.

Fix broken date checking

---

bin/learn_position.rb
data/Estonia/Riigikogu/sources/manual/position-filter.json
data/Estonia/Riigikogu/unstable/stats.json
rake_build/generate_final_csvs.rb
rake_build/generate_stats.rb
templates/position-filter.js

We want to start displaying information on Cabinet memberships. Currently,
however, these are grouped with other positions under the
'Executive' section. So we need to split out a separate 'Cabinet' position.
We then want to change the build report and stats generation to show
information solely about the Cabinet, not the other Executive positions.
Estonia has been rebuilt to show this in action.

split Cabinet positions from Other Executive

---

.rubocop.yml

we're now requiring Ruby 2.1 generally, so we should update Rubocop to
also target that (e.g. so that it's happier with default named
parameter syntax)

Raise rubocop's TargetRubyVersion

---

lib/position/map.rb
rake_build/generate_final_csvs.rb

This adds a new column to the `positions.csv` file telling us the 'type'
of position (cabinet, executive, other_legislatures, etc)
This then will let us select a subset of positions from it (e.g. the
Cabinet memberships someone has held)

Add a 'type' column to positions.csv

---

lib/uuid_map.rb
test/uuid_map_test.rb

The code that was used to migrate the id map files from `data-ids.csv`
to `idmap/data.csv` was throwing a rake error when adding a new
source and rebuilding the data with rake clean default, since there
was no @oldfile or @ newfile. Moving the .read down to the
Rcsv.parse call seemed to fix the error.
Thanks @chrismytton for the tip :D

Update mapping method in the UuidMapFile class

---

.travis.yml
Gemfile
Gemfile.lock
Rakefile.rb

This adds a new Rake task that gets run on Travis which goes through the open pull requests and closes any that are outdated. It uses [close_old_pull_requests](https://github.com/everypolitician/close_old_pull_requests) to do the actual work, and it replaces [pull_request_cleaner](https://github.com/everypolitician/pull_request_cleaner).

Run pull request cleaner on Travis

---

rake_build/generate_final_csvs.rb

The build for Spain was failing due to a Position with no label. For now we simply stop this blowing up, though ideally we should be able to handle this sort of case better. As we probably want to move most of this out to Morph, however, we can defer that for a while.

fix: handle positions with no label

---

bin/dashboard.rb

When reading the export file from Google Analytics, ignore any lines
that don't have enough fields.
Various parts of this file (particularly at the start and end) have an
entirely different format from the 'meat' that we care about, and
something that recently changed in the layout of this started breaking
the dashboard generation script. The easiest way to prevent this is to
simply ignore lines that don't look like they're in the correct format.

Ignore short lines from Google Analytics

---

lib/country_data.rb

We alias EveryPolitician to Everypolitician separately, so explicitly
using EveryPolitician in the module definition causes:
```
warning: already initialized constant EveryPolitician
```

use Everypolitician not EveryPolitician

---

.travis.yml
Gemfile
Gemfile.lock
Rakefile.rb

~~This change splits up the `rake pull_request_summary` command. There are now three versions:~~
~~1. `pull_request_summary:print` will print a summary of the pull request
to the terminal.
2. `pull_request_summary:comment` is for running locally and will post a
comment to GitHub as you if there's an access token in the environment.
3. `pull_request_summary:travis` is for running on Travis and will post
a comment to GitHub as the bot.~~
This switches to the rake task that was introduced in https://github.com/everypolitician/everypolitician-pull_request/pull/6. This means that we're not filling up the rakefiles with code that's better suited living in the same place as the library it calls.
Follows on from #16985

Use rake task from Everypolitician::PullRequest

---

.travis.yml

The tests are the slowest of the three rake tasks that run on Travis by quite a margin. Running them last means that the pull request summary and cleaner can get their work done before the actual testing begins.
This is all part of the wider move to doing more work as part of the Travis build.

Run the tests last on Travis

---

Rakefile.rb
lib/country_data.rb

Previously we assumed we were working with a country in directory-name format (e.g. South_Africa), but the Rebuilder is passing us slugs (i.e. South-Africa). That's the more correct behaviour, so switch to assuming that's what we're getting.
Closes https://github.com/everypolitician/everypolitician/issues/486
The implementation is a little bit clumsy at the moment — we can clean things up substantially by making everything assume they'll be dealing with `EveryPolitician::Country` or `EveryPolitician::Legislature objects`, but that should happen as a separate change.
Also, there's still a slight bootstrapping problem here when we add a new country, but in that case we can just generate an entire file, rather than by country name.

EP_COUNTRY_REFRESH should work by slug

---

Gemfile
Gemfile.lock
rake_build/generate_final_csvs.rb

The code for generating the term CSVs has been extracted to its own gem:
https://github.com/everypolitician/everypolitician-dataview-terms
This replaces the internal implementation with calls to that library instead.
`bundle exec bin/run_command_for_each_legislature rake clean default` shows no changes to any CSV file.
Part of https://github.com/everypolitician/everypolitician/issues/320

use everpolitician-dataview-terms to generate CSVs

---

.travis.yml
scripts/deploy.sh

This adds a script to deploy http://everypolitician.org that runs each time Travis successfully builds the `master` branch.
It does this by installing [viewer-sinatra](https://github.com/everypolitician/viewer-sinatra) and using it to rebuild [viewer-static](https://github.com/everypolitician/viewer-static).
Related to https://github.com/everypolitician/everypolitician/issues/506 as part of [changing how everypolitician.org is deployed](https://github.com/everypolitician/everypolitician/projects/2).

Deploy everypolitician.org from Travis

---

scripts/deploy.sh

Travis was failing to deploy because the version of tar(1) on Linux
doesn't automatically add the -z switch like the OS X version does.
https://travis-ci.org/everypolitician/everypolitician-data/builds/161313383#L312-L313

Add missing switch to tar command in deploy script

---

.travis.yml

Rather than embed the access token in the url we want to add it to `.netrc` so that it gets picked up by git.
This is the same as the change I made in https://github.com/everypolitician/viewer-sinatra/pull/15551, it should have been part of https://github.com/everypolitician/everypolitician-data/pull/17407 but I forgot to include it 😞 
Travis docs: https://docs.travis-ci.com/user/private-dependencies/#API-Token

Use .netrc on Travis for GitHub access token

---

.travis.yml

Travis [defaults to Ruby 1.9.3 for "reliability"](https://docs.travis-ci.com/user/deployment/script/#Deployment-is-executed-by-Ruby-1.9.3). This change means that the deploy script will be run in an [rvm environment](https://rvm.io/set/do) that configures the Ruby on the current `PATH` to be the same as the Ruby that we use for the rest of the build.
Fixes https://github.com/everypolitician/everypolitician/issues/511

Try using a newer Ruby version for deploy script

---

CHANGES.md
data/Estonia/Riigikogu/ep-popolo-v1.0.json
rake_build/generate_ep_popolo.rb

These should be included in `identifiers` per http://www.popoloproject.com/specs/event.html (and per how we do it for Persons, Organisations, etc), not directly embedded at the top level.
Fixes https://github.com/everypolitician/everypolitician/issues/513

Correct how Wikidata is added to a Term

---

lib/instructions.rb
lib/source.rb
rake_build/combine_sources.rb
rake_build/generate_ep_popolo.rb
rake_config/wikidata.rb

Rather than having multiple places iterate over all sources, checking their
type, hide this all behind a `sources_of_type` method on the Instructions class.
This isn’t really an ideal name, but it’ll do for now, whilst we’re heavily rewriting this whole area.

Add an `Instructions.sources_of_type` method

---

lib/source.rb
lib/source/area.rb
lib/source/corrections.rb
lib/source/csv.rb
lib/source/elections.rb
lib/source/gender.rb
lib/source/group.rb
lib/source/json.rb
lib/source/membership.rb
lib/source/ocd.rb
lib/source/person.rb
lib/source/plain_csv.rb
lib/source/positions.rb
lib/source/term.rb
lib/source/wikidata.rb

Rather than having all the different Source classes embedded in a single file, split it up into one file per class. This is largely preparation for starting to add a lot more behaviour onto the individual classes.

Split out separate Source class files

---

lib/remotesource.rb

https://github.com/everypolitician/everypolitician-data/pull/17645 changed how `Instructions` work, and didn't update the `RemoteSource` class to work with it (having tested only `rake clean` builds, rather than `rake clobber` ones)
Bring this back in line.
The class now has some odd redirections, but we can tidy that up later.

Make RemoteSource work with new Instructions file

---

lib/source.rb
lib/source/corrections.rb
lib/source/gender.rb
lib/source/membership.rb
lib/source/ocd.rb
lib/source/person.rb
rake_build/combine_sources.rb

`combine_sources` steps through lots of sources building up the datastructure that will become `merged.csv`.
Rather than having the logic for how to combine each source in the Rakefile, pull it out into the Source classes.
We still need to handle legacy IDs, and then work out how to reduce the duplication (each section is almost identical), and we also need to do more work on refactoring the code that has been extracted, but this a major step forward, and reduces the flog score of `combine_sources` from 408.4 to 175.2

Move "combine this source" logic into Source classes

---

.travis.yml
scripts/deploy.sh

This changes the way we're attempting to deploy everypolitician.org on Travis to use an `after_success` hook, rather than using [Travis' script deployment](https://docs.travis-ci.com/user/deployment/script/).
The script based deployment doesn't seem to work because it runs in an odd environment that has a very old version of ruby and git. This was causing errors saying [`fatal: repository 'https://github.com/everypolitician/close_old_pull_requests/' not found`](https://travis-ci.org/everypolitician/everypolitician-data/builds/163344759#L325), which is odd because that repository very much _does_ exist.
This follows on from other attempts to deploy everypolitician.org as part of this repo's Travis build - #17407 and #17487.
Fixes https://github.com/everypolitician/everypolitician/issues/511 …

Switch to deploying everypolitician.org in after_success hook

---

scripts/deploy.sh

Travis sets a BUNDLE_GEMFILE environment variable pointing to the
`Gemfile` of the application that's being built, everypolitician-data in
this case. However we want to install viewer-sinatra so that we can
deploy everypolitician.org, so we need to unset BUNDLE_GEMFILE so that
`bundle install` picks up the correct `Gemfile` for viewer-sinatra.
This follows on from https://github.com/everypolitician/everypolitician-data/pull/17836
Fixes https://github.com/everypolitician/everypolitician/issues/511 🙏

Unset BUNDLE_GEMFILE before trying to install viewer-sinatra

---

lib/source/membership.rb
lib/uuid_map.rb

It's useful to be able to access the ID map information for a Membership
source in other contexts (e.g. from Rakefiles), so promote it from
private to public.

Make Source::Membershis#id_mapper public

---

countries.json
data/Kenya/Assembly/ep-popolo-v1.0.json
data/Uganda/Parliament/ep-popolo-v1.0.json
rake_build/generate_ep_popolo.rb

When we assign the legislature's UUID, we update all the Memberships to
point at the correct organization_id, but we had previously forgotten to
also do this for Posts. So also update it there as well.
Closes https://github.com/everypolitician/everypolitician-data/issues/18412

Use legislature UUIDs in Posts

---

countries.json

This does a full refresh of `countries.json` to catch a few countries where things had slipped a bit out of sync. Specifically this fixes Malaysia, which is currently pointing to a SHA that doesn't exist on `master`.
This uses the code from https://github.com/everypolitician/everypolitician-data/pull/18449 to perform the full rebuild.

Refresh countries.json for all countries

---

Rakefile.rb
lib/task/rebuild_countries_json.rb

Move the logic for the 'countries.json' task out of the Rakefile into a
Task class.
Then use this to fixes the bug that was preventing all countries being rebuilt when there is no EP_COUNTRY_REFRESH environment variable set. (https://github.com/everypolitician/everypolitician-data/pull/18449)

Add Task class for rebuilding countries.json

---

countries.json
data/Brunei/Legislative_Council/ep-popolo-v1.0.json
data/Brunei/Legislative_Council/meta.json

The meta file for the legislature included the ISO code for the country.
This is meant to live in the meta file one directory up instead (as it
already does).
Fixes https://github.com/everypolitician/everypolitician/issues/524

Brunei: remove ISO code from legislature

---

rake_build/generate_ep_popolo.rb

We will probably want to expose the more detailed information later, but
for now we want to expose this in a simple and consistent way for people
using the data. https://github.com/everypolitician/everypolitician/issues/525
This should fix the New Zealand and Poland builds, which are both currently failing because `transgender female` wasn't mapped to anything.

Map 'transgender female' to 'female' in Popolo

---

lib/source/area.rb
lib/source/elections.rb
lib/source/group.rb
rake_build/generate_ep_popolo.rb

As part of the ongoing process of moving logic out of the Rakefiles into
the Source classes, teach some of those classes how to return Popolo that the
Rakefile can then merge together with that from the other sources.
The logic for combining them is quite similar, and can be teased out
further in a later change.

Refactor build: move logic from Rakefile to Source classes

---

.travis.yml
Gemfile
Gemfile.lock
Rakefile.rb

Adds the bundle audit gem to the Gemfile
For security reasons snce we want to switch to using https to link to gems that live in GitHub, as described in http://bundler.io/git.html#security
Part of https://github.com/everypolitician/everypolitician/issues/518
* There was no rake task for bundle:audit so I added the gem
* The rake file and Travis where updated to use bundle audit 
* I made [another PR](https://github.com/everypolitician/everypolitician-data/pull/18542) to test that it works, where I change the git urls in the Gemfile. After that I ran `bundle exec rake bundle:audit` against that PR and got:
```bash
:) be rake bundle:audit
Updating ruby-advisory-db ...
De https://github.com/rubysec/ruby-advisory-db
* branch            master     -> FETCH_HEAD
Already up-to-date.
Updated …
```

Add bundle audit

---

.travis.yml
Gemfile
Gemfile.lock
Rakefile.rb

Reverts everypolitician/everypolitician-data#18496
The rebuilder log is full of errors:
```
2016-10-16T07:21:38.995840+00:00 app[worker.1]: rake aborted!
2016-10-16T07:21:38.995870+00:00 app[worker.1]: LoadError: cannot load such file -- bundler/audit/task
2016-10-16T07:21:38.996016+00:00 app[worker.1]: /tmp/d20161016-3-1twjob0/Rakefile.rb:53:in `require'
2016-10-16T07:21:38.996017+00:00 app[worker.1]: /tmp/d20161016-3-1twjob0/Rakefile.rb:53:in `<top (required)>'
2016-10-16T07:21:38.996021+00:00 app[worker.1]: /tmp/d20161016-3-1twjob0/vendor/bundle/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
2016-10-16T07:21:38.996023+00:00 app[worker.1]: (See full trace by running task with --trace)
```
and the `countries.json` file isn't being added to any PR

Revert "Add bundle audit"

---

countries.json
data/Guernsey/States/ep-popolo-v1.0.json
data/Guernsey/States/names.csv
data/Guernsey/States/sources/manual/data-2012.csv
data/Guernsey/States/term-2012.csv
data/Guernsey/States/unstable/positions.csv

In preparation of adding term 2016 data -- where the names are formatted:
'first_name last_name' order -- this PR swaps the ordering of the 2012
term names.
This is a step towards fixing: https://github.com/everypolitician/everypolitician-data/issues/18489

Guernsey: Swap name order

---

lib/position/position_file.rb

When working with the Position file, don't keep reloading the JSON every time we're asking for the Positions for a given Person. The build calls this potentially thousands of time in sequence, for each person with Wikidata.
Removing this speeds up this section of the build for Sweden (for example) from over 15 seconds to 0.037s, or for Turkey from 139 seconds to 0.16s.

Memoize the Position File JSON

---

rake_build/fetch_sources.rb

This was broken when we switched to using a `Pathname` as we need to
call `#to_s` first, otherwise we get an error because there is no
`Pathname#include?` method.
Fixes https://github.com/everypolitician/everypolitician/issues/527

Fix REBUILD_SOURCE option

---

.rubocop_base.yml

Most of our tests are written "spec-style" and therefore have lots of long do...end blocks, this causes the block-length cop to complain, so disable that block for the tests.
Note that this includes `spec`, `t` and `test` because this base config is shared between all the EveryPolitician repos.
This will prevent failures like [this one](https://travis-ci.org/everypolitician/close_old_pull_requests/builds/169286902).

Rubocop: Ignore long blocks in tests

---

countries.json
data/Lithuania/Seimas/ep-popolo-v1.0.json
data/Lithuania/Seimas/sources/manual/position-filter.json
data/Lithuania/Seimas/sources/wikidata/elections.json
data/Lithuania/Seimas/sources/wikidata/groups.json
data/Lithuania/Seimas/sources/wikidata/positions.json

```
⤈ No ORDER BY for sources/morph/data.csv
* 1 of 151 unmatched
{:id=>"Q12672459", :name=>"Saulius Jakimavičius"}
150 x wikidata
31 x viaf
29 x freebase
17 x lcauth
9 x gnd
Unknown position (x1): Q3273722 health minister — e.g. Q3660989
Persons matched to Wikidata: 150 ✓ 
Parties matched to Wikidata: 7 ✓ | 1 ✘
No wikidata: Mišri Seimo narių grupė (party/mišri_seimo_narių_grupė)
```

Lithuania (Seimas): refresh data

---

countries.json
data/Romania/Deputies/ep-popolo-v1.0.json
data/Romania/Deputies/sources/wikidata/groups.json

```
☁ Mismatch in birth_date for b0623653-8fdd-4faf-b50d-48063a59e283 (1967-09-28) vs 1969-09-28 (for Q12720255)
☁ Mismatch in birth_date for 473969c1-bfaa-412b-a478-2ffb365bda42 (1952-10-01) vs 1952-01-01 (for Q12729178)
☁ Mismatch in birth_date for 4bd74999-948d-4e21-8200-8cd0139a51ee (1953-07-06) vs 1953-06-07 (for Q12731213)
☁ Mismatch in birth_date for eda51a85-68ef-4bdb-905c-f1ff2dcfc1ea (1981-06-27) vs 1981-06-17 (for Q15967888)
☁ Mismatch in birth_date for fc253b36-486e-4e26-b829-6fed61b676a6 (1975-11-24) vs 1975-11-04 (for Q18541857)
☁ Mismatch in birth_date for e4d212ee-d084-445e-80c6-39f6d0b926d1 (1948-07-27) vs 1949-07-27 (for Q18549572) …
```

Romania (Deputies): refresh data

---

lib/task/rebuild_countries_json.rb
test/selective_countries_json_refresh_test.rb

Previously you'd get no error if you mispell a country in
EP_COUNTRY_REFRESH; that makes it easy to assume that countries.json
rebuilt with no changes, when in fact nothing has been rebuilt at all.
This commit makes sure that an error is thrown f EP_COUNTRY_REFRESH
is specified, but doesn't correspond to any country.

Error if the EP_COUNTRY_REFRESH value doesn't match a country

---

lib/source/membership.rb

Previously we haven't needed to merge Membership sources with the same ID, as those will almost always be coming from the same upstream source, and will therefore be in the same Morph database, and can be fetched together as a single 'source'.
Sometimes, however, we will have archived off a previous term to a manual source file, and will want to merge this with a new source file for the latest term from the same upstream source, with shared IDs.
In such a case — i.e. where we have an `instructions.json` stanza for a second Membership source, and no `merge` details, we can simply re-use any ID → UUID mapping we already know of for any of the people in this source.
There are no direct tests for this functionality, but it's easy to test the behaviour exhaustively by running a build of all …

Allow Merging of Membership sources with same IDs

---

countries.json
data/Hong_Kong/Legislative_Council/ep-popolo-v1.0.json
data/Hong_Kong/Legislative_Council/sources/manual/terms.csv

@tmtmtmtm pointed out that the header row in the manual terms.csv source
was missing `end_date`, and so the end_date of the term wasn't being picked
up. This pull request should fix that.

Hong Kong: fix the missing end_date for term 5

---

Gemfile
Gemfile.lock
rake_build/validate_raw_sources.rb
rakefile_common.rb

Use the ODI csv linter to make sure that our source CSVs (particularly the ones  we generate ourselves, such as terms files, reconciliation files etc, are well  formed before attempting a build.
This can be run manually from within a legislature sub-directory with `rake csvlint:validate`, but it is also set to be a default rake task, and thus will happen automatically in-between the `clean` or `clobber` and the start of the generation process in our normal approach.
Closes https://github.com/everypolitician/everypolitician/issues/534
1. This gem unfortunately requires us to up our minimally-supported ruby version. If there's a way to conditionally run these checks only if a suitable ruby version is installed, I'd be quite tempted to do that instead, but it seems to be a non-trivial amount …

Check source CSVs for well-formedness

---

Gemfile

The rebuilder skips all gems that are in the `:test` group (https://github.com/everypolitician/rebuilder/blob/4a3562aa106404c00b2e7bfb707bb4e4d79b364d/app.rb#L54), so attempting to run the csv linting task fails.
In theory we shouldn't _need_ to run that task at the point of the actual build, but the extra check is useful, so move this to production setting rather than test.

Move csvlint from test to production

---

countries.json
data/Guatemala/Congress/ep-popolo-v1.0.json
data/Guatemala/Congress/unstable/stats.json
lib/source/elections.rb

We currently use Wikidata IDs as our own primary IDs, but for consistency
(and so that users of the everypolitician-popolo gem can access it with the
.wikidata method) we should really expose them as identifiers too.

Add wikidata identifiers to elections

---

data/Guatemala/Congress/unstable/stats.json
lib/legislature_stats.rb

The new version of `everypolitician-popolo` now returns an `Events` collection rather than list of `Event` obejcts, so we can't call `.last` on `terms` here. But we do have a `latest_term` method we can use instead, and can simplify the other similar code.
Fixes https://github.com/everypolitician/everypolitician/issues/537

Use new everypolitician-popolo methods for stats

---

countries.json
data/Slovakia/National_Council/ep-popolo-v1.0.json
data/Slovakia/National_Council/sources/instructions.json
data/Slovakia/National_Council/sources/manual/terms.csv

Term information was being sourced from http://api.parldata.eu
We're moving the terms to a manual file, since this source
is no longer being maintained.
This is a step towards adding a new term.

Slovakia: Move terms file to manual

---

data/Laos/Assembly/sources/instructions.json
data/Laos/Assembly/sources/morph/data.csv

This PR prepares for the addition of the 2016 term.
Memberships do not have upstream IDs and matching by name is precarious as spellings differ between terms.
The plan is to import terms to separate files and reconcile new members with existing members using the reconciliation interface.
This PR makes the first step of changing the existing membership import instruction to import term 2011 (the existing term) specifically.

Laos Assembly -- change 2011 term import instruction

---

rake_build/generate_ep_popolo.rb

If we have a group with no ID, the later group_wikidata task will blow
up noisily, with an error that doesn’t really say what’s going on.
Explicitly checking for this earlier lets us isolate the issue better
and give a better error message.

Check for missing Group IDs

---

countries.json
data/Nigeria/Assembly/ep-popolo-v1.0.json
data/Nigeria/Assembly/sources/wikidata/elections.json

Rebuild all sources other than nigeria-national-assembly (which is a difficult import)
```
Persons matched to Wikidata: 0 ✓ | 362 ✘
Parties matched to Wikidata: 2 ✓ | 4 ✘
No wikidata: All Progressives Grand Alliance (APGA)
No wikidata: Labour Party (LP)
No wikidata: ACCORD (A)
No wikidata: Social Democratic Party (SDP)
```

Nigeria (Assembly): rebuild data

---

countries.json
data/Guernsey/States/ep-popolo-v1.0.json
data/Guernsey/States/sources/manual/data-2012.csv
data/Guernsey/States/term-2012.csv

In the 2012 term, Alderney representatives currently have their area listed as 'Alderney Representative'.
The area should be 'Alderney'. Term 2016 is scraping this area as 'Alderney'.
Closes: https://github.com/everypolitician/everypolitician-data/issues/20460

Guernsey States: Rename area from 'Alderney Representative' to 'Alderney'

---

countries.json
data/Jersey/States/ep-popolo-v1.0.json
data/Jersey/States/sources/instructions.json
lib/source/membership.rb

In https://github.com/everypolitician/everypolitician-data/pull/19223 we introduced the ability to treat the incoming IDs from multiple sources as being for the same person.
However, this isn’t always going to be true, and we don’t always want to have to add a `merge` section when it’s not (especially for a manual file with a single member, where the reconciliation file would be empty)
So, allow a 'reuse_ids' instruction that if set to 'false', will fall back on the old behaviour of assuming that the IDs are to map to different UUIDs.
Show this in action with Jersey (Tunisia and New Caledonia both also require it, but can be done in separate PRs)

Don’t always assume same IDs

---

countries.json
data/Canada/Commons/ep-popolo-v1.0.json
lib/source/elections.rb

Some elections have a start_date and end_date defined (which are usually
precise dates), plus a "point in time" date, which is sometimes only a
year.
See, for example,
https://www.wikidata.org/w/index.php?title=Q2075093&oldid=402960350
In those cases, prefer the start/end-dates, otherwise fallback on the 'point in time' dates.

Prefer election start/end dates if provided

---

.travis.yml

This will post a message to our Slack's #travis channel whenever a build on Travis completes. This should help us spot any errors that occur on the `master` branch when deploying everypolitician.org.

Add Slack notifications for Travis builds

---

countries.json
data/Slovakia/National_Council/ep-popolo-v1.0.json
data/Slovakia/National_Council/sources/instructions.json

There was an unwanted `'` character at the beginning of the source url in the Slovakia `instructions.json` which was causing an invalid link in the viewer-sinatra HTML, which in turn prevented http://everypolitician.org/ from being deployed correctly. This invalid url was originally introduced in https://github.com/everypolitician/everypolitician-data/pull/19629.
This change just fixes the source url, I'll open a separate pull request to make some changes to ensure we catch this in the future.

Slovakia (National Assembly): Fix source url

---

countries.json
data/Jordan/House_of_Representatives/ep-popolo-v1.0.json
data/Jordan/House_of_Representatives/sources/instructions.json

The scraper source had been given as: https://en.wikipedia.org/wiki/Constituencies_of_Jamaica
This, of course, is incorrect. I've replaced it with the source URL from the scraper.

Jordan, House of Representatives: Correct morph source URL

---

lib/uuid_map.rb
test/uuid_map_test.rb

Occasionally the test for rewriting a UUID map would fail, saying there
are zero entries in the file rather than two.
This is very hard to replicate, so difficult to investigate, but we
suspect that it might be because nothing is holding a reference to the
Tempfile itself, and so sometimes the garbage collection kicks in and
deletes it before we get around to reading from it again.
Setting this up in a `let` block instead should keep it around long
enough to not disappear (if this _is_ the problem), and with no
ill-effects even if it's not.

Hopefully fix intermittent UUID map error

---

test/uuid_map_test.rb

This is a hard to debug failure, but I think this test is occasionally
failing because we're not holding onto the reference to the tempfile
that we're using, so it's getting garbage collected before we can read
from it.
This should fix errors like https://travis-ci.org/everypolitician/everypolitician-data/builds/177861445.
This follows on from https://github.com/everypolitician/everypolitician-data/pull/20899

Hopefully fix intermittent UUID test error

---

countries.json
data/Spain/Congress/ep-popolo-v1.0.json
data/Spain/Congress/sources/manual/terms.csv

This PR updates the terms file to:
1) Update it to the new format described in <https://github.com/everypolitician/everypolitician/wiki/terms.csv>
2) Add the ending date of the previous term and the starting date of the new term according to [the IPU site](http://www.ipu.org/parline-e/reports/2293_E.htm).

Spain add term 12 to manual/terms.csv file

---

lib/reconciliation/fuzzer.rb
lib/task/rebuild_countries_json.rb

Kill off these warnings:
```
/home/travis/build/everypolitician/everypolitician-data/lib/reconciliation/fuzzer.rb:29: warning: method redefined; discarding old fuzzer
/home/travis/build/everypolitician/everypolitician-data/lib/task/rebuild_countries_json.rb:64: warning: shadowing outer local variable - c
```

Silence a few test warnings

---

countries.json
data/Mongolia/Assembly/ep-popolo-v1.0.json

Rebuild with new 'source' credits
```
* 1 of 72 unmatched
{:id=>"212", :name=>"SARANGEREL Davaajantsan"}
* 14 of 47 unmatched
{:id=>"Q24174848", :name=>"Догсомын Батцогт"}
{:id=>"Q24174856", :name=>"Раднаасүмбэрэлийн Гончигдорж"}
{:id=>"Q24174855", :name=>"Агипарын Бакей"}
{:id=>"Q23771599", :name=>"Nyamaagiin Enkhbold"}
{:id=>"Q276238", :name=>"Санжаасүрэнгийн Оюун"}
{:id=>"Q24174854", :name=>"Данзангийн Лүндээжанцан"}
{:id=>"Q24174857", :name=>"Мигэддоржийн Батчимэг"}
{:id=>"Q25848773", :name=>"Жаргалтулгын Эрдэнэбат"}
{:id=>"Q24174849", :name=>"Лувсанцэрэнгийн Энх-Амгалан"}
{:id=>"Q7849825", :name=>"Tsogtyn Batbayar"}
Adding …
```

Mongolia (Assembly): rebuild data

---

lib/wikidata_lookup.rb

This is a workaround for Yajl not correctly encoding objects that
contain strings that contain double quotes. I'm not entirely sure what
it is in Yajl that is causing this, I _think_ it's because they redefine
the `to_json` method in the `json_gem` file, but I haven't dug into it
any deeper than that.
You can find a simple script for reproducing this problem here - https://gist.github.com/chrismytton/3d4166069556a4e44e76306e7904f4f1.
This fixes the Ukraine error, which means that can now be built again without errors.

Fix Yajl double quote encoding error

---

data/Estonia/Riigikogu/sources/instructions.json
data/Gambia/National_Assembly/sources/instructions.json
data/Honduras/Congreso_Nacional/sources/instructions.json
data/Jordan/House_of_Representatives/sources/instructions.json
data/Kuwait/National_Assembly/sources/instructions.json
data/Lebanon/Parliament/sources/instructions.json
data/Malaysia/Dewan_Rakyat/sources/instructions.json
data/Saint_Helena/Legislative_Council/sources/instructions.json
data/Saint_Kitts_and_Nevis/Assembly/sources/instructions.json
data/Samoa/Parliament/sources/instructions.json
data/Suriname/Assembly/sources/instructions.json
data/Thailand/National_Legislative_Assembly/sources/instructions.json
data/Turks_and_Caicos_Islands/Assembly/sources/instructions.json
data/UK/Commons/sources/instructions.json
data/US_Virgin_Islands/Legislature/sources/instructions.json
data/Wallis_and_Futuna/Territorial_Assembly/sources/instructions.json

The code currently infers one if it's not provided, but we want to get rid of that, and require an explicit block everywhere.
Closes https://github.com/everypolitician/everypolitician/issues/541

Ensure every legislature has a 'terms' instruction

---

rake_build/generate_final_csvs.rb

Rather than having the process for generating the HTML interface for selecting what "type" each P39 position is (cabinet, other legislature, etc) controlled by having an environment variable set at build time, have a separate rake task for generating it.

Extract generate_position_interface rake task

---

.rubocop_base.yml

In the rubocop configuration we inhert from in pretty much every other
repo, set the default max LineLength to 120 characters. Individual repos
can still increase, or decrease, this at will, but this will give them a
little more latitude to start with.

Increase our default allowable LineLength to 120

---

data/Belgium/Representatives/sources/instructions.json
data/Belgium/Representatives/unstable/stats.json

There isn't actually any source data coming in at the minute, but I've
reinstated that on the scraper too, so it should flow through once Morph
returns to action.
```
Merging with sources/morph/data.csv
⚥ data for 121; 0 added
169 x wikidata
38 x freebase
28 x viaf
24 x belgian_senate
19 x flemish_parliament
Unknown position (x1): Q21401179 municipal councillor — e.g. Q1663490
Unknown position (x1): Q30185 mayor — e.g. Q2305667
Unknown position (x1): Q877955 deputy prime minister — e.g. Q1534851 …
```

Belgium (Representatives): reinstate source field

---

data/Slovenia/National_Assembly/sources/instructions.json

This was still pointing at the version in @chrismytton's own account
(Chris: you should also now delete https://morph.io/chrismytton/slovenia-national-assembly-wikidata)

Slovenia (National Assembly): switch Morph source to EP-scrapers

---

data/Falkland_Islands/Assembly/unstable/stats.json
data/Germany/Bundestag/unstable/stats.json
data/Lebanon/Parliament/unstable/stats.json
data/Netherlands/House_of_Representatives/unstable/stats.json
data/Somaliland/Representatives/unstable/stats.json
data/South_Sudan/Assembly/unstable/stats.json
data/Timor_Leste/Parlamento/unstable/stats.json
data/Yemen/Majlis/unstable/stats.json

The stats file skips elections that are in a year greater than the
current one. As we've now rolled over into 2017, elections that are
scheduled for this year are no longer ignored.

Update stats files for 2017 elections

---

lib/source.rb
lib/source/positions.rb

This is the old, deprecated, way where we build all the P39 information
using Wikisnakker at build time. This is very slow, and is being
migrated to being build in morph scrapers.
Renaming this file makes it more obvious that this is the old way, and
frees up the namespace for the new approach.

rename 'Source::Positions' to '::Old'

---

data/Estonia/Riigikogu/sources/manual/position-filter.csv
lib/position/map.rb
lib/source/cabinet.rb
rake_build/generate_final_csvs.rb
rakefile_common.rb

Simplify the position filter file from the old JSON-based version to a
simpler CSV-based one, and add a rake task to migrate from one to the
other.

Migrate the JSON position filter to CSV

---

rake_config/vanishing_data.rb

Since 03e6acd3 the `sources` method no longer exists, and we need to get this data directly from `@SOURCES`

Fix vanishing_sources helper

---

data/Canada/Commons/unstable/stats.json
data/Estonia/Riigikogu/unstable/stats.json
data/Ireland/Dail/unstable/stats.json
lib/legislature_stats.rb
rake_build/generate_stats.rb

Change the stats reporting to list the number of known Cabinet memberships
not just roles — i.e. so that it goes up when we know a new person becoming
Minister of Defence, not just when we add a new position.

Report on Cabinet memberships not posts

---

countries.json
data/Syria/Majlis/ep-popolo-v1.0.json
data/Syria/Majlis/sources/manual/terms.csv
data/Syria/Majlis/unstable/stats.json

This is a step towards adding the 2016 term.
The end date of the 2012 term has been recorded as the day before the 2016 election.
The start date of the 2016 term has been recorded as the date of the first session of parliament.
Source: http://www.ipu.org/parline-e/reports/2307_E.htm

Syria Majlis -- add term dates

---

countries.json
data/Belarus/Chamber/ep-popolo-v1.0.json
data/Belarus/Chamber/sources/manual/terms.csv
data/Belarus/Chamber/unstable/stats.json

This is a step towards importing data for the new term.
Records end of 2012 term as the day before 2016 election.
Start of 2016 term recorded as the day of the 2016 election.
Source: http://www.ipu.org/parline-e/reports/2027_E.htm

Belarus House of Representatives -- add term dates

---

rake_config/vanishing_data.rb

If a column has no ID column, we want to blow up, rather than silently
claiming there are no changes.
It would be nice if we could specify an alternative column to group by,
but that can be a later addition.

Error if no ID column in 'vanishing_data' source

---

.rubocop_base.yml

Rubocop recently introduced a 'Metrics/BlockLength' cop, which is
similar to the `MethodLength` one, though interestingly its default is
25 lines, rather than the default 10 for methods. This is particularly
bad for us in scrapers (which inherit from this config), where `field`
should essentially be treated as a method, but is really a block.
So set the default BlockLength to 10 as well.
The other place this will force us to get better is in `rake` tasks, but
that's also a Good Thing.

Set default Max BlockLength to 10

---

countries.json
data/Lithuania/Seimas/ep-popolo-v1.0.json
data/Lithuania/Seimas/sources/manual/terms.csv
data/Lithuania/Seimas/unstable/stats.json

Generated from `generate_terms_from_wikidata.rb Q27749062`
```
* 1 of 151 unmatched
{:id=>"Q12672459", :name=>"Saulius Jakimavičius"}
150 x wikidata
32 x viaf
29 x freebase
17 x lcauth
9 x gnd
Persons matched to Wikidata: 150 ✓ 
Parties matched to Wikidata: 7 ✓ | 1 ✘
No wikidata: Mišri Seimo narių grupė (party/mišri_seimo_narių_grupė)
```

Lithuania (Seimas): add new term data

---

data/Alderney/States/sources/manual/terms.csv

The legislature has an 'ordinary' election every two years where five
of the standing legislature stand for re-election. There are no formal
terms therefore this term represents a 'virtual' term.
Previously, the term start dates had been recorded as the date of the 2016 election. The end date had been given as the month of the next election.
Now, the start date is recorded as the start date of members elected in 2014
(http://www.alderney.gov.gg/article/4386/Steve-Roberts).
The end date is recorded as the 31st December 2016 (End date of 2014
elected members is 31st December 2008
(http://www.alderney.gov.gg/article/4389/Matthew-Birmingham) -- and
2016 elected members is 31st Decemeber 2020
(http://www.alderney.gov.gg/article/157566/Mike-Dean)).
This is a step towards importing adding the …

Alderney States -- Change term dates

---

rake_report/missing_wikidata.rb

Add a rake task (rake report:missing_wikidata) to tell us which members
of the latest term aren't yet matched to Wikidata.
This will make it easier to ensure that at least the current information
is as well matched as possible.

Add rake report on missing Wikidata members

---

.rubocop_base.yml

The rubocop config in this repo is used in other projects.
Gemspec files can contain lengthy blocks. For example:
https://github.com/everypolitician/scraped/blob/master/scraped.gemspec
Blocks of such length would not pass rubocop tests.

Instruct rubocop to ignore gemspec files

---

rake_build/generate_final_csvs.rb

Similarly to how we report on People and Parties matched to Wikidata, also report on Areas.
This will let us see which areas still need mapped, and also which countries we still haven't mapped at all.

Report on Areas matched to Wikidata

---

countries.json
data/Ireland/Dail/ep-popolo-v1.0.json
data/Ireland/Dail/sources/reconciliation/areas.csv
data/Ireland/Dail/unstable/stats.json

This was previously mis-assigned to the ID for Dublin Bay North
```
Add memberships from sources/morph/kildare31.csv
Add memberships from sources/morph/kildare32.csv
Merging with sources/morph/twitter-donie.csv
* 7 of 233 unmatched
{:id=>"Q3778169", :name=>"Luke 'Ming' Flanagan"}
{:id=>"Q13653269", :name=>"Nicky McFadden"}
{:id=>"Q912430", :name=>"Brian Lenihan, Jnr"}
{:id=>"Q7147356", :name=>"Patrick Nulty"}
{:id=>"Q983508", :name=>"Phil Hogan"}
{:id=>"Q1499408", :name=>"Shane McEntee"}
{:id=>"Q4963985", :name=>"Brian Hayes"}
⚥ data for 264; 0 added
226 x wikidata
108 x freebase
39 x viaf
7 x lcauth
7 x sudoc
☇ No dates for …
```

Ireland (Dail): correct reconciliation for Dublin Bay South

---

rake_build/generate_ep_popolo.rb

If a membership record has no term data, or a term ID that has no
equivalent in `events`, don't just blow up, but say which data is
exhibiting the problem.
Fixes https://github.com/everypolitician/everypolitician/issues/568

Give better error on unknown term in membership

---

countries.json
data/Slovenia/National_Assembly/ep-popolo-v1.0.json
data/Slovenia/National_Assembly/sources/manual/terms.csv
data/Slovenia/National_Assembly/unstable/stats.json

I used quickstatements to connect up all 7 terms, including links to the lists of members.
```
Add memberships from sources/manual/memberships.csv
Add memberships from sources/archive/official-ceased.csv
* 12 of 46 unmatched
{:id=>"Q12789041", :name=>"Franc Breznik"}
{:id=>"Q27929326", :name=>"Matjaž Nemec"}
{:id=>"Q17117413", :name=>"Miro Cerar"}
{:id=>"Q12793070", :name=>"Julijana Bizjak Mlakar"}
{:id=>"Q18627734", :name=>"Margareta Guček Zakošek"}
{:id=>"Q23418897", :name=>"Andreja Katič"}
{:id=>"Q27651990", :name=>"Bojan Dobovšek"}
{:id=>"Q58079", :name=>"Karl Erjavec"}
{:id=>"Q19932345", :name=>"7. državni zbor Republike Slovenije"}
{:id=>"Q12787433", :name=>"Dejan Židan"}
Merging with …
```

Slovenia (National Assembly): add Wikidata for term

---

bin/dashboard.rb

Add the number of Areas we know about and how many of those are mapped
to Wikidata. Later we might want to make this explicitly about
constituencies, but for now there's no difference.

Add Area count to the dashboard

---

Gemfile
Gemfile.lock

Nokogiri isn't being used anywhere in this repo, so remove it to help speed up the `bundle install` step of the rebuilder.
Part of https://github.com/everypolitician/everypolitician/issues/585
Related to https://github.com/everypolitician/rebuilder/issues/60

Remove unused nokogiri dependency

---

countries.json
data/Sint_Maarten/Estates/ep-popolo-v1.0.json
data/Sint_Maarten/Estates/names.csv
data/Sint_Maarten/Estates/sources/archive/official_term2.csv
data/Sint_Maarten/Estates/term-2.csv

This is a step towards adding the new term. Part of: https://github.com/everypolitician/everypolitician-data/issues/25778
The scraper has been updated to pull in members of the most recent term with member names and prefixes separated. 
A member of the most recent term exists in the archived data with their honorific prefix attached to their name. In preparation of adding the new term, this PR moves the member's title to an honorific_prefix field.
~~~
Add memberships from sources/archive/official_term2.csv
Persons matched to Wikidata: 0 ✓ | 17 ✘
Areas matched to Wikidata: 0 ✓ 
~~~

Sint maarten estates add honorific prefix column to term 2

---

countries.json
data/Australia/Senate/sources/instructions.json
data/Australia/Senate/sources/morph/contacts.csv

Australia (Senate): remove Membership fields from Person source

---

countries.json
data/Belgium/Representatives/sources/instructions.json
data/Belgium/Representatives/sources/morph/official.csv

Belgium (Representatives): remove Membership fields from Person source

---

data/Falkland_Islands/Assembly/sources/instructions.json
data/Falkland_Islands/Assembly/sources/morph/official.csv

Falkland Islands (Assembly): remove Membership fields from Person source

---

data/Solomon_Islands/Parliament/sources/instructions.json
data/Solomon_Islands/Parliament/sources/morph/gov.csv

Solomon Islands (Parliament): rebuild data

---

data/Wallis_and_Futuna/Territorial_Assembly/sources/instructions.json
data/Wallis_and_Futuna/Territorial_Assembly/sources/morph/official.csv

Wallis and Futuna (Territorial Assembly): remove Membership fields from Person source

---

data/Saint_Kitts_and_Nevis/Assembly/sources/instructions.json
data/Saint_Kitts_and_Nevis/Assembly/sources/morph/wikipedia.csv

Saint Kitts and Nevis (Assembly): remove Membership fields from Person source

---

countries.json
data/Turks_and_Caicos_Islands/Assembly/sources/instructions.json
data/Turks_and_Caicos_Islands/Assembly/sources/morph/wikipedia.csv

The wikipedia source contains data for both the 2012 and 2016 terms. This PR prepares for a forthcoming PR in which I will change the wikipedia source type from person to membership (WIP: https://github.com/everypolitician/everypolitician-data/pull/26967).
I am limiting the incoming data to term 2012 otherwise, in the forthcoming PR, the Wikidata upstream source will add membership data for term 2016 too -- which I don't want as the legislature is not yet ready for the new term.
Part of: https://github.com/everypolitician/everypolitician-data/issues/25274
```
Add memberships from sources/archive/official-2012-appointed-members.csv
Add memberships from sources/archive/official-2012-elected-members.csv
Merging with sources/morph/wikipedia.csv
* 1 of 15 unmatched …
```

Turks and Caicos (assembly) import only term 2012 from wikipedia

---

countries.json
data/Moldova/Parlamentul/ep-popolo-v1.0.json
data/Moldova/Parlamentul/sources/manual/terms.csv
data/Moldova/Parlamentul/unstable/stats.json

```
Add memberships from sources/manual/gone.csv
* 14 of 107 unmatched
{:id=>"Q5609021", :name=>"Grigore Belostecinic"}
{:id=>"Q6968023", :name=>"Natalia Gherman"}
{:id=>"Q21746906", :name=>"Veronica Herța"}
{:id=>"Q20431851", :name=>"Oleg Balan"}
{:id=>"Q7155601", :name=>"Pavel Filip"}
{:id=>"Q1110215", :name=>"Dorin Chirtoacă"}
{:id=>"Q12731069", :name=>"Irina Vlah"}
{:id=>"Q15071201", :name=>"Monica Babuc"}
{:id=>"Q13428691", :name=>"Vasile Botnari"}
{:id=>"Q15071069", :name=>"Maia Sandu"}
93 x wikidata
15 x …
```

Moldova (Parlamentul): connect Term to Wikidata

---

data/Northern_Ireland/Assembly/sources/manual/terms.csv

Northern Ireland: Fix start date of 6th term

---

countries.json
data/Puerto_Rico/House_of_Representatives/ep-popolo-v1.0.json
data/Puerto_Rico/House_of_Representatives/sources/manual/terms.csv

The terms were overlapping in a bad way, so I've fixed up the data in
Wikidata, and then rebuilt this using using
`generate_terms_from_wikidata.rb Q28152279`
Part of https://github.com/everypolitician/everypolitician/issues/594
```
Add memberships from sources/morph/official29.csv
Add memberships from sources/morph/official30.csv
56 x wikidata
1 x fec
1 x freebase
1 x opensecrets
1 x uscongress
Persons matched to Wikidata: 56 ✓ | 18 ✘
No wikidata: Guillermo Miranda Rivera (85759a70-565c-416a-87c0-7b32bbbf188e)
No wikidata: Eddie Charbonier Chinea (29702730-fe12-4853-af21-53a536db2d94)
No wikidata: Félix G. Lassalle Toro …
```

Puerto Rico (House of Representatives): fix term dates

---

.travis.yml

There's a lot of noise in the Travis channel on Slack, and we almost
never want to know when a build succeeded — only when it fails. So turn
off success notifications.
See: https://docs.travis-ci.com/user/notifications/#Changing-notification-frequency

Travis: Don't send 'success' notifications to Slack

---

countries.json
data/Egypt/Parliament/ep-popolo-v1.0.json
data/Egypt/Parliament/sources/instructions.json

Fixes: https://github.com/everypolitician/everypolitician-data/issues/29058
The source for the data was recorded as `http://www.assemblee-nationale.tg`. This PR corrects it to: `http://www.parliament.gov.eg/`

Egypt Parliament correct data source

---

.travis.yml

The way travis expands 'secure' (https://docs.travis-ci.com/user/encryption-keys/#Detailed-Discussion) converts the hash to a plain string, and thus can’t be left dangling at the existing level of nesting, but instead needs a section it can live within. The "This is how a setup with encrypted credentials could look like" (sic) at https://docs.travis-ci.com/user/notifications/#Configuring-slack-notifications suggests putting it into 'rooms'.
Continues from https://github.com/everypolitician/everypolitician-data/pull/28717

Give the travis 'secure' token somewhere to live

---

countries.json
data/Lesotho/Assembly/ep-popolo-v1.0.json
data/Lesotho/Assembly/sources/instructions.json

The scraper pulls data from two separate sources.
The instruction was written when it was not possible to cite multiple sources. This PR adds the second source, now that it is possible to do so.
(This change is being made in advance of renaming the source file: https://github.com/everypolitician/everypolitician-data/pull/29050)

Lesotho Assembly: reference second source in import instruction

---

scripts/deploy.sh

There is little point in rebuilding the site unless `countries.json` has
changed since the last build (as otherwise we'll be building from the
same source files, and thus there shouldn't be any changes[1])
In theory that should mean that we only need to do the build & deploy if
we have a commit to `master`, and it includes `countries.json` (assuming
we're doing (rebase and merge, rather than merge-commits)
Checking TRAVIS_COMMIT_RANGE _should_ tell us this, though as this is a
little difficult to test other than by just doing it, we'll start by
simply outputting whether it contains `countries.json` or not, rather
than switching any of the logic yet to do anything based on that. Then
we can check travis logs to make sure it's doing the right thing before
starting to actually use it.
[1] …

Deploy: Report if countries.json has changed

---

.travis.yml

This repo only really cares about being > 2.3, but viewer-sinatra is
running 2.3.3, and we install that when we trigger `deploy.sh` from
travis. So we need to keep these in sync.

Run ruby 2.3.3 in travis

---

scripts/deploy.sh

We don't want to deploy everypolitician.org unless there has been a change to `countries.json`.
This uses the "TRAVIS_COMMIT_RANGE" environment variable to check if there has been a change to `countries.json` in the commit being built. If not then the deploy is skipped to avoid unnecessary spidering.
Follows on from https://github.com/everypolitician/everypolitician-data/pull/30681

Only deploy when countries.json changes

---

scripts/deploy.sh

Previously we were deploying when the _only_ file that changed was `countries.json`, but we also want to handle the case where `countries.json` and a bunch of other files all change at once.
I've changed this check to use the [`-z` operand](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html) to test for zero length output from the diff command, which indicates that `countries.json` wasn't changed.
Follows on from https://github.com/everypolitician/everypolitician-data/pull/30686#pullrequestreview-30237792

Always deploy when countries.json changes

---

data/Cabo_Verde/Assembly/ep-popolo-v1.0.json
data/Cabo_Verde/Assembly/sources/manual/terms.csv
data/Cabo_Verde/Assembly/unstable/stats.json

```
Add memberships from sources/morph/offical-8.csv
Add memberships from sources/morph/offical-9.csv
Add memberships from sources/manual/memberships.csv
⚥ data for 149; 149 added
Persons matched to Wikidata: 0 ✓ | 127 ✘
Parties matched to Wikidata: 3 ✓ | 1 ✘
No wikidata: unknown (party/_unknown)
Areas matched to Wikidata: 0 ✓ | 13 ✘
```

Cabo Verde (Assembly): map terms to Wikidata

---

data/Denmark/Folketing/sources/instructions.json

```
Add memberships from sources/archive/official-vanished.csv
Add memberships from sources/morph/wikipedia-historic.csv
* 21 of 588 unmatched
{:id=>"Q12301843", :name=>"Anne Marie Geisler Andersen"}
{:id=>"Q12331302", :name=>"Per Dalgaard Christiansen"}
{:id=>"Q5738260", :name=>"Alexander Foss"}
{:id=>"Q12331626", :name=>"Peter Laigaard"}
{:id=>"Q12331644", :name=>"Peter Madsen"}
{:id=>"Q18199370", :name=>"Helge Vagn Jacobsen"}
{:id=>"Q15944298", :name=>"Vibeke Grave"}
{:id=>"Q17610849", :name=>"Helle Løvgreen Mølvig"}
{:id=>"Q556712", :name=>"Aksel V. Johannesen"}
{:id=>"Q12316018", :name=>"Helge Dohrmann"}
* 4 of 254 …
```

Denmark (Folketing): move to EP-scrapers source

---

data/Estonia/Riigikogu/unstable/stats.json
lib/legislature_stats.rb

For now, only count the people within the current term; we can add the full
count later if required.

Add image count to legislature stats

---

data/Belarus/Chamber/ep-popolo-v1.0.json
data/Belarus/Chamber/meta.json

We had the ID for the whole National Assembly, rather than the lower house
```
Add memberships from sources/archive/official-term-5.csv
* 83 of 121 unmatched
{:id=>"Q26897738", :name=>"Уладзіслаў Станіслававіч Цыдзік"}
{:id=>"Q26897751", :name=>"Алена Іванаўна Астапюк"}
{:id=>"Q26897691", :name=>"Жанна Мікалаеўна Мішур"}
{:id=>"Q26897647", :name=>"Мікалай Анісімавіч Калтуноў"}
{:id=>"Q26897748", :name=>"Мікалай Мяфодзьевіч Язубец"}
{:id=>"Q26897642", :name=>"Сяргей Веніямінавіч Дудкін"}
{:id=>"Q26897724", :name=>"Міхаіл Фёдаравіч Савановіч"}
{:id=>"Q26897753", :name=>"Вольга Мікалаеўна Папко"}
{:id=>"Q26897713", :name=>"Васіль Парфёнавіч Папко"}
{:id=>"Q26897707", :name=>"Ілья …
```

Belarus (Chamber): correct Wikidata ID for House

---

CHANGES.md
lib/source/area.rb

If an area has a 'name__xx' field that is identical to the 'name__en' field, we don't need to include it, as clients can fall back to the English version.
Later we will add parallel fallbacks for other language chains (see https://meta.wikimedia.org/wiki/Wikidata/Notes/Language_fallback), and apply this to other collections.

Fallback to 'en' for Areas with identical labels

---

data/Australia/Senate/ep-popolo-v1.0.json
data/Brazil/Deputies/ep-popolo-v1.0.json
data/Cyprus/House_of_Representatives/ep-popolo-v1.0.json
data/Finland/Eduskunta/ep-popolo-v1.0.json
data/Ireland/Dail/ep-popolo-v1.0.json
data/New_Zealand/House/ep-popolo-v1.0.json
data/Northern_Ireland/Assembly/ep-popolo-v1.0.json
data/Portugal/Assembly/ep-popolo-v1.0.json

We no longer include labels that are duplicate of the English ones.
Rebuild all sources to trim these down.

refresh data without duplicate Area labels

---

data/Grenada/House_of_Representatives/ep-popolo-v1.0.json
data/Grenada/House_of_Representatives/meta.json

We were pointing at the Parliament as a whole, not the lower house.
```
⚥ data for 13; 13 added
Persons matched to Wikidata: 0 ✓ | 15 ✘
Parties matched to Wikidata: 1 ✓ 
Areas matched to Wikidata: 0 ✓ | 15 ✘
```

Grenada (House of Representatives): correct Wikidata ID

---

data/Gibraltar/Parliament/sources/instructions.json
data/Italy/House/sources/instructions.json

This assumes the following repos have been forked over to everypolitician-scrapers:
* https://github.com/andylolz/gibraltar-parliament
* https://github.com/andylolz/gibraltar-wikipedia
* https://github.com/andylolz/italy-camera
…and the relevant https://morph.io scrapers set up.

Move andylolz scrapers to everypolitician-scrapers

---

lib/wikidata_lookup.rb

The build fails for a few countries (e.g. France and Japan), when rebuilding the position data, because `posn.value.to_s` sometimes returns `nil`. We'll want to fix that upstream in Wikisnakker, but for now work around it by calling `to_s` again(!)
https://github.com/everypolitician/wikisnakker/issues/58

work around Wikisnakker problem with to_s returning nil

---

Gemfile.lock
rake_report/missing_wikidata.rb

When displaying the list of current members with no Wikidata, it's handy to
also see the source URL, to make it easier to add the person.

Show source URL in missing_wikidata

---

data/Colombia/Representatives/ep-popolo-v1.0.json
data/Colombia/Representatives/sources/manual/terms.csv
data/Colombia/Representatives/sources/wikidata/elections.json
data/Colombia/Representatives/unstable/stats.json

```
* 2 of 61 unmatched
{:id=>"Q20022295", :name=>"Yahir Acuña"}
{:id=>"Q6005013", :name=>"María del Socorro Bustamante"}
Applying local corrections from sources/manual/corrections.csv
59 x wikidata
1 x bnf
1 x fast
1 x freebase
1 x gnd
Persons matched to Wikidata: 59 ✓ | 112 ✘
No wikidata: EDUARDO JOSÉ TOUS DE LA OSSA (0ef7dc5c-3b41-41ed-8fac-c37c3318f3a5)
No wikidata: CANDELARIA PATRICIA ROJAS VERGARA (e97e2cbc-f8ac-4535-87bf-862b3e18f161)
No wikidata: JULIO EUGENIO GALLARDO ARCHBOLD (9ed3248d-170f-4e39-ac7c-4d10957220c2)
No wikidata: …
```

Colombia (Representatives): add term end date and Wikidata

---

lib/source.rb
lib/source/ocd.rb
rake_build/merge_members.rb

We no longer have any legislatures doing this sort of build.
We can't get rid of *all* the OCD code yet, as the US Congress is
looking things up the other way around. But we'll get there eventually!
Closes https://github.com/everypolitician/everypolitician/issues/599

remove OCD::IDs

---

rake_report/missing_wikidata.rb

Rather than only reporting on missing Wikidata identiiers for members of
the most recent term (with an empty report if everyone in that term has
been reconciled), report on everyone unreconciled in the most recent
term that has not yet been fully reconciled.
In other words, if the most recent term has been fully reconciled, step
back to the previous terms, until it in turn is fully reconciled, and so
on.

Report missing wikidata from latest applicable term

---

data/Mongolia/Assembly/sources/instructions.json
data/Mongolia/Assembly/sources/morph/wikipedia.csv

We want to give cosntituencies UUIDs, and for that they need IDs. It
doesn't really matter _what_ these are, as long as they stay fairly
consistent.
Generating these via SQL makes no difference to the output.
```
* 48 of 119 unmatched
{:id=>"225", :name=>"Dolgorsuren Sumiyabazar"}
{:id=>"414", :name=>"Nyam-Osor Uchral"}
{:id=>"55", :name=>"Khayangaa Bolorchuluun"}
{:id=>"396", :name=>"Jamiyan Munkhbat"}
{:id=>"388", :name=>"Davaa Ganbold"}
{:id=>"397", :name=>"Gompildoo Munkhtsetseg"}
{:id=>"387", :name=>"Jambal Ganbaatar"}
{:id=>"385", :name=>"Magvan Bilegt"}
{:id=>"389", :name=>"Dorjdugar Gantulga"}
{:id=>"383", :name=>"Baagaa Battumur"}
Data …
```

Mongolia (Assembly): generate constituency IDs

---

data/Japan/House_of_Representatives/ep-popolo-v1.0.json
data/Japan/House_of_Representatives/sources/manual/terms.csv

```
Add memberships from sources/archive/official-vanished.csv
* 268 of 541 unmatched
{:id=>"Q26044181", :name=>"Makoto Hamaguchi"}
{:id=>"Q11418015", :name=>"Masamune Wada"}
{:id=>"Q7677127", :name=>"Takamaro Fukuoka"}
{:id=>"Q17220804", :name=>"Shōji Maitachi"}
{:id=>"Q28682170", :name=>"Masaru Miyazaki"}
{:id=>"Q28682073", :name=>"Kei Satō"}
{:id=>"Q937682", :name=>"Hirofumi Nakasone"}
{:id=>"Q11533971", :name=>"Yoshifumi Tsuge"}
{:id=>"Q8056133", :name=>"Yoshiki Yamashita"}
{:id=>"Q8062688", :name=>"Yōsuke Tsuruho"}
Party plptyf not in Popolo
Party nippon_ishin_no_kai not in Popolo
273 x wikidata
160 x freebase
127 x viaf …
```

Japan (House of Representatives): end 47th term

---

rake_build/generate_ep_popolo.rb
rake_build/generate_final_csvs.rb
rake_build/generate_stats.rb
rake_config/wikidata.rb
rake_generate/area_reconciliation.rb
rake_report/area_list.rb
rake_report/missing_parties.rb
rake_report/missing_wikidata.rb
rakefile_common.rb

Rather than having to repeat these everywhere, make the Pathname, and the EveryPolitician::Popolo parsed form available throughout the build process.
NB: We could probably optimise this by caching the Popolo file, but I've skipped that for now in case there are cases where there might cause subtle bugs. This change will make it much easier to add that later if required/useful.

Add POPOLO_JSON and ep_popolo helpers

---

lib/remotesource.rb

If we check this after qe've already URL-encoded the query, it will
never match, as the space will be replaced already.

Check for "ORDER BY" before encoding

---

data/Japan/House_of_Representatives/ep-popolo-v1.0.json

```
Add memberships from sources/archive/official-vanished.csv
* 268 of 541 unmatched
{:id=>"Q11434490", :name=>"Satoshi Ōie"}
{:id=>"Q7497821", :name=>"Shinya Adachi"}
{:id=>"Q263703", :name=>"Seiko Hashimoto"}
{:id=>"Q11652175", :name=>"Makoto Nagamine"}
{:id=>"Q7677198", :name=>"Takanori Kawai"}
{:id=>"Q11360463", :name=>"Michiko Ueno"}
{:id=>"Q6313056", :name=>"Junichi Ishii"}
{:id=>"Q28682170", :name=>"Masaru Miyazaki"}
{:id=>"Q26043802", :name=>"小鑓隆史"}
{:id=>"Q3056615", :name=>"Eriko Imai"}
Party plptyf not in Popolo
Party nippon_ishin_no_kai not in Popolo
273 x wikidata
160 x freebase
127 x viaf
122 x ndl
84 x isni …
```

Japan (House of Representatives): rebuild areas

---

data/Portugal/Assembly/ep-popolo-v1.0.json

```
Add memberships from sources/morph/centraldedados.csv
Merging with sources/morph/democratica.csv
☁ Mismatch in birth_date for 100ea2cc-58f1-4b0b-97a8-8ca6e9881e7c (2009-01-01) vs 1962-03-14 (for Q10284869)
☁ Mismatch in birth_date for 04fa6992-ec8f-468e-9ee7-a5b8b33b5815 (1955-06-28) vs 1920-06-12 (for Q10285168)
☁ Mismatch in birth_date for 4470d035-b9f2-4d75-bbcb-489866c67a2e (1952-02-18) vs 1952-01-17 (for Q10307408)
☁ Mismatch in birth_date for 2825283d-270b-40f1-a190-f9e664157335 (1975-04-19) vs 1974-04-19 (for Q10322008)
☁ Mismatch in birth_date for 0a9700bc-31ed-4928-8519-592d99e4c4af (1965-05-23) vs 1899-09-06 (for Q1339831)
☁ Mismatch in birth_date for 5c26770e-1bdf-4285-a1b8-98ae91a94ab2 (1937-01-01) vs 1936-11-21 (for …
```

Portugal (Assembly): rebuild areas

---

data/Argentina/Diputados/ep-popolo-v1.0.json
data/Argentina/Senado/ep-popolo-v1.0.json
data/Australia/Senate/ep-popolo-v1.0.json
data/Belgium/Representatives/ep-popolo-v1.0.json
data/Brazil/Deputies/ep-popolo-v1.0.json
data/Cyprus/House_of_Representatives/ep-popolo-v1.0.json
data/Portugal/Assembly/ep-popolo-v1.0.json
data/Romania/Deputies/ep-popolo-v1.0.json
data/United_States_of_America/Senate/ep-popolo-v1.0.json
rakefile_common.rb

Within an Area, make the sort order of the identifiers stable, to avoid
needless diffs.

Order Area identifiers stably

---

data/Aruba/Estates/sources/instructions.json
data/Benin/National_Assembly/sources/instructions.json
data/Bermuda/Assembly/sources/instructions.json
data/Brunei/Legislative_Council/sources/instructions.json
data/Curacao/Estates/sources/instructions.json
data/French_Polynesia/Assembly/sources/instructions.json
data/India/Lok_Sabha/sources/instructions.json
data/Indonesia/Council/sources/instructions.json
data/Ivory_Coast/Assembly/sources/instructions.json
data/Kenya/Assembly/sources/instructions.json
data/Kosovo/Assembly/sources/instructions.json
data/Libya/House_of_Representatives/sources/instructions.json
data/Mauritania/National_Assembly/sources/instructions.json
data/Montserrat/Assembly/sources/instructions.json
data/Mozambique/Assembly/sources/instructions.json
data/Pakistan/Assembly/sources/instructions.json
data/Saint_Vincent_and_the_Grenadines/Assembly/sources/instructions.json
data/Sark/Chief_Pleas/sources/instructions.json
data/South_Sudan/Assembly/sources/instructions.json
data/Turks_and_Caicos_Islands/Assembly/sources/instructions.json
data/UK/Commons/sources/instructions.json
lib/instructions.rb

We previously decided to treat them as JSON5, to be more flexible, but
this has generally caused more problems than it has fixed. Instead we
should bail out early if the file isn't true JSON.

Ensure all instucitons files parse as pure JSON

---

data/Australia/Representatives/ep-popolo-v1.0.json
data/Australia/Representatives/sources/manual/terms.csv
data/Australia/Representatives/unstable/stats.json

```
Add memberships from sources/morph/openaustralia.csv
Merging with sources/morph/openaustralia-contact-details.csv
* 2 of 514 unmatched
{:id=>"Q55807656", :name=>"Patrick Gorman"}
{:id=>"Q14954679", :name=>"Ged Kearney"}
Merging with sources/manual/emails.csv
Merging with sources/manual/guessed-emails.csv
☁ Mismatch in gender for 0448f62d-f3ab-4aa1-86da-70c3fe73912d (male) vs female (for )
☁ Mismatch in gender for 56477745-9d1a-437d-944a-95f0d8ba164a (male) vs female (for )
☁ Mismatch in gender for f24b325e-6885-4028-b414-3b98d8b287ff (female) vs male (for )
Applying local corrections from sources/manual/corrections.csv
512 x openaustralia
512 x wikidata …
```

Australia (Representatives): add Wikidata ID for terms

---

data/Ireland/Dail/sources/instructions.json
lib/source/person.rb

This presumably existed at some point in the past, as we have a flag for
this set in a variety of instructions files, but it has disappeared. Bring
it back.
This is usually for the case where a Wikidata source includes lots of
details for former members who we don’t know anything about, and we don’t
need to clutter up the build output with lots of "unmatched" warnings,
especially if we’ve actually matched every member.

Don’t display unmatched reconciliation if 'report_missing' set

---

rake_build/generate_final_csvs.rb

This doesn't really add much value, and clutters up the build. It's
better to keep the output as empty as possible, so that anything
needing investigation is more obvious.

Remove reporting on 'Top identifiers' from build

---

lib/source/cabinet.rb
rake_build/generate_final_csvs.rb

This will be a sign that either the query to find the list of positions
held by members is too broad (finding non-Cabinet positions), or that the
position filter is too narrow (not including a position that _is_ actually
part of the Cabinet)

Warn on positions being skipped when building Cabinet

---

lib/matcher.rb

If we're going to group by a field in order to make lookups on it
quicker, we should really also cache the grouping.
This speeds up the Wikidata merge of the German Bundestag, for example,
from just under 2 minutes on my laptop, to about 40 seconds.

Cache grouped match rows

---

rake_build/generate_final_csvs.rb

When reporting on people/parties/areas matched to Wikidata, also include whether
terms have been matched.

Also report on number of terms matched to Wikidata

---

rake_build/generate_stats.rb
rakefile_common.rb

The everypolitician-bot works with a shallow clone of the repo, with no
history, so if it asks `git` for the last change time of a file, it will be
seconds ago. So make it so that we look up the date via the Github API
instead, unless EP_FULL_GIT is set in the environment.

Look up file change times via Octokit if no local history

---

rake_build/generate_stats.rb

The GitHub API is rate-limited, so if we hit too many requests, we should fail graceully.
Ideally we'll be able to authenticate, and get a much higher limit, but we should handle errors better anyway.

Gracefully handle Octokit errors

---

rake_build/generate_stats.rb

This lets us have 5000 requests per hour, compared to 60 per hour
if unathenticated:
https://developer.github.com/v3/#rate-limiting
Heroku is already configured to have access to this, since 2016:
https://github.com/everypolitician/rebuilder/pull/34

Use GITHUB_ACCESS_TOKEN when making API calls

---

data/South_Africa/Assembly/sources/manual/position-filter.csv
data/South_Africa/Assembly/unstable/positions.csv
data/South_Africa/Assembly/unstable/stats.json

```
10:52:14 Validating CSVs
10:52:15 Add memberships from sources/morph/wikidata-memberships.csv
10:52:15 Merging with sources/morph/peoplesassembly.csv
10:52:15 Merging with sources/morph/wikidata.csv
☁ Mismatch in honorific_prefix for c4e3374e-12ba-477b-b654-abd17a9b343c (Prof) vs professor (for Q47536761)
* 1 of 495 unmatched
{:id=>"Q936528", :name=>"Dov Yosef"}
10:52:16 Merging with sources/morph/genderbalance.csv
☁ Mismatch in gender for 161d4dff-6a3a-4740-9db8-71b417717384 (female) vs male (for )
* 3 of 400 unmatched
10:52:16 Generating legacy_id file
10:52:16 Verifying sources/merged.csv
10:52:16 Converting to Popolo
10:52:17 Creating termfiles
10:52:17 Creating names.csv
10:52:17 Creating unstable/positions.csv
☇ No dates for Naledi Pandor (Q11043304) as Minister of Education
☇ …
```

South Africa (Assembly): regenerate Cabinet position list

---

data/South_Africa/Assembly/ep-popolo-v1.0.json
data/South_Africa/Assembly/sources/instructions.json
data/South_Africa/Assembly/sources/manual/terms.csv
data/South_Africa/Assembly/sources/morph/terms.csv
data/South_Africa/Assembly/unstable/stats.json

Part of https://github.com/everypolitician/everypolitician/issues/626
```
11:02:44 Validating CSVs
11:02:45 Refetching sources/morph/terms.csv
11:02:46 Add memberships from sources/morph/wikidata-memberships.csv
11:02:46 Merging with sources/morph/peoplesassembly.csv
11:02:46 Merging with sources/morph/wikidata.csv
☁ Mismatch in honorific_prefix for c4e3374e-12ba-477b-b654-abd17a9b343c (Prof) vs professor (for Q47536761)
* 1 of 495 unmatched
{:id=>"Q936528", :name=>"Dov Yosef"}
11:02:47 Merging with sources/morph/genderbalance.csv
☁ Mismatch in gender for 161d4dff-6a3a-4740-9db8-71b417717384 (female) vs male (for )
* 3 of 400 unmatched
11:02:47 Generating legacy_id file
11:02:47 Verifying sources/merged.csv
11:02:47 Converting to Popolo
11:02:48 Creating termfiles
11:02:48 Creating …
```

South Africa (Assembly): get terms from Wikidata

---

lib/position/map.rb
lib/source/cabinet.rb
rake_build/generate_final_csvs.rb

This usually means that we need to regenerate the map.
We should also skip those when reporting on unexpected positions actively
held by people (which might either need to be added to the map, or for the
scraper to be adjusted to not include them)

report if Position Map still includes non-cabinet positions

---

Gemfile

Since d4c001abeee we've explicitly required a ruby 2.3 or greater. But per https://github.com/everypolitician/everypolitician/issues/614 we can't yet handle ruby 2.4, so we should make that explicit too.

Explicitly require ruby 2.3

---

data/Taiwan/meta.json

Add cabinet wikidata ID
```
07:53:54 Validating CSVs
07:53:54 Refetching sources/wikidata/positions.json
07:54:07 Add memberships from sources/morph/official.csv
07:54:07 Add memberships from sources/morph/official9.csv
07:54:07 Merging with sources/morph/wikidata.csv
* 81 of 251 unmatched
{:id=>"Q8350655", :name=>"余陳月瑛"}
{:id=>"Q3847080", :name=>"賴清德"}
{:id=>"Q8277764", :name=>"魏鏞"}
{:id=>"Q8348633", :name=>"黃仁杼"}
{:id=>"Q453289", :name=>"紀政"}
{:id=>"Q716710", :name=>"張俊雄"}
{:id=>"Q8938281", :name=>"朱惠良"}
{:id=>"Q8274095", :name=>"韓國瑜"}
{:id=>"Q700659", :name=>"蕭萬長"}
{:id=>"Q8274333", :name=>"林明溱"}
07:54:07 Adding unmigrated GenderBalance results from sources/gender-balance/results.csv
07:54:07 Generating legacy_id file
07:54:07 Verifying sources/merged.csv
07:54:07 Converting to Popolo …
```

Taiwan (Legislative Yuan): rake refresh_country_meta

---

data/Estonia/Riigikogu/sources/instructions.json
data/Estonia/Riigikogu/sources/wikidata/elections.json
lib/wikidata_lookup.rb

Rather of supplying a base Item each relevant election should be an
instance of, we should instead be checking that an election has an
'Office contested' of a relevant Item (usually the "Member of X
legislature" one)
We'll need to migrate these all one by one, so in the mean time, warn if
anything is using the old approach.

Add office-based election lookups

---

lib/git.rb
lib/task/rebuild_countries_json.rb

Clean up the git history command, extracting it into a class of its own, and parsing the output section by section rather than line by line.

Extract a GitHistory class

---

.rubocop_todo.yml
bin/wikidata_info.rb

We only have one of them, so it's easily fixed.

Remove 'indent heredocs' warnings from rubocop

---

.rubocop_todo.yml
rake_build/generate_ep_popolo.rb

As part of clearing the rubocop backlog, get rid of the sole ShadowingOuterLocalVariable warning.

Don't shadow external variables

---

.rubocop_todo.yml
lib/source/term.rb

Especially easy as these are autocorrect-able

Fix rubocop RegexpLiteral warnings

---

Rakefile.rb

Most of this hasn't been needed since 1b659301a30f76ab159cc536dde4cb9e02950adf
but it's left behind, slowing things down, and making the code uglier,
since then.

Remove obsolete code from Rakefile

---

lib/matcher.rb

This makes it reek-clean as well as rubocop-clean.
I've tested that every legislature still builds cleanly with this
applied.
Previously the warnings were:
```
lib/matcher.rb -- 9 warnings:
[10, 10]:DuplicateMethodCall: Matcher#initialize calls 'r.to_hash' 2 times [https://github.com/troessner/reek/blob/v5.3.1/docs/Duplicate-Method-Call.md]
[33, 35]:DuplicateMethodCall: Matcher::Exact#find_all calls 'incoming_row[@_incoming_field]' 2 times [https://github.com/troessner/reek/blob/v5.3.1/docs/Duplicate-Method-Call.md]
[25, 25]:DuplicateMethodCall: Matcher::Reconciled#find_all calls 'match[:uuid]' 2 times [https://github.com/troessner/reek/blob/v5.3.1/docs/Duplicate-Method-Call.md]
[31]:InstanceVariableAssumption: Matcher::Exact assumes too much for instance variable '@_incoming_field' …
```

Refactor matcher.rb

---

data/Aland/Lagting/meta.json
data/Aland/Lagting/sources/instructions.json
data/Alderney/States/meta.json
data/Alderney/States/sources/instructions.json
data/British_Virgin_Islands/Council/meta.json
data/Cayman_Islands/Legislative_Assembly/meta.json
data/Cayman_Islands/Legislative_Assembly/sources/instructions.json
data/Egypt/Parliament/meta.json
data/Egypt/Parliament/sources/instructions.json
data/Montserrat/Assembly/meta.json
data/Montserrat/Assembly/sources/instructions.json
data/Nagorno_Karabakh/Assembly/meta.json
data/Nagorno_Karabakh/Assembly/sources/instructions.json
data/Norfolk_Island/Assembly/meta.json
data/Norfolk_Island/Assembly/sources/instructions.json
data/Puerto_Rico/House_of_Representatives/meta.json
data/Puerto_Rico/House_of_Representatives/sources/instructions.json
data/Saint_Helena/Legislative_Council/meta.json
data/Saint_Helena/Legislative_Council/sources/instructions.json
data/Saint_Martin/Council/meta.json
data/Saint_Martin/Council/sources/instructions.json
data/Sint_Maarten/Estates/meta.json
data/Sint_Maarten/Estates/sources/instructions.json
data/South_Ossetia/Parliament/meta.json
data/South_Ossetia/Parliament/sources/instructions.json
data/Thailand/National_Legislative_Assembly/meta.json
data/United_States_of_America/House/meta.json
data/United_States_of_America/House/sources/instructions.json

Find the final stragglers with no wikidata membership ID (creating the item in many cases), and then tie those to elections where necessary.
Both of these commands now return no results:
```
> fgrep -L member data/*/*/meta.json
> fgrep base data/**/instructions.json
```

Make sure all legislatures know their membership ID

---

Gemfile.lock
lib/source.rb
rake_build/generate_ep_popolo.rb

Update to csv-to-popolo 0.31, which removes the handing of 'chamber'/'house' columns, which then lets us simplify some of our post-processing.

Remove 'chamber' handling
