estonia/Rakefile.rb
estonia/popit.json
estonia/processed.json

Initial import from Riigikogu2015 Popit

Data for Estonia

---

chile/Rakefile.rb
chile/processed.json

from http://opendata.congreso.cl/wscamaradiputados.asmx/getPeriodosLegislativos

Chile term

---

canada/Rakefile.rb
canada/popit.json
canada/processed.json

via https://morph.io/tmtmtmtm/represent-ca

Canadian House of Commons

---

Rakefile.rb

Rake task to send a PR to popolo-data-viewer

Rake publish

---

denmark/Rakefile.rb
denmark/final.json
estonia/Rakefile.rb
estonia/final.json
greenland/Rakefile.rb
greenland/final.json
iceland/Rakefile.rb
iceland/final.json
iran/Rakefile.rb
iran/final.json
italy/Rakefile.rb
italy/final.json
kazakhstan/Rakefile.rb
kazakhstan/final.json
rakefile_common.rb
wales/Rakefile.rb

Anythinng in the `@LEGISLATURE` array of a Rakefile will now become part of the data of the legislature.

Legislative names

---

iceland/Rakefile.rb
iceland/clean.json
iceland/final.json
iceland/morph.csv

The Morph scraper changed the names of the Terms

Refresh Iceland data

---

czechia/final.json
denmark/Rakefile.rb
hungary/final.json
kosovo/final.json
montenegro/final.json
poland/final.json
rakefile_common.rb
serbia/final.json
slovakia/final.json

Defaulting it to an “Independent” party if necessary. There’s almost certainly a better concept to be found here, but this will do for now.

Ensure every legislative membership has an on_behalf_of

---

rakefile_common.rb
rakefile_popit.rb
za/Rakefile.rb
za/clean.json
za/final.json

Still not ready, but improving, so merge.

more South Africa munging

---

data/Northern_Ireland/Rakefile.rb
data/Northern_Ireland/clean.json
data/Northern_Ireland/final.json
data/Northern_Ireland/terms.csv

Extract NI Assembly data from the new TWFY Popolo data.

Add Northern Ireland

---

Rakefile.rb

For each Country that’s not Work-In-Progress, find the last commit that changed its `final.json`, and push that to the Popolo-Viewer-Sinatra `src` dir.

Add `install` target to Rakefile

---

Rakefile.rb
data/Finland/Rakefile.rb
data/Finland/clean.json
data/Finland/final.json
data/Finland/github.json

We had grandfathered this in — load it properly now.
Closes #46

Finland: initial data

---

Rakefile.rb

As well as the SHA1, add the timestamp too.

Add the timestamp during a rake install

---

countries.json
data/Mozambique/Rakefile.rb
data/Mozambique/clean.json
data/Mozambique/final.json
data/Mozambique/morph.csv
data/Mozambique/sources/terms.csv
rakefile_morph.rb

Mozambique: Initial Data

---

countries.json
data/Northern_Ireland/Rakefile.rb
data/Northern_Ireland/clean.json
data/Northern_Ireland/final.json
data/Scotland/Rakefile.rb
data/Scotland/clean.json
data/Scotland/final.json
rakefile_parlparse.rb

* Refresh the data
* Handle the new `names` approach
* move data into `sources` dir

Refresh Parlparse data

---

data/Canada/Rakefile.rb
data/Canada/clean.json
data/Canada/final.json
data/Canada/sources/manual/terms.csv
data/Canada/sources/morph/data.csv

* Add a party_id field
* Split the term information out to a terms.csv file

Canada: add party_id

---

rakefile_common.rb

As part of moving all the data into the data repo, we want to generate the CSVs here, rather than in Sinatra. 
This adds the rake task for doing so — generating the actual CSV files will happen separately.

Add task for building term_table CSVs

---

Rakefile.rb
countries.json

For each country, include a list of legislative sessions, and where to find the CSV of data for each.

Add term list to `countries.json`

---

Rakefile.rb
countries.json

Not just the last change of `final.json`, as we now need to catch
changes to csv files etc too.

Build countries.json on last change within dir

---

lib/builder.rb
rakefile_morph.rb

Move the Morph fetching to a new Builder class

Start to create a Builder

---

countries.json
data/Malaysia/Dewan_Rakyat/Rakefile.rb
data/Malaysia/Dewan_Rakyat/clean.json
data/Malaysia/Dewan_Rakyat/final.json
data/Malaysia/Dewan_Rakyat/sources/manual/terms.csv
data/Malaysia/Dewan_Rakyat/sources/morph/data.csv

with more precision on the term start date, and removing the wikipedia source references to make it easier to read the JSON

Malaysia: refresh data

---

countries.json

including https://github.com/everypolitician/everypolitician-data/commit/20b685e1ee759e385d718f7bf04af629907f7685

Australia: Add Senate

---

Rakefile.rb
countries.json

Add country[name] and term[slug] to countries.json
Closes #311. Closes #312

Extend countries json

---

countries.json
data/Namibia/Council/term-1.csv
data/Namibia/Council/term-2.csv
data/Namibia/Council/term-3.csv
data/Namibia/Council/term-4.csv
rakefile_common.rb

This currently only _conceptually_ adds them — we still need to actually rebuild all the existing CSVs to add this column.
Closes #320

Add an `image` column to the term CSVs

---

data/Andorra/General_Council/Rakefile.rb
data/Bhutan/Assembly/Rakefile.rb
data/Bhutan/Assembly/meta.json
data/Burundi/Assembly/Rakefile.rb
data/Burundi/Assembly/meta.json
data/Denmark/Folketing/Rakefile.rb
data/Denmark/Folketing/final.json
data/Denmark/Folketing/meta.json
data/Estonia/Riigikogu/Rakefile.rb
data/Estonia/Riigikogu/meta.json
data/Finland/Eduskunta/Rakefile.rb
data/Finland/Eduskunta/meta.json
data/Greenland/Inatsisartut/Rakefile.rb
data/Greenland/Inatsisartut/meta.json
data/Iran/Assembly/Rakefile.rb
data/Iran/Assembly/meta.json
data/Northern_Ireland/Assembly/Rakefile.rb
data/Northern_Ireland/Assembly/meta.json
data/Scotland/Parliament/Rakefile.rb
data/Scotland/Parliament/meta.json
data/South_Africa/Assembly/Rakefile.rb
data/South_Africa/Assembly/meta.json
data/Swaziland/Assembly/Rakefile.rb
data/Swaziland/Assembly/meta.json
data/UK/Commons/Rakefile.rb
data/UK/Commons/Rakefile.ynmp.rb
data/UK/Commons/meta.json
data/Zimbabwe/Assembly/Rakefile.rb
data/Zimbabwe/Assembly/meta.json
rakefile_parlparse.rb

Add a meta.json for every remain ging legislature (other than Italy, which still needs split in two).

Add (almost) all remaining legislatures' meta.json

---

Rakefile.rb
countries.json

Use the correct legislature name, rather than the shortened version used as the directory name. (Though keep that version as the slug).
Closes https://github.com/everypolitician/everypolitician/issues/110

Use the Legislature name from Popolo

---

countries.json
data/Cook_Islands/Parliament/Rakefile.rb
data/Cook_Islands/Parliament/ep-popolo-v1.0.json
data/Cook_Islands/Parliament/meta.json
data/Cook_Islands/Parliament/sources/manual/terms.csv
data/Cook_Islands/Parliament/sources/merged.json
data/Cook_Islands/Parliament/sources/morph/data.csv
data/Cook_Islands/Parliament/sources/morph/instructions.json
data/Cook_Islands/Parliament/term-14.csv

Related to #418  (still to add previous term)

Cook Islands: Initial data

---

countries.json
data/Montserrat/Assembly/Rakefile.rb
data/Montserrat/Assembly/ep-popolo-v1.0.json
data/Montserrat/Assembly/meta.json
data/Montserrat/Assembly/sources/merged.json
data/Montserrat/Assembly/sources/morph/data.csv
data/Montserrat/Assembly/sources/morph/instructions.json
data/Montserrat/Assembly/sources/morph/terms.csv
data/Montserrat/Assembly/term-1.csv

Scraper at https://morph.io/tmtmtmtm/montseratt-election-2014
Closes #514

Montserrat: Initial data

---

rakefile_merged.rb

Cherry picked from https://github.com/everypolitician/everypolitician-data/commit/42e1efd8744645e8ed60a91de88ab456546287c9 so we can use it in other branches before merging that.

Allow merging with multiple 'person' files

---

rakefile_merged.rb
rakefile_morph.rb

Rake task to migrate a Morph-based Rakefile to a Merge+Local based one.

Auto-migrate to new Rakefile

---

countries.json
data/Norfolk_Island/Assembly/Rakefile.rb
data/Norfolk_Island/Assembly/ep-popolo-v1.0.json
data/Norfolk_Island/Assembly/meta.json
data/Norfolk_Island/Assembly/sources/Rakefile.rb
data/Norfolk_Island/Assembly/sources/instructions.json
data/Norfolk_Island/Assembly/sources/manual/instructions.json
data/Norfolk_Island/Assembly/sources/manual/members.csv
data/Norfolk_Island/Assembly/sources/merged.json
data/Norfolk_Island/Assembly/sources/morph/data.csv
data/Norfolk_Island/Assembly/sources/morph/terms.csv
data/Norfolk_Island/Assembly/term-14.csv

Scraper at: https://morph.io/tmtmtmtm/norfolk-island-assembly
Closes #574

Norfolk Island: initial data

---

countries.json
data/Kiribati/Parliament/Rakefile.rb
data/Kiribati/Parliament/ep-popolo-v1.0.json
data/Kiribati/Parliament/meta.json
data/Kiribati/Parliament/sources/Rakefile.rb
data/Kiribati/Parliament/sources/instructions.json
data/Kiribati/Parliament/sources/manual/instructions.json
data/Kiribati/Parliament/sources/manual/members.csv
data/Kiribati/Parliament/sources/manual/terms.csv
data/Kiribati/Parliament/sources/merged.json
data/Kiribati/Parliament/sources/morph/data.csv
data/Kiribati/Parliament/term-10.csv

Scraper at https://morph.io/tmtmtmtm/kiribati-parliament
Closes #177

Kiribati: Initial data

---

countries.json
data/Saint_Kitts_and_Nevis/Assembly/Rakefile.rb
data/Saint_Kitts_and_Nevis/Assembly/ep-popolo-v1.0.json
data/Saint_Kitts_and_Nevis/Assembly/meta.json
data/Saint_Kitts_and_Nevis/Assembly/sources/instructions.json
data/Saint_Kitts_and_Nevis/Assembly/sources/manual/members.csv
data/Saint_Kitts_and_Nevis/Assembly/sources/manual/terms.csv
data/Saint_Kitts_and_Nevis/Assembly/sources/merged.json
data/Saint_Kitts_and_Nevis/Assembly/sources/morph/wikidata.csv
data/Saint_Kitts_and_Nevis/Assembly/sources/morph/wikipedia.csv
data/Saint_Kitts_and_Nevis/Assembly/term-2015.csv

Scrapers at https://morph.io/tmtmtmtm/saint-kitts-and-nevis-elections-wikipedia and https://morph.io/tmtmtmtm/saint-kitts-and-nevis-elections-wikidata
Closes https://github.com/everypolitician/everypolitician-data/issues/576

Saint Kitts and Nevis: Initial data

---

README.md

Add a note to the readme about needing to specify a morph.io API key

---

Rakefile.rb
countries.json
data/UK/meta.json

It’s more in keeping with everything else, and fixes https://github.com/everypolitician/gender-balance/issues/271

Make "United Kingdom" the name for the UK

---

data/Ukraine/Verkhovna_Rada/Rakefile.rb
data/Ukraine/Verkhovna_Rada/meta.json
data/Ukraine/Verkhovna_Rada/sources/Rakefile.rb
data/Ukraine/Verkhovna_Rada/sources/instructions.json
data/Ukraine/Verkhovna_Rada/sources/manual/terms.csv

This is a work in progress to add the Ukrainian parliament.
The data generation runs OK but I haven't committed it yet because there's a bunch of outstanding questions I have about the data in the scraper repo: https://github.com/openaustralia/ukraine_verkhovna_rada_deputies
Eventually... resolves #111.

[WIP] Ukraine

---

countries.json
data/Yemen/Majlis/Rakefile.rb
data/Yemen/Majlis/ep-popolo-v1.0.json
data/Yemen/Majlis/meta.json
data/Yemen/Majlis/sources/instructions.json
data/Yemen/Majlis/sources/manual/members.csv
data/Yemen/Majlis/sources/manual/terms.csv
data/Yemen/Majlis/sources/merged.json
data/Yemen/Majlis/sources/morph/data.csv
data/Yemen/Majlis/term-2003.csv

Scraper at https://morph.io/tmtmtmtm/yemen-ypwatch
Closes https://github.com/everypolitician/everypolitician-data/issues/698

Yemen: initial data

---

countries.json
data/Austria/Nationalrat/ep-popolo-v1.0.json
data/Austria/Nationalrat/sources/instructions.json
data/Austria/Nationalrat/sources/merged.json

Austria: update source URL

---

rake_helpers/combine_sources.rb
rake_helpers/turn_csv_to_popolo.rb
rake_helpers/verify_source_data.rb
rakefile_common.rb

Check that the merged CSV has everything we need, and is well-formed, before turning it into JSON.
Closes https://github.com/everypolitician/everypolitician-data/issues/597

Add a `verify_source_data` step to the Build

---

countries.json
data/Saint_Helena/Legislative_Council/Rakefile.rb
data/Saint_Helena/Legislative_Council/ep-popolo-v1.0.json
data/Saint_Helena/Legislative_Council/meta.json
data/Saint_Helena/Legislative_Council/sources/instructions.json
data/Saint_Helena/Legislative_Council/sources/manual/terms.csv
data/Saint_Helena/Legislative_Council/sources/merged.csv
data/Saint_Helena/Legislative_Council/sources/merged.json
data/Saint_Helena/Legislative_Council/sources/morph/official.csv
data/Saint_Helena/Legislative_Council/sources/morph/wikipedia.csv
data/Saint_Helena/Legislative_Council/term-2013.csv

Scrapers at https://morph.io/tmtmtmtm/saint-helena-election-2013 and https://morph.io/tmtmtmtm/saint-helena-legislative-council
Closes https://github.com/everypolitician/everypolitician-data/issues/672

Saint Helena: initial data

---

countries.json
data/Niger/Assembly/ep-popolo-v1.0.json
data/Niger/Assembly/sources/merged.csv
data/Niger/Assembly/sources/merged.json
data/Niger/Assembly/sources/morph/data.csv
data/Niger/Assembly/term-7.1.csv

Their website has changed URLs

Niger: rebuild with new source URL

---

countries.json
data/Bolivia/Deputies/ep-popolo-v1.0.json
data/Bolivia/Deputies/meta.json
data/Jamaica/House_of_Representatives/ep-popolo-v1.0.json
data/Jamaica/House_of_Representatives/meta.json
data/Montserrat/Assembly/ep-popolo-v1.0.json
data/Montserrat/Assembly/meta.json
data/Tajikistan/Representatives/ep-popolo-v1.0.json
data/Tajikistan/Representatives/meta.json

Part of https://github.com/everypolitician/everypolitician-data/issues/398
The only one missing now is the lower house in Somalia

Add some missing wikidata links for legislatures

---

countries.json
data/Wallis_and_Futuna/Territorial_Assembly/Rakefile.rb
data/Wallis_and_Futuna/Territorial_Assembly/ep-popolo-v1.0.json
data/Wallis_and_Futuna/Territorial_Assembly/meta.json
data/Wallis_and_Futuna/Territorial_Assembly/sources/instructions.json
data/Wallis_and_Futuna/Territorial_Assembly/sources/manual/terms.csv
data/Wallis_and_Futuna/Territorial_Assembly/sources/merged.csv
data/Wallis_and_Futuna/Territorial_Assembly/sources/merged.json
data/Wallis_and_Futuna/Territorial_Assembly/sources/morph/wikidata.csv
data/Wallis_and_Futuna/Territorial_Assembly/sources/morph/wikipedia.csv
data/Wallis_and_Futuna/Territorial_Assembly/term-2012.csv

Scrapers at https://morph.io/tmtmtmtm/wallis-and-futuna-territorial-assembly and https://morph.io/tmtmtmtm/wallis-and-futuna-territorial-assembly-wikidata
Closes https://github.com/everypolitician/everypolitician-data/issues/527

Wallis and Futuna: initial data

---

rake_helpers/combine_sources.rb

These are two distinct things, and should be separated out better so we can evolve each in turn without them being quite so closely intertwined.

Split Merge into Reconcile and Patch

---

rake_helpers/combine_sources.rb

This knocks about 15% off the run-time. We'll probably need https://github.com/everypolitician/everypolitician/issues/157 to bring it down much more.
Closes https://github.com/everypolitician/everypolitician/issues/162

Try exact match before approximate match

---

countries.json
data/Azerbaijan/National_Assembly/ep-popolo-v1.0.json
data/Azerbaijan/National_Assembly/names.csv
data/Azerbaijan/National_Assembly/sources/instructions.json
data/Azerbaijan/National_Assembly/sources/morph/wikidata.csv
data/Azerbaijan/National_Assembly/term-4.csv

Closes https://github.com/everypolitician/everypolitician-data/issues/481

Azerbaijan: merge Wikidata

---

countries.json
data/Cameroon/Senate/Rakefile.rb
data/Cameroon/Senate/ep-popolo-v1.0.json
data/Cameroon/Senate/meta.json
data/Cameroon/Senate/names.csv
data/Cameroon/Senate/sources/instructions.json
data/Cameroon/Senate/sources/manual/terms.csv
data/Cameroon/Senate/sources/morph/data.csv
data/Cameroon/Senate/term-9.csv

Scraper at https://morph.io/tmtmtmtm/cameroon-senate 
Closes https://github.com/everypolitician/everypolitician-data/issues/859

Cameroon: Add Senate

---

countries.json
data/Cameroon/Senate/ep-popolo-v1.0.json
data/Cameroon/Senate/names.csv
data/Cameroon/Senate/sources/instructions.json
data/Cameroon/Senate/sources/morph/data.csv
data/Cameroon/Senate/term-9.csv

Cameroon (Senate): Refresh data with party info

---

bin/compare_term_memberships.rb
countries.json
data/UK/Commons/ep-popolo-v1.0.json
data/UK/Commons/sources/instructions.json

Script to compare the Term memberships in Popolo with the Term memberships
in Wikidata

compare term memberships

---

bin/wikidata_info.rb

Script to generate the table at
https://www.wikidata.org/wiki/Wikidata_talk:EveryPolitician

Wikidata stats

---

countries.json
data/Scotland/Parliament/ep-popolo-v1.0.json
data/Scotland/Parliament/names.csv
data/Scotland/Parliament/sources/reconciliation/wikidata.csv
data/Scotland/Parliament/term-1.csv
data/Scotland/Parliament/term-2.csv
data/Scotland/Parliament/term-3.csv
data/Scotland/Parliament/term-4.csv

Switch to the newer format of reconciliation files (with an ID), and rebuild the data.

Scotland: new Reconciliation file

---

Rakefile.rb
countries.json

ensure that all country codes are upper case, to prevent problems like https://github.com/everypolitician/viewer-sinatra/issues/935

Coerce country codes to upper case

---

bin/run_command_for_each_legislature

A handy script I've been using to check that rebuilding each legislature doesn't error after I've made a change to the rake scripts.

Add script to run command for each legislature

---

countries.json
data/Aland/Lagting/sources/reconciliation/wikidata.csv

Aland: switch to new-style reconciliation file

---

countries.json
data/Denmark/Folketing/sources/reconciliation/wikidata.csv

Denmark: switch to new-style reconciliation file

---

data/Puerto_Rico/House_of_Representatives/sources/reconciliation/wikidata.csv

Switch to ID/UUID, and refresh data

Puerto Rico: switch to new-style reconciliation file

---

data/Kuwait/National_Assembly/sources/reconciliation/wikidata.csv

Switch to ID/UUID, and refresh data

Kuwait: switch to new-style reconciliation file

---

data/New_Caledonia/Congress/sources/reconciliation/wikidata.csv

Switch to ID/UUID, and refresh data

New Caledonia: switch to new-style reconciliation file

---

data/Sweden/Riksdag/ep-popolo-v1.0.json
data/Sweden/Riksdag/names.csv
data/Sweden/Riksdag/sources/reconciliation/wikidata.csv

Switch to ID/UUID, and refresh data

Sweden: switch to new-style reconciliation file

---

data/United_States_of_America/House/sources/instructions.json
data/United_States_of_America/House/sources/manual/parties_wikidata.csv
data/United_States_of_America/House/sources/wikidata/parties.json
data/United_States_of_America/Senate/ep-popolo-v1.0.json
data/United_States_of_America/Senate/sources/instructions.json
data/United_States_of_America/Senate/sources/manual/parties_wikidata.csv
data/United_States_of_America/Senate/sources/wikidata/parties.json

Add Party information from Wikidata

US (House + Senate): Merge Wikidata parties

---

data/Ghana/Parliament/ep-popolo-v1.0.json
data/Ghana/Parliament/sources/instructions.json
data/Ghana/Parliament/sources/manual/group_wikidata.csv
data/Ghana/Parliament/sources/wikidata/groups.json
data/Nigeria/Assembly/sources/instructions.json

Ghana: Merge Wikidata party info

---

data/Nigeria/Assembly/ep-popolo-v1.0.json
data/Nigeria/Assembly/sources/instructions.json
data/Nigeria/Assembly/sources/manual/group_wikidata.csv
data/Nigeria/Assembly/sources/wikidata/groups.json

Nigeria: Merge Wikidata party info

---

data/Australia/Representatives/ep-popolo-v1.0.json
data/Australia/Representatives/sources/instructions.json
data/Australia/Representatives/sources/manual/group_wikidata.csv
data/Australia/Representatives/sources/wikidata/groups.json
data/Australia/Senate/ep-popolo-v1.0.json
data/Australia/Senate/sources/instructions.json
data/Australia/Senate/sources/manual/group_wikidata.csv
data/Australia/Senate/sources/wikidata/groups.json

Australia: Merge Wikidata party info

---

data/Angola/National_Assembly/ep-popolo-v1.0.json
data/Angola/National_Assembly/sources/instructions.json
data/Angola/National_Assembly/sources/manual/group_wikidata.csv
data/Angola/National_Assembly/sources/wikidata/groups.json

Angola: Merge Wikidata party info

---

data/Canada/Commons/ep-popolo-v1.0.json
data/Canada/Commons/sources/instructions.json
data/Canada/Commons/sources/manual/group_wikidata.csv
data/Canada/Commons/sources/wikidata/groups.json

Canada: Merge Wikidata party info

---

data/Guam/Parliament/ep-popolo-v1.0.json
data/Guam/Parliament/sources/instructions.json
data/Guam/Parliament/sources/manual/group_wikidata.csv
data/Guam/Parliament/sources/wikidata/groups.json

Guam: Merge Wikidata party info

---

countries.json
data/Northern_Ireland/Assembly/ep-popolo-v1.0.json
data/Northern_Ireland/Assembly/sources/instructions.json
data/Northern_Ireland/Assembly/sources/manual/group_wikidata.csv
data/Northern_Ireland/Assembly/sources/wikidata/groups.json

Northern Ireland: Merge Wikidata party info

---

data/Guatemala/Congress/ep-popolo-v1.0.json
data/Guatemala/Congress/sources/instructions.json
data/Guatemala/Congress/sources/manual/group_wikidata.csv
data/Guatemala/Congress/sources/wikidata/groups.json

Guatemala: Merge Wikidata party info

---

rake_helpers/combine_sources.rb

Convert legacy reconciliation CSVs that contain an id.
Converting reconciliation files that have something like `incoming_name,existing_name,confidence` in the header is going to be harder because there is no `id` in the incoming data, so there's no obvious way to map it in the new style reconciliation files, which have `id,uuid` headers.
Fixes https://github.com/everypolitician/everypolitician/issues/209

Convert legacy reconciliation CSVs in place

---

rake_helpers/combine_sources.rb

When upgrading the reconciliation CSV on the fly warn if there isn't an `id` field on the incoming row.

Handle incoming rows with no id

---

countries.json
data/Falkland_Islands/Assembly/sources/reconciliation/wikidata.csv

Falkland Islands: switch to new-style reconciliation file

---

countries.json
data/Belgium/Representatives/sources/reconciliation/data.csv

Switch to ID/UUID and refresh data

Belgium: switch to new-style reconciliation file

---

countries.json
data/Netherlands/House_of_Representatives/sources/reconciliation/wikidata.csv

Netherlands: switch to new-style reconciliation file

---

countries.json
data/Czech_Republic/Deputies/ep-popolo-v1.0.json
data/Czech_Republic/Deputies/names.csv
data/Czech_Republic/Deputies/sources/reconciliation/wikidata.csv
data/Czech_Republic/Deputies/term-4.csv

Czech Republic: switch to new-style reconciliation file

---

countries.json
data/France/National_Assembly/sources/reconciliation/wikidata.csv

France: switch to new-style reconciliation file

---

countries.json
data/Isle_of_Man/House_of_Keys/sources/reconciliation/images.csv

Isle of Man: switch to new-style reconciliation file

---

countries.json
data/Norway/Storting/sources/reconciliation/wikidata.csv

Norway: switch to new-style reconciliation file

---

countries.json
data/Samoa/Parliament/sources/reconciliation/data.csv

Samoa: switch to new-style reconciliation file

---

countries.json
data/Solomon_Islands/Parliament/sources/reconciliation/gov.csv

Solomon Islands: switch to new-style reconciliation file

---

countries.json
data/Wales/Assembly/sources/reconciliation/wikidata.csv

Wales: switch to new-style reconciliation file

---

countries.json
data/US_Virgin_Islands/Legislature/sources/reconciliation/official.csv

US Virgin Islands: switch to new-style reconciliation file

---

countries.json
data/Taiwan/Legislative_Yuan/sources/reconciliation/wikidata.csv

Taiwan: switch to new-style reconciliation file

---

lib/reconciliation/interface.rb
lib/reconciliation/legacy_csv.rb

Pass in the csv_path so it can be used to convert legacy CSVs

---

countries.json
data/Costa_Rica/Assembly/sources/instructions.json
data/Costa_Rica/Assembly/sources/morph/wikipedia.csv
data/Costa_Rica/Assembly/sources/reconciliation/wikimedia.csv
lib/reconciliation/interface.rb
lib/reconciliation/legacy_csv.rb

Costa Rica: Add an ID column for reconciliation

---

countries.json
data/Gibraltar/Parliament/sources/instructions.json
data/Gibraltar/Parliament/sources/morph/wikipedia.csv
data/Gibraltar/Parliament/sources/reconciliation/wikidata.csv

Gibraltar: Add an ID column for reconciliation

---

countries.json
data/Falkland_Islands/Assembly/sources/instructions.json
data/Falkland_Islands/Assembly/sources/morph/official.csv
data/Falkland_Islands/Assembly/sources/morph/wikipedia.csv
data/Falkland_Islands/Assembly/sources/reconciliation/official.csv

Part of https://github.com/everypolitician/everypolitician/issues/225

Falklands: Add an ID column for reconciliation

---

countries.json
data/Saint_Helena/Legislative_Council/sources/instructions.json
data/Saint_Helena/Legislative_Council/sources/morph/official.csv
data/Saint_Helena/Legislative_Council/sources/morph/wikipedia.csv
data/Saint_Helena/Legislative_Council/sources/reconciliation/official.csv

St Helena: Add an ID column for reconciliation

---

countries.json
data/Niue/Assembly/ep-popolo-v1.0.json
data/Niue/Assembly/sources/instructions.json
data/Niue/Assembly/sources/morph/gov.nu.csv
data/Niue/Assembly/sources/morph/wikipedia-2014-election.csv
data/Niue/Assembly/sources/reconciliation/wikipedia-2014-election.csv
data/Niue/Assembly/term-15.csv

Niue: Add an ID column for reconciliation

---

countries.json
data/Singapore/Parliament/ep-popolo-v1.0.json
data/Singapore/Parliament/names.csv
data/Singapore/Parliament/sources/morph/data.csv
data/Singapore/Parliament/sources/morph/terms.csv
data/Singapore/Parliament/term-11.csv
data/Singapore/Parliament/term-12.csv

after wiping and rebuilding database upstream to cope with Lee Bee Wah
name change to "Dr Lee Bee Wah" having created duplicate records.

Singapore: refresh data

---

countries.json
data/Jamaica/House_of_Representatives/ep-popolo-v1.0.json
data/Jamaica/House_of_Representatives/sources/instructions.json
data/Jamaica/House_of_Representatives/sources/manual/group_wikidata.csv
data/Jamaica/House_of_Representatives/sources/wikidata/groups.json

Jamaica: Merge Wikidata party info

---

countries.json
data/Macedonia/Sobranie/ep-popolo-v1.0.json
data/Macedonia/Sobranie/sources/instructions.json
data/Macedonia/Sobranie/sources/manual/group_wikidata.csv
data/Macedonia/Sobranie/sources/wikidata/groups.json

Macedonia: Merge Wikidata party info

---

countries.json
data/Singapore/Parliament/ep-popolo-v1.0.json
data/Singapore/Parliament/sources/instructions.json
data/Singapore/Parliament/sources/manual/group_wikidata.csv
data/Singapore/Parliament/sources/wikidata/groups.json

Singapore: Merge Wikidata party info

---

countries.json
data/Latvia/Saeima/ep-popolo-v1.0.json
data/Latvia/Saeima/sources/instructions.json
data/Latvia/Saeima/sources/manual/group_wikidata.csv
data/Latvia/Saeima/sources/wikidata/groups.json

Latvia: Merge Wikidata party info

---

countries.json
data/Lithuania/Seimas/ep-popolo-v1.0.json
data/Lithuania/Seimas/sources/instructions.json
data/Lithuania/Seimas/sources/manual/group_wikidata.csv
data/Lithuania/Seimas/sources/wikidata/groups.json

Lithuania: Merge Wikidata party info

---

countries.json
data/Portugal/Assembly/ep-popolo-v1.0.json
data/Portugal/Assembly/sources/instructions.json
data/Portugal/Assembly/sources/manual/group_wikidata.csv
data/Portugal/Assembly/sources/wikidata/groups.json

Portugal: Merge Wikidata party info

---

countries.json
data/Taiwan/Legislative_Yuan/ep-popolo-v1.0.json
data/Taiwan/Legislative_Yuan/sources/instructions.json
data/Taiwan/Legislative_Yuan/sources/manual/group_wikidata.csv
data/Taiwan/Legislative_Yuan/sources/wikidata/groups.json

Taiwan: Merge Wikidata party info

---

countries.json
data/Northern_Cyprus/Assembly/ep-popolo-v1.0.json
data/Northern_Cyprus/Assembly/sources/instructions.json
data/Northern_Cyprus/Assembly/sources/manual/group_wikidata.csv
data/Northern_Cyprus/Assembly/sources/wikidata/groups.json

Northern Cyprus: Merge Wikidata party info

---

countries.json
data/Cyprus/House_of_Representatives/ep-popolo-v1.0.json
data/Cyprus/House_of_Representatives/sources/instructions.json
data/Cyprus/House_of_Representatives/sources/manual/group_wikidata.csv
data/Cyprus/House_of_Representatives/sources/wikidata/groups.json

Cyprus: Merge Wikidata party info

---

countries.json
data/Uruguay/Deputies/ep-popolo-v1.0.json
data/Uruguay/Deputies/sources/instructions.json
data/Uruguay/Deputies/sources/manual/group_wikidata.csv
data/Uruguay/Deputies/sources/wikidata/groups.json

Uruguay: Merge Wikidata party info

---

templates/reconciliation.html.erb
templates/reconciliation.js
templates/sass/_styles.scss

Fixes everypolitician/everypolitician#203.

Show helpful message when there’s nothing to reconcile

---

templates/reconciliation.js

Especially handy for using the right-arrow key to navigate the text inside the CSV textarea.
Fixes everypolitician/everypolitician#214.

Ignore keyboard shortcuts when CSV tray is open

---

templates/reconciliation.html.erb
templates/reconciliation.js
templates/sass/_styles.scss
templates/sass/_variables.scss

Fixes everypolitician/everypolitician#215.
If you come across a suggested person who's already been matched to an incoming person (either by you in this sitting, or previously) then you get a little warning:

Highlight suggestions that have already been matched

---

data/Northern_Ireland/Assembly/ep-popolo-v1.0.json
data/Northern_Ireland/Assembly/sources/wikidata/groups.json
lib/wikidata_lookup.rb

Fetch party logos from Wikidata where available.

Add P154 (Party Logo) to Parties

---

templates/reconciliation.html.erb
templates/reconciliation.js

* Allow undo at the end (Fixes https://github.com/everypolitician/everypolitician/issues/241)
* Check for existing matches on first pairing (Fixes https://github.com/everypolitician/everypolitician/issues/239)
* Add a "Reconciliation complete" message at the end
* Various refactorings

Various Reconciler improvements and fixes

---

data/Aland/Lagting/ep-popolo-v1.0.json
data/Aland/Lagting/sources/instructions.json
data/Aland/Lagting/sources/manual/group_wikidata.csv
data/Aland/Lagting/sources/wikidata/groups.json

Aland: Merge Wikidata party info

---

countries.json
data/UK/Commons/ep-popolo-v1.0.json
data/UK/Commons/sources/instructions.json
data/UK/Commons/sources/manual/group_wikidata.csv
data/UK/Commons/sources/wikidata/groups.json

UK: Merge Wikidata party info

---

countries.json
data/New_Zealand/House/ep-popolo-v1.0.json
data/New_Zealand/House/sources/instructions.json
data/New_Zealand/House/sources/manual/group_wikidata.csv
data/New_Zealand/House/sources/wikidata/groups.json

New Zealand: Merge Wikidata party info

---

countries.json
data/British_Virgin_Islands/Assembly/ep-popolo-v1.0.json
data/British_Virgin_Islands/Assembly/sources/instructions.json
data/British_Virgin_Islands/Assembly/sources/manual/group_wikidata.csv
data/British_Virgin_Islands/Assembly/sources/wikidata/groups.json

British Virgin Islands: Merge Wikidata party info

---

countries.json
data/Trinidad_and_Tobago/Representatives/ep-popolo-v1.0.json
data/Trinidad_and_Tobago/Representatives/sources/instructions.json
data/Trinidad_and_Tobago/Representatives/sources/manual/group_wikidata.csv
data/Trinidad_and_Tobago/Representatives/sources/wikidata/groups.json
data/Trinidad_and_Tobago/Senate/ep-popolo-v1.0.json
data/Trinidad_and_Tobago/Senate/sources/instructions.json
data/Trinidad_and_Tobago/Senate/sources/manual/group_wikidata.csv
data/Trinidad_and_Tobago/Senate/sources/wikidata/groups.json

Trinidad and Tobago: Merge Wikidata party info

---

countries.json
data/Anguilla/Assembly/ep-popolo-v1.0.json
data/Anguilla/Assembly/sources/instructions.json
data/Anguilla/Assembly/sources/manual/group_wikidata.csv
data/Anguilla/Assembly/sources/wikidata/groups.json

Anguilla: Merge Wikidata party info

---

countries.json
data/Monaco/Council/ep-popolo-v1.0.json
data/Monaco/Council/sources/instructions.json
data/Monaco/Council/sources/manual/group_wikidata.csv
data/Monaco/Council/sources/wikidata/groups.json

Monaco: Merge Wikidata party info

---

bin/wikidata_info.rb
countries.json

Add info to the Wikidata Info page about the number of Parties matched,
to go with the number of people.

Wikidata party info count

---

countries.json
data/Zimbabwe/Assembly/ep-popolo-v1.0.json
data/Zimbabwe/Assembly/sources/google/people.csv
data/Zimbabwe/Assembly/term-8.csv
data/Zimbabwe/Senate/ep-popolo-v1.0.json
data/Zimbabwe/Senate/sources/google/people.csv
data/Zimbabwe/Senate/term-8.csv

The source spreadsheet now has a sort_name column

Zimbabwe: add sort_name field

---

rake_helpers/generate_final_csvs.rb

At the end of building the data, report on how many people and parties
have been matched to Wikidata and report on the missing ones if only a
few.

Generate wikidata reports

---

countries.json
data/El_Salvador/Legislative_Assembly/ep-popolo-v1.0.json
data/El_Salvador/Legislative_Assembly/sources/instructions.json
data/El_Salvador/Legislative_Assembly/sources/manual/group_wikidata.csv
data/El_Salvador/Legislative_Assembly/sources/wikidata/groups.json

El Salvador: Wikidata party info

---

countries.json
data/Cameroon/Assembly/ep-popolo-v1.0.json
data/Cameroon/Assembly/sources/instructions.json
data/Cameroon/Assembly/sources/manual/group_wikidata.csv
data/Cameroon/Assembly/sources/wikidata/groups.json

Cameroon: Wikidata party info

---

countries.json
data/Panama/Assembly/ep-popolo-v1.0.json
data/Panama/Assembly/sources/instructions.json
data/Panama/Assembly/sources/manual/group_wikidata.csv
data/Panama/Assembly/sources/wikidata/groups.json

Panama: Merge Wikidata party info

---

countries.json
data/Gabon/Assembly/ep-popolo-v1.0.json
data/Gabon/Assembly/sources/instructions.json
data/Gabon/Assembly/sources/manual/group_wikidata.csv
data/Gabon/Assembly/sources/wikidata/groups.json

Gabon: Add Wikidata party info

---

countries.json
data/France/National_Assembly/ep-popolo-v1.0.json
data/France/National_Assembly/sources/instructions.json
data/France/National_Assembly/sources/manual/group_wikidata.csv
data/France/National_Assembly/sources/wikidata/groups.json

France: Add Wikidata party info

---

rake_helpers/verify_source_data.rb

We don't want to give warnings once per Membership — only once per
Person.
Closes https://github.com/everypolitician/everypolitician/issues/283

Only warn about short dates once person

---

lib/matcher.rb
lib/reconciliation/fuzzer.rb
lib/reconciliation/interface.rb
rake_helpers/combine_sources.rb

As a lead-in to changing some of how Reconciliation works, tidy lots of the existing code up.

Refactor, tidy, and document the Reconciliation code

---

lib/reconciliation/interface.rb
rake_helpers/combine_sources.rb

only generate the Reconciliation Interface if GENERATE_RECONCILIATION_INTERFACE is set.
Closes https://github.com/everypolitician/everypolitician/issues/277
With this, building France without a reconciliation interface now takes 32 seconds on my laptop, compared to 8 minutes previously.

Make generating the Reconciliation Interface an optional step

---

countries.json
data/Alderney/States/ep-popolo-v1.0.json
data/Alderney/States/sources/instructions.json
data/Algeria/Majlis/ep-popolo-v1.0.json
data/Algeria/Majlis/sources/instructions.json
data/Angola/National_Assembly/ep-popolo-v1.0.json
data/Angola/National_Assembly/sources/instructions.json
data/Anguilla/Assembly/ep-popolo-v1.0.json
data/Anguilla/Assembly/sources/instructions.json
data/Barbados/House_of_Assembly/ep-popolo-v1.0.json
data/Barbados/House_of_Assembly/sources/instructions.json
data/Belarus/Chamber/ep-popolo-v1.0.json
data/Belarus/Chamber/sources/instructions.json
data/Benin/National_Assembly/ep-popolo-v1.0.json
data/Benin/National_Assembly/sources/instructions.json
data/Bermuda/Assembly/ep-popolo-v1.0.json
data/Bermuda/Assembly/sources/instructions.json
data/Bhutan/Assembly/ep-popolo-v1.0.json
data/Bhutan/Assembly/sources/instructions.json
data/Brazil/Deputies/ep-popolo-v1.0.json
data/Brazil/Deputies/sources/instructions.json

Rather then listing morph.io as the source for data, list the underlying sources.
Part of https://github.com/everypolitician/everypolitician/issues/156

Credit original sources

---

countries.json
data/Montenegro/Assembly/ep-popolo-v1.0.json
data/Montenegro/Assembly/sources/instructions.json
data/Montenegro/Assembly/sources/manual/group_wikidata.csv
data/Montenegro/Assembly/sources/wikidata/groups.json

Montenegro: Add Wikidata party info

---

countries.json
data/Kyrgyzstan/Council/ep-popolo-v1.0.json
data/Kyrgyzstan/Council/sources/instructions.json
data/Kyrgyzstan/Council/sources/manual/group_wikidata.csv
data/Kyrgyzstan/Council/sources/wikidata/groups.json

Kyrgyzstan: Add Wikidata party info

---

data/Ecuador/Asamblea/ep-popolo-v1.0.json
data/Ecuador/Asamblea/sources/instructions.json
data/Ecuador/Asamblea/sources/manual/group_wikidata.csv
data/Ecuador/Asamblea/sources/wikidata/groups.json

Ecuador: Add Wikidata party info

---

countries.json
data/Romania/Deputies/ep-popolo-v1.0.json
data/Romania/Deputies/sources/instructions.json
data/Romania/Deputies/sources/manual/group_wikidata.csv
data/Romania/Deputies/sources/wikidata/groups.json

Romania: Add Wikidata party info

---

countries.json
data/Tunisia/Majlis/ep-popolo-v1.0.json
data/Tunisia/Majlis/sources/instructions.json
data/Tunisia/Majlis/sources/manual/group_wikidata.csv
data/Tunisia/Majlis/sources/wikidata/groups.json

Tunisia: Add Wikidata party info

---

countries.json
data/Bolivia/Deputies/ep-popolo-v1.0.json
data/Bolivia/Deputies/sources/instructions.json
data/Bolivia/Deputies/sources/manual/group_wikidata.csv
data/Bolivia/Deputies/sources/wikidata/groups.json

Bolivia: Add Wikidata party info

---

countries.json
data/Algeria/Majlis/ep-popolo-v1.0.json
data/Algeria/Majlis/sources/instructions.json
data/Algeria/Majlis/sources/manual/group_wikidata.csv
data/Algeria/Majlis/sources/wikidata/groups.json

Algeria: Add Wikidata party info

---

countries.json
data/Mongolia/Assembly/ep-popolo-v1.0.json
data/Mongolia/Assembly/sources/instructions.json
data/Mongolia/Assembly/sources/manual/group_wikidata.csv
data/Mongolia/Assembly/sources/wikidata/groups.json

Mongolia: Add Wikidata party info

---

data/Finland/Eduskunta/ep-popolo-v1.0.json
data/Finland/Eduskunta/sources/instructions.json
data/Finland/Eduskunta/sources/manual/group_wikidata.csv
data/Finland/Eduskunta/sources/wikidata/groups.json

Finland: Add Wikidata party info

---

lib/wikidata_lookup.rb

Store an srgb value for each Party, if available from Wikidata
Closes  https://github.com/everypolitician/everypolitician/issues/93

Add party colours

---

Rakefile.rb
countries.json

Rather than consuming applications needing to generate this themselves,
provide a URL straight into rawgit.com
Closes https://github.com/everypolitician/everypolitician/issues/244
(rebuilt `countries.json` not included so as to avoid clashes — once this is merged future PRs will automatically get the new format)

Add a `popolo_url` field for each legislature

---

countries.json
data/Cyprus/House_of_Representatives/ep-popolo-v1.0.json
data/Cyprus/House_of_Representatives/sources/manual/group_wikidata.csv
data/Cyprus/House_of_Representatives/sources/wikidata/groups.json

per discussion on https://github.com/everypolitician/everypolitician-data/pull/4114 we should be pointing at the AKEL-ND parliamentary group, rather than the party.

Cyprus: point at AKEL-ND group, rather than party

---

lib/fetcher.rb
rake_helpers/combine_sources.rb

extract the code for regenerating source files into its own class
hierarchy

extract Fetcher class

---

countries.json
data/Northern_Ireland/Assembly/sources/instructions.json
data/Northern_Ireland/Assembly/sources/manual/position-filter.json
data/Northern_Ireland/Assembly/sources/wikidata/positions.json
data/Northern_Ireland/Assembly/unstable/positions.csv
rake_helpers/generate_final_csvs.rb

Northern Ireland: Add position data

---

countries.json
data/Finland/Eduskunta/sources/instructions.json
data/Finland/Eduskunta/sources/manual/position-filter.json
data/Finland/Eduskunta/sources/wikidata/positions.json
data/Finland/Eduskunta/unstable/positions.csv

Finland: Add position data

---

countries.json
data/Norway/Storting/sources/instructions.json
data/Norway/Storting/sources/manual/position-filter.json
data/Norway/Storting/sources/wikidata/positions.json
data/Norway/Storting/unstable/positions.csv

Norway: Add position data

---

countries.json
data/South_Africa/Assembly/sources/instructions.json
data/South_Africa/Assembly/sources/manual/position-filter.json
data/South_Africa/Assembly/sources/wikidata/positions.json
data/South_Africa/Assembly/unstable/positions.csv

South Africa: Add position data

---

countries.json
data/Israel/Knesset/sources/instructions.json
data/Israel/Knesset/sources/manual/position-filter.json
data/Israel/Knesset/sources/wikidata/positions.json
data/Israel/Knesset/unstable/positions.csv

Israel: Add position data

---

countries.json
data/Lithuania/Seimas/sources/instructions.json
data/Lithuania/Seimas/sources/manual/position-filter.json
data/Lithuania/Seimas/sources/wikidata/positions.json
data/Lithuania/Seimas/unstable/positions.csv

Lithuania: Add position data

---

countries.json
data/Latvia/Saeima/sources/instructions.json
data/Latvia/Saeima/sources/manual/position-filter.json
data/Latvia/Saeima/sources/wikidata/positions.json
data/Latvia/Saeima/unstable/positions.csv

Latvia: Add position data

---

countries.json
data/Ireland/Dail/sources/instructions.json
data/Ireland/Dail/sources/manual/position-filter.json
data/Ireland/Dail/sources/wikidata/positions.json
data/Ireland/Dail/unstable/positions.csv

Ireland: Add position data

---

countries.json
data/Zimbabwe/Assembly/sources/instructions.json
data/Zimbabwe/Assembly/sources/manual/position-filter.json
data/Zimbabwe/Assembly/sources/wikidata/positions.json
data/Zimbabwe/Assembly/unstable/positions.csv

Zimbabwe: Add position data

---

countries.json
data/Kenya/Assembly/sources/instructions.json
data/Kenya/Assembly/sources/manual/position-filter.json
data/Kenya/Assembly/sources/wikidata/positions.json
data/Kenya/Assembly/unstable/positions.csv

Kenya: Add position data

---

countries.json
data/Romania/Deputies/sources/instructions.json
data/Romania/Deputies/sources/manual/position-filter.json
data/Romania/Deputies/sources/wikidata/positions.json
data/Romania/Deputies/unstable/positions.csv

Romania: Add position data

---

countries.json
data/Slovenia/National_Assembly/sources/instructions.json
data/Slovenia/National_Assembly/sources/manual/position-filter.json
data/Slovenia/National_Assembly/sources/wikidata/positions.json
data/Slovenia/National_Assembly/unstable/positions.csv

Slovenia: Add position data

---

countries.json
data/Scotland/Parliament/sources/instructions.json
data/Scotland/Parliament/sources/manual/position-filter.json
data/Scotland/Parliament/sources/wikidata/positions.json
data/Scotland/Parliament/unstable/positions.csv

Scotland: Add position data

---

countries.json
data/Czech_Republic/Deputies/sources/instructions.json
data/Czech_Republic/Deputies/sources/manual/position-filter.json
data/Czech_Republic/Deputies/sources/wikidata/positions.json
data/Czech_Republic/Deputies/unstable/positions.csv

Czech Republic: Add position data

---

countries.json
data/Vietnam/National_Assembly/sources/instructions.json
data/Vietnam/National_Assembly/sources/manual/position-filter.json
data/Vietnam/National_Assembly/sources/wikidata/positions.json
data/Vietnam/National_Assembly/unstable/positions.csv

Vietnam: Add position data

---

countries.json
data/Czech_Republic/Deputies/ep-popolo-v1.0.json
data/Czech_Republic/Deputies/sources/morph/data.csv
data/Czech_Republic/Deputies/term-3.csv
data/Czech_Republic/Deputies/term-5.csv
data/Czech_Republic/Deputies/term-6.csv
data/Czech_Republic/Deputies/term-7.csv

Update without Wikidata (to make it easier to see what's going on)

Czechia: Refresh data

---

countries.json
data/Luxembourg/Chamber/sources/instructions.json
data/Luxembourg/Chamber/sources/manual/position-filter.json
data/Luxembourg/Chamber/sources/wikidata/positions.json
data/Luxembourg/Chamber/unstable/positions.csv

Luxembourg: Add position data

---

countries.json
data/Tanzania/Assembly/sources/instructions.json
data/Tanzania/Assembly/sources/manual/position-filter.json
data/Tanzania/Assembly/sources/wikidata/positions.json
data/Tanzania/Assembly/unstable/positions.csv

Tanzania: Add position data

---

countries.json
data/Sri_Lanka/Parliament/sources/instructions.json
data/Sri_Lanka/Parliament/sources/manual/position-filter.json
data/Sri_Lanka/Parliament/sources/wikidata/positions.json
data/Sri_Lanka/Parliament/unstable/positions.csv

Sri Lanka: Add position data

---

countries.json
data/Hong_Kong/Legislative_Council/sources/instructions.json
data/Hong_Kong/Legislative_Council/sources/manual/position-filter.json
data/Hong_Kong/Legislative_Council/sources/wikidata/positions.json
data/Hong_Kong/Legislative_Council/unstable/positions.csv

Hong Kong: Add position data

---

countries.json
data/Singapore/Parliament/sources/instructions.json
data/Singapore/Parliament/sources/manual/position-filter.json
data/Singapore/Parliament/sources/wikidata/positions.json
data/Singapore/Parliament/unstable/positions.csv

Singapore: Add position data

---

countries.json
data/Ukraine/Verkhovna_Rada/sources/instructions.json
data/Ukraine/Verkhovna_Rada/sources/manual/position-filter.json
data/Ukraine/Verkhovna_Rada/sources/wikidata/positions.json
data/Ukraine/Verkhovna_Rada/unstable/positions.csv

Ukraine: Add position data

---

countries.json
data/Abkhazia/Assembly/sources/instructions.json
data/Abkhazia/Assembly/sources/manual/position-filter.json
data/Abkhazia/Assembly/sources/wikidata/positions.json
data/Abkhazia/Assembly/unstable/positions.csv
data/Czech_Republic/Deputies/sources/parldata/instructions.json

Abkhazia: Add position data

---

countries.json
data/Afghanistan/Wolesi_Jirga/sources/instructions.json
data/Afghanistan/Wolesi_Jirga/sources/manual/position-filter.json
data/Afghanistan/Wolesi_Jirga/sources/wikidata/positions.json
data/Afghanistan/Wolesi_Jirga/unstable/positions.csv

Afghanistan: Add position data

---

countries.json
data/Aland/Lagting/sources/instructions.json
data/Aland/Lagting/sources/manual/position-filter.json
data/Aland/Lagting/sources/wikidata/positions.json
data/Aland/Lagting/unstable/positions.csv

Aland: Add position data

---

countries.json
data/Argentina/Diputados/sources/instructions.json
data/Argentina/Diputados/sources/manual/position-filter.json
data/Argentina/Diputados/sources/wikidata/positions.json
data/Argentina/Diputados/unstable/positions.csv

Argentina: Add position data

---

countries.json
data/Armenia/Assembly/sources/instructions.json
data/Armenia/Assembly/sources/manual/position-filter.json
data/Armenia/Assembly/sources/wikidata/positions.json
data/Armenia/Assembly/unstable/positions.csv

Armenia: Add position data

---

countries.json
data/Brazil/Deputies/sources/instructions.json
data/Brazil/Deputies/sources/manual/position-filter.json
data/Brazil/Deputies/sources/wikidata/positions.json
data/Brazil/Deputies/unstable/positions.csv

Brazil: Add position data

---

countries.json
data/Colombia/Representatives/sources/instructions.json
data/Colombia/Representatives/sources/manual/position-filter.json
data/Colombia/Representatives/sources/wikidata/positions.json
data/Colombia/Representatives/unstable/positions.csv

Colombia: Add position data

---

countries.json
data/Georgia/Parliament/sources/instructions.json
data/Georgia/Parliament/sources/manual/position-filter.json
data/Georgia/Parliament/sources/wikidata/positions.json
data/Georgia/Parliament/unstable/positions.csv

Georgia: Add position data

---

countries.json
data/Ghana/Parliament/sources/instructions.json
data/Ghana/Parliament/sources/manual/position-filter.json
data/Ghana/Parliament/sources/wikidata/positions.json
data/Ghana/Parliament/unstable/positions.csv

Ghana: Add position data

---

countries.json
data/Denmark/Folketing/sources/instructions.json
data/Denmark/Folketing/sources/manual/position-filter.json
data/Denmark/Folketing/sources/wikidata/positions.json
data/Denmark/Folketing/unstable/positions.csv

Denmark: Add position data

---

countries.json
data/Serbia/National_Assembly/sources/instructions.json
data/Serbia/National_Assembly/sources/manual/position-filter.json
data/Serbia/National_Assembly/sources/wikidata/positions.json
data/Serbia/National_Assembly/unstable/positions.csv

Serbia: Add position data

---

countries.json
data/Portugal/Assembly/sources/instructions.json
data/Portugal/Assembly/sources/manual/position-filter.json
data/Portugal/Assembly/sources/wikidata/positions.json
data/Portugal/Assembly/unstable/positions.csv

Portugal: Add position data

---

countries.json
data/Philippines/House/sources/instructions.json
data/Philippines/House/sources/manual/position-filter.json
data/Philippines/House/sources/wikidata/positions.json
data/Philippines/House/unstable/positions.csv

Philippines: Add position data

---

countries.json
data/Peru/Congreso/sources/instructions.json
data/Peru/Congreso/sources/manual/position-filter.json
data/Peru/Congreso/sources/wikidata/positions.json
data/Peru/Congreso/unstable/positions.csv

Peru: Add position data

---

countries.json
data/Mongolia/Assembly/sources/instructions.json
data/Mongolia/Assembly/sources/manual/position-filter.json
data/Mongolia/Assembly/sources/wikidata/positions.json
data/Mongolia/Assembly/unstable/positions.csv

Mongolia: Add position data

---

countries.json
data/Malta/Assembly/sources/instructions.json
data/Malta/Assembly/sources/manual/position-filter.json
data/Malta/Assembly/sources/wikidata/positions.json
data/Malta/Assembly/unstable/positions.csv

Malta: Add position data

---

countries.json
data/Japan/House_of_Representatives/sources/instructions.json
data/Japan/House_of_Representatives/sources/manual/position-filter.json
data/Japan/House_of_Representatives/sources/wikidata/positions.json
data/Japan/House_of_Representatives/unstable/positions.csv

Japan: Add position data

---

countries.json
data/Italy/House/sources/instructions.json
data/Italy/House/sources/manual/position-filter.json
data/Italy/House/sources/wikidata/positions.json
data/Italy/House/unstable/positions.csv

Italy: Add position data

---

countries.json
data/New_Zealand/House/sources/instructions.json
data/New_Zealand/House/sources/manual/position-filter.json
data/New_Zealand/House/sources/wikidata/positions.json
data/New_Zealand/House/unstable/positions.csv

New Zealand: Add position data

---

Gemfile
Gemfile.lock
countries.json
data/Netherlands/House_of_Representatives/sources/instructions.json
data/Netherlands/House_of_Representatives/sources/manual/position-filter.json
data/Netherlands/House_of_Representatives/sources/wikidata/positions.json
data/Netherlands/House_of_Representatives/unstable/positions.csv
rake_helpers/generate_final_csvs.rb

Netherlands: Add position data

---

countries.json
data/Taiwan/Legislative_Yuan/sources/instructions.json
data/Taiwan/Legislative_Yuan/sources/manual/position-filter.json
data/Taiwan/Legislative_Yuan/sources/wikidata/positions.json
data/Taiwan/Legislative_Yuan/unstable/positions.csv

Taiwan: Add position data

---

countries.json
data/Puerto_Rico/House_of_Representatives/sources/instructions.json
data/Puerto_Rico/House_of_Representatives/sources/manual/position-filter.json
data/Puerto_Rico/House_of_Representatives/sources/wikidata/positions.json
data/Puerto_Rico/House_of_Representatives/unstable/positions.csv

Puerto Rico: Add position data

---

countries.json
data/Solomon_Islands/Parliament/sources/instructions.json
data/Solomon_Islands/Parliament/sources/manual/position-filter.json
data/Solomon_Islands/Parliament/sources/wikidata/positions.json
data/Solomon_Islands/Parliament/unstable/positions.csv

Solomon Islands: Add position data

---

countries.json
data/Albania/Assembly/sources/instructions.json
data/Albania/Assembly/sources/manual/position-filter.json
data/Albania/Assembly/sources/wikidata/positions.json
data/Albania/Assembly/unstable/positions.csv
data/Vatican_City/Pontifical_Commission/sources/instructions.json
data/Vatican_City/Pontifical_Commission/sources/manual/position-filter.json
data/Vatican_City/Pontifical_Commission/sources/wikidata/positions.json
data/Vatican_City/Pontifical_Commission/unstable/positions.csv

Albania: Add position data

---

countries.json
data/Austria/Nationalrat/sources/instructions.json
data/Austria/Nationalrat/sources/manual/position-filter.json
data/Austria/Nationalrat/sources/wikidata/positions.json
data/Austria/Nationalrat/unstable/positions.csv

Add position data from Wikidata

Austria: Add position data

---

countries.json
data/Belize/Representatives/sources/instructions.json
data/Belize/Representatives/sources/manual/position-filter.json
data/Belize/Representatives/sources/wikidata/positions.json
data/Belize/Representatives/unstable/positions.csv

Belize: Add position data

---

countries.json
data/Croatia/Sabor/sources/instructions.json
data/Croatia/Sabor/sources/manual/position-filter.json
data/Croatia/Sabor/sources/wikidata/positions.json
data/Croatia/Sabor/unstable/positions.csv

Croatia: Add position data

---

countries.json
data/Cyprus/House_of_Representatives/sources/instructions.json
data/Cyprus/House_of_Representatives/sources/manual/position-filter.json
data/Cyprus/House_of_Representatives/sources/wikidata/positions.json
data/Cyprus/House_of_Representatives/unstable/positions.csv

Cyprus: Add position data

---

countries.json
data/Fiji/Parliament/sources/instructions.json
data/Fiji/Parliament/sources/manual/position-filter.json
data/Fiji/Parliament/sources/wikidata/positions.json
data/Fiji/Parliament/unstable/positions.csv

Fiji: Add position data

---

data/Falkland_Islands/Assembly/sources/instructions.json
data/Falkland_Islands/Assembly/sources/manual/position-filter.json
data/Falkland_Islands/Assembly/sources/wikidata/positions.json
data/Falkland_Islands/Assembly/unstable/positions.csv

Falkland Islands: Add position data

---

data/Lebanon/Parliament/sources/instructions.json
data/Lebanon/Parliament/sources/manual/position-filter.json
data/Lebanon/Parliament/sources/wikidata/positions.json
data/Lebanon/Parliament/unstable/positions.csv

Lebanon: Add position data

---

data/Moldova/Parlamentul/sources/instructions.json
data/Moldova/Parlamentul/sources/manual/position-filter.json
data/Moldova/Parlamentul/sources/wikidata/positions.json
data/Moldova/Parlamentul/unstable/positions.csv

Moldova: Add position data

---

countries.json
data/Guam/Parliament/sources/instructions.json
data/Guam/Parliament/sources/manual/position-filter.json
data/Guam/Parliament/sources/wikidata/positions.json
data/Guam/Parliament/unstable/positions.csv

Guam: Add position data

---

data/New_Caledonia/Congress/sources/instructions.json
data/New_Caledonia/Congress/sources/manual/position-filter.json
data/New_Caledonia/Congress/sources/wikidata/positions.json
data/New_Caledonia/Congress/unstable/positions.csv

New Caledonia: Add position data

---

countries.json
data/Niue/Assembly/sources/instructions.json
data/Niue/Assembly/sources/manual/position-filter.json
data/Niue/Assembly/sources/wikidata/positions.json
data/Niue/Assembly/unstable/positions.csv

Niue: Add position data

---

data/Pakistan/Assembly/sources/instructions.json
data/Pakistan/Assembly/sources/manual/position-filter.json
data/Pakistan/Assembly/sources/wikidata/positions.json
data/Pakistan/Assembly/unstable/positions.csv

Pakistan: Add position data

---

countries.json
data/US_Virgin_Islands/Legislature/ep-popolo-v1.0.json
data/US_Virgin_Islands/Legislature/sources/instructions.json

US Virgin Islands: Refresh data

---

countries.json
data/Turkey/Assembly/sources/instructions.json

Turkey: Refresh data

---

countries.json
data/Tunisia/Majlis/ep-popolo-v1.0.json
data/Tunisia/Majlis/sources/instructions.json
data/Tunisia/Majlis/sources/wikidata/groups.json

Tunisia: Refresh data

---

countries.json
data/Togo/Assembly/ep-popolo-v1.0.json
data/Togo/Assembly/sources/instructions.json

Togo: Refresh data

---

data/Tanzania/Assembly/ep-popolo-v1.0.json
data/Tanzania/Assembly/sources/instructions.json
data/Tanzania/Assembly/sources/manual/position-filter.json

Tanzania: Refresh data

---

data/Spain/Congress/ep-popolo-v1.0.json
data/Spain/Congress/sources/instructions.json
data/Spain/Congress/sources/manual/position-filter.json
rake_helpers/generate_final_csvs.rb

Spain: Refresh data

---

countries.json
data/South_Africa/Assembly/ep-popolo-v1.0.json
data/South_Africa/Assembly/sources/instructions.json

South Africa (Assembly) — point at original source

---

countries.json
data/South_Sudan/Assembly/ep-popolo-v1.0.json
data/South_Sudan/Assembly/sources/instructions.json

South Sudan (Assembly) — point at original source

---

countries.json
data/Slovenia/National_Assembly/ep-popolo-v1.0.json
data/Slovenia/National_Assembly/sources/instructions.json

Slovenia (National Assembly) — point at original source

---

countries.json
data/Singapore/Parliament/ep-popolo-v1.0.json
data/Singapore/Parliament/sources/instructions.json
data/Singapore/Parliament/sources/manual/position-filter.json

Singapore (Parliament) — point at original source

---

countries.json
data/Philippines/House/ep-popolo-v1.0.json
data/Philippines/House/sources/instructions.json

Philippines (House) — point at original source

---

countries.json
data/Pakistan/Assembly/ep-popolo-v1.0.json
data/Pakistan/Assembly/sources/instructions.json
data/Pakistan/Assembly/sources/manual/position-filter.json

Pakistan (Assembly) — point at original source

---

countries.json
data/Oman/Majlis/ep-popolo-v1.0.json
data/Oman/Majlis/sources/instructions.json

Oman (Majlis) — point at original source

---

countries.json
data/Niger/Assembly/ep-popolo-v1.0.json
data/Niger/Assembly/sources/instructions.json

Niger (Assembly) — point at original source

---

countries.json
data/New_Zealand/House/ep-popolo-v1.0.json
data/New_Zealand/House/sources/instructions.json

New Zealand (House) — point at original source

---

countries.json
data/Mozambique/Assembly/ep-popolo-v1.0.json
data/Mozambique/Assembly/sources/gender-balance/results.csv
data/Mozambique/Assembly/sources/instructions.json

Mozambique (Assembly) — point at original source

---

countries.json
data/Namibia/Assembly/ep-popolo-v1.0.json
data/Namibia/Assembly/sources/instructions.json

Namibia (Assembly) — point at original source

---

countries.json
data/Mauritania/National_Assembly/ep-popolo-v1.0.json
data/Mauritania/National_Assembly/sources/gender-balance/results.csv
data/Mauritania/National_Assembly/sources/instructions.json

Mauritania (National Assembly) — point at original source

---

countries.json
data/Maldives/Majlis/ep-popolo-v1.0.json
data/Maldives/Majlis/sources/instructions.json

Maldives (Majlis) — point at original source

---

countries.json
data/Malawi/Assembly/ep-popolo-v1.0.json
data/Malawi/Assembly/sources/instructions.json
data/Malawi/Assembly/sources/wikidata/groups.json

Malawi (Assembly) — point at original source

---

countries.json
data/Madagascar/Assembly/ep-popolo-v1.0.json
data/Madagascar/Assembly/sources/instructions.json

Madagascar (Assembly) — point at original source

---

countries.json
data/Lithuania/Seimas/ep-popolo-v1.0.json
data/Lithuania/Seimas/sources/instructions.json

Lithuania (Seimas) — point at original source

---

countries.json
data/Liechtenstein/Landtag/ep-popolo-v1.0.json
data/Liechtenstein/Landtag/sources/instructions.json

Liechtenstein (Landtag) — point at original source

---

countries.json
data/Kiribati/Parliament/ep-popolo-v1.0.json
data/Kiribati/Parliament/sources/gender-balance/results.csv
data/Kiribati/Parliament/sources/instructions.json

Kiribati (Parliament) — point at original source

---

countries.json
data/Kenya/Assembly/ep-popolo-v1.0.json
data/Kenya/Assembly/sources/instructions.json

Kenya (Assembly) — point at original source

---

countries.json
data/Italy/House/ep-popolo-v1.0.json
data/Italy/House/sources/instructions.json
data/Italy/House/sources/manual/position-filter.json

Italy (House) — point at original source

---

countries.json
data/Israel/Knesset/ep-popolo-v1.0.json
data/Israel/Knesset/sources/instructions.json
data/Israel/Knesset/sources/manual/position-filter.json
data/Israel/Knesset/unstable/positions.csv

Israel (Knesset) — point at original source

---

countries.json
data/Ireland/Dail/ep-popolo-v1.0.json
data/Ireland/Dail/sources/instructions.json
data/Ireland/Dail/sources/manual/position-filter.json

Ireland (Dail) — point at original source

---

countries.json
data/Hungary/Assembly/ep-popolo-v1.0.json
data/Hungary/Assembly/sources/instructions.json

Hungary (Assembly) — point at original source

---

data/Haiti/Deputies/ep-popolo-v1.0.json
data/Haiti/Deputies/sources/gender-balance/results.csv
data/Haiti/Deputies/sources/instructions.json

Haiti (Deputies) — point at original source

---

countries.json
data/Greece/Parliament/ep-popolo-v1.0.json
data/Greece/Parliament/sources/instructions.json

Greece (Parliament) — point at original source

---

countries.json
data/Gibraltar/Parliament/ep-popolo-v1.0.json
data/Gibraltar/Parliament/sources/instructions.json

Gibraltar (Parliament) — point at original source

---

countries.json
data/Ghana/Parliament/ep-popolo-v1.0.json
data/Ghana/Parliament/sources/instructions.json

Ghana (Parliament) — point at original source

---

countries.json
data/Czech_Republic/Deputies/sources/instructions.json

Czech Republic (Deputies) — point at original source

---

data/Chile/Deputies/ep-popolo-v1.0.json
data/Chile/Deputies/sources/instructions.json

Chile (Deputies) — point at original source

---

countries.json
data/Denmark/Folketing/ep-popolo-v1.0.json
data/Denmark/Folketing/sources/instructions.json
data/Denmark/Folketing/sources/manual/position-filter.json

Denmark (Folketing) — point at original source

---

countries.json
data/Bangladesh/House/sources/instructions.json

Make the output more deterministic.

Bangladesh: standardise load order

---

countries.json
data/Canada/Commons/ep-popolo-v1.0.json
data/Canada/Commons/sources/instructions.json

Canada (Commons) — point at original source

---

countries.json
data/Nauru/Parliament/sources/instructions.json
data/Nauru/Parliament/sources/manual/position-filter.json
data/Nauru/Parliament/sources/wikidata/positions.json
data/Nauru/Parliament/unstable/positions.csv

Nauru (Parliament) — add position data

---

countries.json
data/Kiribati/Parliament/sources/instructions.json
data/Kiribati/Parliament/sources/manual/position-filter.json
data/Kiribati/Parliament/sources/wikidata/positions.json
data/Kiribati/Parliament/unstable/positions.csv

Kiribati (Parliament) — add position data

---

countries.json
data/San_Marino/Council/sources/instructions.json
data/San_Marino/Council/sources/manual/position-filter.json
data/San_Marino/Council/sources/wikidata/positions.json
data/San_Marino/Council/unstable/positions.csv

San Marino (Council) — add position data

---

bin/wikidata_info.rb

Output a final total of how many people we've matched to Wikidata

Add totals to wikidata_info

---

rake_helpers/combine_sources.rb
rake_helpers/generate_final_csvs.rb

*    report on Top identifiers
*    Only report on up to 10 unmatched rows
*    Indent the mismatches

Tweaks to build output

---

rake_helpers/generate_final_csvs.rb

Otherwise lots of countries fail to build

Cope better with No identifiers

---

Rakefile.rb

When making the `countries.son` file, keep a count of how many
statements we have in the Popolo
Will be used in https://github.com/everypolitician/viewer-sinatra/pull/5351

Count the statements for each legislature

---

countries.json
data/Macedonia/Sobranie/sources/instructions.json
data/Macedonia/Sobranie/sources/manual/position-filter.json
data/Macedonia/Sobranie/sources/wikidata/positions.json
data/Macedonia/Sobranie/unstable/positions.csv

Macedonia (Sobranie) — add position data

---

countries.json
data/Antigua_and_Barbuda/Representatives/sources/instructions.json
data/Antigua_and_Barbuda/Representatives/sources/manual/position-filter.json
data/Antigua_and_Barbuda/Representatives/sources/wikidata/positions.json
data/Antigua_and_Barbuda/Representatives/unstable/positions.csv

Antigua and Barbuda (Representatives) — add position data

---

countries.json
data/Bolivia/Deputies/sources/instructions.json
data/Bolivia/Deputies/sources/manual/position-filter.json
data/Bolivia/Deputies/sources/wikidata/positions.json
data/Bolivia/Deputies/unstable/positions.csv

Bolivia (Deputies) — add position data

---

countries.json
data/India/Lok_Sabha/sources/instructions.json
data/India/Lok_Sabha/sources/manual/position-filter.json
data/India/Lok_Sabha/sources/wikidata/positions.json
data/India/Lok_Sabha/unstable/positions.csv

India (Lok Sabha) — add position data

---

countries.json
data/Netherlands/House_of_Representatives/ep-popolo-v1.0.json
data/Netherlands/House_of_Representatives/names.csv
data/Netherlands/House_of_Representatives/sources/manual/position-filter.json

Soft refresh without new data, to make data changes more visible.

Netherlands (House of Representatives): rebuild data

---

countries.json
data/Israel/Knesset/ep-popolo-v1.0.json
data/Israel/Knesset/names.csv
data/Israel/Knesset/sources/manual/position-filter.json

Rebuild data without refreshing, so that future updates are more clearly based on new data.

Israel (Knesset): rebuild data

---

countries.json
data/Poland/Sejm/names.csv
data/Poland/Sejm/sources/manual/position-filter.json

Soft rebuild to distinguish format changes from later new data PR

Poland (Sejm): rebuild data

---

countries.json
data/Belgium/Representatives/sources/instructions.json
data/Guatemala/Congress/sources/instructions.json
lib/source.rb
rake_helpers/combine_sources.rb

Start to extract lots of the logic out of the Rakefile into classes.
At first, we only use it to build up the list of fields we're interested in.

Create a Source file hierarchy

---

countries.json
data/Zimbabwe/Assembly/ep-popolo-v1.0.json
data/Zimbabwe/Senate/ep-popolo-v1.0.json

Zimbabwe: Rebuild data

---

lib/source.rb
rake_helpers/combine_sources.rb
rakefile_common.rb

General cleanup, moving more code out of the Rakefiles and into the Source classes.

Factor more code out to the Source hierarchy

---

lib/reconciliation.rb
rake_helpers/combine_sources.rb

Move the code that generates the Reconciliation interface out of the Rakefile into a Reconciler class.

Add a Reconciler class

---

countries.json
data/Montenegro/Assembly/sources/instructions.json
data/Montenegro/Assembly/sources/manual/position-filter.json
data/Montenegro/Assembly/sources/wikidata/positions.json
data/Montenegro/Assembly/unstable/positions.csv

Montenegro (Assembly) — add position data

---

countries.json
data/Iran/Assembly/sources/instructions.json
data/Iran/Assembly/sources/manual/position-filter.json
data/Iran/Assembly/sources/wikidata/positions.json
data/Iran/Assembly/unstable/positions.csv

Iran (Assembly) — add position data

---

countries.json
data/Gabon/Assembly/sources/instructions.json
data/Gabon/Assembly/sources/manual/position-filter.json
data/Gabon/Assembly/sources/wikidata/positions.json
data/Gabon/Assembly/unstable/positions.csv

Gabon (Assembly) — add position data

---

lib/source.rb

Add some extra methods on Sources

---

Gemfile.lock
countries.json
data/Aland/Lagting/ep-popolo-v1.0.json
data/Aland/Lagting/sources/wikidata/groups.json
data/Northern_Ireland/Assembly/ep-popolo-v1.0.json
data/Northern_Ireland/Assembly/sources/wikidata/groups.json
lib/wikidata_lookup.rb

As well as getting labels from Wikidata for Groups (and Areas etc), also
store their aliases.

Store aliases for Groups

---

countries.json
data/Zambia/Assembly/sources/instructions.json
data/Zambia/Assembly/sources/manual/position-filter.json
data/Zambia/Assembly/sources/wikidata/positions.json
data/Zambia/Assembly/unstable/positions.csv

Zambia (Assembly) — add position data

---

countries.json
data/Barbados/House_of_Assembly/ep-popolo-v1.0.json
data/Barbados/House_of_Assembly/sources/instructions.json
data/Barbados/House_of_Assembly/sources/manual/group_wikidata.csv
data/Barbados/House_of_Assembly/sources/wikidata/groups.json

Barbados (House of Assembly) — add Group information

---

countries.json
data/Belarus/Chamber/ep-popolo-v1.0.json
data/Belarus/Chamber/sources/instructions.json
data/Belarus/Chamber/sources/manual/group_wikidata.csv
data/Belarus/Chamber/sources/wikidata/groups.json

Belarus (Chamber) — add Group information

---

countries.json
data/Belize/Representatives/ep-popolo-v1.0.json
data/Belize/Representatives/sources/instructions.json
data/Belize/Representatives/sources/manual/group_wikidata.csv
data/Belize/Representatives/sources/wikidata/groups.json

Belize (Representatives) — add Group information

---

countries.json
data/Bhutan/Assembly/ep-popolo-v1.0.json
data/Bhutan/Assembly/sources/instructions.json
data/Bhutan/Assembly/sources/manual/group_wikidata.csv
data/Bhutan/Assembly/sources/wikidata/groups.json

Bhutan (Assembly) — add Group information

---

countries.json
data/Djibouti/Assembly/ep-popolo-v1.0.json
data/Djibouti/Assembly/sources/instructions.json
data/Djibouti/Assembly/sources/manual/group_wikidata.csv
data/Djibouti/Assembly/sources/wikidata/groups.json

Djibouti (Assembly) — add Group information

---

countries.json
data/Cambodia/National_Assembly/ep-popolo-v1.0.json
data/Cambodia/National_Assembly/sources/instructions.json
data/Cambodia/National_Assembly/sources/manual/group_wikidata.csv
data/Cambodia/National_Assembly/sources/wikidata/groups.json

Cambodia (National Assembly) — add Group information

---

countries.json
data/Guyana/National_Assembly/ep-popolo-v1.0.json
data/Guyana/National_Assembly/sources/instructions.json
data/Guyana/National_Assembly/sources/manual/group_wikidata.csv
data/Guyana/National_Assembly/sources/wikidata/groups.json

Guyana (National Assembly) — add Group information

---

data/Cook_Islands/Parliament/ep-popolo-v1.0.json
data/Cook_Islands/Parliament/sources/instructions.json
data/Cook_Islands/Parliament/sources/manual/group_wikidata.csv
data/Cook_Islands/Parliament/sources/wikidata/groups.json

Cook Islands (Parliament) — add Group information

---

countries.json
data/Gambia/National_Assembly/ep-popolo-v1.0.json
data/Gambia/National_Assembly/sources/instructions.json
data/Gambia/National_Assembly/sources/manual/group_wikidata.csv
data/Gambia/National_Assembly/sources/wikidata/groups.json

Gambia (National Assembly) — add Group information

---

data/French_Polynesia/Assembly/ep-popolo-v1.0.json
data/French_Polynesia/Assembly/sources/instructions.json
data/French_Polynesia/Assembly/sources/manual/group_wikidata.csv
data/French_Polynesia/Assembly/sources/wikidata/groups.json

French Polynesia (Assembly) — add Group information

---

data/South_Sudan/Assembly/ep-popolo-v1.0.json
data/South_Sudan/Assembly/sources/instructions.json
data/South_Sudan/Assembly/sources/manual/group_wikidata.csv
data/South_Sudan/Assembly/sources/wikidata/groups.json

South Sudan (Assembly) — add Group information

---

data/Sierra_Leone/Parliament/ep-popolo-v1.0.json
data/Sierra_Leone/Parliament/sources/instructions.json
data/Sierra_Leone/Parliament/sources/manual/group_wikidata.csv
data/Sierra_Leone/Parliament/sources/wikidata/groups.json

Sierra Leone (Parliament) — add Group information

---

countries.json
data/Seychelles/Assembly/ep-popolo-v1.0.json
data/Seychelles/Assembly/sources/instructions.json
data/Seychelles/Assembly/sources/manual/group_wikidata.csv
data/Seychelles/Assembly/sources/wikidata/groups.json

Seychelles (Assembly) — add Group information

---

data/Samoa/Parliament/ep-popolo-v1.0.json
data/Samoa/Parliament/sources/instructions.json
data/Samoa/Parliament/sources/manual/group_wikidata.csv
data/Samoa/Parliament/sources/wikidata/groups.json

Samoa (Parliament) — add Group information

---

data/Nicaragua/Asamblea/ep-popolo-v1.0.json
data/Nicaragua/Asamblea/sources/instructions.json
data/Nicaragua/Asamblea/sources/manual/group_wikidata.csv
data/Nicaragua/Asamblea/sources/wikidata/groups.json

Nicaragua (Asamblea) — add Group information

---

countries.json
data/Mauritius/National_Assembly/ep-popolo-v1.0.json
data/Mauritius/National_Assembly/sources/instructions.json
data/Mauritius/National_Assembly/sources/manual/group_wikidata.csv
data/Mauritius/National_Assembly/sources/wikidata/groups.json

Mauritius (National Assembly) — add Group information

---

countries.json
data/Montserrat/Assembly/ep-popolo-v1.0.json
data/Montserrat/Assembly/sources/instructions.json
data/Montserrat/Assembly/sources/manual/group_wikidata.csv
data/Montserrat/Assembly/sources/wikidata/groups.json

Montserrat (Assembly) — add Group information

---

countries.json
data/Isle_of_Man/House_of_Keys/ep-popolo-v1.0.json
data/Isle_of_Man/House_of_Keys/sources/instructions.json
data/Isle_of_Man/House_of_Keys/sources/manual/group_wikidata.csv
data/Isle_of_Man/House_of_Keys/sources/manual/position-filter.json
data/Isle_of_Man/House_of_Keys/sources/morph/wikidata.csv
data/Isle_of_Man/House_of_Keys/sources/wikidata/groups.json
data/Isle_of_Man/House_of_Keys/sources/wikidata/positions.json

Isle of Man (House of Keys) — add Group information

---

data/Saint_Barthelemy/Council/ep-popolo-v1.0.json
data/Saint_Barthelemy/Council/sources/instructions.json
data/Saint_Barthelemy/Council/sources/manual/group_wikidata.csv
data/Saint_Barthelemy/Council/sources/wikidata/groups.json

Saint Barthelemy (Council) — add Group information

---

data/Saint_Lucia/Assembly/ep-popolo-v1.0.json
data/Saint_Lucia/Assembly/sources/instructions.json
data/Saint_Lucia/Assembly/sources/manual/group_wikidata.csv
data/Saint_Lucia/Assembly/sources/wikidata/groups.json

Saint Lucia (Assembly) — add Group information

---

countries.json
data/Nauru/Parliament/ep-popolo-v1.0.json
data/Nauru/Parliament/sources/instructions.json
data/Nauru/Parliament/sources/manual/group_wikidata.csv
data/Nauru/Parliament/sources/wikidata/groups.json

Nauru (Parliament) — add Group information

---

countries.json
data/Saint_Pierre_and_Miquelon/Territorial_Council/ep-popolo-v1.0.json
data/Saint_Pierre_and_Miquelon/Territorial_Council/sources/instructions.json
data/Saint_Pierre_and_Miquelon/Territorial_Council/sources/manual/group_wikidata.csv
data/Saint_Pierre_and_Miquelon/Territorial_Council/sources/wikidata/groups.json

Saint Pierre and Miquelon (Territorial Council) — add Group information

---

countries.json
data/Turkmenistan/Mejlis/ep-popolo-v1.0.json
data/Turkmenistan/Mejlis/sources/instructions.json
data/Turkmenistan/Mejlis/sources/manual/group_wikidata.csv
data/Turkmenistan/Mejlis/sources/wikidata/groups.json
rake_helpers/generate_final_csvs.rb

Turkmenistan (Mejlis) — add Group information

---

countries.json
data/Timor_Leste/Parlamento/ep-popolo-v1.0.json
data/Timor_Leste/Parlamento/sources/instructions.json
data/Timor_Leste/Parlamento/sources/manual/group_wikidata.csv
data/Timor_Leste/Parlamento/sources/wikidata/groups.json

Timor Leste (Parlamento) — add Group information

---

countries.json
data/Kiribati/Parliament/ep-popolo-v1.0.json
data/Kiribati/Parliament/sources/instructions.json
data/Kiribati/Parliament/sources/manual/group_wikidata.csv
data/Kiribati/Parliament/sources/wikidata/groups.json

Kiribati (Parliament) — add Group information

---

countries.json
data/Niger/Assembly/ep-popolo-v1.0.json
data/Niger/Assembly/sources/instructions.json
data/Niger/Assembly/sources/manual/group_wikidata.csv
data/Niger/Assembly/sources/wikidata/groups.json

Niger (Assembly) — add Group information

---

countries.json
data/Sint_Maarten/Estates/ep-popolo-v1.0.json
data/Sint_Maarten/Estates/sources/instructions.json
data/Sint_Maarten/Estates/sources/manual/group_wikidata.csv
data/Sint_Maarten/Estates/sources/wikidata/groups.json

Sint Maarten (Estates) — add Group information

---

countries.json
data/Gibraltar/Parliament/ep-popolo-v1.0.json
data/Gibraltar/Parliament/sources/instructions.json
data/Gibraltar/Parliament/sources/manual/group_wikidata.csv
data/Gibraltar/Parliament/sources/wikidata/groups.json

Gibraltar (Parliament) — add Group information

---

Gemfile
Gemfile.lock
bin/last_updated.rb

Report on which each legislature was last updated

Add a `last_modified` script

---

countries.json
data/New_Caledonia/Congress/ep-popolo-v1.0.json
data/New_Caledonia/Congress/sources/instructions.json
data/New_Caledonia/Congress/sources/manual/group_wikidata.csv
data/New_Caledonia/Congress/sources/wikidata/groups.json

New Caledonia (Congress) — add Group information

---

countries.json
data/Nagorno_Karabakh/Assembly/ep-popolo-v1.0.json
data/Nagorno_Karabakh/Assembly/sources/instructions.json
data/Nagorno_Karabakh/Assembly/sources/manual/group_wikidata.csv
data/Nagorno_Karabakh/Assembly/sources/wikidata/groups.json

Nagorno Karabakh (Assembly) — add Group information

---

countries.json
data/Vatican_City/Pontifical_Commission/ep-popolo-v1.0.json
data/Vatican_City/Pontifical_Commission/sources/instructions.json
data/Vatican_City/Pontifical_Commission/sources/manual/group_wikidata.csv
data/Vatican_City/Pontifical_Commission/sources/wikidata/groups.json

Vatican City (Pontifical Commission) — add Group information

---

countries.json
data/Thailand/National_Legislative_Assembly/ep-popolo-v1.0.json
data/Thailand/National_Legislative_Assembly/sources/instructions.json
data/Thailand/National_Legislative_Assembly/sources/manual/group_wikidata.csv
data/Thailand/National_Legislative_Assembly/sources/wikidata/groups.json

Thailand (National Legislative Assembly) — add Group information

---

countries.json
data/Saudi_Arabia/Shura/ep-popolo-v1.0.json
data/Saudi_Arabia/Shura/sources/instructions.json
data/Saudi_Arabia/Shura/sources/manual/group_wikidata.csv
data/Saudi_Arabia/Shura/sources/wikidata/groups.json

Saudi Arabia (Shura) — add Group information

---

countries.json
data/Saint_Helena/Legislative_Council/ep-popolo-v1.0.json
data/Saint_Helena/Legislative_Council/sources/instructions.json
data/Saint_Helena/Legislative_Council/sources/manual/group_wikidata.csv
data/Saint_Helena/Legislative_Council/sources/wikidata/groups.json

Saint Helena (Legislative Council) — add Group information

---

countries.json
data/Palau/House_of_Delegates/ep-popolo-v1.0.json
data/Palau/House_of_Delegates/sources/instructions.json
data/Palau/House_of_Delegates/sources/manual/group_wikidata.csv
data/Palau/House_of_Delegates/sources/wikidata/groups.json

Palau (House of Delegates) — add Group information

---

countries.json
data/Oman/Majlis/ep-popolo-v1.0.json
data/Oman/Majlis/names.csv
data/Oman/Majlis/sources/instructions.json
data/Oman/Majlis/sources/manual/group_wikidata.csv
data/Oman/Majlis/sources/wikidata/groups.json

Oman (Majlis) — add Group information

---

countries.json
data/Niue/Assembly/ep-popolo-v1.0.json
data/Niue/Assembly/sources/instructions.json
data/Niue/Assembly/sources/manual/group_wikidata.csv
data/Niue/Assembly/sources/wikidata/groups.json

Niue (Assembly) — add Group information

---

countries.json
data/Libya/House_of_Representatives/ep-popolo-v1.0.json
data/Libya/House_of_Representatives/sources/instructions.json
data/Libya/House_of_Representatives/sources/manual/group_wikidata.csv
data/Libya/House_of_Representatives/sources/wikidata/groups.json

Libya (House of Representatives) — add Group information

---

countries.json
data/Kuwait/National_Assembly/ep-popolo-v1.0.json
data/Kuwait/National_Assembly/sources/instructions.json
data/Kuwait/National_Assembly/sources/manual/group_wikidata.csv
data/Kuwait/National_Assembly/sources/wikidata/groups.json

Kuwait (National Assembly) — add Group information

---

countries.json
data/Jersey/States/ep-popolo-v1.0.json
data/Jersey/States/sources/instructions.json
data/Jersey/States/sources/manual/group_wikidata.csv
data/Jersey/States/sources/wikidata/groups.json

Jersey (States) — add Group information

---

countries.json
data/Guernsey/States/ep-popolo-v1.0.json
data/Guernsey/States/names.csv
data/Guernsey/States/sources/instructions.json
data/Guernsey/States/sources/manual/group_wikidata.csv
data/Guernsey/States/sources/morph/data-ids.csv
data/Guernsey/States/sources/morph/data.csv
data/Guernsey/States/sources/wikidata/groups.json
data/Guernsey/States/term-2012.csv

Guernsey (States) — add Group information

---

countries.json
data/Finland/Eduskunta/sources/manual/position-filter.json
data/Finland/Eduskunta/sources/wikidata/positions.json
data/Finland/Eduskunta/unstable/positions.csv

And disambiguate the Minister of Health and Social Services

Finland (Eduskunta): Learn new Positions

---

countries.json
data/Tunisia/Majlis/sources/instructions.json
data/Tunisia/Majlis/sources/manual/position-filter.json
data/Tunisia/Majlis/sources/wikidata/positions.json
data/Tunisia/Majlis/unstable/positions.csv

Tunisia (Majlis) — add position data

---

countries.json
data/Uganda/Parliament/sources/instructions.json
data/Uganda/Parliament/sources/manual/position-filter.json
data/Uganda/Parliament/sources/wikidata/positions.json
data/Uganda/Parliament/unstable/positions.csv

Uganda (Parliament) — add position data

---

countries.json
data/Uruguay/Deputies/sources/instructions.json
data/Uruguay/Deputies/sources/manual/position-filter.json
data/Uruguay/Deputies/sources/wikidata/positions.json
data/Uruguay/Deputies/unstable/positions.csv

Uruguay (Deputies) — add position data

---

countries.json
data/Latvia/Saeima/sources/instructions.json
data/Latvia/Saeima/sources/wikidata/elections.json
rakefile_common.rb

Latvia (Saeima) — add Election information

---

data/Belgium/Representatives/sources/instructions.json
data/Belgium/Representatives/sources/wikidata/elections.json
lib/wikidata_lookup.rb

Belgium (Representatives) — add Election information

---

countries.json
data/Lithuania/Seimas/sources/instructions.json
data/Lithuania/Seimas/sources/wikidata/elections.json

Lithuania (Seimas) — add Election information

---

countries.json
data/Cyprus/House_of_Representatives/sources/instructions.json
data/Cyprus/House_of_Representatives/sources/wikidata/elections.json

Cyprus (House of Representatives) — add Election information

---

countries.json
data/Spain/Congress/sources/instructions.json
data/Spain/Congress/sources/wikidata/elections.json

Spain (Congress) — add Election information

---

countries.json
data/Ireland/Dail/sources/instructions.json
data/Ireland/Dail/sources/wikidata/elections.json

Ireland (Dail) — add Election information

---

countries.json
data/Czech_Republic/Deputies/sources/instructions.json
data/Czech_Republic/Deputies/sources/wikidata/elections.json
lib/wikidata_lookup.rb

Czech Republic (Deputies) — add Election information

---

countries.json
data/Montenegro/Assembly/sources/instructions.json
data/Montenegro/Assembly/sources/wikidata/elections.json

Montenegro (Assembly) — add Election information

---

countries.json
data/Greenland/Inatsisartut/sources/instructions.json
data/Greenland/Inatsisartut/sources/wikidata/elections.json

Greenland (Inatsisartut) — add Election information

---

countries.json
data/Moldova/Parlamentul/sources/instructions.json
data/Moldova/Parlamentul/sources/wikidata/elections.json

Moldova (Parlamentul) — add Election information

---

countries.json
data/Macedonia/Sobranie/sources/instructions.json
data/Macedonia/Sobranie/sources/wikidata/elections.json

Macedonia (Sobranie) — add Election information

---

countries.json
data/Finland/Eduskunta/sources/instructions.json
data/Finland/Eduskunta/sources/wikidata/elections.json

Finland (Eduskunta) — add Election information

---

countries.json
data/Sweden/Riksdag/sources/instructions.json
data/Sweden/Riksdag/sources/wikidata/elections.json

Sweden (Riksdag) — add Election information

---

countries.json
data/Slovakia/National_Council/sources/instructions.json
data/Slovakia/National_Council/sources/wikidata/elections.json

Slovakia (National Council) — add Election information

---

countries.json
data/Hungary/Assembly/sources/instructions.json
data/Hungary/Assembly/sources/wikidata/elections.json

Hungary (Assembly) — add Election information

---

countries.json
data/Netherlands/House_of_Representatives/sources/instructions.json
data/Netherlands/House_of_Representatives/sources/wikidata/elections.json

Netherlands (House of Representatives) — add Election information

---

countries.json
data/Denmark/Folketing/sources/instructions.json
data/Denmark/Folketing/sources/wikidata/elections.json

Denmark (Folketing) — add Election information

---

countries.json
data/Serbia/National_Assembly/sources/instructions.json
data/Serbia/National_Assembly/sources/wikidata/elections.json

Serbia (National Assembly) — add Election information

---

countries.json
data/Croatia/Sabor/sources/instructions.json
data/Croatia/Sabor/sources/wikidata/elections.json

Croatia (Sabor) — add Election information

---

countries.json
data/Austria/Nationalrat/sources/instructions.json
data/Austria/Nationalrat/sources/wikidata/elections.json

Austria (Nationalrat) — add Election information

---

countries.json
data/Malta/Assembly/sources/instructions.json
data/Malta/Assembly/sources/wikidata/elections.json

Malta (Assembly) — add Election information

---

countries.json
data/Slovenia/National_Assembly/sources/instructions.json
data/Slovenia/National_Assembly/sources/wikidata/elections.json

Slovenia (National Assembly) — add Election information

---

countries.json
data/Kosovo/Assembly/sources/instructions.json
data/Kosovo/Assembly/sources/wikidata/elections.json

Kosovo (Assembly) — add Election information

---

countries.json
data/Bosnia_and_Herzegovina/House_of_Representatives/ep-popolo-v1.0.json
data/Bosnia_and_Herzegovina/House_of_Representatives/sources/instructions.json
data/Bosnia_and_Herzegovina/House_of_Representatives/sources/wikidata/elections.json

Bosnia and Herzegovina (House of Representatives) — add Election information

---

countries.json
data/Scotland/Parliament/sources/instructions.json
data/Scotland/Parliament/sources/wikidata/elections.json

Scotland (Parliament) — add Election information

---

countries.json
data/Albania/Assembly/sources/instructions.json
data/Albania/Assembly/sources/wikidata/elections.json

Albania (Assembly) — add Election information

---

countries.json
data/Wales/Assembly/sources/instructions.json
data/Wales/Assembly/sources/wikidata/elections.json

Wales (Assembly) — add Election information

---

countries.json
data/Andorra/General_Council/sources/instructions.json
data/Andorra/General_Council/sources/wikidata/elections.json

Andorra (General Council) — add Election information

---

countries.json
data/Northern_Ireland/Assembly/sources/instructions.json
data/Northern_Ireland/Assembly/sources/wikidata/elections.json

Northern Ireland (Assembly) — add Election information

---

countries.json
data/Romania/Deputies/sources/instructions.json
data/Romania/Deputies/sources/wikidata/elections.json

Romania (Deputies) — add Election information

---

countries.json
data/Iceland/Assembly/sources/instructions.json
data/Iceland/Assembly/sources/wikidata/elections.json

Iceland (Assembly) — add Election information

---

countries.json
data/Switzerland/National_Council/sources/instructions.json
data/Switzerland/National_Council/sources/wikidata/elections.json

Switzerland (National Council) — add Election information

---

countries.json
data/Faroe_Islands/Logting/sources/instructions.json
data/Faroe_Islands/Logting/sources/wikidata/elections.json

Faroe Islands (Logting) — add Election information

---

countries.json
data/San_Marino/Council/sources/instructions.json
data/San_Marino/Council/sources/wikidata/elections.json

San Marino (Council) — add Election information

---

countries.json
data/Liechtenstein/Landtag/sources/instructions.json
data/Liechtenstein/Landtag/sources/wikidata/elections.json

Liechtenstein (Landtag) — add Election information

---

countries.json
data/Norway/Storting/sources/instructions.json
data/Norway/Storting/sources/wikidata/elections.json

Norway (Storting) — add Election information

---

countries.json
data/Bulgaria/National_Assembly/sources/instructions.json
data/Bulgaria/National_Assembly/sources/wikidata/elections.json

Bulgaria (National Assembly) — add Election information

---

countries.json
data/Greece/Parliament/sources/instructions.json
data/Greece/Parliament/sources/wikidata/elections.json

Greece (Parliament) — add Election information

---

countries.json
data/Luxembourg/Chamber/sources/instructions.json
data/Luxembourg/Chamber/sources/wikidata/elections.json

Luxembourg (Chamber) — add Election information

---

countries.json
data/France/National_Assembly/sources/instructions.json
data/France/National_Assembly/sources/wikidata/elections.json

France (National Assembly) — add Election information

---

countries.json
data/Italy/House/sources/instructions.json
data/Italy/House/sources/wikidata/elections.json

Italy (House) — add Election information

---

countries.json
data/Kyrgyzstan/Council/sources/instructions.json
data/Kyrgyzstan/Council/sources/wikidata/elections.json

Kyrgyzstan (Council) — add Election information

---

countries.json
data/Belarus/Chamber/sources/instructions.json
data/Belarus/Chamber/sources/wikidata/elections.json

Belarus (Chamber) — add Election information

---

countries.json
data/Ukraine/Verkhovna_Rada/sources/instructions.json
data/Ukraine/Verkhovna_Rada/sources/wikidata/elections.json

Ukraine (Verkhovna Rada) — add Election information

---

countries.json
data/Russia/Duma/sources/instructions.json
data/Russia/Duma/sources/wikidata/elections.json

Russia (Duma) — add Election information

---

countries.json
data/Azerbaijan/National_Assembly/sources/instructions.json
data/Azerbaijan/National_Assembly/sources/wikidata/elections.json

Azerbaijan (National Assembly) — add Election information

---

countries.json
data/Armenia/Assembly/sources/instructions.json
data/Armenia/Assembly/sources/wikidata/elections.json

Armenia (Assembly) — add Election information

---

countries.json
data/Georgia/Parliament/sources/instructions.json
data/Georgia/Parliament/sources/wikidata/elections.json

Georgia (Parliament) — add Election information

---

countries.json
data/Germany/Bundestag/sources/instructions.json
data/Germany/Bundestag/sources/wikidata/elections.json

Germany (Bundestag) — add Election information

---

countries.json
data/Uzbekistan/Legislative_Chamber/ep-popolo-v1.0.json
data/Uzbekistan/Legislative_Chamber/sources/instructions.json
data/Uzbekistan/Legislative_Chamber/sources/wikidata/elections.json
data/Uzbekistan/Legislative_Chamber/sources/wikidata/groups.json

Uzbekistan (Legislative Chamber) — add Election information

---

countries.json
data/Kyrgyzstan/Council/sources/instructions.json
data/Kyrgyzstan/Council/sources/wikidata/elections.json
data/Tajikistan/Representatives/sources/instructions.json
data/Tajikistan/Representatives/sources/wikidata/elections.json

Tajikistan (Representatives) — add Election information

---

countries.json
data/Kyrgyzstan/Council/sources/instructions.json
data/Kyrgyzstan/Council/sources/wikidata/elections.json
data/Tonga/Assembly/ep-popolo-v1.0.json
data/Tonga/Assembly/sources/instructions.json
data/Tonga/Assembly/sources/wikidata/elections.json

Tonga (Assembly) — add Election information

---

countries.json
data/Samoa/Parliament/sources/instructions.json
data/Samoa/Parliament/sources/wikidata/elections.json

Samoa (Parliament) — add Election information

---

countries.json
data/Fiji/Parliament/sources/instructions.json
data/Fiji/Parliament/sources/wikidata/elections.json

Fiji (Parliament) — add Election information

---

countries.json
data/British_Virgin_Islands/Assembly/sources/instructions.json
data/British_Virgin_Islands/Assembly/sources/wikidata/elections.json

British Virgin Islands (Assembly) — add Election information

---

countries.json
data/UK/Commons/sources/instructions.json
data/UK/Commons/sources/wikidata/elections.json

UK (Commons) — add Election information

---

countries.json
data/Turkey/Assembly/sources/instructions.json
data/Turkey/Assembly/sources/wikidata/elections.json

Turkey (Assembly) — add Election information

---

countries.json
data/Iraq/Majlis/sources/instructions.json
data/Iraq/Majlis/sources/wikidata/elections.json

Iraq (Majlis) — add Election information

---

countries.json
data/Iran/Assembly/sources/instructions.json
data/Iran/Assembly/sources/wikidata/elections.json

Iran (Assembly) — add Election information

---

countries.json
data/Afghanistan/Wolesi_Jirga/sources/instructions.json
data/Afghanistan/Wolesi_Jirga/sources/wikidata/elections.json

Afghanistan (Wolesi Jirga) — add Election information

---

countries.json
data/India/Lok_Sabha/sources/instructions.json
data/India/Lok_Sabha/sources/wikidata/elections.json

India (Lok Sabha) — add Election information

---

countries.json
data/Australia/Representatives/sources/instructions.json
data/Australia/Representatives/sources/wikidata/elections.json

Australia (Representatives) — add Election information

---

countries.json
data/Pakistan/Assembly/sources/instructions.json
data/Pakistan/Assembly/sources/wikidata/elections.json

Pakistan (Assembly) — add Election information

---

countries.json
data/New_Zealand/House/sources/instructions.json
data/New_Zealand/House/sources/wikidata/elections.json

New Zealand (House) — add Election information

---

countries.json
data/Canada/Commons/sources/instructions.json
data/Canada/Commons/sources/wikidata/elections.json

Canada (Commons) — add Election information

---

data/Northern_Ireland/Assembly/sources/manual/terms.csv
data/Scotland/Parliament/sources/manual/terms.csv

The parlparse script needs these to already be in master so it can allocate people correctly.

Scotland (Parliament): add details of 5th Term

---

countries.json
data/South_Korea/National_Assembly/ep-popolo-v1.0.json
data/South_Korea/National_Assembly/sources/instructions.json
data/South_Korea/National_Assembly/sources/wikidata/groups.json
data/South_Korea/National_Assembly/term-19.csv

The South Korean scraper is now getting data from a different source, so
update the meta-information to reflect that.

South Korea: Correct the 'sources' section

---

Gemfile
Gemfile.lock
rake_helpers/verify_source_data.rb

This should speed up building larger countries (e.g. Turkey).

Use rcsv for faster CSV parsing

---

countries.json
data/Nauru/Parliament/sources/instructions.json
data/Nauru/Parliament/sources/wikidata/elections.json

Nauru (Parliament) — add Election information

---

countries.json
data/Kiribati/Parliament/sources/instructions.json
data/Kiribati/Parliament/sources/wikidata/elections.json

Kiribati (Parliament) — add Election information

---

countries.json
data/Micronesia/Congress/sources/instructions.json
data/Micronesia/Congress/sources/wikidata/elections.json

Micronesia (Congress) — add Election information

---

countries.json
data/Vanuatu/Parliament/sources/instructions.json
data/Vanuatu/Parliament/sources/wikidata/elections.json

Vanuatu (Parliament) — add Election information

---

countries.json
data/Pitcairn/Island_Council/sources/instructions.json
data/Pitcairn/Island_Council/sources/wikidata/elections.json

Pitcairn (Island Council) — add Election information

---

countries.json
data/Cook_Islands/Parliament/sources/instructions.json
data/Cook_Islands/Parliament/sources/wikidata/elections.json

Cook Islands (Parliament) — add Election information

---

countries.json
data/New_Caledonia/Congress/sources/instructions.json
data/New_Caledonia/Congress/sources/wikidata/elections.json

New Caledonia (Congress) — add Election information

---

countries.json
data/Niue/Assembly/sources/instructions.json
data/Niue/Assembly/sources/wikidata/elections.json

Niue (Assembly) — add Election information

---

countries.json
data/Northern_Mariana_Islands/House/sources/instructions.json
data/Northern_Mariana_Islands/House/sources/wikidata/elections.json

Northern Mariana Islands (House) — add Election information

---

countries.json
data/Solomon_Islands/Parliament/sources/instructions.json
data/Solomon_Islands/Parliament/sources/wikidata/elections.json

Solomon Islands (Parliament) — add Election information

---

countries.json
data/Papua_New_Guinea/Parliament/sources/instructions.json
data/Papua_New_Guinea/Parliament/sources/wikidata/elections.json

Papua New Guinea (Parliament) — add Election information

---

countries.json
data/Palau/House_of_Delegates/sources/instructions.json
data/Palau/House_of_Delegates/sources/wikidata/elections.json

Palau (House of Delegates) — add Election information

---

countries.json
data/Wallis_and_Futuna/Territorial_Assembly/sources/instructions.json
data/Wallis_and_Futuna/Territorial_Assembly/sources/wikidata/elections.json

Wallis and Futuna (Territorial Assembly) — add Election information

---

countries.json
data/French_Polynesia/Assembly/sources/instructions.json
data/French_Polynesia/Assembly/sources/manual/position-filter.json
data/French_Polynesia/Assembly/sources/wikidata/positions.json
data/French_Polynesia/Assembly/unstable/positions.csv

French Polynesia (Assembly) — add position data

---

countries.json
data/Guernsey/States/sources/instructions.json
data/Guernsey/States/sources/manual/position-filter.json
data/Guernsey/States/sources/wikidata/positions.json
data/Guernsey/States/unstable/positions.csv

Guernsey (States) — add position data

---

countries.json
data/Bangladesh/House/sources/instructions.json
data/Bangladesh/House/sources/manual/position-filter.json
data/Bangladesh/House/sources/wikidata/positions.json
data/Bangladesh/House/unstable/positions.csv

Bangladesh (House) — add position data

---

countries.json
data/Vanuatu/Parliament/sources/instructions.json
data/Vanuatu/Parliament/sources/manual/position-filter.json
data/Vanuatu/Parliament/sources/wikidata/positions.json
data/Vanuatu/Parliament/unstable/positions.csv

Vanuatu (Parliament) — add position data

---

countries.json
data/Northern_Mariana_Islands/House/sources/instructions.json
data/Northern_Mariana_Islands/House/sources/manual/position-filter.json
data/Northern_Mariana_Islands/House/sources/wikidata/positions.json
data/Northern_Mariana_Islands/House/unstable/positions.csv

Northern Mariana Islands (House) — add position data

---

countries.json
data/Australia/Senate/sources/instructions.json
data/Australia/Senate/sources/manual/position-filter.json
data/Australia/Senate/sources/wikidata/positions.json
data/Australia/Senate/unstable/positions.csv

Australia (Senate) — add position data

---

countries.json
data/Honduras/Congreso_Nacional/ep-popolo-v1.0.json
data/Honduras/Congreso_Nacional/sources/instructions.json
data/Honduras/Congreso_Nacional/sources/manual/group_wikidata.csv
data/Honduras/Congreso_Nacional/sources/wikidata/groups.json

Honduras (Congreso Nacional) — add Group information

---

countries.json
data/Cyprus/House_of_Representatives/ep-popolo-v1.0.json
data/Cyprus/House_of_Representatives/sources/manual/terms.csv

Fixes https://github.com/everypolitician/everypolitician-data/issues/10543

Cyprus (House of Representatives): change name of last term

---

Rakefile.rb

Rebuilding the entire countries.json from scratch every time is very
slow. So allow an optional option to only rebuild a single country.
This still almost certainly isn't the best approach to this — we should
probably explicitly keep this updated, file by file, based on commits
— but it's an improvement over what's currently there, at least for
developing locally. We can work out how to improve the interaction with
the bot later.

Rebuild a single entry in countries.json

---

countries.json
data/Bosnia_and_Herzegovina/House_of_Representatives/ep-popolo-v1.0.json
data/Bosnia_and_Herzegovina/House_of_Representatives/sources/instructions.json
data/Bosnia_and_Herzegovina/House_of_Representatives/sources/manual/group_wikidata.csv
data/Bosnia_and_Herzegovina/House_of_Representatives/sources/wikidata/groups.json

Bosnia and Herzegovina (House of Representatives) — add Group information

---

countries.json
data/Comoros/Assembly/ep-popolo-v1.0.json
data/Comoros/Assembly/sources/instructions.json
data/Comoros/Assembly/sources/manual/group_wikidata.csv
data/Comoros/Assembly/sources/wikidata/groups.json

Comoros (Assembly) — add Group information

---

countries.json
data/Tanzania/Assembly/ep-popolo-v1.0.json
data/Tanzania/Assembly/sources/instructions.json
data/Tanzania/Assembly/sources/manual/group_wikidata.csv
data/Tanzania/Assembly/sources/wikidata/groups.json

Tanzania (Assembly) — add Group information

---

countries.json
data/Belgium/Representatives/ep-popolo-v1.0.json
data/Belgium/Representatives/sources/instructions.json
data/Belgium/Representatives/sources/manual/group_wikidata.csv
data/Belgium/Representatives/sources/wikidata/groups.json

Belgium (Representatives) — add Group information

---

countries.json
data/Bangladesh/House/ep-popolo-v1.0.json
data/Bangladesh/House/sources/instructions.json
data/Bangladesh/House/sources/manual/group_wikidata.csv
data/Bangladesh/House/sources/manual/position-filter.json
data/Bangladesh/House/sources/wikidata/groups.json
data/Bangladesh/House/unstable/positions.csv

Bangladesh (House) — add Group information

---

countries.json
data/Madagascar/Assembly/ep-popolo-v1.0.json
data/Madagascar/Assembly/sources/instructions.json
data/Madagascar/Assembly/sources/manual/group_wikidata.csv
data/Madagascar/Assembly/sources/wikidata/groups.json

Madagascar (Assembly) — add Group information

---

countries.json
data/Solomon_Islands/Parliament/ep-popolo-v1.0.json
data/Solomon_Islands/Parliament/sources/instructions.json
data/Solomon_Islands/Parliament/sources/manual/group_wikidata.csv
data/Solomon_Islands/Parliament/sources/wikidata/groups.json

Solomon Islands (Parliament) — add Group information

---

countries.json
data/Georgia/Parliament/ep-popolo-v1.0.json
data/Georgia/Parliament/sources/instructions.json
data/Georgia/Parliament/sources/manual/group_wikidata.csv
data/Georgia/Parliament/sources/wikidata/groups.json

Georgia (Parliament) — add Group information

---

countries.json
data/Japan/House_of_Representatives/ep-popolo-v1.0.json
data/Japan/House_of_Representatives/sources/instructions.json
data/Japan/House_of_Representatives/sources/manual/group_wikidata.csv
data/Japan/House_of_Representatives/sources/wikidata/groups.json

Japan (House of Representatives) — add Group information

---

countries.json
data/Lesotho/Assembly/ep-popolo-v1.0.json
data/Lesotho/Assembly/sources/instructions.json
data/Lesotho/Assembly/sources/manual/group_wikidata.csv
data/Lesotho/Assembly/sources/wikidata/groups.json

Lesotho (Assembly) — add Group information

---

countries.json
data/Indonesia/Council/ep-popolo-v1.0.json
data/Indonesia/Council/sources/instructions.json
data/Indonesia/Council/sources/manual/group_wikidata.csv
data/Indonesia/Council/sources/wikidata/groups.json

Indonesia (Council) — add Group information

---

countries.json
data/Dominican_Republic/Diputados/ep-popolo-v1.0.json
data/Dominican_Republic/Diputados/sources/instructions.json
data/Dominican_Republic/Diputados/sources/manual/group_wikidata.csv
data/Dominican_Republic/Diputados/sources/wikidata/groups.json

Dominican Republic (Diputados) — add Group information

---

CHANGES.md
data/Estonia/Riigikogu/ep-popolo-v1.0.json
rake_helpers/generate_ep_popolo.rb

Turn the election data we have into Popolo `Event` entries. We still need to link them up with the relevant Terms (https://github.com/everypolitician/everypolitician/issues/429)

Add elections to the Popolo JSON

---

countries.json
data/Uganda/Parliament/sources/instructions.json
data/Uganda/Parliament/sources/wikidata/elections.json

Uganda (Parliament) — add Election information

---

countries.json
data/Cameroon/Assembly/ep-popolo-v1.0.json
data/Cameroon/Assembly/sources/instructions.json
data/Cameroon/Assembly/sources/wikidata/elections.json

Cameroon (Assembly) — add Election information

---

countries.json
data/Djibouti/Assembly/ep-popolo-v1.0.json
data/Djibouti/Assembly/sources/instructions.json
data/Djibouti/Assembly/sources/wikidata/elections.json

Djibouti (Assembly) — add Election information

---

countries.json
data/US_Virgin_Islands/Legislature/ep-popolo-v1.0.json
data/US_Virgin_Islands/Legislature/sources/instructions.json
data/US_Virgin_Islands/Legislature/sources/wikidata/elections.json

US Virgin Islands (Legislature) — add Election information

---

bin/dashboard.rb

Generate a CSV of statistics for each legislature to build a simple dashboard.

Simple dashboard command

---

countries.json
data/Kenya/Assembly/ep-popolo-v1.0.json
data/Kenya/Assembly/sources/instructions.json
data/Kenya/Assembly/sources/wikidata/elections.json

Kenya (Assembly) — add Election information

---

countries.json
data/Myanmar/House_of_Representatives/ep-popolo-v1.0.json
data/Myanmar/House_of_Representatives/sources/instructions.json
data/Myanmar/House_of_Representatives/sources/wikidata/elections.json

Myanmar (House of Representatives) — add Election information

---

countries.json
data/United_States_of_America/Senate/ep-popolo-v1.0.json
data/United_States_of_America/Senate/sources/instructions.json
data/United_States_of_America/Senate/sources/wikidata/elections.json

United States of America (Senate) — add Election information

---

countries.json
data/Mozambique/Assembly/ep-popolo-v1.0.json
data/Mozambique/Assembly/sources/instructions.json
data/Mozambique/Assembly/sources/wikidata/elections.json

Mozambique (Assembly) — add Election information

---

countries.json
data/Guinea-Bissau/Assembly/ep-popolo-v1.0.json
data/Guinea-Bissau/Assembly/sources/instructions.json
data/Guinea-Bissau/Assembly/sources/wikidata/elections.json

Guinea-Bissau (Assembly) — add Election information

---

countries.json
data/Somalia/Lower/ep-popolo-v1.0.json
data/Somalia/Lower/sources/instructions.json
data/Somalia/Lower/sources/wikidata/elections.json

Somalia (Lower) — add Election information

---

countries.json
data/Malawi/Assembly/ep-popolo-v1.0.json
data/Malawi/Assembly/sources/instructions.json
data/Malawi/Assembly/sources/wikidata/elections.json

Malawi (Assembly) — add Election information

---

bin/dashboard.rb

Add information on recent/upcoming Elections (to help see if we're out
of date, or about to become so), and on how many parties/groups have
been matched to Wikidata.

Add some extra columns to the Dashboard

---

countries.json
data/Northern_Cyprus/Assembly/sources/manual/terms.csv

The current term is actually the 8th (per http://www.cm.gov.nc.tr/EskiFaaliyet.aspx)
Thanks to @wfdd for pointer.

Northern Cyprus: Correct term numbering

---

countries.json
data/United_States_of_America/House/sources/instructions.json
data/United_States_of_America/House/sources/wikidata/elections.json

United States of America (House) — add Election information

---

countries.json
data/Taiwan/Legislative_Yuan/ep-popolo-v1.0.json
data/Taiwan/Legislative_Yuan/sources/instructions.json
data/Taiwan/Legislative_Yuan/sources/wikidata/elections.json

Taiwan (Legislative Yuan) — add Election information

---

countries.json
data/Algeria/Majlis/ep-popolo-v1.0.json
data/Algeria/Majlis/sources/instructions.json
data/Algeria/Majlis/sources/wikidata/elections.json

Algeria (Majlis) — add Election information

---

countries.json
data/Zimbabwe/Assembly/ep-popolo-v1.0.json
data/Zimbabwe/Assembly/sources/instructions.json
data/Zimbabwe/Assembly/sources/wikidata/elections.json
data/Zimbabwe/Assembly/unstable/stats.json

Zimbabwe (Assembly) — add Election information

---

countries.json
data/Tanzania/Assembly/ep-popolo-v1.0.json
data/Tanzania/Assembly/sources/instructions.json
data/Tanzania/Assembly/sources/wikidata/elections.json
data/Tanzania/Assembly/unstable/stats.json

Tanzania (Assembly) — add Election information

---

countries.json
data/Lesotho/Assembly/ep-popolo-v1.0.json
data/Lesotho/Assembly/sources/instructions.json
data/Lesotho/Assembly/sources/wikidata/elections.json
data/Lesotho/Assembly/unstable/stats.json

Lesotho (Assembly) — add Election information

---

countries.json
data/Angola/National_Assembly/ep-popolo-v1.0.json
data/Angola/National_Assembly/sources/instructions.json
data/Angola/National_Assembly/sources/wikidata/elections.json
data/Angola/National_Assembly/unstable/stats.json

Angola (National Assembly) — add Election information

---

countries.json
data/South_Africa/Assembly/ep-popolo-v1.0.json
data/South_Africa/Assembly/sources/instructions.json
data/South_Africa/Assembly/sources/wikidata/elections.json
data/South_Africa/Assembly/unstable/stats.json

South Africa (Assembly) — add Election information

---

countries.json
data/Morocco/House/ep-popolo-v1.0.json
data/Morocco/House/sources/instructions.json
data/Morocco/House/sources/wikidata/elections.json
data/Morocco/House/unstable/stats.json

Morocco (House) — add Election information

---

countries.json
data/Libya/House_of_Representatives/ep-popolo-v1.0.json
data/Libya/House_of_Representatives/sources/instructions.json
data/Libya/House_of_Representatives/sources/wikidata/elections.json
data/Libya/House_of_Representatives/unstable/stats.json

Libya (House of Representatives) — add Election information

---

countries.json
data/Abkhazia/Assembly/ep-popolo-v1.0.json
data/Abkhazia/Assembly/sources/instructions.json
data/Abkhazia/Assembly/sources/wikidata/elections.json
data/Abkhazia/Assembly/unstable/stats.json

Abkhazia (Assembly) — add Election information

---

countries.json
data/Burkina_Faso/Assembly/ep-popolo-v1.0.json
data/Burkina_Faso/Assembly/sources/instructions.json
data/Burkina_Faso/Assembly/sources/wikidata/elections.json
data/Burkina_Faso/Assembly/unstable/stats.json

Burkina Faso (Assembly) — add Election information

---

countries.json
data/Turkmenistan/Mejlis/ep-popolo-v1.0.json
data/Turkmenistan/Mejlis/sources/instructions.json
data/Turkmenistan/Mejlis/sources/wikidata/elections.json
data/Turkmenistan/Mejlis/unstable/stats.json

Turkmenistan (Mejlis) — add Election information

---

countries.json
data/Portugal/Assembly/ep-popolo-v1.0.json
data/Portugal/Assembly/sources/instructions.json
data/Portugal/Assembly/sources/wikidata/elections.json
data/Portugal/Assembly/unstable/stats.json

Portugal (Assembly) — add Election information

---

countries.json
data/Austria/Nationalrat/ep-popolo-v1.0.json
data/Austria/Nationalrat/sources/instructions.json
data/Austria/Nationalrat/sources/manual/group_wikidata.csv
data/Austria/Nationalrat/sources/wikidata/groups.json
data/Austria/Nationalrat/unstable/stats.json

Austria (Nationalrat) — add Group information

---

countries.json
data/Morocco/House/ep-popolo-v1.0.json
data/Morocco/House/sources/instructions.json
data/Morocco/House/sources/manual/group_wikidata.csv
data/Morocco/House/sources/wikidata/groups.json
data/Morocco/House/unstable/stats.json

Morocco (House) — add Group information

---

countries.json
data/Greenland/Inatsisartut/ep-popolo-v1.0.json
data/Greenland/Inatsisartut/sources/instructions.json
data/Greenland/Inatsisartut/sources/manual/group_wikidata.csv
data/Greenland/Inatsisartut/sources/wikidata/groups.json
data/Greenland/Inatsisartut/unstable/stats.json

Greenland (Inatsisartut) — add Group information

---

countries.json
data/Togo/Assembly/ep-popolo-v1.0.json
data/Togo/Assembly/sources/instructions.json
data/Togo/Assembly/sources/manual/group_wikidata.csv
data/Togo/Assembly/sources/wikidata/groups.json
data/Togo/Assembly/unstable/stats.json

Togo (Assembly) — add Group information

---

bin/dashboard.rb

Whilst we build up the stats files for every legislature, report on whether they already exist or not.

Dashboard: report on existence of stats file

---

data/Australia/Representatives/sources/instructions.json

Reverts everypolitician/everypolitician-data#12020

Revert "Australia (House of Representatives) collect twitter data from openaustralia scraper"

---

countries.json
data/South_Korea/National_Assembly/ep-popolo-v1.0.json
data/South_Korea/National_Assembly/sources/instructions.json
data/South_Korea/National_Assembly/sources/wikidata/elections.json
data/South_Korea/National_Assembly/unstable/stats.json

South Korea (National Assembly) — add Election information

---

countries.json
data/Egypt/Parliament/ep-popolo-v1.0.json
data/Egypt/Parliament/sources/instructions.json
data/Egypt/Parliament/sources/wikidata/elections.json
data/Egypt/Parliament/unstable/stats.json

Egypt (Parliament) — add Election information

---

countries.json
data/Japan/House_of_Representatives/ep-popolo-v1.0.json
data/Japan/House_of_Representatives/sources/instructions.json
data/Japan/House_of_Representatives/sources/wikidata/elections.json
data/Japan/House_of_Representatives/unstable/stats.json

Japan (House of Representatives) — add Election information
